# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "Home"
#   url = "#posts"
#   weight = 10

[[main]]
  pre = "<i class='fas fa-laptop'></i>&ensp;"
  name = "Projekte"
  url = "/projects"
  weight = 10

[[main]]
  pre = "<i class='fab fa-google'></i>&ensp;"
  name = "Trends"
  url = "/projects#project_01"
  parent = "Projekte"
  weight = 20

# [[main]]
#   name = "Übersicht"
#   identifier = "uebersicht1"
#   url = "/post/uebersicht1"
#   parent = "Trends"
#   weight = 21
#
# [[main]]
#   name = "Problemstellung"
#   identifier = "problemstellung1"
#   url = "/post/problemstellung1"
#   parent = "Trends"
#   weight = 22
#
# [[main]]
#   name = "Tipps"
#   identifier = "tipps1"
#   url = "/post/tipps1"
#   parent = "Trends"
#   weight = 23
#
# [[main]]
#   name = "Lösungen"
#   identifier = "loesungen1"
#   url = "/post/loesungen1"
#   parent = "Trends"
#   weight = 24


[[main]]
  pre = "<i class='fas fa-dice'></i>&ensp;"
  name = "Casino"
  url = "/projects#project_02"
  parent = "Projekte"
  weight = 30

# [[main]]
#   name = "Übersicht"
#   identifier = "uebersicht2"
#   url = "/post/uebersicht2"
#   parent = "Casino"
#   weight = 31
#
# [[main]]
#   name = "Problemstellung"
#   identifier = "problemstellung2"
#   url = "/post/problemstellung2"
#   parent = "Casino"
#   weight = 32
#
# [[main]]
#   name = "Tipps"
#   identifier = "tipps2"
#   url = "/post/tipps2"
#   parent = "Casino"
#   weight = 33
#
# [[main]]
#   name = "Lösungen"
#   identifier = "loesungen2"
#   url = "/post/loesungen2"
#   parent = "Casino"
#   weight = 34


[[main]]
  pre = "<i class='fab fa-whatsapp'></i>&ensp;"
  name = "WhatsApp"
  url = "/projects#project_03"
  parent = "Projekte"
  weight = 40

# [[main]]
#   name = "Übersicht"
#   identifier = "uebersicht3"
#   url = "/post/uebersicht3"
#   parent = "WhatsApp"
#   weight = 41
#
# [[main]]
#   name = "Problemstellung"
#   identifier = "problemstellung3"
#   url = "/post/problemstellung3"
#   parent = "WhatsApp"
#   weight = 42
#
# [[main]]
#   name = "Tipps"
#   identifier = "tipps3"
#   url = "/post/tipps3"
#   parent = "WhatsApp"
#   weight = 43
#
# [[main]]
#   name = "Lösungen"
#   identifier = "loesungen3"
#   url = "/post/loesungen3"
#   parent = "WhatsApp"
#   weight = 44
#

[[main]]
  pre = "<i class='fa fa-map'></i>&ensp;"
  name = "Karten"
  url = "/projects#project_04"
  parent = "Projekte"
  weight = 50

#
# [[main]]
#   name = "Übersicht"
#   identifier = "uebersicht4"
#   url = "/post/uebersicht4"
#   parent = "Karten"
#   weight = 51
#
# [[main]]
#   name = "Problemstellung"
#   identifier = "problemstellung4"
#   url = "/post/problemstellung4"
#   parent = "Karten"
#   weight = 52
#
# [[main]]
#   name = "Tipps"
#   identifier = "tipps4"
#   url = "/post/tipps4"
#   parent = "Karten"
#   weight = 53
#
# [[main]]
#   name = "Lösungen"
#   identifier = "loesungen4"
#   url = "/post/loesungen4"
#   parent = "Karten"
#   weight = 54
#
[[main]]
  pre = "<i class='fa fa-th'></i>&ensp;"
  name = "Sudoku"
  url = "/projects#project_05"
  parent = "Projekte"
  weight = 60

# [[main]]
#   name = "Übersicht"
#   identifier = "uebersicht5"
#   url = "/post/uebersicht5"
#   parent = "Sudoku"
#   weight = 61
#
# [[main]]
#   name = "Problemstellung"
#   identifier = "problemstellung5"
#   url = "/post/problemstellung5"
#   parent = "Sudoku"
#   weight = 62
#
# [[main]]
#   name = "Tipps"
#   identifier = "tipps5"
#   url = "/post/tipps5"
#   parent = "Sudoku"
#   weight = 63
#
# [[main]]
#   name = "Lösungen"
#   identifier = "loesungen5"
#   url = "/post/loesungen5"
#   parent = "Sudoku"
#   weight = 64
#


[[main]]
  pre = "<i class='fas fa-poll'></i>&ensp;"
  name = "FormR"
  url = "/projects#project_06"
  parent = "Projekte"
  weight = 70

# [[main]]
#   name = "Übersicht"
#   identifier = "uebersicht6"
#   url = "/post/uebersicht6"
#   parent = "FormR"
#   weight = 71
#
# [[main]]
#   name = "Problemstellung"
#   identifier = "problemstellung6"
#   url = "/post/problemstellung6"
#   parent = "FormR"
#   weight = 72
#
# [[main]]
#   name = "Tipps"
#   identifier = "tipps6"
#   url = "/post/tipps6"
#   parent = "FormR"
#   weight = 73
#
# [[main]]
#   name = "Lösungen"
#   identifier = "loesungen6"
#   url = "/post/loesungen6"
#   parent = "FormR"
#   weight = 74



[[main]]
  pre = "<i class='fa fa-cogs'></i>&ensp;"
  name = "ShinyR"
  url = "/projects#project_07"
  parent = "Projekte"
  weight = 80

# [[main]]
#   name = "Übersicht"
#   identifier = "uebersicht7"
#   url = "/post/uebersicht7"
#   parent = "ShinyR"
#   weight = 81
#
# [[main]]
#   name = "Problemstellung"
#   identifier = "problemstellung7"
#   url = "/post/problemstellung7"
#   parent = "ShinyR"
#   weight = 82
#
# [[main]]
#   name = "Tipps"
#   identifier = "tipps7"
#   url = "/post/tipps7"
#   parent = "ShinyR"
#   weight = 83
#
# [[main]]
#   name = "Lösungen"
#   identifier = "loesungen7"
#   url = "/post/loesungen7"
#   parent = "ShinyR"
#   weight = 84


[[main]]
  pre = "<i class='fas fa-network-wired'></i>&ensp;"
  name = "API"
  url = "/projects#project_08"
  parent = "Projekte"
  weight = 90
#
# [[main]]
#   name = "Übersicht"
#   identifier = "uebersicht8"
#   url = "/post/uebersicht8"
#   parent = "API"
#   weight = 91
#
# [[main]]
#   name = "Problemstellung"
#   identifier = "problemstellung8"
#   url = "/post/problemstellung8"
#   parent = "API"
#   weight = 92
#
# [[main]]
#   name = "Tipps"
#   identifier = "tipps8"
#   url = "/post/tipps8"
#   parent = "API"
#   weight = 93
#
# [[main]]
#   name = "Lösungen"
#   identifier = "loesungen8"
#   url = "/post/loesungen8"
#   parent = "API"
#   weight = 94

[[main]]
  pre = "<i class='fas fa-chalkboard-teacher'></i>&ensp;"
  name = "Lehre"
  url = "/lehre"
  weight = 100

[[main]]
  pre = "<i class='fas fa-chart-pie'></i>&ensp;"
  name = "Statistik I"
  url = "/lehre#BSc2"
  parent = "Lehre"
  weight = 101

[[main]]
  pre = "<i class='fas fa-chart-bar'></i>&ensp;"
  name = "Statistik II"
  url = "/lehre#BSc7"
  parent = "Lehre"
  weight = 102

[[main]]
  pre = "<i class='fas fa-bezier-curve'></i>&ensp;"
  name = "Multivariat"
  url = "/lehre#MSc1"
  parent = "Lehre"
  weight = 103

[[main]]
  pre = "<i class='fas fa-laptop-code'></i>&ensp;"
  name = "Forschungsmod. F&E"
  url = "/lehre#MSc5_fe"
  parent = "Lehre"
  weight = 104

[[main]]
  pre = "<i class='fas fa-database'></i>&ensp;"
  name = "Forschungsmod. A&O"
  url = "/lehre#MSc5_ao"
  parent = "Lehre"
  weight = 105

[[main]]
  pre = "<i class='fas fa-book'></i>&ensp;"
  name = "Extras"
  url = "/extras"
  weight = 110

[[main]]
  pre = "<i class='fab fa-github'></i>&ensp;"
  name = "Git"
  url = "/extras#Git"
  parent = "Extras"
  weight = 111
