# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "Home"
#   url = "#posts"
#   weight = 10

[[main]]
  name = "Projekte:"
  url = "/projects"
  weight = 10

[[main]]
  pre = "<i class='fab fa-google'></i>&ensp;"
  name = "Trends"
  #url = "/post/uebersicht1"
  # parent = "Projekte"
  weight = 20

[[main]]
  name = "Übersicht"
  identifier = "uebersicht1"
  url = "/post/uebersicht1"
  parent = "Trends"
  weight = 21

[[main]]
  name = "Problemstellung"
  identifier = "problemstellung1"
  url = "/post/problemstellung1"
  parent = "Trends"
  weight = 22

[[main]]
  name = "Tipps"
  identifier = "tipps1"
  url = "/post/tipps1"
  parent = "Trends"
  weight = 23

[[main]]
  name = "Lösungen"
  identifier = "loesungen1"
  url = "/post/loesungen1"
  parent = "Trends"
  weight = 24


[[main]]
  pre = "<i class='fas fa-dice'></i>&ensp;"
  name = "Casino"
  # url = "/post/under-construction"
  # parent = "Projekte"
  weight = 30

[[main]]
  name = "Übersicht"
  identifier = "uebersicht2"
  url = "/post/uebersicht2"
  parent = "Casino"
  weight = 31

[[main]]
  name = "Problemstellung"
  identifier = "problemstellung2"
  url = "/post/problemstellung2"
  parent = "Casino"
  weight = 32

[[main]]
  name = "Tipps"
  identifier = "tipps2"
  url = "/post/tipps2"
  parent = "Casino"
  weight = 33

[[main]]
  name = "Lösungen"
  identifier = "loesungen2"
  url = "/post/loesungen2"
  parent = "Casino"
  weight = 34


[[main]]
  pre = "<i class='fab fa-whatsapp'></i>&ensp;"
  name = "WhatsApp"
  # url = "/post/under-construction"
  # parent = "Projekte"
  weight = 40

[[main]]
  name = "Übersicht"
  identifier = "uebersicht3"
  url = "/post/under-construction"
  parent = "WhatsApp"
  weight = 41

[[main]]
  name = "Problemstellung"
  identifier = "problemstellung3"
  url = "/post/under-construction"
  parent = "WhatsApp"
  weight = 42

[[main]]
  name = "Tipps"
  identifier = "tipps3"
  url = "/post/under-construction"
  parent = "WhatsApp"
  weight = 43

[[main]]
  name = "Lösungen"
  identifier = "loesungen3"
  url = "/post/under-construction"
  parent = "WhatsApp"
  weight = 44


[[main]]
  pre = "<i class='fa fa-user-secret'></i>&ensp;"
  name = "Kriminalität"
  url = "/post/under-construction"
  # parent = "Projekte"
  weight = 50

[[main]]
  pre = "<i class='fa fa-th'></i>&ensp;"
  name = "Sudoku"
  url = "/post/under-construction"
  # parent = "Projekte"
  weight = 60
