# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Neuigkeiten"
  url = "#posts"
  weight = 10

[[main]]
  name = "Projekte"
  url = "/projects"
  weight = 20

[[main]]
  pre = "<i class='fab fa-google'></i>"
  name = " Trends"
  url = "/projects#project_01"
  parent = "Projekte"
  weight = 21

[[main]]
  pre = "<i class='fas fa-dice'></i>"
  name = " Kasino"
  url = "/projects#project_02"
  parent = "Projekte"
  weight = 22

[[main]]
  pre = "<i class='fab fa-whatsapp'></i>"
  name = " WhatsApp"
  url = "/projects#project_03"
  parent = "Projekte"
  weight = 23

[[main]]
  pre = "<i class='fa fa-user-secret'></i>"
  name = " Kriminalität"
  url = "/projects#project_04"
  parent = "Projekte"
  weight = 24

[[main]]
  pre = "<i class='fa fa-th'></i>"
  name = " Sudoku"
  url = "/projects#project_05"
  parent = "Projekte"
  weight = 25

[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 30
