---
title: R Deskritpivstatistik - Lösungen
date: '2020-11-26'
slug: r-deskriptiv-loesungen
categories:
  - BSc2
  - Loesungen
tags:
  - R Deskriprivstatistik
subtitle: ''
summary: ''
authors: [buchholz]
lastmod: '2020-11-26T21:07:11+02:00'
featured: no
header:
  image: "/header/descriptive_post.jpg"
  caption: "[Courtesy of pxhere](https://pxhere.com/en/photo/1227907)"
projects: []
expiryDate: '2021-09-01'
publishDate: '2020-12-04'
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="vorbereitung" class="section level3">
<h3>Vorbereitung</h3>
<details>
<summary>
Lösung
</summary>
<p>Laden Sie zunächst den Datensatz <code>fb20</code> von der pandar-Website.</p>
<pre class="r"><code>fb20 &lt;- read.table(&#39;https://pandar.netlify.app/post/fb20.csv&#39;, 
  header = TRUE,
  sep = &#39;,&#39;,
  na.strings = &#39;-99&#39;)</code></pre>
<p>Die Bedeutung der einzelnen Variablen und ihre Antwortkategorien können Sie dem Dokument <a href="/post/variablen.pdf">Variablenübersicht.docx</a> entnehmen.</p>
<p>Verschaffen Sie sich nun einen Überblick über den Datensatz:</p>
<pre class="r"><code>dim(fb20)</code></pre>
<pre><code>## [1] 98 32</code></pre>
<pre class="r"><code>str(fb20)</code></pre>
<pre><code>## &#39;data.frame&#39;:    98 obs. of  32 variables:
##  $ mdbf1  : int  3 5 4 4 5 4 3 4 2 4 ...
##  $ mdbf2  : int  2 3 4 2 4 4 4 2 2 2 ...
##  $ mdbf3  : int  4 2 2 3 2 1 1 4 4 2 ...
##  $ mdbf4  : int  3 1 1 NA 1 1 2 3 4 2 ...
##  $ mdbf5  : int  2 3 1 4 1 1 1 3 4 4 ...
##  $ mdbf6  : int  1 4 4 2 4 3 4 3 2 4 ...
##  $ mdbf7  : int  2 3 1 5 2 3 1 4 4 4 ...
##  $ mdbf8  : int  3 5 4 3 5 4 4 4 2 4 ...
##  $ mdbf9  : int  4 1 2 4 2 1 1 4 4 2 ...
##  $ mdbf10 : int  3 3 4 1 3 4 3 3 2 4 ...
##  $ mdbf11 : int  2 1 1 3 2 1 1 3 5 2 ...
##  $ mdbf12 : int  2 5 4 2 4 4 4 2 2 4 ...
##  $ lz     : num  5.4 6.8 5 3.6 5.6 5.4 4.8 3.6 5 5.4 ...
##  $ extra  : num  3.5 4 3.5 2.75 4.25 3 3.5 4 3.25 3.5 ...
##  $ vertr  : num  3.5 5 5 3.75 3.5 4.5 4.5 4 4.5 5 ...
##  $ gewis  : num  4 3.5 3.75 4.25 4.25 4.75 4.5 4.25 3 4.75 ...
##  $ neuro  : num  4.25 3 4.5 4.75 4.25 2 4 3.5 3.25 4.25 ...
##  $ intel  : num  3.25 3.75 4.5 2.25 4.5 4 3.25 3.5 2.75 3.5 ...
##  $ pro    : num  1.9 2.1 2.5 2.7 2.9 2.1 2.4 2 2.5 2.2 ...
##  $ grund  : chr  &quot;weil mich die menschliche Psyche sehr interessiert, vor allem die Ursachen für negative Verhaltenweisen, Charak&quot;| __truncated__ &quot;Tiefes Interesse&quot; &quot;Interessante Themen&quot; &quot;Interesse auf Menschen&quot; ...
##  $ fach   : int  3 3 4 3 2 1 4 1 4 NA ...
##  $ ziel   : int  2 2 2 3 3 1 2 1 2 NA ...
##  $ lerntyp: int  1 3 1 1 3 1 1 3 3 NA ...
##  $ geschl : int  1 1 2 2 1 2 1 1 NA NA ...
##  $ job    : int  2 1 1 2 1 1 1 1 1 NA ...
##  $ ort    : int  1 2 1 2 1 1 1 2 NA NA ...
##  $ ort12  : int  2 2 1 2 1 1 1 3 1 NA ...
##  $ wohnen : int  1 4 2 1 1 2 3 2 1 NA ...
##  $ uni1   : int  1 1 1 0 1 0 0 0 0 0 ...
##  $ uni2   : int  1 0 1 1 1 1 1 1 0 0 ...
##  $ uni3   : int  0 0 0 0 0 1 0 0 0 0 ...
##  $ uni4   : int  0 0 0 0 0 0 0 1 0 0 ...</code></pre>
<p>Der Datensatz besteht aus 98 Zeilen (Beobachtungen) und 32 Spalten (=Variablen).</p>
</details>
</div>
<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<p>Untersuchen Sie, welche Arbeitsbranche Sie und Ihre Kommilitonen/innen nach dem Studium anstreben!</p>
<ul>
<li>Vergeben Sie zunächst die korrekten Wertelabels an die Ausprägungen der Variable.<br />
</li>
<li>Lassen Sie sich absolute und relative Häufigkeiten ausgeben.<br />
</li>
<li>Untersuchen Sie, mit den geeigneten Maßen, die zentrale Tendenz und Dispersion dieser Variable.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><strong>Faktor erstellen</strong></p>
<pre class="r"><code>fb20$ziel &lt;- factor(fb20$ziel,
                        levels = 1:4,
                        labels = c(&quot;Wirtschaft&quot;, &quot;Therapie&quot;, &quot;Forschung&quot;, &quot;Andere&quot;))
levels(fb20$ziel)</code></pre>
<pre><code>## [1] &quot;Wirtschaft&quot; &quot;Therapie&quot;   &quot;Forschung&quot;  &quot;Andere&quot;</code></pre>
<p><strong>Absolute und relative Häufigkeiten anfordern</strong></p>
<pre class="r"><code>table(fb20$ziel)              # absolut</code></pre>
<pre><code>## 
## Wirtschaft   Therapie  Forschung     Andere 
##         16         37         29         11</code></pre>
<pre class="r"><code>prop.table(table(fb20$ziel))  # relativ</code></pre>
<pre><code>## 
## Wirtschaft   Therapie  Forschung     Andere 
##  0.1720430  0.3978495  0.3118280  0.1182796</code></pre>
<p><strong>Zentrale Tendenz und Dispersion für nominalskalierte Variablen: Modus, relativer Informationsgehalt</strong></p>
<pre class="r"><code># Modus
which.max(table(fb20$ziel))</code></pre>
<pre><code>## Therapie 
##        2</code></pre>
<pre class="r"><code>#relativer Informationsgehalt
hj &lt;- prop.table(table(fb20$ziel))  # hj erstellen
ln_hj &lt;- log(hj)                    # Logarithmus bestimmen
summand &lt;- ln_hj * hj               # Berechnung fuer jede Kategorie
summe &lt;- sum(summand)               # Gesamtsumme
k &lt;- length(hj)                     # Anzahl Kategorien bestimmen
relInf &lt;- -1/log(k) * summe         # Relativer Informationsgehalt
relInf</code></pre>
<pre><code>## [1] 0.9271871</code></pre>
<p>Der Modus der Variable lautet ‘Therapie’ - die meisten Ihres Jahrgangs (<em>n</em> = 37 bzw. 39.78%) streben einen Job als Therapeut/-in an. Der relative Informationsgehalt der Variable beträgt 0.93.</p>
</details>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<p>Die Variable <code>mdbf7</code> enthält die Angaben über das Ausmaß, in dem Sie und Ihre Kommilitonen/-innen sich zum Zeitpunkt des Ausfüllens “müde” fühlten.</p>
<ul>
<li>Bestimmen Sie für diese Variable den Modus.<br />
</li>
<li>Untersuchen Sie die Streuung für diese Variable optisch, indem Sie einen Boxplot erstellen.<br />
</li>
<li>Bestimmen Sie die Quartile und den Interquartilsbereich (IQB) auch als Zahlen.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><strong>Modus</strong></p>
<pre class="r"><code>which.max(table(fb20$mdbf7))</code></pre>
<pre><code>## 3 
## 3</code></pre>
<p><strong>Häufigkeiten</strong></p>
<pre class="r"><code>table(fb20$mdbf7)</code></pre>
<pre><code>## 
##  1  2  3  4  5 
## 16 26 29 19  8</code></pre>
<pre class="r"><code>prop.table(table(fb20$mdbf7))</code></pre>
<pre><code>## 
##          1          2          3          4          5 
## 0.16326531 0.26530612 0.29591837 0.19387755 0.08163265</code></pre>
<p>Der Modus der Variable “mdbf7” (“müde”) beträgt 3, d.h. die Antwortkategorie ‘3’ wurde am häufigsten genannt (<em>n</em> = 29 bzw. 29.59%).</p>
<p><strong>Boxplot</strong></p>
<pre class="r"><code>boxplot(fb20$mdbf7)</code></pre>
<p><img src="/post/2020-11-26-r05-deskriptiv-loesungen_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p><strong>Quartile</strong></p>
<pre class="r"><code>quantile(fb20$mdbf7, c(.25,.5,.75), na.rm=T)</code></pre>
<pre><code>## 25% 50% 75% 
##   2   3   4</code></pre>
<p>Der Median beträgt 3. Das 1. und 3. Quartil betragen 2 bzw. 4. Folglich beträgt der Interquartilsbereich (IQB) 2.</p>
</details>
</div>
<div id="aufgabe-3" class="section level2">
<h2>Aufgabe 3</h2>
<p>Erstellen Sie für die Variable <code>wohnen</code> eine geeignete Abbildung.</p>
<ul>
<li>Stellen Sie sicher, dass die einzelnen Ausprägungen der Variable in der Darstellung interpretierbar benannt sind!<br />
</li>
<li>Dekorieren Sie diese Abbildung nach eigenen Wünschen (z.B. mit einer Farbpalette und Achsenbeschriftungen).</li>
<li>Speichern Sie die Grafik per Syntax als .jpg-Datei mit dem Namen “Befragung-fb20.jpg” ab.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><strong>Faktor erstellen</strong></p>
<pre class="r"><code>fb20$wohnen &lt;- factor(fb20$wohnen, 
                      levels = 1:4, 
                      labels = c(&quot;WG&quot;, &quot;bei Eltern&quot;, &quot;allein&quot;, &quot;sonstiges&quot;))</code></pre>
<p><strong>Default Darstellung und überarbeitete Grafik</strong></p>
<pre class="r"><code>par(mfrow=c(1,2))

# Default
barplot(table(fb20$wohnen))

# Überarbeitet
barplot(
  # wichtig: Funktion auf Häufigkeitstabelle, nicht die Variable selbst anwenden:
  table(fb20$wohnen),                               
  # aussagekräftiger Titel, inkl. Zeilenumbruch (&quot;\n&quot;) 
  main = &quot;Befragung Erstis im WS 20/21:\nAktuelle Wohnsituation&quot;, 
  # y-Achsen-Beschriftung:
  ylab = &quot;Häufigkeit&quot;,
  # Farben aus einer Farbpalette:
  col = rainbow(10),
  # Platz zwischen Balken minimieren:
  space = 0.1,
  # graue Umrandungen der Balken:
  border = &quot;grey2&quot;,
  # Unterscheidlich dichte Schattierungen (statt Füllung) für die vier Balken:
  density = c(50, 75, 25, 50),
  # Richtung, in dem die Schattierung in den vier Balken verläuft
  angle = c(-45, 0, 45, 90),
  # Schriftausrichtung der Achsen horizontal:
  las=2,
  #y-Achse erweitern, sodass mehr Platz zum Titel bleibt:
  ylim = c(0,60))</code></pre>
<p><img src="/post/2020-11-26-r05-deskriptiv-loesungen_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p><strong>Speichern (per Syntax)</strong></p>
<pre class="r"><code>jpeg(&quot;Befragung-fb20.jpg&quot;, width=20, height=10, units=&quot;cm&quot;, res=200)
barplot(
  table(fb20$wohnen),                               
  main = &quot;Befragung Erstis im WS 20/21:\nAktuelle Wohnsituation&quot;, 
  ylab = &quot;Häufigkeit&quot;,
  col = rainbow(10),
  space = 0.1,
  border = &quot;grey2&quot;,
  density = c(50,75,25,50),
  angle = c(-45,0,45,90),
  las=2,
  ylim = c(0,60))
dev.off()</code></pre>
<p>Im Arbeitsverzeichnis ist nun folgende Datei entstanden:<br />
<img src="Screenshot-Befragung-fb20.PNG" /></p>
</details>
</div>
<div id="aufgabe-4" class="section level2">
<h2>Aufgabe 4</h2>
<p>Erstellen Sie im Datensatz <code>fb20</code> die Skalenwerte für wach vs. müde (wm) und ruhig vs. unruhig (ru). Diese Skalen umfassen die folgenden Items (negative Items sind unterstrichen):</p>
<ul>
<li>Wach vs. müde: ausgeruht (mdbf2), <span style="text-decoration: underline">schlapp (mdbf5)</span>, <span style="text-decoration: underline">müde (mdbf7)</span>, munter (mdbf10)</li>
<li>Ruhig vs. unruhig: <span style="text-decoration: underline">ruhelos (mdbf3)</span>, gelassen (mdbf6), <span style="text-decoration: underline">unruhig (mdbf9)</span>, entspannt (mdbf12)</li>
</ul>
<p>Erstellen Sie die Skalenwerte als Mittelwert der jeweiligen vier Items.</p>
<details>
<summary>
Lösung
</summary>
<p><strong>Für wach/müde Items</strong></p>
<pre class="r"><code># Rekodierung 
# Variante 1: lineare Transformation

fb20$mdbf5_r &lt;- -1 * (fb20$mdbf5 - 6)
fb20$mdbf7_r &lt;- -1 * (fb20$mdbf7 - 6)

# Skalenwert

wach &lt;- fb20[, c(&#39;mdbf2&#39;, &#39;mdbf5_r&#39;, &#39;mdbf7_r&#39;, &#39;mdbf10&#39;)]
fb20$wm &lt;- rowMeans(wach)</code></pre>
<p><strong>Für ruhig/unruhig Items</strong></p>
<pre class="r"><code># Rekodierung 
# Variante 2: logische Filter

fb20$mdbf3_r[fb20$mdbf3 == 1] &lt;- 5
fb20$mdbf3_r[fb20$mdbf3 == 2] &lt;- 4
fb20$mdbf3_r[fb20$mdbf3 == 3] &lt;- 3
fb20$mdbf3_r[fb20$mdbf3 == 4] &lt;- 2
fb20$mdbf3_r[fb20$mdbf3 == 5] &lt;- 1

fb20$mdbf9_r[fb20$mdbf9 == 1] &lt;- 5
fb20$mdbf9_r[fb20$mdbf9 == 2] &lt;- 4
fb20$mdbf9_r[fb20$mdbf9 == 3] &lt;- 3
fb20$mdbf9_r[fb20$mdbf9 == 4] &lt;- 2
fb20$mdbf9_r[fb20$mdbf9 == 5] &lt;- 1

# Skalenwert

ruhig &lt;- fb20[, c(&#39;mdbf3_r&#39;, &#39;mdbf6&#39;, &#39;mdbf9_r&#39;, &#39;mdbf12&#39;)]
fb20$ru &lt;- rowMeans(ruhig)</code></pre>
</details>
</div>
<div id="aufgabe-5" class="section level2">
<h2>Aufgabe 5</h2>
<p>Bestimmen Sie für beide Skalenwerte jeweils Mittelwert und Median.</p>
<ul>
<li>Was vermuten Sie, aufgrund des Verhältnisses der beiden Maße der zentralen Tendenz, bezüglich der Schiefe der Verteilungen?</li>
<li>Prüfen Sie Ihre Vermutungen anhand von Histogrammen!</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code># Für wach/müde
median(fb20$wm, na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.5</code></pre>
<pre class="r"><code>mean(fb20$wm, na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.313776</code></pre>
<pre class="r"><code># Für ruhig/unruhig
median(fb20$ru, na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.5</code></pre>
<pre class="r"><code>mean(fb20$ru, na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.32398</code></pre>
<p>In beiden Fällen ist der Median (geringfügig) größer als der Mittelwert, was auf eine (leicht) linkssteile bzw. rechtsschiefe Verteilung schließen lässt.</p>
<p><strong>Prüfen der Vermutungen anhand von Histogrammen!</strong></p>
<pre class="r"><code># Histogramme (nebeneinander)
par(mfrow=c(1,2))
hist(fb20$wm)
hist(fb20$ru)</code></pre>
<p><img src="/post/2020-11-26-r05-deskriptiv-loesungen_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Beide Verteilungen sind tatsächlich (leicht) linkssteil bzw. rechtsschief.</p>
</details>
</div>
<div id="aufgabe-6" class="section level2">
<h2>Aufgabe 6</h2>
<p>Bestimmen Sie für den Skalenwert <code>wm</code> die empirische Varianz.</p>
<ul>
<li>Ist diese größer oder kleiner als diejenige Schätzung, die mithilfe von <code>var(...)</code> bestimmt wird?<br />
</li>
<li>Warum?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><strong>Erinnerung:</strong></p>
<ul>
<li>Empirische Varianz: <span class="math inline">\(s^2_{X} = \frac{\sum_{m=1}^n (x_m - \bar{x})^2}{n}\)</span><br />
</li>
<li>Schätzer der Populationsvarianz: <span class="math inline">\(\hat{\sigma}^2_{X} = \frac{\sum_{m=1}^n (x_m - \bar{x})^2}{n - 1}\)</span></li>
</ul>
<p>Zur Berechnung der Varianz gemäß Formel benötigen wir <span class="math inline">\(n\)</span>. Wir könnten mit <code>nrow(fb20)</code> die Länge des Datensatzes für <code>n</code> heranziehen. Dies ist jedoch nur dann sinnvoll, wenn auf der Variable <code>wm</code> keine fehlenden Werte vorhanden sind!</p>
<pre class="r"><code>sum(is.na(fb20$wm))</code></pre>
<pre><code>## [1] 0</code></pre>
<p>Hier gibt es tatäschlich keine fehlenden Werte, daher ist folgende Formel legitim:</p>
<pre class="r"><code># empirische Varianz
# per Hand
sum((fb20$wm - mean(fb20$wm))^2) / nrow(fb20)</code></pre>
<pre><code>## [1] 0.7299888</code></pre>
<pre class="r"><code># durch Umrechnung 
var(fb20$wm) * (nrow(fb20)-1) / nrow(fb20)</code></pre>
<pre><code>## [1] 0.7299888</code></pre>
<pre class="r"><code># Populationsschätzer
var(fb20$wm)</code></pre>
<pre><code>## [1] 0.7375145</code></pre>
<p>Die empirische Varianz (0.73) ist kleiner als der Populationsschätzer (0.738), weil durch <code>n</code>, beim Populationsschätzer jeodoch durch <code>(n-1)</code> geteilt wird.</p>
</details>
</div>
<div id="aufgabe-7" class="section level2">
<h2>Aufgabe 7</h2>
<p>Erstellen Sie eine z-standardisierte Variante der wach vs. müde Skala als <code>wm_z</code>.</p>
<ul>
<li>Erstellen Sie für diese standardisierte Variable ein Histogramm.</li>
<li>Was fällt Ihnen auf, wenn Sie dieses mit dem Histogramm der unstandardisierten Werte vergleichen?</li>
<li>Erstellen Sie beide Histogramme noch einmal mit 20 Kategorien.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>par(mfrow=c(1,2))

# z-Standardisierung
fb20$wm_z &lt;- scale(fb20$wm)

# Histogramme
hist(fb20$wm_z)
hist(fb20$wm)</code></pre>
<p><img src="/post/2020-11-26-r05-deskriptiv-loesungen_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Beim Vergleich der beiden Histogrammen fällt auf, dass sich - aufgrund der R-Voreinstellungen - das Erscheinungsbild fälschlicherweise unterscheidet - eigentlich sollte sich durch die z-Transformation nur Skalierung der x-Achsen-Variable verändern. Tatsächlich aber bestimmt R hier eine unterschiedliche Anzahl von Kategorien. Wir halten diese nun über das <code>breaks</code>-Argument konstant:</p>
<pre class="r"><code># Histogramme mit jeweils 20 Kategorien
par(mfrow=c(1,2))
hist(fb20$wm_z, breaks = 20)
hist(fb20$wm, breaks = 20)</code></pre>
<p><img src="/post/2020-11-26-r05-deskriptiv-loesungen_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Die Verteilungen sehen nun tatächlich (fast) gleich aus.</p>
</details>
</div>
