---
title: Logistische Regression
date: '2020-10-27'
slug: logistische-regression
categories:
  - MSc1
tags:
  - dichotom
  - GLM
  - generalisiertes lineares Modell
  - Regression
  - Linkfunktion
  - Maximum Likelihood
  - Likelihood Ratio Test
subtitle: 'Generalisiertes lineares Modell: dichotome abhängige Variablen'
summary: ''
authors: [irmer]
lastmod: '2021-10-06T08:32:21+02:00'
featured: no
header:
  image: "/header/FEI_Sitzung4_post.jpg"
  caption: "[Courtesy of pxhere](https://pxhere.com/en/photo/776748)"
projects: []
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="einleitung" class="section level2">
<h2>Einleitung</h2>
<p>In dieser Sitzung wollen wir dichotome abhängige Variablen mit der logistischen Regression (vgl. bspw. <a href="https://ubffm.hds.hebis.de/Record/HEB366849158">Eid, Gollwitzer &amp; Schmitt, 2017</a>, Kapitel 22 und <a href="https://ubffm.hds.hebis.de/Record/HEB371183324">Pituch und Stevens, 2016,</a> Kapitel 11) analysieren. Diese Daten sind dahingehend speziell, dass die abhängige Variable nur zwei Ausprägungen hat, welche in der Regel mit <span class="math inline">\(0\)</span> und <span class="math inline">\(1\)</span> kodiert werden. Dies führt dazu, dass der Wertebereich der abhängigen Variable so gut wie gar nicht durch die Vorhersage innerhalb einer normalen Regressionsanalyse “getroffen” wird, die Residuen nicht länger unabhängig von der Ausprägung der abhängigen Variablen sind und auch die Normalverteilungsannahme der Residuen verletzt ist. Wir wollen uns ein reales Datenbeispiel (Datensatz <code>Titanic</code> aus dem gleichnamigen .rda File <code>Titanic.rda</code>) ansehen, in welchem die Überlebenswahrscheinlichkeit des Titanicunglücks durch das Alter sowie die Klassenzugehörigkeit auf dem Schiff vorhergesagt werden soll. Der Datensatz ist öffentlich zugänglich auf <a href="https://public.opendatasoft.com">Open-Daten-Soft</a> zu finden. Sie können sich den <a href="https://public.opendatasoft.com/explore/dataset/titanic-passengers">vollständigen Datensatz hier</a> ansehen. Bevor wir Ihn verwenden, wurden alle fehlenden Werte entfernt (wir gehen einfach mal davon aus, dass das keine Effekte auf die Ergebnisse hat, obwohl wir dies selbstverständlich prüfen müssten) und es wurden einige Variablen rekodiert bzw. entfernt. Sie können den im Folgenden verwendeten <a href="https://pandar.netlify.app/post/Titanic.rda"><svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M216 0h80c13.3 0 24 10.7 24 24v168h87.7c17.8 0 26.7 21.5 14.1 34.1L269.7 378.3c-7.5 7.5-19.8 7.5-27.3 0L90.1 226.1c-12.6-12.6-3.7-34.1 14.1-34.1H192V24c0-13.3 10.7-24 24-24zm296 376v112c0 13.3-10.7 24-24 24H24c-13.3 0-24-10.7-24-24V376c0-13.3 10.7-24 24-24h146.7l49 49c20.1 20.1 52.5 20.1 72.6 0l49-49H488c13.3 0 24 10.7 24 24zm-124 88c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm64 0c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20z"/></svg> Datensatz “Titanic.rda” hier herunterladen</a>.</p>
<div id="daten-laden" class="section level3">
<h3>Daten laden</h3>
<p>Wir laden zunächst die Daten: entweder lokal von Ihrem Rechner:</p>
<pre class="r"><code>load(&quot;C:/Users/Musterfrau/Desktop/Titanic.rda&quot;)</code></pre>
<p>oder wir laden sie direkt über die Website:</p>
<pre class="r"><code>load(url(&quot;https://pandar.netlify.app/post/Titanic.rda&quot;))</code></pre>
<p>Nun sollte in <code>R</code>-Studio oben rechts in dem Fenster unter der Rubrik “Data” unser Datensatz mit dem Namen “<em>Titanic</em>” erscheinen.</p>
</div>
<div id="übersicht-über-die-daten" class="section level3">
<h3>Übersicht über die Daten</h3>
<p>Wir wollen uns einen Überblick über die Daten verschaffen:</p>
<pre class="r"><code>head(Titanic)</code></pre>
<pre><code>##   survived pclass sex age
## 1        1      1   2  28
## 2        0      3   2  36
## 3        1      2   1   3
## 4        1      2   1  40
## 5        0      3   2  32
## 6        0      2   2  34</code></pre>
<pre class="r"><code>dim(Titanic) # Dimensionen des Datensatzes</code></pre>
<pre><code>## [1] 714   4</code></pre>
<p>Die Variable <code>survived</code> gibt an, ob eine Person das Unglück überlebt hat. <code>sex</code> kodiert das Geschlecht, wobei <code>1</code> für weiblich und <code>2</code> für männlich steht. Die Variablen <code>age</code> und <code>pclass</code> beschreiben das Alter und die Klasse, in der die Person reiste (Klasse 1 bis 3). In dieser Analyse werden 714 Personen berücksichtigt.</p>
</div>
<div id="hypothesen" class="section level3">
<h3>Hypothesen</h3>
<p>Während das Schiff sank, galt die Devise: <em>Frauen und Kinder zuerst!</em> Zumindest wird einem dies vermittelt, wenn man sich den gleichnamigen Spielfilm von James Cameron aus dem Jahr 1997 mit Kate Winslet und Leonardo DiCaprio in den Hauptrollen ansieht. Außerdem waren die Klassen an Board so angeordnet, dass die erste Klasse oberhalb der 2. lag, welche wiederum oberhalb der 3. Klasse lag. Daher hatten es Passagiere aus der 3. Klasse schwerer an Deck des Schiffs zu gelangen. Folglich sind unsere Hypothesen die Folgenden:</p>
<ol style="list-style-type: decimal">
<li>Das Überleben des Unglücks hängt vom Alter ab</li>
<li>Das Überleben des Unglücks hängt vom Geschlecht ab</li>
<li>Das Überleben des Unglücks hängt von der Klasse an Bord ab</li>
</ol>
</div>
</div>
<div id="modellspezifikation" class="section level2">
<h2>Modellspezifikation</h2>
<p>Um das Überleben zu modellieren, könnten wir eine <a href="/post/regression-und-ausreisserdiagnostik">Regressionsanalyse</a> heranziehen und das Überleben (<code>survived</code>) durch bspw. das Alter (<code>age</code>) vorhersagen:</p>
<ul>
<li><code>lm(survived ~ 1 + age, data = Titanic)</code></li>
</ul>
<p>In dieser Analyse sind einige Annahmen der Regressionsanalyse verletzt: Normalverteilung der Residuen, Homoskedastizität und auch Unabhängigkeit der Residuen. Aus diesem Grund wollen wir die logistische Regression heranziehen. In einer Regressionsanalyse wird der Mittelwert gegeben die unabhängigen Variablen modelliert. Es handelt sich also um einen bedingten Mittelwert. Dies ist daran ersichtlich, dass die Residuen im Mittel zu jeder Ausprägung von <span class="math inline">\(\hat{y}\)</span> gerade Null sind und somit im Mittel immer der vorhergesagte Wert eintritt. Dieser mittlere Wert ist gerade der Mittelwert oder (korrekter) der Erwartungswert an dieser Stelle.</p>
<p>Gleiches wollen wir auf eine 0-1-Variable verallgemeinern. Wenn Sie einen Münzwurf durchführen und Kopf als 1 und Zahl als 0 kodieren, so erhalten Sie eine Zahlenfolge von 0en und 1en. Wenn Sie nun die relative Häufigkeit (also die Wahrscheinlichkeit) untersuchen wollen, dass Kopf auftritt, so müssen Sie lediglich den Mittelwert über alle 0en und 1en bestimmen. Dieser Mittelwert ist dann genau die Wahrscheinlichkeit, dass die Münze Kopf zeigt. Im folgenden Beispiel ist die relative Häufigkeit Kopf zu werfen 25%:</p>
<pre class="r"><code>Münze &lt;- c(0, 1, 0, 0)
mean(Münze)</code></pre>
<pre><code>## [1] 0.25</code></pre>
<p>Diese 25% sind selbstverständlich nur eine Schätzung für die wahre Wahrscheinlichkeit, Kopf zu werfen. In einer idealen Welt würden wir davon ausgehen, dass die Wahrscheinlichkeit bei 50% liegt! <em>Für Interessierte unter Ihnen:</em> dieser Mittelwert ist der Maximum-Likelihood (ML) Schätzer für die Auftretenswahrscheinlichkeit von Kopf.</p>
<p>Im Grunde wird bei der logistischen Regression die Wahrscheinlichkeit des Erfolgs (was auch immer das ist: Kopf bei einem Münzwurf, Überleben eines Unglücks ja/nein, befördert ja/nein, <em>oder besonders im psychologischen oder medizinischen Kontext relevant:</em> erkrankt ja/nein, genesen ja/nein etc.) modelliert, welche eigentlich einfach wieder dem Mittelwert entspricht (bzw. der bedingten Erwartung). Die Funktion in <code>R</code> hierzu heißt <code>glm</code>, was für <strong>G</strong>eneralized <strong>L</strong>inear <strong>M</strong>odel steht. Um den Wertebereich der AV einzuhalten, wird die Erfolgswahrscheinlichkeit so transformiert, dass sie linear durch die UVs vorhergesagt werden kann, aber die Wahrscheinlichkeit trotzdem zwischen 0 und 1 liegt. Gehen wir bspw. von zwei Prädiktoren <span class="math inline">\(X_1\)</span> und <span class="math inline">\(X_2\)</span> aus:</p>
<p><span class="math display">\[\begin{align*}
p &amp;= \mathbb{P}(Y = 1 | X_1 = x_1, X_2 = x_2) = \frac{e^{\beta_0 + \beta_1x_1 + \beta_2x_2}}{1 + e^{\beta_0 + \beta_1x_1 + \beta_2x_2}}\\[2ex]
odds(p) &amp; = \frac{\mathbb{P}(Y = 1 | X_1 = x_1, X_2 = x_2)}{1-\mathbb{P}(Y = 1 | X_1 = x_1, X_2 = x_2)} = e^{\beta_0 + \beta_1x_1 + \beta_2x_2}\\[2ex]
logit(p) &amp;  = \ln\left(\frac{\mathbb{P}(Y = 1 | X_1 = x_1, X_2 = x_2)}{1-\mathbb{P}(Y = 1 | X_1 = x_1, X_2 = x_2)}\right) = \beta_0 + \beta_1x_1 + \beta_2x_2
\end{align*}\]</span></p>
<p>Hier ist <span class="math inline">\(\ln\)</span> der natürlich Logarithmus zur Basis <span class="math inline">\(e\)</span> (<span class="math inline">\(e\)</span> ist die Eulersche Zahl <span class="math inline">\(\approx 2.718282\)</span>). Der <span class="math inline">\(logit\)</span> stellt hierbei die Link-Funktion dar, die den Erwartungswert den wir Untersuchen wollen, linear durch die Prädiktoren darstellen lässt. Die <span class="math inline">\(odds\)</span> und <span class="math inline">\(p\)</span> sind dann nur Retransformationen, die aus der Link-Funktion resultieren. Einige Wiederholungen zu Exponenten- oder Logarithmusregeln können Sie am Anfang der <a href="/post/nichtlineare-regression">Sitzung zu exponentiellem Wachstum aus dem Bachelor</a> nachlesen.</p>
<p>Eine Schreibweise für die normale Regression ist <span class="math inline">\(\mathbb{E}[Y | X_1 = x_1, X_2 = x_2]=\beta_0 + \beta_1x_1 + \beta_2x_2\)</span>. Gilt für <span class="math inline">\(Y=0,1\)</span>, so ist <span class="math inline">\(\mathbb{E}[Y | X_1 = x_1, X_2 = x_2] = \mathbb{P}(Y = 1 | X_1 = x_1, X_2 = x_2)=p\)</span>, also der (bedingte) Mittelwert über <span class="math inline">\(Y\)</span> ist die (bedingte) Wahrscheinlichkeit, dass <span class="math inline">\(Y=1\)</span> (wie wir oben am Münzwurfbeispiel gesehen haben). Somit ist ersichtlich, dass bei der logistischen Regression im Grunde nichts anderes als der (bedingte) Mittelwert/die (bedingte) Erwartung, dass <span class="math inline">\(Y=1\)</span> ist, modelliert wird.</p>
</div>
<div id="analysen-mit-dem-beispieldatensatz" class="section level2">
<h2>Analysen mit dem Beispieldatensatz</h2>
<p>Um die Probleme einer normalen Regression besser zu erkennen, führen wir eine solche durch.</p>
<div id="hypothese-1-alter-als-prädiktor" class="section level3">
<h3>Hypothese 1: Alter als Prädiktor</h3>
<p>Für die erste Hypothese müssen wir den Einfluss des Alters auf die Überlebenswahrscheinlichkeit (im logistischen Regressionsfall) bzw. das Überleben (im linearen Regressionsfall) bestimmen.</p>
<div id="lineares-modell-einfache-regressionsanalyse" class="section level4">
<h4>Lineares Modell: Einfache Regressionsanalyse</h4>
<p>Wir nennen unser Modell zur Modellierung des Überlebens <code>reg_model</code>.</p>
<pre class="r"><code>library(lm.beta) # std. Koeffizienten
reg_model &lt;- lm(survived ~ 1 + age, data = Titanic)
summary(lm.beta(reg_model))</code></pre>
<pre><code>## 
## Call:
## lm(formula = survived ~ 1 + age, data = Titanic)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.4811 -0.4158 -0.3662  0.5789  0.7252 
## 
## Coefficients:
##              Estimate Standardized Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.483753     0.000000   0.041788  11.576   &lt;2e-16 ***
## age         -0.002613    -0.077221   0.001264  -2.067   0.0391 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4903 on 712 degrees of freedom
## Multiple R-squared:  0.005963,   Adjusted R-squared:  0.004567 
## F-statistic: 4.271 on 1 and 712 DF,  p-value: 0.03912</code></pre>
<p>Laut der einfachen Regressionsanalyse scheint das Alter nur gering mit dem Überleben des Unglücks zusammenzuhängen. Wir führen noch einige Analysen zur Diagnostik durch.</p>
<pre class="r"><code>library(car) # nötiges Paket laden</code></pre>
<pre class="r"><code>avPlots(model = reg_model, pch = 16)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>residualPlots(model = reg_model, pch = 16)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-7-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>##            Test stat Pr(&gt;|Test stat|)
## age           1.5925           0.1117
## Tukey test    1.5925           0.1113</code></pre>
<pre class="r"><code>library(MASS)# nötiges Paket laden
res &lt;- studres(reg_model) # Studentisierte Residuen als Objekt speichern
hist(res, freq = F)
xWerte &lt;- seq(from = min(res), to = max(res), by = 0.01)
lines(x = xWerte, y = dnorm(x = xWerte, mean = mean(res), sd = sd(res)), lwd = 3)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-7-3.png" width="672" style="display: block; margin: auto;" /></p>
<p>Den Verteilungen der Residuen können wir deutlich entnehmen, dass diese höchst systematisch ausfallen (mit steigendem Alter fallen die Residuen linear ab) und auch die Normalverteilungsannahme ist deutlich verletzt. Eine Regression erscheint nicht sinnvoll. Den Ergebnisse der Signifikanzentscheidungen kann nicht getraut werden. Wir müssen uns also irgendwie anders mit den Daten auseinandersetzen!</p>
</div>
</div>
<div id="generalisiertes-lineares-modell-logistische-regressionsanalyse" class="section level3">
<h3>Generalisiertes Lineares Modell: Logistische Regressionsanalyse</h3>
<p>Nun wollen wir eine logistische Regressionsanlyse durchführen. In dieser werden die Residuen nicht länger als normalverteilt angenommen, sondern die AV wird als (bedingt) binomialverteilt modelliert. Wir nennen das Modell <code>m1</code>, da es die erste Hypothese untersucht. Die Funktion <code>glm</code> übernimmt für uns die richtige Transformation, nämlich den Logit als Link-Funktion, indem wir noch das Zusatzargument <code>family = "binomial"</code> festlegen. Die Binomialverteilung ist gerade jene Verteilung, die beschreibt, wie häufig bei <span class="math inline">\(n\)</span> Versuchen Erfolg eintritt (also genau die richtige Verteilung für unser Modell!).</p>
<pre class="r"><code>m1 &lt;- glm(survived ~ 1 + age, family = &quot;binomial&quot;, data = Titanic)
summary(m1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = survived ~ 1 + age, family = &quot;binomial&quot;, data = Titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.1488  -1.0361  -0.9544   1.3159   1.5908  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) -0.05672    0.17358  -0.327   0.7438  
## age         -0.01096    0.00533  -2.057   0.0397 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 964.52  on 713  degrees of freedom
## Residual deviance: 960.23  on 712  degrees of freedom
## AIC: 964.23
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Der Output der Summary unterscheidet sich geringfügig von der der normalen Regressionsanalyse:</p>
<pre><code>## 
##  Call:
##  glm(formula = survived ~ 1 + age, family = &quot;binomial&quot;, data = Titanic)
## 
##  Deviance Residuals: 
##      Min       1Q   Median       3Q      Max  
##  -1.1488  -1.0361  -0.9544   1.3159   1.5908</code></pre>
<p>zeigt uns, dass wir kein <code>lm</code>-Objekt sondern ein <code>glm</code>-Objekt vor uns haben. Außerdem werden uns dieses Mal <code>Deviance Residuals</code> angezeigt anstatt normale Residuen. Das Schätzverfahren ist ein anderes. Es wird nicht das Kleinste-Quadrate-Verfahren angewandt, sondern die Maximum-Likelihood-Schätzmethode (ML).</p>
<pre><code>## 
##  Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)
##  (Intercept) -0.05672    0.17358  -0.327   0.7438  
##  age         -0.01096    0.00533  -2.057   0.0397 *
##  ---
##  Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Der Überblick über die (ML-)Parameterschätzung unterscheidet sich kaum von der normalen Regression. Lediglich die <span class="math inline">\(t\)</span>-Werte werden durch <span class="math inline">\(z\)</span>-Werte ersetzt. Die Idee hinter der Signifikanzentscheidung ist aber komplett identisch (außerdem geht die <span class="math inline">\(t\)</span>-Verteilung für große <span class="math inline">\(n\)</span> in die <span class="math inline">\(z\)</span>-(Standardnormal-)Verteilung über). Hier scheint sich ein signifikanter Effekt des Alters zu zeigen.</p>
<pre><code>##      Null deviance: 964.52  on 713  degrees of freedom
##  Residual deviance: 960.23  on 712  degrees of freedom
##  AIC: 964.23
## 
##  Number of Fisher Scoring iterations: 4</code></pre>
<p>In diesem Abschnitt werden die Devianzen angezeigt. Diese beschreiben gerade die Log-Likelihooddifferenz zum saturierten Modell (also de facto die Abweichung des Modells zu den Daten). Die <code>Null deviance</code> beschreibt hier den Unterschied eines Modells ohne Prädiktoren zu den Daten. Dieses hat hier <code>713</code> Freiheitsgrade. Unter <code>Residual deviance</code> wird nun die Devianz unseres angenommenen Modells verstanden. Da wir einen Prädiktor mit in das Modell aufgenommen haben (das Alter), geht ein Freiheitsgrad für diesen Parameter verloren, weswegen die Residualdevianz hier <code>712</code> Freiheitsgrade hat (siehe bspw. <a href="https://ubffm.hds.hebis.de/Record/HEB366849158">Eid, et al., 2017,</a> Kapitel 22.8 und insbesondere Seiten 823-824). Der AIC (Akaike’s Information Criterion) unseres Modells liegt bei <code>AIC: 964.23</code>. Mit Hilfe dieses AICs können auch nicht geschachtelte Modelle sowie Modelle mit unterschiedlichen Annahmen verglichen werden. Eine Signifikanzentscheidung ist allerdings nicht möglich (siehe bspw. <a href="https://ubffm.hds.hebis.de/Record/HEB366849158">Eid, et al., 2017,</a> Seite 750). <code>Number of</code> <code>Fisher Scoring</code> <code>iterations: 4</code> gibt an, wie lange der Fisher-Scoring-Algorithmus gebraucht hat, um die Standardfehler zu bestimmen. Dies kann Auskunft über mögliche Konvergenzschwierigkeiten liefern. Hier ist ein Wert von 4 aber sehr niedrig!</p>
<div id="fazit-der-analyse" class="section level4">
<h4>Fazit der Analyse</h4>
<p>Der Effekt des Alters ist statistisch signifikant. Wir haben dieses Mal ein sinnvolleres Modell eingesetzt, was bedeutet, dass wir den Ergebnissen eher trauen können. Insgesamt stützen die Daten unsere erste Hypothese. Allerdings ist dieser Effekt sehr klein (dazu später mehr, wenn wir zur Ergebnisinterpretation und zur Einordnung der Koeffizienten kommen). Wenn wir den Wertebereich entlang der x-Achse sehr/unrealistisch groß wählen und das Alter von -500 bis 500 laufen lassen, so können wir uns die linearen und nichtlinearen Beziehungen zwischen Alter und Logit und Alter und Odds und Wahrscheinlichkeit ansehen, andernfalls ist der Effekt so klein, dass wir kaum etwas erkennen. <code>m_age$coefficients[1] +</code> <code>m_age$coefficients[2]*AltersWerte</code> ist hierbei die Formel für den Logit, da die Parameterschätzungen einfach die <span class="math inline">\(\beta\)</span>-Koeffizienten sind, welche linear verknüpft den Logit ergeben. Wir könnten hier auch mit <code>predict</code> arbeiten, um die vorhergesagten Werte des Logit dieser Analyse zu erhalten – allerdings nur für jede Person und nicht für ein hypothetisches Alter von -500 bis 500. Glücklicherweise sind Logit, Odds und Wahrscheinlichkeit sehr leicht ineinander überführbar:</p>
<pre class="r"><code>AltersWerte &lt;- seq(-500, 500, 0.1)
logit &lt;- m1$coefficients[1] + m1$coefficients[2]*AltersWerte 
plot(x = AltersWerte, y = logit, type = &quot;l&quot;, col = &quot;blue&quot;, lwd = 3)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>odds &lt;- exp(logit)
plot(x = AltersWerte, y = odds, type = &quot;l&quot;, col = &quot;blue&quot;, lwd = 3)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-12-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>p &lt;- odds/(1 + odds)
plot(x = AltersWerte, y = p, type = &quot;l&quot;, col = &quot;blue&quot;, lwd = 3)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-12-3.png" width="672" style="display: block; margin: auto;" /></p>
<p><code>type = "l"</code> fordert eine Linie anstatt von Punkten an, <code>lwd = 3</code> sagt, dass diese Linie dreimal so dick wie der Default sein soll und <code>col = "blue"</code> sagt, dass die Linie blau sein soll. Wir erkennen in allen drei Plots die negative Beziehung zwischen Überleben und Alter. Der Logit ist eine lineare Funktion (Wertebereich [<span class="math inline">\(-\infty\)</span>,<span class="math inline">\(\infty\)</span>]). Somit steigt (bzw. sinkt) der Logit um <span class="math inline">\(\beta_1\)</span>, wenn der Prädiktor (hier Alter) um eine Einheit erhöht wird. Die Odds sind eine Exponentialfunktion (Wertebereich [0,<span class="math inline">\(\infty\)</span>]) und bei der Wahrscheinlichkeit handelt es sich um eine sogenannte Ogive (Wertebereich [0,1]). Die Odds steigen (bzw. sinken) um den Faktor <span class="math inline">\(e^{\beta_1}\)</span> (auch Odds-Ratio genannt), wenn der Prädiktor (hier Alter) um eine Einheit erhöht wird - die Beziehung zwischen Odds und Prädiktor ist somit multiplikativ! Wir schauen uns die Parameterinterpretation der Odds im nächsten Abschnitt genauer an. Wie sich die Wahrscheinlichkeit verändert, ist nicht pauschal zu sagen. Diese Veränderung hängt von der Ausprägung des Prädiktors ab und lässt sich nicht durch eine einzige Zahl quantifizieren. Wir erkennen aber, dass die Ogive erst deutlich nach einem Alter von Null nach links laufend flacher gegen 1 geht. Im Intervall von 0 bis 80 (also realistischem Alter) ist die Wahrscheinlichkeit zu überleben kleiner als 50% und fallend mit dem Alter. In <a href="#AppendixA">Appendix A</a> haben Sie die Möglichkeit, spielerisch die Einflüsse der Parameter in der logistischen Regression kennen zu lernen.</p>
</div>
</div>
<div id="hypothese-2" class="section level3">
<h3>Hypothese 2</h3>
<p>Nun wollen wir das Geschlecht mit in unser Modell aufnehmen und somit Hypothese 2 untersuchen. Da das Geschlecht hier auch nur 2 Ausprägungen hat, kann dieser Effekt als Vergleich zwischen Gruppen verstanden werden. Intern wird dann mit “Dummy”-Variablen gerechnet. Wir können sicher gehen, dass mit “Dummy”-Variablen gerechnet wird (dies ist analog dazu, dass wir das Geschlecht mit 0 und 1 kodieren, anstatt 1 und 2 - so wie wir dies in den anderen Sitzungen getan hatten!), indem wir <code>R</code> sagen, dass es sich bei der Variable Geschlecht um einen “Faktor” handelt, der Gruppenzugehörigkeit symbolisiert. Wir können prüfen, ob diese Variable ein Faktor ist, indem wir <code>is.factor</code> auf die Variable <code>sex</code> anwenden.</p>
<pre class="r"><code>is.factor(Titanic$sex)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Es scheint sich also um einen Faktor zu handeln. Falls dies nicht der Fall gewesen wäre, so hätten wir <code>as.factor</code> auf die Variable anwenden können. Wäre das Geschlecht über Strings kodiert (bspw. “m” und “w”), so würde <code>R</code> dies automatisch in einen Faktor umwandeln, sobald es in einem Modell als Variable verwendet wird. Mit der Funktion <code>table</code> erhalten wir einen Überblick über die Kombination an Überlebenden und dem Geschlecht.</p>
<pre class="r"><code>table(Titanic$survived, Titanic$sex)</code></pre>
<pre><code>##    
##       2   1
##   0 360  64
##   1  93 197</code></pre>
<p>In der Tabelle wird entlang der Spalten das Geschlecht vs. der Überlebensstatus in den Zeilen abgetragen. Dieser Tabelle ist zu entnehmen, dass der relative Anteil an Frauen, die das Unglück überlebt haben, höher ist als der der Männer: 197 vs. 64 für die Frauen und 93 vs. 360 für die Männer. Auch absolut gesehen haben mehr Frauen das Unglück überlebt. Folglich würden wir einen Geschlechtereffekt erwarten. Diese 4-Feldertafel könnten wir auch heranziehen, um einen <span class="math inline">\(\chi^2\)</span>-Unabhängigkeitstest durchzuführen. Wir wollen aber den Effekt des Geschlechts über das Alter hinaus auf die Überlebenswahrscheinlichkeit des Titanicunglücks modellieren:</p>
<pre class="r"><code>m2 &lt;-  glm(survived ~ 1 + age + sex, family = &quot;binomial&quot;, data = Titanic)
summary(m2)</code></pre>
<pre><code>## 
## Call:
## glm(formula = survived ~ 1 + age + sex, family = &quot;binomial&quot;, 
##     data = Titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.7405  -0.6885  -0.6558   0.7533   1.8989  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.188647   0.222432  -5.344  9.1e-08 ***
## age         -0.005426   0.006310  -0.860     0.39    
## sex1         2.465920   0.185384  13.302  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 964.52  on 713  degrees of freedom
## Residual deviance: 749.96  on 711  degrees of freedom
## AIC: 755.96
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Das besondere an diesem Output ist, dass bei der Variable Geschlecht eine kleine <code>1</code> dahinter steht:</p>
<pre><code>##  Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)
##  (Intercept) -1.188647   0.222432  -5.344  9.1e-08 ***
##  age         -0.005426   0.006310  -0.860     0.39    
##  sex1         2.465920   0.185384  13.302  &lt; 2e-16 ***</code></pre>
<p>Dies gibt an, dass hier dummy-kodiert wurde und der Effekt von 1 (Frauen) im Vergleich zur Referenzgruppe (also 2, der Männer) dargestellt ist. Wir bekommen einen Überblick über die Kodierung, indem wir entweder die Variable Geschlecht ansehen oder die Funktion <code>levels</code> auf das Geschlecht anwenden:</p>
<pre class="r"><code>Titanic$sex</code></pre>
<pre><code>##   [1] 2 2 1 1 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 2 1 2 2 2 2 2 1 1 2 1 1 1 2
##  [38] 2 2 1 1 1 1 1 1 2 2 1 2 2 2 1 1 1 2 1 1 1 1 2 1 2 2 1 1 2 2 2 2 1 2 1 1 1
##  [75] 1 2 1 2 2 1 2 1 2 2 2 2 2 2 2 1 1 2 1 1 1 2 1 2 2 1 2 2 2 1 1 2 2 2 2 1 2
## [112] 2 2 2 1 1 1 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 1 2 2 2 2 1 1 2 2 2 2 2 2 2 1
## [149] 2 1 1 2 1 1 1 1 2 1 1 1 1 2 2 1 2 2 2 2 1 2 2 1 1 2 1 1 1 2 2 2 2 2 2 1 2
## [186] 1 1 2 1 1 1 2 2 2 2 1 2 1 2 2 1 1 1 1 2 2 1 2 1 1 2 2 1 2 2 2 2 1 2 2 2 1
## [223] 2 2 2 2 2 2 2 1 1 1 2 2 2 2 1 2 2 2 2 1 2 2 2 2 2 1 1 2 1 2 1 1 2 1 1 2 2
## [260] 2 1 1 2 2 2 1 1 2 1 1 1 1 1 2 1 2 2 2 1 2 2 2 2 2 1 2 2 2 1 2 2 2 2 2 1 1
## [297] 1 1 1 2 1 2 2 1 1 2 1 2 1 2 1 1 2 2 2 2 1 1 1 2 2 2 2 1 2 2 2 2 2 1 2 1 1
## [334] 1 1 2 2 2 1 2 1 2 2 2 2 2 1 2 2 1 2 1 1 2 2 2 1 1 2 2 1 2 2 2 2 2 1 2 1 1
## [371] 2 1 1 2 2 2 1 2 2 1 1 1 2 1 2 2 1 2 1 2 2 2 2 2 1 2 2 1 2 1 1 2 1 2 1 2 2
## [408] 2 1 2 1 1 2 1 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 1
## [445] 1 2 1 2 2 2 2 1 2 2 1 2 2 1 1 2 2 2 2 2 2 1 2 1 2 1 2 1 2 2 2 2 2 1 2 2 2
## [482] 2 2 1 2 1 1 2 1 2 2 2 2 2 2 1 2 1 1 2 1 1 2 2 1 1 2 2 2 2 1 1 2 2 2 2 1 2
## [519] 2 2 2 1 1 2 2 2 2 1 2 2 2 2 1 1 2 2 2 2 2 2 2 2 2 1 1 2 2 1 2 2 2 1 1 1 2
## [556] 1 1 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 1 1 2 1 2 2 2 1 1 1 1 2 1 1 1 2 2 2 2 2
## [593] 2 1 2 2 2 1 2 1 2 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 1 2 2 2 1 2 2 1 2 2 1 1
## [630] 2 2 2 2 2 1 1 2 1 2 2 1 2 1 1 2 2 1 2 2 2 2 2 1 1 1 2 1 2 1 1 1 2 1 2 2 2
## [667] 1 1 2 2 1 2 2 1 2 1 2 2 1 1 2 2 1 2 2 2 2 2 2 2 1 2 1 2 1 2 2 2 2 2 2 2 2
## [704] 2 2 2 2 1 2 2 2 1 2 2
## Levels: 2 1</code></pre>
<pre class="r"><code>levels(Titanic$sex)</code></pre>
<pre><code>## [1] &quot;2&quot; &quot;1&quot;</code></pre>
<p>Bei ersterer Wahl wird, nachdem alle Ausprägungen ausgegeben wurden, <code>## Levels: 2 1</code> dargestellt. Dies ist der gleiche Output, den auch die Funktion <code>levels</code> erzeugt. Er ist folgendermaßen zu verstehen: es gibt hier zwei Faktoren/Gruppenzugehörigkeiten/Kategorien, wobei der Faktor mit dem Namen 2 (also die Männer) als Referenz für die Kodierung verwendet wird. Somit sind alle Effekt immer im Vergleich zur Referenzkategorie zu interpretieren. Mit Hilfe von <code>relevel</code> könnten wir die Referenzkategorie ändern und dann der Variable erneut zuordnen via <code>Titanic$sex_relevel &lt;-</code> <code>relevel(Titanic$sex, ref = "1")</code> (hier würde eine neue Variable mit mit dem Namen <code>sex_relevel</code> dem Datensatz angehängt werden, in welchem die Frauen die Referenzkategorie darstellen würden).</p>
<div id="ergebnisinterpretation" class="section level4">
<h4>Ergebnisinterpretation</h4>
<p>Die <span class="math inline">\(\beta\)</span>-Gewichte zu interpretieren, hat wenig inhaltliche Aussagekraft. Wir könnten bspw. für das Geschlecht lediglich die Aussage treffen, dass (unter Konstanthaltung aller weiteren Prädiktoren im Modell), wenn Frauen im Vergleich zu Männern betrachtet werden, der Logit (der Überlebenswahrscheinlichkeit) um 2.46 steigt. Wenn wir allerdings anstatt des Logits die Odds heranziehen, so können wir mit Hilfe des Odds-Ratio doch eine Aussage über die Überlebenswahrscheinlichkeit treffen. Dazu müssen wir die <span class="math inline">\(\beta\)</span>-Gewichte transformieren via <span class="math inline">\(e^\beta\)</span>:</p>
<pre class="r"><code>exp(m2$coefficients) # Odds-Ratios</code></pre>
<pre><code>## (Intercept)         age        sex1 
##   0.3046332   0.9945888  11.7743113</code></pre>
<p>Nun können wir die Ergebnisse (einigermaßen) sinnvoll interpretieren. Das Interzept wird an der Stelle interpretiert, wo alle Prädiktoren den Wert 0 annehmen. Das Alter am Wert 0 ist wenig sinnvoll, wir könnten uns allerdings einen Säugling vorstellen, der ein Alter von 0 Jahren hat. Außerdem ist noch die Variable <code>sex1</code> im Modell. Dies ist eine Dummy-Variable, die den Wert 1 annimmt, wenn das Geschlecht den Wert 1 (im Vergleich zu 2; der Referenzkategorie) annimmt; also wenn wir eine Frau im Vergleich zu einem Mann betrachten. Folglich hat diese Dummy-Variable gerade den Wert 0, wenn ein Mann betrachtet wird. Wir interpretieren das Interzept bzgl. der Odds wie folgt: Ein männlicher Säugling hat Überlebens-Odds von 0.305. Dies bedeutet, dass es für ihn 0.305-mal so wahrscheinlich ist zu überleben wie nicht zu überleben. Leider spricht dieses Ergebnis für recht schlechte Aussichten. Der Effekt des Alters lässt sich wie folgt interpretieren: Steigt das Alter um 1 Jahr (unter Konstanthaltung aller weiteren Prädiktoren im Modell), so verändern sich die Odds zu überleben um den Faktor (multiplikativ) 0.995. Insgesamt sinken die Odds zu überleben und damit die Überlebenswahrscheinlichkeit mit dem Alter, denn das Odds-Ratio ist genau dann kleiner 1, wenn der <span class="math inline">\(\beta\)</span>-Koeffizient des Logit kleiner 0 ist und es sich somit um eine negative/abfallende Beziehung handelt! Dieser Effekt ist allerdings nicht statistisch signifikant und wird somit nur für die Stichprobe, nicht aber für die Population interpretiert. Wird nun eine Frau im Vergleich zu einem Mann betrachtet, so steigen die Odds zu überleben um den Faktor 11.774. Somit haben (unter Konstanthaltung aller weiteren Prädiktoren im Modell) Frauen eine 11.774 mal so hohe Überlebenswahrscheinlichkeit wie die Männer. Hier ist extrem wichtig, zu beachten, dass die Odds sich multiplikativ ändern und nicht additiv, wie wir es von der linearen Regression (und im Übrigen auch vom Logit) gewohnt sind.</p>
</div>
<div id="grafische-veranschaulichung" class="section level4">
<h4>Grafische Veranschaulichung</h4>
<p>Wir können uns dieses Modell auch grafisch ansehen und damit die oben aufgezeigten Effekte verdeutlichen. Dazu werden wir diesmal <code>ggplot</code> aus dem <code>ggplot2</code> Paket verwenden. Dieses muss natürlich installiert sein (<code>install.packages("ggplot2")</code>) und geladen werden.</p>
<pre class="r"><code>library(ggplot2)</code></pre>
<p>Wir können hier sehr leicht Gruppierungen in Grafiken darstellen. Zunächst müssen wir allerdings die Prädiktionen unseres Modells bestimmen, denn wir wollen uns die Vorhersage/Erwartung (unter) unseres Modells ansehen. Die Funktion, mit der wir dies machen können, heißt genauso wie die Funktion die sie ausführt: <code>predict</code>. Wir sagen damit den Logit für alle Konstellationen von Alter und Geschlecht in unseren Daten vorher, indem wir der Funktion das Modell übergeben. Wir bestimmen also für jede Personen die erwartete Überlebenswahrscheinlichkeit unter diesem Modell (der Prädiktion durch Geschlecht und Alter). Anschließend können wir den Logit so transformieren, dass wir die Odds oder die Wahrscheinlichkeit erhalten. Um dies leichter nachvollziehbar zu machen, führen wir die Transformationen mit neu erstellten Variablen durch, ehe wir diese dem Datensatz anhängen (denn <code>ggplot</code> hat es am liebsten, wenn wir mit <code>data.frames</code>, also ganzen Datensätzen arbeiten).</p>
<pre class="r"><code>logit_m2 &lt;- predict(m2)           # Logit unter Modell m2 bestimmen
odds_m2 &lt;- exp(logit_m2)          # Logit unter Modell m2 in Odds transformieren
p_m2 &lt;- odds_m2/(1 + odds_m2)     # Odds in Wahrscheinlichkeiten transformieren
  
# dem Datensatz anhängen:
Titanic$logit_m2 &lt;- logit_m2
Titanic$odds_m2 &lt;- odds_m2
Titanic$p_m2 &lt;- p_m2

head(Titanic)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">survived</th>
<th align="left">pclass</th>
<th align="left">sex</th>
<th align="right">age</th>
<th align="right">logit_m2</th>
<th align="right">odds_m2</th>
<th align="right">p_m2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">1</td>
<td align="left">2</td>
<td align="right">28</td>
<td align="right">-1.340572</td>
<td align="right">0.2616959</td>
<td align="right">0.2074160</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="right">36</td>
<td align="right">-1.383979</td>
<td align="right">0.2505794</td>
<td align="right">0.2003707</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="left">2</td>
<td align="left">1</td>
<td align="right">3</td>
<td align="right">1.260995</td>
<td align="right">3.5289329</td>
<td align="right">0.7791974</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">2</td>
<td align="left">1</td>
<td align="right">40</td>
<td align="right">1.060237</td>
<td align="right">2.8870558</td>
<td align="right">0.7427359</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="right">32</td>
<td align="right">-1.362276</td>
<td align="right">0.2560774</td>
<td align="right">0.2038707</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="left">2</td>
<td align="left">2</td>
<td align="right">34</td>
<td align="right">-1.373128</td>
<td align="right">0.2533135</td>
<td align="right">0.2021150</td>
</tr>
</tbody>
</table>
<p>Eine Grafik erhalten wir nun mit <code>ggplot</code> sehr einfach:</p>
<pre class="r"><code>ggplot(data = Titanic, mapping = aes(x = age, y = logit_m2, col = sex)) +
        geom_line(lwd = 2) +
        ggtitle(&quot;Logit vs Age and Sex&quot;)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-22-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><code>ggplot</code> arbeitet etwas anders als die Basisfunktion <code>plot</code>. Zunächst übergeben wir ihr die Daten <code>data = Titanic</code>. Dem <code>mapping</code> übergeben wir sozusagen das Achsenkreuz und Gruppenzugehörigkeiten und Farbkodierungen innerhalb von <code>aes(x = age, y = logit_m2, col = sex)</code>. Hier wird gesagt, dass das Alter auf die x-Achse soll und wir den Logit entlang der y-Achse plotten wollen. Außerdem soll für das Geschlecht eine separate Linie eingezeichnet werden und diese soll farblich kodiert sein. Damit dies funktioniert, müssen natürlich die Variablen im richtigen Format vorliegen. Bspw. müssen Gruppierungen, wie etwa das Geschlecht, als Faktor vorliegen. Anschließend fügen wir mit <code>+</code> hinzu, was genau geplottet werden soll. In diesem Beispiel wollen wir Linien haben. Deshalb verwenden wir die Funktion <code>geom_line</code> mit dem Argument <code>lwd = 2</code> für zweifache Liniendicke. Würden wir hier bspw. <code>geom_point</code> verwenden, so würden Punkte gezeichnet werden. Wieder mit dem <code>+</code> fügen wir außerdem einen Titel hinzu mit der Funktion <code>ggtitle</code>. Gleiches können wir auch für die Odds oder die Wahrscheinlichkeit durchführen:</p>
<pre class="r"><code>ggplot(data = Titanic, mapping = aes(x = age, y = odds_m2, col = sex)) +
        geom_line(lwd = 2) +
        ggtitle(&quot;Odds vs Age and Sex&quot;)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-23-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(data = Titanic, mapping = aes(x = age, y = p_m2, col = sex)) +
        geom_line(lwd = 2) +
        ggtitle(&quot;P vs Age and Sex&quot;)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-24-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Einen drastischen Alterseffekt können wir in keiner der Grafiken erkennen. Dass sich Unterschiede über das Geschlecht abbilden, sehen wir allerdings recht deutlich! Weitere Informationen zu <code>ggplot2</code> erhalten Sie bspw. auf <a href="https://ggplot2.tidyverse.org"><svg aria-hidden="true" role="img" viewBox="0 0 640 512" style="height:1em;width:1.25em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M622.34 153.2L343.4 67.5c-15.2-4.67-31.6-4.67-46.79 0L17.66 153.2c-23.54 7.23-23.54 38.36 0 45.59l48.63 14.94c-10.67 13.19-17.23 29.28-17.88 46.9C38.78 266.15 32 276.11 32 288c0 10.78 5.68 19.85 13.86 25.65L20.33 428.53C18.11 438.52 25.71 448 35.94 448h56.11c10.24 0 17.84-9.48 15.62-19.47L82.14 313.65C90.32 307.85 96 298.78 96 288c0-11.57-6.47-21.25-15.66-26.87.76-15.02 8.44-28.3 20.69-36.72L296.6 284.5c9.06 2.78 26.44 6.25 46.79 0l278.95-85.7c23.55-7.24 23.55-38.36 0-45.6zM352.79 315.09c-28.53 8.76-52.84 3.92-65.59 0l-145.02-44.55L128 384c0 35.35 85.96 64 192 64s192-28.65 192-64l-14.18-113.47-145.03 44.56z"/></svg> Tidyverse</a>. Außerdem können Sie sich auch eine <a href="/post/grafiken-mit-ggplot2"><svg aria-hidden="true" role="img" viewBox="0 0 640 512" style="height:1em;width:1.25em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M622.34 153.2L343.4 67.5c-15.2-4.67-31.6-4.67-46.79 0L17.66 153.2c-23.54 7.23-23.54 38.36 0 45.59l48.63 14.94c-10.67 13.19-17.23 29.28-17.88 46.9C38.78 266.15 32 276.11 32 288c0 10.78 5.68 19.85 13.86 25.65L20.33 428.53C18.11 438.52 25.71 448 35.94 448h56.11c10.24 0 17.84-9.48 15.62-19.47L82.14 313.65C90.32 307.85 96 298.78 96 288c0-11.57-6.47-21.25-15.66-26.87.76-15.02 8.44-28.3 20.69-36.72L296.6 284.5c9.06 2.78 26.44 6.25 46.79 0l278.95-85.7c23.55-7.24 23.55-38.36 0-45.6zM352.79 315.09c-28.53 8.76-52.84 3.92-65.59 0l-145.02-44.55L128 384c0 35.35 85.96 64 192 64s192-28.65 192-64l-14.18-113.47-145.03 44.56z"/></svg> Einführung in <code>ggplot2</code></a> auf dieser Website ansehen.</p>
</div>
</div>
<div id="hypothese-3" class="section level3">
<h3>Hypothese 3</h3>
<p>Nun wollen wir die Reiseklasse mit in unser Modell aufnehmen und somit Hypothese 3 untersuchen. Die Klasse ist auch ein Faktor, der 3 Ausprägungen hat. Wir schauen uns die Level an:</p>
<pre class="r"><code>levels(Titanic$pclass)</code></pre>
<pre><code>## [1] &quot;3&quot; &quot;1&quot; &quot;2&quot;</code></pre>
<p>Die drei Klassen sind mit 1, 2 und 3 kodiert, wobei die 3. Klasse die Referenz ist (da sie an erster Stelle steht). Dies müssen wir bei der Interpretation berücksichtigen. Schauen wir uns die Ergebnisse an:</p>
<pre class="r"><code>m3 &lt;-  glm(survived ~ 1 + age + sex + pclass, family = &quot;binomial&quot;, data = Titanic)
summary(m3)</code></pre>
<pre><code>## 
## Call:
## glm(formula = survived ~ 1 + age + sex + pclass, family = &quot;binomial&quot;, 
##     data = Titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7303  -0.6780  -0.3953   0.6485   2.4657  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.326394   0.247892  -5.351 8.76e-08 ***
## age         -0.036985   0.007656  -4.831 1.36e-06 ***
## sex1         2.522781   0.207391  12.164  &lt; 2e-16 ***
## pclass1      2.580625   0.281442   9.169  &lt; 2e-16 ***
## pclass2      1.270826   0.244048   5.207 1.92e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 964.52  on 713  degrees of freedom
## Residual deviance: 647.28  on 709  degrees of freedom
## AIC: 657.28
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Dieses Mal sind alle Prädiktoren signifikant - auch das <em>Alter.</em> Bevor wir zur Interpretation übergehen, wollen wir die Hinzunahme der Klasse noch insgesamt auf Signifikanz prüfen. Wir sehen am Output, dass jede Dummy-Variable für sich signifikante Vorhersagekraft leistet, allerdings wollen wir eine Signifikanzentscheidung für die Variable <em>Reiseklasse</em> als Ganzes durchführen und ziehen dazu den Likelihood-Ratio-Test (<span class="math inline">\(\chi^2\)</span>-Differenzen-Test) heran.</p>
<div id="modellvergleich" class="section level4">
<h4>Modellvergleich</h4>
<p>Diesen kennen wir bereits aus der <a href="/post/multi-level-modeling">hierarchischen Regressionssitzung</a>. Da wir hier keine Varianzen prüfen, können wir die <span class="math inline">\(p\)</span>-Werte so interpretieren, wie sie ausgegeben werden.</p>
<pre class="r"><code>anova(m2, m3, test = &quot;LRT&quot;)</code></pre>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: survived ~ 1 + age + sex
## Model 2: survived ~ 1 + age + sex + pclass
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1       711     749.96                          
## 2       709     647.28  2   102.67 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Der Test liefert eine signifikante Likelihood-Differenz, <span class="math inline">\(\chi^2(df=2)=\)</span> 102.674, <span class="math inline">\(p&lt;.001\)</span>. Der Test hat hier 2 Freiheitsgrade, da auch zwei Dummy-Variablen mit in das Modell aufgenommen wurden! <em>Hätten wir eine Gruppierungsvariable mit 5 Ausprägungen gehabt, so wären es 4 Freiheitsgrade gewesen.</em> Folglich verbessert die Klassenzugehörigkeit die Prädiktion der Überlebenswahrscheinlichkeit des Titanicunglücks.</p>
</div>
<div id="ergebnisinterpretation-1" class="section level4">
<h4>Ergebnisinterpretation</h4>
<p>Um die Ergebnisse sinnvoll zu interpretieren, schauen wir uns wieder die Odds-Ratios an:</p>
<pre class="r"><code>exp(m3$coefficients) # Odds-Ratio</code></pre>
<pre><code>## (Intercept)         age        sex1     pclass1     pclass2 
##   0.2654328   0.9636903  12.4632077  13.2053931   3.5637952</code></pre>
<p>Das Interzept wird an der Stelle interpretiert, an dem alle Prädiktoren den Wert 0 annehmen. Dies ist der Fall, wenn das Alter sowie alle Dummy-Variablen den Wert 0 annehmen, wir uns also für alle kategorialen Prädiktoren in der Referenzkategorie befinden. Somit hat ein männlicher Säugling aus der 3. Klasse eine um den Faktor 0.265 kleinere Wahrscheinlichkeit zu überleben im Vergleich zu zu sterben. Unter Konstanthaltung aller weiteren Prädiktoren im Modell sinken die Odds zu Überleben um den Faktor 0.964, wenn das Alter um ein Jahr steigt. Unter Konstanthaltung aller weiteren Prädiktoren im Modell steigen die Odds zu Überleben um den Faktor 12.463, wenn Frauen im Vergleich zu Männern betrachtet werden. Unter Konstanthaltung aller weiteren Prädiktoren im Modell steigen die Odds zu überleben um den Faktor 13.205, wenn eine Person aus der 1. Klasse im Vergleich zu einer Person aus der 3. Klasse betrachtet wird. Unter Konstanthaltung aller weiteren Prädiktoren im Modell steigen die Odds zu überleben um den Faktor 3.564, wenn eine Person aus der 2. Klasse im Vergleich zu einer Person aus der 3. Klasse betrachtet wird. Es scheint also so, dass je höher das Alter ist, desto geringer ist die Überlebenswahrscheinlichkeit, während je besser die Reiseklasse war, die Überlebenswahrscheinlichkeit höher ausfiel.</p>
</div>
<div id="grafische-veranschaulichung-1" class="section level4">
<h4>Grafische Veranschaulichung</h4>
<p>Die selbigen Ergebnisse wollen wir uns auch noch einmal grafisch ansehen. Dazu müssen wir wieder einer Prädiktion mittels unseres Modells <code>m3</code> durchführen. Die Prädiktion und das Anhängen an den Datensatz erfolgt analog zu oben:</p>
<pre class="r"><code>logit_m3 &lt;- predict(m3)           # Logit unter Modell m3 bestimmen
odds_m3 &lt;- exp(logit_m3)          # Logit unter Modell m3 in Odds transformieren
p_m3 &lt;- odds_m3/(1 + odds_m3)     # Odds in Wahrscheinlichkeiten transformieren
  
# dem Datensatz anhängen:
Titanic$logit_m3 &lt;- logit_m3
Titanic$odds_m3 &lt;- odds_m3
Titanic$p_m3 &lt;- p_m3

head(Titanic)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">survived</th>
<th align="left">pclass</th>
<th align="left">sex</th>
<th align="right">age</th>
<th align="right">logit_m2</th>
<th align="right">odds_m2</th>
<th align="right">p_m2</th>
<th align="right">logit_m3</th>
<th align="right">odds_m3</th>
<th align="right">p_m3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">1</td>
<td align="left">2</td>
<td align="right">28</td>
<td align="right">-1.340572</td>
<td align="right">0.2616959</td>
<td align="right">0.2074160</td>
<td align="right">0.2186443</td>
<td align="right">1.2443886</td>
<td align="right">0.5544444</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="right">36</td>
<td align="right">-1.383979</td>
<td align="right">0.2505794</td>
<td align="right">0.2003707</td>
<td align="right">-2.6578631</td>
<td align="right">0.0700979</td>
<td align="right">0.0655060</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="left">2</td>
<td align="left">1</td>
<td align="right">3</td>
<td align="right">1.260995</td>
<td align="right">3.5289329</td>
<td align="right">0.7791974</td>
<td align="right">2.3562576</td>
<td align="right">10.5513898</td>
<td align="right">0.9134303</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">2</td>
<td align="left">1</td>
<td align="right">40</td>
<td align="right">1.060237</td>
<td align="right">2.8870558</td>
<td align="right">0.7427359</td>
<td align="right">0.9878028</td>
<td align="right">2.6853277</td>
<td align="right">0.7286537</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="right">32</td>
<td align="right">-1.362276</td>
<td align="right">0.2560774</td>
<td align="right">0.2038707</td>
<td align="right">-2.5099221</td>
<td align="right">0.0812746</td>
<td align="right">0.0751655</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="left">2</td>
<td align="left">2</td>
<td align="right">34</td>
<td align="right">-1.373128</td>
<td align="right">0.2533135</td>
<td align="right">0.2021150</td>
<td align="right">-1.3130666</td>
<td align="right">0.2689939</td>
<td align="right">0.2119741</td>
</tr>
</tbody>
</table>
<p>Nun können wir die Grafiken analog zu oben erstellen, wobei wir lediglich die Benennung für die Farbe, die Linienform, das Modell sowie den Titel ein wenig abändern müssen. Das fantastische an <code>ggplot</code> ist nun, dass wir einfach eine neue Gruppierungsvariable in der <code>aes</code> vermerken können. Bspw. können wir mit <code>lty</code> die Linienart verändern. Wenn wir hier das Geschlecht festlegen, also <code>lty = sex</code>, dann wird für das Geschlecht jeweils eine eigene Linienart eingeführt (durchgezogen vs. gestrichelt). Wenn wir nun der Reiseklasse jeweils eine eigene Farbe geben (wie vorher dem Geschlecht) via <code>col = pclass</code>, dann erhalten wir einen sehr übersichtlichen Plot:</p>
<pre class="r"><code>ggplot(data = Titanic, mapping = aes(x = age, y = logit_m3, col = pclass, lty = sex)) +
     geom_line(lwd = 1) +
     ggtitle(&quot;Logit vs Age, Sex and Class&quot;)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-31-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(data = Titanic, mapping = aes(x = age, y = odds_m3, col = pclass, lty = sex)) +
     geom_line(lwd = 1) +
     ggtitle(&quot;Odds vs Age, Sex and Class&quot;)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-32-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(data = Titanic, mapping = aes(x = age, y = p_m3, col = pclass, lty = sex)) +
     geom_line(lwd = 1) +
     ggtitle(&quot;P vs Age, Sex and Class&quot;)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-33-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Alle drei Grafiken zeigen deutlich die Haupteffekte der Analyse: Die Überlebenswahrscheinlichkeit des Titanicunglücks sinkt mit dem Alter. Frauen haben eine höhere Überlebenswahrscheinlichkeit als Männer (bei vergleichbarem Alter) sowie deskriptiv gesprochen hatten Menschen die in der 1. Klasse reisen eine höhere Überlebenswahrscheinlichkeit als jene aus der 2. und 3. Klasse und die aus der 2. Klasse hatten ebenfalls eine höhere Überlebenswahrscheinlichkeit als jene aus der 3. Klasse (jeweils immer für vergleichbares Alter und Geschlecht). Der Zusatz “für vergleichbares Alter” ist im Grunde das Gleiche wie der Zusatz “unter Konstanthaltung aller weiteren Prädiktoren im Modell”, denn wir können schlecht die Überlebenswahrscheinlichkeit eines zwanzigjährigen Mannes aus der 1. Klasse mit der einer sechzigjährigen Frau aus der 3. Klasse vergleichen, denn dann wissen wir nicht, ob die Wahrscheinlichkeiten unterschiedlich sind, weil es sich um eine Frau oder einen Mann aus der jeweiligen Klasse handelt oder, ob es sich auf das Alter zurückführen lässt, oder ob eine Kombination der Variablen das Ergebnis erzeugt. Was wir aber tun können, ist für ein gleiches Alter die 6 Linien jeweils zu vergleichen! Außerdem erkennen wir insbesondere an der Modellierung des Logit oder der Wahrscheinlichkeit, dass Frauen, die in der 3. Klasse reisten, eine annähernd gleiche Überlebenswahrscheinlichkeit hatten wie Männer aus der 1. Klasse (erneut: jeweils für vergleichbares Alter!). Innerhalb der Geschlechter waren die Klassen allerdings auf die gleiche Art und Weise sortiert: <span class="math inline">\(1 &gt; 2 &gt; 3\)</span>. Insgesamt suggeriert dies also, dass dem Motto “<em>Frauen und Kinder zuerst</em>” Folge geleistet wurde.</p>
<p>Final können wir festhalten, dass wahrscheinlich alle drei Hypothesen erfüllt sind und sowohl das Alter als auch das Geschlecht und die Klassenzugehörigkeit die Überlebenswahrscheinlichkeit des Titanicunglücks beeinflussten.</p>
<hr />
</div>
</div>
</div>
<div id="r-skript" class="section level2">
<h2>R-Skript</h2>
<p>Den gesamten <code>R</code>-Code, der in dieser Sitzung genutzt wird, können Sie <a href="/post/MSc1_R_Files/4_Log_Reg_RCode.R"><svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M216 0h80c13.3 0 24 10.7 24 24v168h87.7c17.8 0 26.7 21.5 14.1 34.1L269.7 378.3c-7.5 7.5-19.8 7.5-27.3 0L90.1 226.1c-12.6-12.6-3.7-34.1 14.1-34.1H192V24c0-13.3 10.7-24 24-24zm296 376v112c0 13.3-10.7 24-24 24H24c-13.3 0-24-10.7-24-24V376c0-13.3 10.7-24 24-24h146.7l49 49c20.1 20.1 52.5 20.1 72.6 0l49-49H488c13.3 0 24 10.7 24 24zm-124 88c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm64 0c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20z"/></svg> hier herunterladen</a>.</p>
<hr />
</div>
<div id="appendix" class="section level2">
<h2>Appendix</h2>
<div id="AppendixA" class="section level3">
<h3>Appendix A</h3>
<details>
<summary>
<strong>Parametereinflüsse</strong>
</summary>
<p>Die folgende Funktion stellt vier Grafiken dar: den Logit, die Odds, die Wahrscheinlichkeit und die Wahrscheinlichkeit vs. eine Zufallserhebung. Sie können <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> dieses Modells so einstellen, wie Sie wünschen und können sich den Effekt auf die verschiedenen Darstellungsformen der logistischen Regression ansehen. In hellblau wird jeweils die Funktion mit <span class="math inline">\(\beta_0 = 0\)</span> und <span class="math inline">\(\beta_1 = 1\)</span> als Referenz dargestellt. Die gestrichelten Linien stellen jeweils die x- und die y-Achse dar. In roten Punkten werden Realisierungen von <span class="math inline">\(Y=0,1\)</span> dargestellt, die mit der angezeigten Wahrscheinlichkeit gezogen wurden. Um die Ergebnisse vergleichbar zu machen, wird <code>set.seed(1234)</code> verwendet (vgl. <a href="/post/einleitung-und-wiederholung">Einführungssitzung</a>).</p>
<pre class="r"><code>Logistic_functions &lt;- function(beta0 = 0, beta1 = 1)
{
        par(mfrow=c(2,2)) # 4 Grafiken in einer

        xWerte &lt;- seq(-5, 5, 0.1)
        logit &lt;- beta0 + beta1*xWerte
        plot(x = xWerte, y = logit, type = &quot;l&quot;, col = &quot;blue&quot;, lwd = 3, main = &quot;Logit vs X&quot;, xlab = &quot;X&quot;)
        lines(xWerte, xWerte, col = &quot;skyblue&quot;)
        abline(h = 0, lty = 3); abline(v = 0, lty = 3)

        odds &lt;- exp(logit)
        plot(x = xWerte, y = odds, type = &quot;l&quot;, col = &quot;blue&quot;, lwd = 3, main = &quot;Odds vs X&quot;, xlab = &quot;X&quot;)
        abline(h = 0, lty = 3); abline(v = 0, lty = 3)
        lines(xWerte, exp(xWerte), col = &quot;skyblue&quot;)

        p &lt;- odds/(1 + odds)
        plot(x = xWerte, y = p, type = &quot;l&quot;, col = &quot;blue&quot;, lwd = 3, main = &quot;P vs X&quot;, ylim = c(0,1), xlab = &quot;X&quot;)
        lines(xWerte, exp(xWerte)/(1 + exp(xWerte)), col = &quot;skyblue&quot;)
        abline(h = 0, lty = 3); abline(v = 0, lty = 3)

        set.seed(1234) # Vergleichbarkeit
        Y &lt;- rbinom(n = length(xWerte), size = 1, prob = p)
        plot(x = xWerte, y = p, type = &quot;l&quot;, col = &quot;blue&quot;, lwd = 3, main = &quot;P vs X und zufällige Realisierungen&quot;,
             ylim = c(0,1), xlab = &quot;X&quot;, ylab = &quot;P und Y&quot;)
        abline(h = 0, lty = 3); abline(v = 0, lty = 3)
        points(x = xWerte, y = Y, pch = 16, cex = .5, col = &quot;red&quot;)
}</code></pre>
<p>Sie führen diese Funktion aus, indem Sie alles von <code>Logistic_functions &lt;- function(beta0 = 0, beta1 = 1){</code> bis <code>}</code> kopieren und in Ihrem <code>R</code>-Studio Fenster ausführen, sodass in der Rubrik oben rechts (dort wo auch immer <code>Data</code> erscheint) unter <code>Functions</code> <code>Logistic_functions</code> als Funktion aufgeführt wird. Sie können sich bspw. die Konstellation für <span class="math inline">\(\beta_0 = 1\)</span> und <span class="math inline">\(\beta_1 = -0.5\)</span> im Vergleich zu <span class="math inline">\(\beta_0 = 0\)</span> und <span class="math inline">\(\beta_1 = 1\)</span> ansehen:</p>
<pre class="r"><code>Logistic_functions(beta0 = 1, beta1 = -.5)</code></pre>
<p><img src="/post/2020-10-27-MSc1_Sitzung4_Logistic_Regression_files/figure-html/unnamed-chunk-35-1.png" width="672" style="display: block; margin: auto;" /></p>
</details>
<hr />
</div>
</div>
<div id="literatur" class="section level2">
<h2>Literatur</h2>
<p><a href="https://ubffm.hds.hebis.de/Record/HEB366849158">Eid, M., Gollwitzer, M., &amp; Schmitt, M. (2017).</a> <em>Statistik und Forschungsmethoden</em> (5. Auflage, 1. Auflage: 2010). Weinheim: Beltz.</p>
<p><a href="https://ubffm.hds.hebis.de/Record/HEB371183324">Pituch, K. A. &amp; Stevens, J. P. (2016).</a> <em>Applied Multivariate Statistics for the Social Sciences</em> (6th ed.). New York: Taylor &amp; Francis.</p>
<ul>
<li><small> <em>Blau hinterlegte Autor:innenangaben führen Sie direkt zur universitätsinternen Ressource.</em> </small></li>
</ul>
</div>
