---
title: R Deskritpivstatistik - Übung
author: buchholz
date: '2020-09-24'
slug: r-deskriptiv-aufgaben
categories:
  - Bsc2
tags:
  - R Deskriprivstatistik
subtitle: ''
summary: ''
authors: [buchholz]
lastmod: '2020-09-24T21:07:11+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


### Vorbereitung

> Laden Sie die Daten aus `fb19.rda`. Die Bedeutung der einzelnen Variablen und ihre Antwortkategorien können Sie dem Dokument **Variablenübersicht.docx** entnehmen.


## Aufgabe 1

Untersuchen Sie, welche Arbeitsbranche Sie und Ihre Kommilitonen/innen nach dem Studium anstreben!  
 
* Vergeben Sie zunächst die korrekten Wertelabels an die Ausprägungen der Variable.  
* Lassen Sie sich absolute und relative Häufigkeiten ausgeben.  
* Untersuchen Sie, mit den geeigneten Maßen, die zentrale Tendenz und Dispersion dieser Variable.  


## Aufgabe 2

Die Variable `mdbf7` enthält die Angaben über das Ausmaß, in dem Sie und Ihre Kommilitonen/-innen sich zum Zeitpunkt des Ausfüllens "müde" fühlten.  
  
* Bestimmen Sie für diese Variable den Modus.     
* Untersuchen Sie die Streuung für diese Variable optisch, indem Sie einen Boxplot erstellen.  
* Bestimmen Sie die Quartile und den Interquartilsbereich (IQB) auch als Zahlen.


## Aufgabe 3

Erstellen Sie für die Variable `wohnen` eine geeignete Abbildung.   

* Stellen Sie sicher, dass die einzelnen Ausprägungen der Variable in der Darstellung interpretierbar benannt sind!  
* Dekorieren Sie diese Abbildung nach eigenen Wünschen (z.B. mit einer Farbpalette und Achsenbeschriftungen).
* Speichern Sie die Grafik per Syntax als .jpg-Datei mit dem Namen "Befragung-fb19.jpg" ab.


## Aufgabe 4

Erstellen Sie im Datensatz `fb19` die Skalenwerte für wach vs. müde (wm) und ruhig vs. unruhig (ru). Diese Skalen umfassen die folgenden Items (negative
Items sind unterstrichen)

* Wach vs. müde: ausgeruht (mdbf2), <span style="text-decoration: underline">schlapp (mdbf5)</span> , <span style="text-decoration: underline">müde (mdbf7)</span>, munter (mdbf10)
* Ruhig vs. unruhig: <span style="text-decoration: underline">ruhelos (mdbf3)</span>, gelassen (mdbf6), <span style="text-decoration: underline">unruhig (mdbf9)</span>, entspannt (mdbf12)

* Erstellen Sie die Skalenwerte als Mittelwert der jeweiligen vier Items.

## Aufgabe 5

Bestimmen Sie für beide Skalenwerte jeweils Mittelwert und Median.

* Was vermuten Sie, aufgrund des Verhältnisses der beiden Maße der zentralen
Tendenz, bezüglich der Schiefe der Verteilungen?
* Prüfen Sie Ihre Vermutungen anhand von Histogrammen!

## Aufgabe 6 

Bestimmen Sie für den Skalenwert `wm` die empirische Varianz. 
* Ist diese größer oder kleiner als diejenige Schätzung, die mithilfe von `var(...)` bestimmt wird?  
* Warum?  


## Aufgabe 7 

Erstellen Sie eine z-standardisierte Variante der wach vs. müde Skala als `wm_z`.

* Erstellen Sie für diese standardisierte Variable ein Histogramm.
* Was fällt Ihnen auf, wenn Sie dieses mit dem Histogramm der unstandardisierten Werte vergleichen?
* Erstellen Sie beide Histogramme noch einmal mit 20 Kategorien. 
