---
title: Tests und Konfidenzintervalle - Aufgaben
author: 
date: '2020-12-11'
slug: tests-und-konfidenzintervalle-aufgaben
categories:
  - BSc2
tags:
  - t-Test
subtitle: ''
summary: ''
authors: [scheppa-lahyani]
lastmod: '2020-12-11T19:07:56+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

## Aufgabe 1

Die mittlere Lebenszufriedenheit (`lz`) in Deutschland liegt bei $\mu$ = 4.7.

1.1 Was ist der Mittelwert ($\bar{x}$), die Standardabweichung (*SD*, $\hat\sigma$) und der Standardfehler ($\sigma_{\bar{x}}$) der Lebenszufriedenheit in der Gruppe der Psychologie-Studierenden?

1.2 Sind die Lebenszufriedenheitswerte normalverteilt? Veranschaulichen Sie dies mit einem geeigneten Plot. Benutzen Sie die lillie.test-Funktion aus dem nortest-Paket sowie die qqPlot-Funktion aus dem car-Paket. Wie unterscheiden Sie sich? Wann kann man in diesem Fall von einer Normalverteilung ausgehen?

1.3 Unterscheidet sich die Lebenszufriedenheit der Psychologie-Studierenden von der Lebenszufriedenheit der Gesamtbevoelkerung ($\mu$ = 4.7)? Bestimmen Sie das 99%ige Konfidenzintervall.

## Aufgabe 2

Die durchschnittliche Abschlussnote im Fach Psychologie (Bachelor) ist 2.01 (*SD* = 0.57). Eine Forschungsgruppe vermutet, dass sich die durchschnittliche Abschlussnote ueber die Jahre veraendert hat und nun besser ist. Um dies zu ueberpruefen, untersucht die Forschergruppe eine zufaellige Stichprobe aus 140 Psychologie-Studierenden (*N* = 140). Sie ermitteln eine durchschnittliche Abschlussnote von 1.81.

2.1 Reicht diese Information aus, um nachzuweisen, dass sich die durchschnittliche Abschlussnote veraendert hat? Berechnen Sie wenn moeglich, ob es eine Veraenderung gab ($\alpha$ = .05).

2.2 Wie wahrscheinlich ist angesichts der bekannten Normalverteilung der z-Werte dieser z-Wert?

## Aufgabe 3 (Zusatz)

3.1 Unterscheiden sich die Extraversionswerte (`extra`) der Studierenden der Psychologie (1. Semester) von den Extraversionswerten der Gesamtbevoelkerung ($\mu$ = 3.5)? Bestimmen Sie das 95%ige Konfidenzintervall und die Effektgroeße.

3.2 Sind die Prokrastinationswerte (`pro`) der Psychologie-Studierenden (1. Semester) groeßer als die Prokrastinationswerte der Gesamtbevoelkerung ($\mu$ = 2.1)? Bestimmen Sie das 99%ige Konfidenzintervall und die Effektgroeße.

3.3 Sind die Psychologie-Studierenden (1. Semester) vertraeglicher (`vertr`) als die Grundgesamtheit ($\mu$ = 3.5)? Bestimmen Sie das 95%ige Konfidenzintervall und die Effektgroeße.
