---
title: Tests und Konfidenzintervalle
date: '2020-12-11'
slug: tests-und-konfidenzintervalle
categories:
  - BSc2
tags:
  - t-Test
subtitle: ''
summary: ''
authors: [scheppa-lahyani, nehler]
lastmod: '2020-12-11T19:04:08+01:00'
featured: no
header:
  image: "/header/BSc2_Tests.jpg"
  caption: "[Courtesy of pxhere](https://pxhere.com/de/photo/1240882)"
projects: []
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<details>
<summary>
Kernfragen dieser Lehreinheit
</summary>
<ul>
<li>Wie berechne ich, ob es einen <strong>Unterschied zwischen einer Stichprobe und der dazugehörigen Population</strong> gibt?</li>
<li>Wann und wie rechne ich einen <strong>z-Test (Einstichproben-Gauss-Test)</strong>? Wie interpretiere ich die Ergebnisse?</li>
<li>Wie bestimme ich das <strong>Konfidenzintervall</strong> des wahren Werts <span class="math inline">\(\mu\)</span>?</li>
<li>Wann und wie rechne ich einen <strong>t-Test</strong>? Welche Voraussetzungen hat dieser? Wie interpretiere ich die Ergebnisse?</li>
<li>Wie gehe ich mit <strong>gerichteten vs. ungerichteten Hypothesen</strong> um?</li>
<li>Was ist Cohen’s <em>d</em> und wie berechne ich es? Wie interpretiere ich die Ergebnisse?</li>
</ul>
</details>
<hr />
<div id="was-erwartet-sie-heute" class="section level2">
<h2>Was erwartet Sie heute?</h2>
<p>Nachdem wir uns die letzten Wochen mit der Deskriptivstatistik und Zusammenhangsmaßen beschäftigt haben, wird unser Thema nun Gruppenunterschiede sein. Wir interessieren uns heute vor allem für den Unterschied zwischen dem Mittelwert einer Stichprobe und dem Mittelwert der dazugehörigen Population, aus der die Stichprobe stammt.</p>
</div>
<div id="aufbau-der-sitzung" class="section level2">
<h2>Aufbau der Sitzung</h2>
<ul>
<li>z-Test</li>
<li>Konfidenzintervalle</li>
<li>t-Test</li>
<li>Beispiel am Datensatz</li>
<li>Effektgröße</li>
</ul>
<hr />
</div>
<div id="lets-start" class="section level1">
<h1>Let’s start</h1>
<p>Der durchschnittliche IQ der Population ist <span class="math inline">\(\mu_0\)</span> = 100 und die Standardabweichung ist 15. Eine Forschungsgruppe glaubt aber, dass sich das verändert hat und entscheidet, diese Vermutung an der zufälligen Stichprobe von 75 Erwachsenen zu testen. Sie finden heraus, dass der durchschnittliche IQ der Stichprobe <span class="math inline">\(\mu_1\)</span> = 105 (<em>SD</em> = 17) ist.</p>
<p><strong>Was wären hier <span class="math inline">\(H_0\)</span> und <span class="math inline">\(H_1\)</span>?</strong></p>
<p><span class="math inline">\(\alpha\)</span> = .05</p>
<p><span class="math inline">\(H_0\)</span>: Der durchschnittliche IQ der Stichprobe ist gleich oder geringer als zuvor.</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(\geq\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p><span class="math inline">\(H_1\)</span>: Der durchschnittliche IQ der Stichprobe ist höher als zuvor.</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(&lt;\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p>Die Frage: Reicht dieses deskriptive Ergebnis (100 vs. 105) um daraus schlusszufolgern, dass der durchschnittliche IQ sich verändert hat?</p>
<p><strong>Nein</strong>. Erst mit Hilfe des z- oder t-Tests kann herausgefunden werden, wie (un)wahrscheinlich die beobachtete Diskrepanz (100 vs. 105) ist.</p>
<p>ABER: ob z- oder t-Test zum Einsatz kommt, hängt davon ab, ob neben dem Mittelwert auch die Standardabweichung (<em>SD</em>, <span class="math inline">\(\sigma\)</span>) der Grundgesamtheit bekannt ist.<br />
In diesem Fall ist die <em>SD</em> bekannt, demnach wäre ein z-Test an dieser Stelle anzuwenden.</p>
<div id="z-test" class="section level2">
<h2>z-Test</h2>
<p>Der <strong>z-Test</strong> oder <strong>Einstichproben-Gauss-Test</strong> setzt voraus, dass das Merkmal in der Population, auf die sich die Nullhypothese (<span class="math inline">\(H_0\)</span>) bezieht, normalverteilt ist und der Mittelwert sowie die Standardabweichung bekannt sind.<br />
Des Weiteren verwendet der Gauss-Test grundsätzlich die Standardnormalverteilung als Stichprobenkennwerteverteilung (SKV), deswegen ist er nicht für kleine Stichproben geeignet.<br />
Der Einstichproben-Gauss-Test prüft anhand des arithmetischen Mittels einer Stichprobe, ob der Erwartungswert der zugehörigen Grundgesamtheit ungleich (bzw. kleiner oder größer) als ein vorgegebener Wert ist.</p>
<p>Die Formel für den <strong>empirischen <em>z-</em>Wert</strong> <span class="math inline">\(z_{emp}\)</span> ist:</p>
<p><span class="math display">\[z_{emp} = |\frac{\bar{x} - {\mu}}{\sigma_{\bar{x}}}|\]</span>
wobei sich der Standardfehler (<em>SE</em>) des Mittelwerts wie folgt berechnet:</p>
<p><span class="math display">\[\sigma_{\bar{x}} = {\frac{{\sigma}}{\sqrt{n}}}\]</span></p>
<p>Zunächst legen wir alle für den <em>z-</em>Wert relevanten Informationen in unser Environment ab, wobei wir auch schon den Standardfehler des Mittelwerts (<span class="math inline">\(\sigma_{\bar{x}}\)</span>) berechnen.</p>
<pre class="r"><code>mean_IQ &lt;- 100 #Mean Grundgesamtheit
sd_IQ &lt;- 15 #SD der Grundgesamtheit
sample_size &lt;- 75 #Stichprobengröße
se_IQ &lt;- sd_IQ/sqrt(sample_size) #standard error (SE), also Standardfehler
new_mean_IQ &lt;- 105 #Stichprobenmittelwert
new_sd_IQ &lt;- 17 #SD der Stichprobe (Populationsschätzer)</code></pre>
<p>Demnach wird der empirische <em>z-</em>Wert <span class="math inline">\(z_{emp}\)</span> wie folgt berechnet (Bedenkt, dass es immer um den Betrag des Ergebnisses geht, weshalb wir die Funktion <code>abs()</code> verwenden.):</p>
<pre class="r"><code>z_IQ &lt;- abs((new_mean_IQ-mean_IQ)/(sd_IQ/sqrt(sample_size))) #abs() berechnet den Betrag des Ergebnisses
z_IQ</code></pre>
<pre><code>## [1] 2.886751</code></pre>
<p>bzw.</p>
<pre class="r"><code>z_IQ &lt;- abs((new_mean_IQ-mean_IQ)/se_IQ)
z_IQ</code></pre>
<pre><code>## [1] 2.886751</code></pre>
<p>Der empirische <em>z-</em>Wert <span class="math inline">\(z_{emp}\)</span> ist eine Angabe, um wie viele Standardabweichungen der Mittelwerte der SKV (<em>SE</em>) der Mittelwert der Stichprobe vom Mittelwert der Grundgesamtheit abweicht.<br />
Der beobachtete Stichprobenmittelwert weicht demnach um <strong><span class="math inline">\(z_{IQ}\)</span> = 2.89</strong> <em>SE</em> (nach oben) vom Mittelwert der Grundgesamtheit ab.<br />
Um entscheiden zu können, ob es sich um eine signifikante Abweichung handelt, muss der <strong>kritische <em>z-</em>Wert</strong> <span class="math inline">\(z_{krit}\)</span> bestimmt werden.<br />
Für eine Irrtumswahrscheinlichkeit von 5% und eine einseitige Hypothesentestung wäre dies:</p>
<pre class="r"><code>z_krit &lt;- qnorm(1-.05) #bei einer zweiseitigen Testung würden wir qnorm(1-(.05/2)) verwenden
z_krit</code></pre>
<pre><code>## [1] 1.644854</code></pre>
<p>Der <strong>kritische <em>z-</em>Wert</strong> beträgt demnach <strong><span class="math inline">\(z_{krit}\)</span> = 1.64</strong>. Damit das Ergebnis als signifikant gewertet wird, muss der empirische <em>z-</em>Wert <span class="math inline">\(z_{emp}\)</span> größer sein als der kritsiche <em>z-</em>Wert (<strong><span class="math inline">\(z_{IQ}\)</span> &gt; <span class="math inline">\(z_{krit}\)</span></strong>). Hierfür können wir auch eine logische Abfrage nutzen:</p>
<pre class="r"><code>z_IQ &gt; z_krit</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Das Ergebnis <code>TRUE</code> zeigt uns, dass es sich um einen signifikanten Unterschied handelt.
Mit einer Irrtumswahrscheinlichkeit von 5% kann die <span class="math inline">\(H_0\)</span> verworfen werden. Der durchschnittliche IQ der Stichprobe ist höher als der durchschnittliche IQ der Grundgesamtheit.</p>
<div id="weitere-möglichkeit-pnorm" class="section level3">
<h3>Weitere Möglichkeit: <code>pnorm</code></h3>
<p>Wie wahrscheinlich ist es angesichts der bekannten Normalverteilung der <em>z-</em>Werte den beobachteten empirischen <em>z-</em>Wert <span class="math inline">\(z_{emp}\)</span> zu erhalten?</p>
<p>Wie hoch ist die Wahrscheinlichkeit diesen oder einen GRÖßEREN (einseitig) <em>z-</em>Wert zu erreichen?</p>
<pre class="r"><code>p_z_IQ_oneside &lt;- pnorm(z_IQ, lower.tail = FALSE)
p_z_IQ_oneside</code></pre>
<pre><code>## [1] 0.001946209</code></pre>
<p>Wie hoch ist die Wahrscheinlichkeit diesen oder einen EXTREMEREN (zweiseitig) <em>z-</em>Wert zu erreichen?</p>
<pre class="r"><code>p_z_IQ_twoside &lt;- 2*pnorm(z_IQ, lower.tail = FALSE) #verdoppeln, da zweiseitig
p_z_IQ_twoside</code></pre>
<pre><code>## [1] 0.003892417</code></pre>
<p>Wir erkennen, dass in beiden Fällen der Wert kleiner als .05 (5%) ist. Demnach ist die Wahrscheinlichkeit, diesen Wert per Zufall erhalten zu haben, sehr gering.</p>
<hr />
</div>
</div>
<div id="konfidenzintervalle" class="section level2">
<h2>Konfidenzintervalle</h2>
<p>Wir können auch ein Konfidenzintervall um den wahren Populationsmittelwert <span class="math inline">\(\mu\)</span> bestimmen. Es geht dabei darum, in welchem Wertebereich der wahre Wert <span class="math inline">\(\mu\)</span> mit einer gewissen vorgegebenen Wahrscheinlichkeit liegt. Wenn wir also ein 95%-Konfidenzintervall wählen und wir aus der selben Grundgesamtheit wiederholt die selbe Anzahl an Fällen ziehen, so ist in 95% der Fälle der Mittelwert in dem vorgegeben Konfidenzintervall enthalten.</p>
<p>Dabei gilt:</p>
<p><span class="math display">\[\mu = \bar{x} \pm \frac{z_{krit}*\sigma}{\sqrt{n}}\]</span></p>
<p>Ein 95%-Konfidenzintervall ist ein Intervall, welches in 95% der Fälle beim Ziehen aus der selben Grundgesamtheit den wahren Wert <span class="math inline">\(\mu\)</span> enthält.</p>
<p>Wenn wir ein 95%-Konfidenzintervall bestimmen wollen, brauchen wir den <strong>kritischen <em>z-</em>Wert</strong> <span class="math inline">\(z_{krit}\)</span> aus der SNV (Standardnormalverteilung).<br />
Für Konfidenzintervalle nutzen wir einen <em>z-</em>Wert für 2-seitiges Testen:</p>
<pre class="r"><code>z_krit2 &lt;- qnorm(1-(.05/2))
z_krit2</code></pre>
<pre><code>## [1] 1.959964</code></pre>
<pre class="r"><code>positive_mean_IQ &lt;- new_mean_IQ+((z_krit2*new_sd_IQ)/sqrt(sample_size))
positive_mean_IQ</code></pre>
<pre><code>## [1] 108.8474</code></pre>
<pre class="r"><code>negative_mean_IQ &lt;- new_mean_IQ-((z_krit2*new_sd_IQ)/sqrt(sample_size))
negative_mean_IQ</code></pre>
<pre><code>## [1] 101.1526</code></pre>
<pre class="r"><code>conf_interval_IQ &lt;- c(negative_mean_IQ, positive_mean_IQ )
conf_interval_IQ</code></pre>
<pre><code>## [1] 101.1526 108.8474</code></pre>
<p>In diesem Fall liegt der wahre IQ Wert der Grundgesamtheit <span class="math inline">\(\mu\)</span>, aus der die Stichprobe gezogen wurde, zwischen 101.1526085 und 108.8473915. Das bedeutet, dass in 95% der Fälle in einer wiederholten Ziehung aus der Grundgesamtheit die mittleren IQ-Werte zwischen 101.1526085 und 108.8473915 liegen.</p>
<hr />
</div>
<div id="t-test" class="section level2">
<h2>t-Test</h2>
<p>Der t-Test ersetzt den z-Test, wenn die Varianz in der Grundgesamtheit nicht bekannt ist. Mit dem t-Test für eine Stichprobe kann man den <strong>Stichprobenmittelwert</strong> einer Variablen mit einem <strong>bekannten Populationsmittelwert</strong> vergleichen.</p>
<p>Der Test hat die folgenden Voraussetzungen:</p>
<ol style="list-style-type: decimal">
<li>Metrisch skalierte abhängige Variable</li>
<li>Bei <em>n</em> &lt; 30 : Normalverteilung der abhängigen Variable in der Population.</li>
</ol>
<p>Unterschiedliche Quellen geben an, dass die durchschnittliche Größe der Männer in Deutschland 180 cm beträgt (z.B. <a href="https://www.länderdaten.info/durchschnittliche-körpergrössen.php" class="uri">https://www.länderdaten.info/durchschnittliche-körpergrössen.php</a>). Eine Forschungsgruppe vermutet jedoch, dass die Männer in Deutschland eigentlich größer sind und ermittelt von zehn zufällig gezogenen Männer die Körpergröße.</p>
<p>Die Größe der Männer beträgt: 183, 178, 175, 186, 185, 179, 181, 179, 182, 177 (gemessen in cm).</p>
<p>Kann die Vermutung der Forschungsgruppe bestätigt werden?</p>
<pre class="r"><code>men.height &lt;- c(183, 178, 175, 186, 185, 179, 181, 179, 182, 177)
mean.men.height &lt;- mean(men.height)
sd.men.height &lt;- sd(men.height)
average.men.height &lt;- 180
n.men.height &lt;- length(men.height)</code></pre>
<pre class="r"><code>mean.men.height</code></pre>
<pre><code>## [1] 180.5</code></pre>
<pre class="r"><code>sd.men.height</code></pre>
<pre><code>## [1] 3.535534</code></pre>
<pre class="r"><code>average.men.height</code></pre>
<pre><code>## [1] 180</code></pre>
<pre class="r"><code>n.men.height</code></pre>
<pre><code>## [1] 10</code></pre>
<div id="voraussetzungsprüfung" class="section level3">
<h3>Voraussetzungsprüfung</h3>
<p><em>Normalverteilt?</em></p>
<p><strong>Variante 1</strong>: Inferenzstatistik: Der <strong>Shapiro-Wilk Test</strong> prüft auf die Normalverteilung von Variablen.
Der Wert <em>W</em> ist die Teststatistik.
Eine Normalverteilung in der Population liegt vor, wenn das Ergebnis NICHT signifikant ist.</p>
<pre class="r"><code>shapiro.test(men.height)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  men.height
## W = 0.97309, p-value = 0.9179</code></pre>
<p><strong>Variante 2</strong>: Grafisch: In einem sog. QQ-Plot werden die unter der Normalverteilung erwarteten Quantile und die tatsächlich beobachteten Quantile in einem Streudiagramm dargestellt. Je deutlicher die Punkte auf der Geraden liegen, desto näher ist die beobachtete Verteilung an der Normalverteilung.</p>
<pre class="r"><code>qqnorm(men.height) 
qqline(men.height)</code></pre>
<p><img src="/post/2020-12-11-tests-und-konfidenzintervalle_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Beide Varianten lassen darauf schließen, dass die Annahme auf Normalverteilung nicht verworfen werden muss.</p>
</div>
<div id="signifikanz-bestimmen" class="section level3">
<h3>Signifikanz bestimmen</h3>
<p>Der t-Test basiert auf folgender Formel und unterscheidet sich damit nur minimal vom z-Test:</p>
<p><span class="math display">\[t_{emp} = |\frac{\bar{x} - {\mu}}{\hat\sigma_{\bar{x}}}|\]</span>
wobei sich der Standardfehler (<em>SE</em>) des Mittelwerts wie folgt berechnet:</p>
<p><span class="math display">\[\hat\sigma_{\bar{x}} = {\frac{{\hat\sigma}}{\sqrt{n}}}\]</span></p>
<p>Der Standardfehler des Mittelwerts wird demnach auf der Basis der Stichprobenvarianz geschätzt.</p>
<pre class="r"><code>se.men.height &lt;- sd.men.height/sqrt(n.men.height)</code></pre>
<p>Bestimmen des empirischen <em>t-</em>Wertes <span class="math inline">\(t_{emp}\)</span>:</p>
<pre class="r"><code>t.men.height &lt;- abs((mean.men.height-average.men.height)/se.men.height)
t.men.height</code></pre>
<pre><code>## [1] 0.4472136</code></pre>
<p>Bestimmen des kritischen <em>t-</em>Wertes <span class="math inline">\(t_{krit}\)</span>:</p>
<pre class="r"><code>krit.t.men.height &lt;- qt(0.95, df=n.men.height-1) 
krit.t.men.height</code></pre>
<pre><code>## [1] 1.833113</code></pre>
<p>Ist der empirische größer als der kritische <em>t-</em>Wert (<span class="math inline">\(t_{emp} &gt; t_{krit}\)</span>)?</p>
<pre class="r"><code>t.men.height &gt; krit.t.men.height</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>Der empirische <em>t-</em>Wert wird hier nicht überboten.</p>
<p>Alternativ: Bestimmen des kritischen <em>p</em>-Wertes <span class="math inline">\(p_{krit}\)</span>:</p>
<pre class="r"><code>p.t.men.height &lt;- pt(t.men.height, n.men.height-1, lower.tail = F) #einseitige Testung
p.t.men.height</code></pre>
<pre><code>## [1] 0.3326448</code></pre>
<p>Der empirische <em>p</em>-Wert liegt über .05 (<span class="math inline">\(p_{emp} &gt; p_{krit}\)</span>).</p>
<p>Die Differenz zwischen dem Mittelwert der Population <span class="math inline">\(\mu\)</span> und dem beobachteten Mittelwert <span class="math inline">\(\bar{x}\)</span> in der Stichprobe ist nicht signifikant. Demnach wird die <span class="math inline">\(H_0\)</span> mit einer Irrtumswahrscheinlichkeit von 5% beibehalten.</p>
</div>
<div id="t-test-mit-t.test-funktion" class="section level3">
<h3>t-test mit <code>t.test</code> Funktion</h3>
<p>Natürlich geht alles auch noch einfacher:</p>
<pre class="r"><code>t.test(men.height, mu=180, alternative=&quot;greater&quot;) #alternative bestimmt, ob die Hypothese gerichtet ist oder nicht. Siehe hierzu ?t.test.</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  men.height
## t = 0.44721, df = 9, p-value = 0.3326
## alternative hypothesis: true mean is greater than 180
## 95 percent confidence interval:
##  178.4505      Inf
## sample estimates:
## mean of x 
##     180.5</code></pre>
<p>Hier haben wir nun alle wichtigen Informationen gebündelt.</p>
<p><code>t</code> = <span class="math inline">\(t_{emp}\)</span> = 0.4472136</p>
<p><code>df</code> = Freiheitsgrade = 9</p>
<p><code>p-value</code> = <span class="math inline">\(p_{emp}\)</span> = 0.3326448</p>
<p><code>mean of x</code> = <span class="math inline">\(\bar{x}\)</span> = 180.5</p>
<p>Wir erkennen auch hier, dass der empirische <em>p</em>-Wert über .05 liegt (<span class="math inline">\(p_{emp} &gt; p_{krit}\)</span>). Demnach wird die <span class="math inline">\(H_0\)</span> mit einer Irrtumswahrscheinlichkeit von 5% beibehalten.</p>
<p>Das 95%ige Konfidenzintervall wird uns ebenfalls ausgegeben. Beachten Sie, dass es sich aufgrund unserer Hypothese um ein einseitiges Intervall handelt (nach oben offen). Basierend auf der Stichprobe liegt der wahre Wert <span class="math inline">\(\mu\)</span> zwischen 178.4505174 und <span class="math inline">\(\infty\)</span>. Man erkennt also, dass der Wert von 180 in diesem Konfidenzintervall liegt, was ebenso bestätigt, dass es keinen Unterschied gibt.</p>
</div>
</div>
<div id="beispiel-mit-unserem-datensatz" class="section level2">
<h2>Beispiel mit unserem Datensatz</h2>
<p>Den Datensatz <code>fb21.rda</code>, mit dem im Folgenden gearbeitet wird, können Sie <a href="/post/fb21.rda"><i class="fas fa-download"></i> hier herunterladen</a>. Anschließend müssen Sie ihn lokal einladen.</p>
<pre class="r"><code>load(&#39;fb21.rda&#39;)</code></pre>
<p>Alternativ können Sie ihn auch direkt über den folgenden Befehl in <code>R</code> laden:</p>
<pre class="r"><code>load(url(&#39;https://pandar.netlify.app/post/fb21.rda&#39;))</code></pre>
<p><strong>Unterscheidet sich unsere studentische Stichprobe in ihrem Neurotizismuswert von Studierenden im Allgemeinen?</strong>
Wir nehmen an, dass der mittlere Neurotizismuswert in der Population der Studierenden bei <span class="math inline">\(\mu\)</span> = 3.3 liegt.</p>
<ol style="list-style-type: decimal">
<li>Ist die erste Voraussetzung erfüllt?</li>
<li>Normalverteilungsananahme darf verletzt sein (verzerrt das Ergebnis des t-Tests nicht), wenn die Stichprobe mindestens 30 Personen umfasst. Dann gilt der <em>zentrale Grenzwertsatz</em>: “Die Stichprobenkennwertverteilung nähert sich einer Normalverteilung an, selbst wenn diese nicht normalverteilt ist.”</li>
</ol>
<p>Bevor wir in die inferenzstatistische Analyse einsteigen, ist es immer gut, sich einen Überblick über die deskriptiven Werte zu verschaffen. Wir können nun natürlich einfach die bereits gelernten Funktionen zu Mittelwert, Varianz, Minimum, etc. nutzen. Doch gibt es einen schnelleren Weg? Die Basisinstallation von <code>R</code> bietet uns keine Alternative. Jedoch gibt es zusätzliche <em>Pakete</em>, die den Pool an möglichen Funktionen erweitern. Die Logik wird im Folgenden erläutert.</p>
<div id="wie-können-andere-funktionen-in-r-genutzt-werden---library-und-pakete" class="section level3">
<h3>Wie können andere Funktionen in R genutzt werden? - Library und Pakete</h3>
<p>R ist in einer Pakete-Logik aufgebaut. Das liegt daran, dass es immer mehr Funktionen in R gibt, die aber nie jemand alle gleichzeitig brauchen wird. Zur Schonung der Kapazität sind diese Funktionalitäten also in Pakete aufgeteilt. In <em>Basispaketen</em>, die standardmäßig geladen werden (also vorinstalliert sind beim Öffnen von R) sind grundlegende Befehle und Analysen implementiert (Beispiele für solche Basispakete sind <code>base</code>, <code>stats</code>, <code>graphics</code>). Für spezifischere Analysen (also Funktionen) müssen <em>Zusatzpakete</em> teilweise erst installiert, zumindest aber immer per Hand geladen werden (Beispiele sind <code>psych</code>, <code>car</code>, <code>ggplot2</code>). Nur die Funktionen von erst installierten und dann geladenen Paketen können in einem Skript benutzt werden.</p>
<p>Unter dem Reiter <em>Packages</em> wird die <em>Library</em> angezeigt. Hier sind alle Pakete enthalten, die einmal installiert wurden. Pakete müssen ab und zu (per Hand) aktualisiert werden.</p>
<p><img src="/post/library.JPG" /></p>
<p>Sobald Sie eigene Pakete installiert haben, gibt es in dem Reiter <em>Packages</em> die Einteilung in die <em>Sytem Library</em> (also standardmäßig installierte Pakete) und die <em>User Library</em> (von Ihnen installierte Pakete).</p>
<p>Die folgenden Bilder verdeutlichen nochmal das Prinzip von Installieren und Laden. Bei der Installation von R werden die Basispakete automatisch in die Library installiert. Zusatzpakete müssen mit der Funktion <code>install.packages()</code> mit dem Paketnamen als Argument installiert werden. Hierzu ist meist eine Internetverbindung nötig.</p>
<p><img src="/post/pakete_installieren.JPG" /></p>
<p>Beim Start von R werden die Basispakete automatisch geladen. Zusatzpakete müssen hingegen mit der Funktion <code>library()</code> mit dem Paketnamen als Argument geladen werden.</p>
<p><img src="/post/pakete_laden.JPG" /></p>
<p>Gehen wir das Prinzip an dem Beispielpaket <code>psych</code> durch, das verschiedene Operationen enthält, die in der psychologischen Forschung häufig benötigt werden. Die Installation muss dem Laden des Paketes logischerweise vorausgestellt sein. Wenn R einmal geschlossen wird, müssen alle Zusatzpakete neu geladen, jedoch nicht neu installiert werden.</p>
<pre class="r"><code>install.packages(&#39;psych&#39;)          # installieren</code></pre>
<pre class="r"><code>library(psych)                     # laden</code></pre>
<pre><code>## Warning: Paket &#39;psych&#39; wurde unter R Version 4.1.1 erstellt</code></pre>
<p>Wir erhalten hier als Warning Message den Hinweis, unter welcher Version das Paket erstellt wurde.
Eine kleine Suche nach Hilfe zu Pakete kann man mit <code>??</code>erhalten.</p>
<pre class="r"><code>??psych                          # Hilfe</code></pre>
<p>Da das Paket <code>psych</code> nun geladen ist, können wir Funktionen aus diesem nutzen. Für unsere Übersicht über deskriptive Maße der Variable <code>neuro</code> gibt es die Funktion <code>describe</code>.</p>
<pre class="r"><code>describe(fb21$neuro)</code></pre>
<pre><code>##    vars   n mean   sd median trimmed  mad  min max range  skew kurtosis   se
## X1    1 114  3.4 0.78   3.38     3.4 0.74 1.25   5  3.75 -0.08    -0.25 0.07</code></pre>
<p>Wir bekommen auf einen Schlag sehr viele relevante Informationen über unsere Variable. Der Mittelwert unserer Stichprobe liegt beispielsweise bei 3.4013158. Beachten Sie, dass auch bei <code>describe</code> unter <code>sd</code> die geschätzte Populationsstandardabweichung angegeben wird (wie bei der Basis-Funktion <code>sd</code>). Man müsste Sie also auch umrechnen, um nur eine Angabe über die Stichprobe zu machen.</p>
</div>
<div id="hypothesengenerierung" class="section level3">
<h3>Hypothesengenerierung</h3>
<p><strong>Variante 1</strong>:</p>
<p><strong>Ungerichtete <span class="math inline">\(H_1\)</span></strong>: “Der mittlere Neurotizismuswert unserer Stichprobe unterscheidet sich vom mittleren Neurotizismuswert der Studierenden-Population”
–&gt; zweiseitiger t-Test</p>
<p><strong>Ungerichtete <span class="math inline">\(H_0\)</span></strong>: “Der mittlere Neurotizismuswert unserer Stichprobe unterscheidet sich nicht vom mittleren Neurotizismuswert der Studierenden-Population”</p>
<p><strong>Variante 2</strong>:</p>
<p><strong>Gerichtete <span class="math inline">\(H_1\)</span></strong>: “Der mittlere Neurotizismuswert unserer Stichprobe ist höher (niedriger) als der mittlere Neurotizismuswert der Studierenden-Population.”
–&gt; einseitiger t-Test</p>
<p><strong>Gerichtete <span class="math inline">\(H_0\)</span></strong>: “Der mittlere Neurotizismuswert unserer Stichprobe ist gleich oder niedriger (höher) als der mittlere Neurotizismuswert der Studierenden-Population.”</p>
<p>In der Praxis würde man sich für eine der beiden Hypothesen-Varianten (<em>ungerichtet</em> vs. <em>gerichtet</em>) entscheiden. Zu Übungszwecken werden aber alle beide Varianten durchgespielt.</p>
<pre class="r"><code>t.test(fb21$neuro, mu=3.3) #ungerichtet</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb21$neuro
## t = 1.3924, df = 113, p-value = 0.1665
## alternative hypothesis: true mean is not equal to 3.3
## 95 percent confidence interval:
##  3.257160 3.545472
## sample estimates:
## mean of x 
##  3.401316</code></pre>
<pre class="r"><code>t.test(fb21$neuro, mu=3.3, alternative=&quot;less&quot;) #gerichtet, Stichprobenmittelwert geringer</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb21$neuro
## t = 1.3924, df = 113, p-value = 0.9167
## alternative hypothesis: true mean is less than 3.3
## 95 percent confidence interval:
##      -Inf 3.521989
## sample estimates:
## mean of x 
##  3.401316</code></pre>
<pre class="r"><code>t.test(fb21$neuro, mu=3.3, alternative=&quot;greater&quot;) #gerichtet, Stichprobenmittelwert höher</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb21$neuro
## t = 1.3924, df = 113, p-value = 0.08327
## alternative hypothesis: true mean is greater than 3.3
## 95 percent confidence interval:
##  3.280643      Inf
## sample estimates:
## mean of x 
##  3.401316</code></pre>
<p><strong>Konfidenzintervall:</strong> Wir erkennen, dass das 95%-ige Konfidenzintervall per Standardeinstellung berechnet wird. Falls wir dieses vergrößern oder verkleinern wollen, müssen wir dies explizit formulieren im Argument <code>conf.level</code>:</p>
<pre class="r"><code>t.test(fb21$neuro, mu=3.3, conf.level=0.99) #99%-iges Konfidenzintervall für die ungerichtete Hypothese</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb21$neuro
## t = 1.3924, df = 113, p-value = 0.1665
## alternative hypothesis: true mean is not equal to 3.3
## 99 percent confidence interval:
##  3.210675 3.591956
## sample estimates:
## mean of x 
##  3.401316</code></pre>
<pre class="r"><code>t.test(fb21$neuro, mu=3.3, alternative=&quot;less&quot;, conf.level=0.99) #99%-iges Konfidenzintervall für die gerichtete Hypothese (Stichprobenmittelwert geringer)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb21$neuro
## t = 1.3924, df = 113, p-value = 0.9167
## alternative hypothesis: true mean is less than 3.3
## 99 percent confidence interval:
##      -Inf 3.573021
## sample estimates:
## mean of x 
##  3.401316</code></pre>
<pre class="r"><code>t.test(fb21$neuro, mu=3.3, alternative=&quot;greater&quot;, conf.level=0.99) #99%-iges Konfidenzintervall für die gerichtete Hypothese (Stichprobenmittelwert höher)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb21$neuro
## t = 1.3924, df = 113, p-value = 0.08327
## alternative hypothesis: true mean is greater than 3.3
## 99 percent confidence interval:
##  3.229611      Inf
## sample estimates:
## mean of x 
##  3.401316</code></pre>
<p>Es zeigt sich, dass der Neurotizismuswert der Studierenden sich von der Studierenden-Population nicht unterscheidet.</p>
<p><strong>Ungerichtet</strong></p>
<p>Die <span class="math inline">\(H_0\)</span> wird mit einer Irrtumswahrscheinlichkeit von 5% beibehalten. Der Neurotizismuswert der Studierenden unterscheidet sich nicht von der Studierenden-Population.</p>
<p><strong>Gerichtet (niedriger)</strong></p>
<p>Die <span class="math inline">\(H_0\)</span> wird mit einer Irrtumswahrscheinlichkeit von 5% beibehalten. Der Neurotizismuswert der Studierenden ist nicht kleiner als der der Studierenden-Population.
<em>Bemerke</em>: Einen gerichteten t-Test, der <span class="math inline">\(\bar{x} &lt; \mu\)</span> untersucht, würde man an dieser Stelle nicht durchführen, da die deskriptiven Werte schon gegen die Hypothese sprechen (da <span class="math inline">\(\bar{x} &gt; \mu\)</span> und nicht <span class="math inline">\(\bar{x} &lt; \mu\)</span>).</p>
<p><strong>Gerichtet (höher)</strong>*</p>
<p>Die <span class="math inline">\(H_0\)</span> wird mit einer Irrtumswahrscheinlichkeit von 5% beibehalten. Der Neurotizismuswert der Studierenden ist nicht höher als der der Studierenden-Population.</p>
<hr />
</div>
</div>
<div id="effektgröße" class="section level2">
<h2>Effektgröße</h2>
<p>Als Effektgröße für Mittelwertsunterschiede kann <strong>Cohen’s d</strong> (Cohen, 1988) verwendet werden.</p>
<p>Cohen, J. (1988). <em>Statistical power analysis for the Behavioral Sciences</em>. Routledge.</p>
<p>Dieses statistische Effektmaß beschreibt die Relevanz von signifikanten Ergebnissen. Zudem kann es verwendet werden, um den Effekt über verschiedene Studien hinweg zu vergleichen.</p>
<p><span class="math display">\[d = |\frac{\bar{x} - {\mu}}{\sigma}|\]</span></p>
<pre class="r"><code>mean_Neuro &lt;- mean(fb21$neuro) #Neurotizismuswert der Stichprobe
sd_Neuro &lt;- sd(fb21$neuro, na.rm = T) #Stichproben SD (Populationsschätzer)
mean_Popu_Neuro &lt;- 3.3 #Neurotizismuswert der Grundgesamtheit
d &lt;- abs((mean_Neuro-mean_Popu_Neuro)/sd_Neuro) #abs(), da Betrag
d</code></pre>
<pre><code>## [1] 0.1304118</code></pre>
<p>Die Effektgröße ist in diesem Fall mit einem Wert von .1469 klein. Normalerweise sollte die Einordnung der Größe anhand vergleichbarer Studien aus dem selben Bereich durchgeführt werden. Bei völliger Ahnungslosigkeit über relevante Größen gibt es eine Übersicht zur Orientierung. Es gilt nach Cohen (1988):</p>
<p><em>d</em> = 0.2 -&gt; kleiner Effekt</p>
<p><em>d</em> = 0.5 -&gt; mittlerer Effekt</p>
<p><em>d</em> = 0.8 -&gt; großer Effekt</p>
<hr />
</div>
</div>
