---
title: Tests und Konfidenzintervalle - Lösungen
author: 
date: '2020-12-11'
slug: tests-und-konfidenzintervalle-loesungen
categories:
  - BSc2
tags:
  - t-Test
subtitle: ''
summary: ''
authors: [scheppa-lahyani]
lastmod: '2020-12-11T19:09:16+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
expiryDate: '2021-03-31'
publishDate: '2021-01-15'
---



<div id="vorbereitung" class="section level2">
<h2>Vorbereitung</h2>
<p>Laden Sie zunächst den Datensatz <code>fb20</code> von der pandar-Website.</p>
<pre class="r"><code>fb20 &lt;- read.table(&#39;https://pandar.netlify.app/post/fb20.csv&#39;, 
  header = TRUE,
  sep = &#39;,&#39;,
  na.strings = &#39;-99&#39;)</code></pre>
<p>Alternativ können Sie die fertige R-Daten-Datei <a href="/post/fb20.rda"><i class="fas fa-download"></i> hier herunterladen</a>. Die Bedeutung der einzelnen Variablen und ihre Antwortkategorien können Sie dem Dokument <a href="/post/variablen.pdf">Variablenübersicht.docx</a> entnehmen.</p>
<p>Prüfen Sie zur Sicherheit, ob alles funktioniert hat:</p>
<pre class="r"><code>dim(fb20)</code></pre>
<pre><code>## [1] 98 32</code></pre>
<pre class="r"><code>str(fb20)</code></pre>
<pre><code>## &#39;data.frame&#39;:    98 obs. of  32 variables:
##  $ mdbf1  : int  3 5 4 4 5 4 3 4 2 4 ...
##  $ mdbf2  : int  2 3 4 2 4 4 4 2 2 2 ...
##  $ mdbf3  : int  4 2 2 3 2 1 1 4 4 2 ...
##  $ mdbf4  : int  3 1 1 NA 1 1 2 3 4 2 ...
##  $ mdbf5  : int  2 3 1 4 1 1 1 3 4 4 ...
##  $ mdbf6  : int  1 4 4 2 4 3 4 3 2 4 ...
##  $ mdbf7  : int  2 3 1 5 2 3 1 4 4 4 ...
##  $ mdbf8  : int  3 5 4 3 5 4 4 4 2 4 ...
##  $ mdbf9  : int  4 1 2 4 2 1 1 4 4 2 ...
##  $ mdbf10 : int  3 3 4 1 3 4 3 3 2 4 ...
##  $ mdbf11 : int  2 1 1 3 2 1 1 3 5 2 ...
##  $ mdbf12 : int  2 5 4 2 4 4 4 2 2 4 ...
##  $ lz     : num  5.4 6.8 5 3.6 5.6 5.4 4.8 3.6 5 5.4 ...
##  $ extra  : num  3.5 4 3.5 2.75 4.25 3 3.5 4 3.25 3.5 ...
##  $ vertr  : num  3.5 5 5 3.75 3.5 4.5 4.5 4 4.5 5 ...
##  $ gewis  : num  4 3.5 3.75 4.25 4.25 4.75 4.5 4.25 3 4.75 ...
##  $ neuro  : num  4.25 3 4.5 4.75 4.25 2 4 3.5 3.25 4.25 ...
##  $ intel  : num  3.25 3.75 4.5 2.25 4.5 4 3.25 3.5 2.75 3.5 ...
##  $ pro    : num  1.9 2.1 2.5 2.7 2.9 2.1 2.4 2 2.5 2.2 ...
##  $ grund  : chr  &quot;weil mich die menschliche Psyche sehr interessiert, vor allem die Ursachen für negative Verhaltenweisen, Charak&quot;| __truncated__ &quot;Tiefes Interesse&quot; &quot;Interessante Themen&quot; &quot;Interesse auf Menschen&quot; ...
##  $ fach   : int  3 3 4 3 2 1 4 1 4 NA ...
##  $ ziel   : int  2 2 2 3 3 1 2 1 2 NA ...
##  $ lerntyp: int  1 3 1 1 3 1 1 3 3 NA ...
##  $ geschl : int  1 1 2 2 1 2 1 1 NA NA ...
##  $ job    : int  2 1 1 2 1 1 1 1 1 NA ...
##  $ ort    : int  1 2 1 2 1 1 1 2 NA NA ...
##  $ ort12  : int  2 2 1 2 1 1 1 3 1 NA ...
##  $ wohnen : int  1 4 2 1 1 2 3 2 1 NA ...
##  $ uni1   : int  1 1 1 0 1 0 0 0 0 0 ...
##  $ uni2   : int  1 0 1 1 1 1 1 1 0 0 ...
##  $ uni3   : int  0 0 0 0 0 1 0 0 0 0 ...
##  $ uni4   : int  0 0 0 0 0 0 0 1 0 0 ...</code></pre>
<p>Der Datensatz besteht aus 98 Zeilen (Beobachtungen) und 32 Spalten (=Variablen).</p>
<hr />
</div>
<div id="installieren-aller-wichtigen-packages" class="section level2">
<h2>Installieren aller wichtigen Packages</h2>
<pre class="r"><code>install.packages(&quot;psych&quot;)
install.packages(&quot;nortest&quot;)
install.packages(&quot;car&quot;)</code></pre>
<pre class="r"><code>library(psych)
library(nortest)
library(car)</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:psych&#39;:
## 
##     logit</code></pre>
<pre class="r"><code>load(&#39;fb20.rda&#39;)</code></pre>
</div>
<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<p><strong>Die mittlere Lebenszufriedenheit (<code>lz</code>) in Deutschland liegt bei <span class="math inline">\(\mu\)</span> = 4.7.</strong></p>
<p><strong>1.1 Was ist der Mittelwert (<span class="math inline">\(\bar{x}\)</span>), die Standardabweichung (<em>SD</em>, <span class="math inline">\(\hat\sigma\)</span>) und der Standardfehler (<span class="math inline">\(\sigma_{\bar{x}}\)</span>) der Lebenszufriedenheit in der Gruppe der Psychologie-Studierenden?</strong></p>
<p><strong>Variante 1</strong>:</p>
<pre class="r"><code>mean.lz &lt;- mean(fb20$lz, na.rm = T) #Mittelwert
mean.lz</code></pre>
<pre><code>## [1] 5.035417</code></pre>
<pre class="r"><code>sd.lz &lt;- sd(fb20$lz, na.rm = T) #Standardabweichung
sd.lz</code></pre>
<pre><code>## [1] 1.146893</code></pre>
<pre class="r"><code>n.lz &lt;- length(na.omit(fb20$lz)) #Stichprobengroesse
se.lz &lt;- sd.lz/sqrt(n.lz) #Standardfehler
se.lz</code></pre>
<pre><code>## [1] 0.1170543</code></pre>
<p><strong>Variante 2</strong>:</p>
<pre class="r"><code>describe(fb20$lz) #Funktion aus Paket &quot;psych&quot;</code></pre>
<pre><code>##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 96 5.04 1.15    5.2    5.09 1.19 2.4   7   4.6 -0.43    -0.51 0.12</code></pre>
<p><strong>1.2 Sind die Lebenszufriedenheitswerte normalverteilt? Veranschaulichen Sie dies mit einem geeigneten Plot. Benutzen Sie die qqPlot-Funktion aus dem car-Paket sowie die lillie.test-Funktion aus dem nortest-Paket. Wie unterscheiden sie sich? Wann kann man in diesem Fall von einer Normalverteilung ausgehen?</strong></p>
<pre class="r"><code>#geeigneter Plot: QQ-Plot. Alle Punkte sollten auf einer Linie liegen.
qqnorm(fb20$lz)
qqline(fb20$lz)</code></pre>
<p><img src="/post/2020-12-11-tests-und-konfidenzintervalle-loesungen_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>#Die qqPlot-Funktion zeichnet ein Konfidenzintervall in den QQ-Plot. Dies macht es fuer den Betrachter einfacher zu entscheiden, ob alle Punkte in etwa auf einer Linie liegen. Die Punkte sollten nicht ausserhalb der blauen Linien liegen.
qqPlot(fb20$lz)</code></pre>
<p><img src="/post/2020-12-11-tests-und-konfidenzintervalle-loesungen_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<pre><code>## [1] 19 56</code></pre>
<pre class="r"><code>#Der Lillie-Test (Kolmogorov-Smirnov Test), testet die H0, dass eine Normalverteilung vorliegt. Daher sollte der Test nicht signifikant sein
lillie.test(fb20$lz)</code></pre>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  fb20$lz
## D = 0.1143, p-value = 0.003513</code></pre>
<p>Sowohl der QQ-Plot als auch der Lilliefors-Test pruefen die Daten auf Normalverteilung, wobei der QQ-Plot grafisch und der Lilliefors-Test inferenzstatistisch vorgeht. Obwohl der QQ-Plot nicht eindeutig ist, kann man davon ausgehen, dass die Daten <strong>nicht</strong> normalverteilt sind.</p>
<p><strong>1.3 Unterscheidet sich die Lebenszufriedenheit der Psychologie-Studierenden von der Lebenszufriedenheit der Gesamtbevoelkerung (<span class="math inline">\(\mu\)</span> = 4.7)? Bestimmen Sie das 99%ige Konfidenzintervall.</strong></p>
<p>Da die Varianz der Grundgesamtheit nicht bekannt ist, wird ein t-Test herangezogen.
Obwohl keine Normalverteilung vorliegt, können wir aufgrund des <em>zentralen Grenzwertsatzes</em> trotzdem einen t-Test rechnen.</p>
<p><strong>Hypothesengenerierung:</strong></p>
<p><span class="math inline">\(\alpha\)</span> = .05</p>
<p><span class="math inline">\(H_0\)</span>: Die durchschnittliche Lebenzufriedenheit der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> unterscheidet sich nicht von der Lebenszufriedenheit der Gesamtbevoelkerung <span class="math inline">\(\mu_0\)</span>.</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(=\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p><span class="math inline">\(H_1\)</span>: Die durchschnittliche Lebenzufriedenheit der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> unterscheidet sich von der Lebenszufriedenheit der Gesamtbevoelkerung <span class="math inline">\(\mu_0\)</span>.</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(\neq\)</span> <span class="math inline">\(\mu_1\)</span></p>
<pre class="r"><code>t.test(fb20$lz, mu=4.7)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb20$lz
## t = 2.8655, df = 95, p-value = 0.005126
## alternative hypothesis: true mean is not equal to 4.7
## 95 percent confidence interval:
##  4.803035 5.267799
## sample estimates:
## mean of x 
##  5.035417</code></pre>
<pre class="r"><code>t.test(fb20$lz, mu=4.7, conf.level = 0.99) #Default ist 95%, deshalb erhoehen wir auf 99%</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb20$lz
## t = 2.8655, df = 95, p-value = 0.005126
## alternative hypothesis: true mean is not equal to 4.7
## 99 percent confidence interval:
##  4.727731 5.343103
## sample estimates:
## mean of x 
##  5.035417</code></pre>
<p>Mit einer Irrtumswahrscheinlichkeit von 5% kann die <span class="math inline">\(H_0\)</span> verworfen werden. Die Psychologie-Studierenden unterscheiden sich in ihrer Lebenszufriedenheit von der Gesamtbevoelkerung.</p>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<p><strong>Die durchschnittliche Abschlussnote im Fach Psychologie (Bachelor) ist 2.01 (<em>SD</em> = 0.57). Eine Forschungsgruppe vermutet, dass sich die durchschnittliche Abschlussnote ueber die Jahre veraendert hat und nun besser ist. Um dies zu ueberpruefen, untersucht die Forschergruppe eine zufuellige Stichprobe aus 140 Psychologie-Studierenden (<em>N</em> = 140). Sie ermitteln eine durchschnittliche Abschlussnote von 1.81.</strong></p>
<p><strong>2.1 Reicht diese Information aus, um nachzuweisen, dass sich die durchschnittliche Abschlussnote veraendert hat? Berechnen Sie wenn moeglich, ob es eine Veraenderung gab (<span class="math inline">\(\alpha\)</span> = .05).</strong></p>
<p>Ja, diese Informationen reichen aus. Die Standardabweichung der Stichprobe wird nicht benoetigt.</p>
<p><strong>Hypothesengenerierung:</strong></p>
<p><span class="math inline">\(\alpha\)</span> = .05</p>
<p><span class="math inline">\(H_0\)</span>: Die durchschnittliche Abschlussnote der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> ist schlechter oder gleich gross wie zuvor (<span class="math inline">\(\mu_0\)</span>).</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(\leq\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p><span class="math inline">\(H_1\)</span>: Die durchschnittliche Abschlussnote der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> ist besser als zuvor (<span class="math inline">\(\mu_0\)</span>).</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(&gt;\)</span> <span class="math inline">\(\mu_1\)</span></p>
<pre class="r"><code>mean.note &lt;- 2.01 #Mittelwert alt
mean.sd &lt;- 0.57 #Standardabweichung alt
n.new.note &lt;- 140 #Stichprobengroesse
new.mean.note &lt;- 1.81 #Mittelwert neu
se.mean.note &lt;- 0.57/sqrt(n.new.note) #Standardfehler
z.note &lt;- abs((new.mean.note-mean.note)/se.mean.note) #empirischer z-Wert
z.note</code></pre>
<pre><code>## [1] 4.151635</code></pre>
<pre class="r"><code>z_krit &lt;- qnorm(1-.05) #kritischer z-Wert
z_krit</code></pre>
<pre><code>## [1] 1.644854</code></pre>
<pre class="r"><code>z.note &gt; z_krit #Signifikanzentscheidung</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Mit einer Irrtumswahrscheinlichkeit von 5% kann die <span class="math inline">\(H_0\)</span> (keine Veraenderung) verworfen werden. Die Abschlussnote hat sich ueber die Jahre verbessert.</p>
<p><strong>2.2 Wie wahrscheinlich ist angesichts der bekannten Normalverteilung der z-Werte dieser z-Wert?</strong></p>
<pre class="r"><code>pnorm(z.note)</code></pre>
<pre><code>## [1] 0.9999835</code></pre>
</div>
<div id="aufgabe-3-zusatz" class="section level2">
<h2>Aufgabe 3 (Zusatz)</h2>
<p><strong>3.1 Unterscheiden sich die Extraversionswerte (<code>extra</code>) der Studierenden der Psychologie (1. Semester) von den Extraversionswerten der Gesamtbevoelkerung (<span class="math inline">\(\mu\)</span> = 3.5)? Bestimmen Sie das 95%ige Konfidenzintervall und die Effektgroesse.</strong></p>
<p><strong>Hypothesengenerierung:</strong></p>
<p><span class="math inline">\(\alpha\)</span> = .05</p>
<p><span class="math inline">\(H_0\)</span>: Die durchschnittlichen Extraversionswerte der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> unterscheiden sich nicht von den Werten der Gesamtbevoelkerung <span class="math inline">\(\mu_0\)</span>.</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(=\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p><span class="math inline">\(H_1\)</span>: Die durchschnittlichen Extraversionswerte der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> unterscheiden sich von den Werten der Gesamtbevoelkerung <span class="math inline">\(\mu_0\)</span>.</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(\neq\)</span> <span class="math inline">\(\mu_1\)</span></p>
<pre class="r"><code>t.test(fb20$extra, mu=3.5)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb20$extra
## t = -0.50995, df = 97, p-value = 0.6112
## alternative hypothesis: true mean is not equal to 3.5
## 95 percent confidence interval:
##  3.325287 3.603284
## sample estimates:
## mean of x 
##  3.464286</code></pre>
<p>Mit einer Irrtumswahrscheinlichkeit von 5% kann die <span class="math inline">\(H_0\)</span> beibehalten werden. Die Psychologie-Studierenden unterscheiden sich nicht in ihrer Extraversion von der Gesamtbevoelkerung.
Mit einer 95%-igen Wahrscheinlichkeit liegt der wahre Extraversionswert <span class="math inline">\(\mu\)</span> zwischen 3.33 und 3.60.</p>
<p>Da sich die Werte nicht signifikant unterscheiden, ist es nicht sinnvoll die Effektgroesse zu berechnen.</p>
<p><strong>3.2 Sind die Prokrastinationswerte (<code>pro</code>) der Psychologie-Studierenden (1. Semester) groesser als die Prokrastinationswerte der Gesamtbevoelkerung (<span class="math inline">\(\mu\)</span> = 2.1)? Bestimmen Sie das 99%ige Konfidenzintervall und die Effektgroesse.</strong></p>
<p><strong>Hypothesengenerierung:</strong></p>
<p><span class="math inline">\(\alpha\)</span> = .05</p>
<p><span class="math inline">\(H_0\)</span>: Die durchschnittlichen Prokrastinationswerte der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> sind geringer oder gleich gross wie die Werte der Gesamtbevoelkerung <span class="math inline">\(\mu_0\)</span>.</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(\geq\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p><span class="math inline">\(H_1\)</span>: Die durchschnittlichen Prokrastinationswerte der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> sind groesser als die Werte der Gesamtbevoelkerung <span class="math inline">\(\mu_0\)</span>.</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(&lt;\)</span> <span class="math inline">\(\mu_1\)</span></p>
<pre class="r"><code>t.test(fb20$pro, mu=2.1, alternative=&quot;greater&quot;, conf.level = 0.99)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb20$pro
## t = 4.6604, df = 97, p-value = 5.03e-06
## alternative hypothesis: true mean is greater than 2.1
## 99 percent confidence interval:
##  2.226629      Inf
## sample estimates:
## mean of x 
##  2.357143</code></pre>
<p>Mit einer Irrtumswahrscheinlichkeit von 5% kann die <span class="math inline">\(H_0\)</span> verworfen und die <span class="math inline">\(H_1\)</span> angenommen werden. Die Psychologie-Studierenden haben hoehere Prokrastinationswerte im Vergleich zur Gesamtbevoelkerung.
Mit einer 99%-igen Wahrscheinlichkeit liegt der wahre Prokrastinationswert <span class="math inline">\(\mu\)</span> zwischen 2.23 und Inf (Ausserhalb des definierten Wertebereichs).</p>
<p><strong>Effektgroesse:</strong></p>
<pre class="r"><code>mean_pro &lt;- mean(fb20$pro, na.rm = T) #MW der Stichprobe
sd_pro &lt;- sd(fb20$pro, na.rm = T) #Stichproben SD (Populationsschaetzer)
mean_Popu_pro &lt;- 2.1 #MW der Grundgesamtheit
d2 &lt;- abs((mean_pro - mean_Popu_pro)/sd_pro) #abs(), da Betrag
d2</code></pre>
<pre><code>## [1] 0.4707725</code></pre>
<p>Die Effektgroesse ist als mittel einzuordnen.</p>
<p><strong>3.3 Sind die Psychologie-Studierenden (1. Semester) vertraeglicher (<code>vertr</code>) als die Grundgesamtheit (<span class="math inline">\(\mu\)</span> = 3.5)? Bestimmen Sie das 95%ige Konfidenzintervall und die Effektgroesse.</strong></p>
<p><strong>Hypothesengenerierung:</strong></p>
<p><span class="math inline">\(\alpha\)</span> = .05</p>
<p><span class="math inline">\(H_0\)</span>: Die durchschnittlichen Vertraeglichkeitswerte der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> sind geringer oder gleich gross wie die Werte der Gesamtbevoelkerung <span class="math inline">\(\mu_0\)</span>.</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(\geq\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p><span class="math inline">\(H_1\)</span>: Die durchschnittlichen Vertraeglichkeitswerte der Psychologie-Studierenden <span class="math inline">\(\mu_1\)</span> sind groesser als die Werte der Gesamtbevoelkerung <span class="math inline">\(\mu_0\)</span>.</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(&lt;\)</span> <span class="math inline">\(\mu_1\)</span></p>
<pre class="r"><code>t.test(fb20$vertr, mu=3.5, alternative = &quot;greater&quot;)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb20$vertr
## t = 15.115, df = 97, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is greater than 3.5
## 95 percent confidence interval:
##  4.222092      Inf
## sample estimates:
## mean of x 
##  4.311224</code></pre>
<p>Mit einer Irrtumswahrscheinlichkeit von 5% kann die <span class="math inline">\(H_0\)</span> verworfen und die <span class="math inline">\(H_1\)</span> angenommen werden. Die Psychologie-Studierenden haben hoehere Vertraeglichkeitswerte im Vergleich zur Gesamtbevoelkerung.
Mit einer 95%-igen Wahrscheinlichkeit liegt der wahre Vertraeglichkeitswert <span class="math inline">\(\mu\)</span> zwischen 4.22 und Inf (Ausserhalb des definierten Wertebereichs).</p>
<p><strong>Effektgroesse:</strong></p>
<pre class="r"><code>mean_vertr &lt;- mean(fb20$vertr, na.rm = T) #MW der Stichprobe
sd_vertr &lt;- sd(fb20$vertr, na.rm = T) #Stichproben SD (Populationsschaetzer)
mean_Popu_vertr &lt;- 3.99 #MW der Grundgesamtheit
d3 &lt;- abs((mean_vertr - mean_Popu_vertr)/sd_vertr) #abs(), da Betrag
d3</code></pre>
<pre><code>## [1] 0.6045841</code></pre>
<p>Die Effektgroesse ist als mittel einzuordnen.</p>
</div>
