---
title: Deskriptivstatistik für Nominal- und Ordinalskalen - Lösungen
date: '2020-11-26'
slug: deskriptiv-nominal-loesungen
categories:
  - BSc2
  - Loesungen
tags:
  - R Deskriptivstatistik
subtitle: ''
summary: ''
authors: [buchholz, nehler]
lastmod: '2020-11-26T21:07:11+02:00'
featured: no
header:
  image: "/header/descriptive_post.jpg"
  caption: "[Courtesy of pxhere](https://pxhere.com/en/photo/1227907)"
projects: []
expiryDate: '2022-09-15'
publishDate: '2021-10-29'
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="vorbereitung" class="section level3">
<h3>Vorbereitung</h3>
<details>
<summary>
Lösung
</summary>
<p>Laden Sie zunächst den Datensatz <code>fb21</code> von der pandar-Website herunter und dann ein.</p>
<pre class="r"><code>load(&#39;fb21.rda&#39;)   # Daten laden</code></pre>
<p>Die Bedeutung der einzelnen Variablen und ihre Antwortkategorien können Sie dem Dokument <a href="/post/variablen.pdf">variablen.pdf</a> entnehmen.</p>
<p>Verschaffen Sie sich nun einen Überblick über den Datensatz:</p>
<pre class="r"><code>dim(fb21)</code></pre>
<pre><code>## [1] 97 36</code></pre>
<pre class="r"><code>str(fb21)</code></pre>
<pre><code>## &#39;data.frame&#39;:    97 obs. of  36 variables:
##  $ prok1  : int  2 3 4 3 3 2 3 1 2 2 ...
##  $ prok2  : int  2 3 4 1 2 1 4 1 4 4 ...
##  $ prok3  : int  2 2 1 2 2 2 2 4 2 1 ...
##  $ prok4  : int  1 4 1 NA 2 4 1 2 1 1 ...
##  $ prok5  : int  1 1 3 2 4 2 1 2 3 2 ...
##  $ prok6  : int  3 4 4 2 2 3 1 2 4 1 ...
##  $ prok7  : int  1 2 3 1 1 3 1 1 1 2 ...
##  $ prok8  : int  1 1 1 3 1 2 2 2 2 4 ...
##  $ prok9  : int  1 3 4 1 2 1 1 2 4 4 ...
##  $ prok10 : int  4 2 2 3 3 3 3 4 2 2 ...
##  $ nr1    : int  4 3 3 1 1 1 1 4 4 2 ...
##  $ nr2    : int  4 5 3 4 2 5 2 4 5 5 ...
##  $ nr3    : int  1 1 3 1 3 3 5 5 3 3 ...
##  $ nr4    : int  3 1 3 1 2 5 4 4 5 5 ...
##  $ nr5    : int  1 5 3 1 1 5 4 5 4 1 ...
##  $ nr6    : int  4 3 1 4 5 1 3 4 1 2 ...
##  $ lz     : num  4.2 3.8 2.4 5.4 3.4 4 3.4 NA 2.2 4 ...
##  $ extra  : num  1.75 4 3.25 4.5 4 3 3.25 3.25 2.5 3 ...
##  $ vertr  : num  4.5 3.5 4 4 3.5 3 4.25 3.5 2.5 2.25 ...
##  $ gewis  : num  2.5 4.5 2.75 3 1.75 2.5 2 4 3.25 1.75 ...
##  $ neuro  : num  3.5 3.25 3 3.25 2.25 2 3.25 4.5 3.5 1.75 ...
##  $ intel  : num  3.25 3.5 3 3 3.25 2.25 3.25 3.75 3.75 2 ...
##  $ nerd   : num  4.67 3.5 2 3.17 2.33 ...
##  $ grund  : chr  &quot;&quot; &quot;&quot; &quot;&quot; &quot;&quot; ...
##  $ fach   : num  2 1 4 1 1 5 4 1 3 4 ...
##  $ ziel   : num  4 4 2 2 2 1 4 3 1 1 ...
##  $ lerntyp: num  2 2 1 2 3 3 3 2 1 2 ...
##  $ geschl : int  2 3 2 3 3 3 3 1 2 3 ...
##  $ job    : int  1 1 1 2 1 2 2 2 1 2 ...
##  $ ort    : int  1 1 2 2 1 2 2 2 1 2 ...
##  $ ort12  : int  3 2 2 3 2 1 2 3 2 2 ...
##  $ wohnen : num  4 3 3 3 4 2 2 1 3 2 ...
##  $ uni1   : num  0 0 0 1 0 0 1 0 0 1 ...
##  $ uni2   : num  0 1 1 0 0 1 0 0 1 0 ...
##  $ uni3   : num  1 0 0 0 0 0 0 0 0 0 ...
##  $ uni4   : num  0 0 0 0 1 0 0 1 0 0 ...</code></pre>
<p>Der Datensatz besteht aus 97 Zeilen (Beobachtungen) und 36 Spalten (=Variablen).</p>
</details>
</div>
<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<p>Untersuchen Sie, welche Arbeitsbranche Sie und Ihre Kommilitonen/innen nach dem Studium anstreben!</p>
<ul>
<li>Vergeben Sie zunächst die korrekten Wertelabels an die Ausprägungen der Variable.<br />
</li>
<li>Lassen Sie sich absolute und relative Häufigkeiten ausgeben.<br />
</li>
<li>Untersuchen Sie mit den geeigneten Maßen die zentrale Tendenz und Dispersion dieser Variable.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><strong>Faktor erstellen</strong></p>
<pre class="r"><code>fb21$ziel &lt;- factor(fb21$ziel,
                        levels = 1:4,
                        labels = c(&quot;Wirtschaft&quot;, &quot;Therapie&quot;, &quot;Forschung&quot;, &quot;Andere&quot;))
levels(fb21$ziel)</code></pre>
<pre><code>## [1] &quot;Wirtschaft&quot; &quot;Therapie&quot;   &quot;Forschung&quot;  &quot;Andere&quot;</code></pre>
<p><strong>Absolute und relative Häufigkeiten anfordern</strong></p>
<pre class="r"><code>table(fb21$ziel)              # absolut</code></pre>
<pre><code>## 
## Wirtschaft   Therapie  Forschung     Andere 
##         24         25         19         29</code></pre>
<pre class="r"><code>prop.table(table(fb21$ziel))  # relativ</code></pre>
<pre><code>## 
## Wirtschaft   Therapie  Forschung     Andere 
##  0.2474227  0.2577320  0.1958763  0.2989691</code></pre>
<p><strong>Zentrale Tendenz und Dispersion für nominalskalierte Variablen: Modus, relativer Informationsgehalt</strong></p>
<pre class="r"><code># Modus
which.max(table(fb21$ziel))</code></pre>
<pre><code>## Andere 
##      4</code></pre>
<pre class="r"><code>#relativer Informationsgehalt
hj &lt;- prop.table(table(fb21$ziel))  # hj erstellen
ln_hj &lt;- log(hj)                    # Logarithmus bestimmen
summand &lt;- ln_hj * hj               # Berechnung fuer jede Kategorie
summe &lt;- sum(summand)               # Gesamtsumme
k &lt;- length(hj)                     # Anzahl Kategorien bestimmen
relInf &lt;- -1/log(k) * summe         # Relativer Informationsgehalt
relInf</code></pre>
<pre><code>## [1] 0.9920823</code></pre>
<p>Der Modus der Variable lautet Andere - die meisten Ihres Jahrgangs (<em>n</em> = 29 bzw. 29.9%) streben einen Job in diesem Bereich an. Der relative Informationsgehalt der Variable beträgt 0.99.</p>
</details>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<p>Die Variable <code>nr3</code> enthält die Angaben über das Ausmaß, in dem Sie und Ihre Kommilitonen/-innen Ihre Verbindung zur Natur als Teil Ihrer Spiritualität ansehen.</p>
<ul>
<li>Bestimmen Sie für diese Variable den Modus.<br />
</li>
<li>Untersuchen Sie die Streuung für diese Variable optisch, indem Sie einen Boxplot erstellen.<br />
</li>
<li>Bestimmen Sie die Quartile und den Interquartilsbereich (IQB) auch als Zahlen.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><strong>Modus</strong></p>
<pre class="r"><code>which.max(table(fb21$nr3))</code></pre>
<pre><code>## 3 
## 3</code></pre>
<p><strong>Häufigkeiten</strong></p>
<pre class="r"><code>table(fb21$nr3)</code></pre>
<pre><code>## 
##  1  2  3  4  5 
## 20 20 21 21 13</code></pre>
<pre class="r"><code>prop.table(table(fb21$nr3))</code></pre>
<pre><code>## 
##         1         2         3         4         5 
## 0.2105263 0.2105263 0.2210526 0.2210526 0.1368421</code></pre>
<p>Der Modus der Variable “nr3” beträgt 3, d.h. diese Antwortkategorie wurde am häufigsten genannt (<em>n</em> = 21 bzw. 22.11%).</p>
<p><strong>Boxplot</strong></p>
<pre class="r"><code>boxplot(fb21$nr3)</code></pre>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen-loesungen_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p><strong>Quartile</strong></p>
<pre class="r"><code>quantile(fb21$nr3, c(.25,.5,.75), na.rm=T)</code></pre>
<pre><code>## 25% 50% 75% 
##   2   3   4</code></pre>
<p>Der Median beträgt 3. Das 1. und 3. Quartil betragen 2 bzw. 4. Folglich beträgt der Interquartilsbereich (IQB) 2.</p>
</details>
</div>
<div id="aufgabe-3" class="section level2">
<h2>Aufgabe 3</h2>
<p>Erstellen Sie für die Variable <code>wohnen</code> eine geeignete Abbildung.</p>
<ul>
<li>Stellen Sie sicher, dass die einzelnen Ausprägungen der Variable in der Darstellung interpretierbar benannt sind!<br />
</li>
<li>Dekorieren Sie diese Abbildung nach eigenen Wünschen (z.B. mit einer Farbpalette und Achsenbeschriftungen).</li>
<li>Speichern Sie die Grafik per Syntax als .jpg-Datei mit dem Namen “Befragung-fb21.jpg” ab.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><strong>Faktor erstellen</strong></p>
<pre class="r"><code>fb21$wohnen &lt;- factor(fb21$wohnen, 
                      levels = 1:4, 
                      labels = c(&quot;WG&quot;, &quot;bei Eltern&quot;, &quot;alleine&quot;, &quot;sonstiges&quot;))</code></pre>
<p><strong>Default Darstellung und überarbeitete Grafik</strong></p>
<pre class="r"><code>par(mfrow=c(1,2))

# Default
barplot(table(fb21$wohnen))

# Überarbeitet
barplot(
  # wichtig: Funktion auf Häufigkeitstabelle, nicht die Variable selbst anwenden:
  table(fb21$wohnen),                               
  # aussagekräftiger Titel, inkl. Zeilenumbruch (&quot;\n&quot;) 
  main = &quot;Befragung Erstis im WS 20/21:\nAktuelle Wohnsituation&quot;, 
  # y-Achsen-Beschriftung:
  ylab = &quot;Häufigkeit&quot;,
  # Farben aus einer Farbpalette:
  col = rainbow(10),
  # Platz zwischen Balken minimieren:
  space = 0.1,
  # graue Umrandungen der Balken:
  border = &quot;grey2&quot;,
  # Unterscheidlich dichte Schattierungen (statt Füllung) für die vier Balken:
  density = c(50, 75, 25, 50),
  # Richtung, in dem die Schattierung in den vier Balken verläuft
  angle = c(-45, 0, 45, 90),
  # Schriftausrichtung der Achsen horizontal:
  las=2,
  #y-Achse erweitern, sodass mehr Platz zum Titel bleibt:
  ylim = c(0,60))</code></pre>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen-loesungen_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p><strong>Speichern (per Syntax)</strong></p>
<pre class="r"><code>jpeg(&quot;Befragung-fb21.jpg&quot;, width=20, height=10, units=&quot;cm&quot;, res=200)
barplot(
  table(fb21$wohnen),                               
  main = &quot;Befragung Erstis im WS 21/22:\nAktuelle Wohnsituation&quot;, 
  ylab = &quot;Häufigkeit&quot;,
  col = rainbow(10),
  space = 0.1,
  border = &quot;grey2&quot;,
  density = c(50,75,25,50),
  angle = c(-45,0,45,90),
  las=2,
  ylim = c(0,60))
dev.off()</code></pre>
<p>Im Arbeitsverzeichnis sollte die Datei nun vorliegen.</p>
</details>
</div>
