---
title: GitHub
date: '2021-06-13'
slug: github
categories:
  - "github"
tags: []
subtitle: ''
summary: ''
authors: [nehler, rouchi]
featured: no
header:
  image: ""
  caption: ""
projects: []
publishDate: '2021-07-16'
---


# Warum GitHub?

Im ersten Teil haben wir mit `git` eine Möglichkeit der lokalen Versionskontrolle kennen gelernt. Welche Vorteile bietet es nun, noch mehr Tools zu erlernen? Oft arbeitet man an einem Projekt nicht alleine, sondern kollaboriert mit anderen. Oder man möchte die Dateien nicht nur lokal auf dem eigenen PC haben sondern auch eine virtuelle Version als Backup. `GitHub` ist die Lösung für beide Anforderungen!

## Einführung

Ganz grundlegend ist `GitHub` ein Seite, die als Host für `git` repositories dienen kann. Es gibt natürlich auch andere Anbieter wie `GitLab` oder `Bitbucket`, aber die Logik hinter diesen ist recht ähnlich. Wir fokussieren uns in dem Tutorial vollständig auf `GitHub`. Durch das Verbinden einer lokalen Version des repositories ist dieses virtuell hinterlegt ähnlich einer Dropbox. Dabei kann man ein repository öffentlich für jeden einsehbar oder auch privat (nur für sich oder Projektpartner:innen einsehbar) zur Verfügung stellen. Während private repositories hauptsächlich der gemeinsamen Arbeit an einem Projekt dienen, kann man in öffentlichen auch Ansätze der Programmierung explorieren, dadurch für die eigene Arbeit lernen oder auf Probleme und Bugs in gehosteten Projekten hinweisen. GitHub bietet gute Möglichkeiten, um schnell zu interagieren, auch ohne die Überwindung eine E-Mail schreiben zu müssen. Es gibt auch einige weitere Features wie bspw. ein Tab zum Projekt Management. Für Studierende und Mitarbeitende in der Wissenschaft ist die Verwendung kostenlos.

Gegenüber häufig genutzten Dropboxen gibt es verschiedene Vorteile. In diesen ist die Versionskontrolle meist nicht über eine lange Zeit und kostenlos nutzbar. Weiterhin ist sie meist jeweils auf eine Datei im Ordner konzentriert und nicht auf den gesamten Stand des Projekts. Nach eigener Erfahrung führt die Kombination von Dropbox und `git` häufiger zu Fehlern und wird daher nicht empfohlen.

Die Arbeit an Dateien wird auch mit einer Verbindung zu `GitHub` weiterhin lokal durchgeführt. Dafür werden die im letzten Tutorial erlernten Befehle verwendet. Diese müssen jedoch erweitert werden, damit das repository auch remote (also online) zur Verfügung gestellt und aktuell gehalten wird.


# GitHub Setup

`GitHub` kann direkt über den Webbrowser genutzt werden. Über [https://github.com/](https://github.com/) kann man auf die Seite zugreifen. Im Vergleich zur Eingabeaufforderung ist GitHub deutlich benutzerfreundlicher aufbereitet. Im Folgenden wird schrittweise erklärt, wie ihr `GitHub` einrichten und mit dem lokalen Ordner auf eurem Rechner verbinden könnt.


### Schritt 1: `GitHub`-Account erstellen

Um GitHub nutzen zu können, müsst ihr zunächst einen **GitHub-Account** erstellen. Das kann man [hier](https://github.com/join) machen. Nehmt dafür am besten die studentische E-Mail-Adresse, die ihr auch bereits im letzten Tutorial mit `git` verbunden habt.


### Schritt 2: Neues `repository` erstellen

#### Fall 1: Lokales `repository` mit `GitHub` verknüpfen

Um ein neues `repository` auf `GitHub` zu erstellen, kann man oben rechts in der Menüleiste unter dem Punkt `+` auf `New repository` klicken. 
Unter `Repository name` kann ein Name festgelegt werden und unter `Description` kann man eine kurze Beschreibung hinzufügen. Wichtig ist, dass die Einstellung für das `repository` auf `Public`, also öffentlich, festgelegt ist. Man kann außerdem eine `README`-Datei erstellen, eine Datei mit Informationen über das angelegte Projekt. Mit einem Klick auf `Create repository` wird dieses dann erstellt.

*Screenshot*

Da wir ein lokales Projekt, unsere Datenauswertung für das Statistik-Praktikum, mit dem `repository` auf GitHub verknüpfen wollen, müssen wir kurz zurück in das Terminals des Rechners. Mithilfe von 
```
git remote add origin DieURL
``` 
können die lokale und die "Cloud"-Version verbunden werden. Dazu benötigt man lediglich die URL des `GitHub`-repositorys. Die URL erhält man, wenn man auf der `GitHub`-Seite auf den grünen Button `Code`klickt. Anschließend muss noch 
```
git push -u origin master
```
eingegeben werden. 

*Screenshot*

Jetzt sind die lokale Version des Projekts auf dem Rechner und die "Cloud"-Version auf `GitHub` miteinander verbunden. Dies ermöglicht, dass mehrere Personen auf das gleiche Projekt zugreifen und jeweils eine lokale Kopie auf ihren Rechnern haben können. Beispielsweise könnt ihr mit euren Kommiliton:innen am gleichen R-Skript für die Datenauswertung arbeiten und seid somit immer auf dem aktuellsten Stand. Ihr müsst auch nicht mehr mühsam Dateien hin- und herschicken und Änderungen versuchen kenntlich zu machen, das erledigt `GitHub` für euch! Damit das gemeinsame Arbeiten am selben Projekt ermöglicht wird, folgen jetzt ein paar Basics zu den Funktionen von `GitHub`.


#### Fall 2: Remote existierendes `repository` von `GitHub` laden

Um ein `repository`, was bereits auf `GitHub` exisitiert, auf unseren Rechner laden zu können, wechseln wir wieder kurz in das **Terminal** des Computers.
Zunächst einmal muss ein Ordner erstellt werden, in den das Projekt geladen werden soll. Das geht einfach über die Ordneransicht oder mithilfe von
```
mkdir praktikum
```
im Terminal. Vergesst hierbei nicht, vorher euer Directory festzulegen! Damit ihr diesen Ordner wieder mit `git` verknüpfen könnt, müsst ihr
```
git init
```
ausführen. Jetzt wurde der Ordner zu einem `git`-Ordner initialisiert und kann mit dem Projekt verknüpft werden.

Um das Projekt jetzt von `GitHub` in diesen Order "praktikum" zu laden, benötigt ihr wieder die URL des Projekts. In das Terminal geben wir nun den Befehl
```
git clone DieURL
```
ein und somit werden die Dateien vom Ordner, wie er auf `GitHub` vorliegt, in unseren neu erstellten Ordner geladen. Mithilfe von `commit`, `push` und `pull` können wir jetzt Änderungen an den Dateien vornehmen, diese mit der Version auf `GitHub` abgleichen und sind somit immer auf dem aktuellsten Stand.

*Screenshot*


# Basics

Jetzt wo `GitHub` eingerichtet und mit unserem lokalen Ordner `praktikum` verbunden ist, können wir Änderungen an den Dateien vornehmen. Wenn ihr etwas an dem R-Skript zur Datenauswertung ändert und commitet, ist diese Änderung zunächst nur in eurer lokalen Datei umgesetzt.


### Pull

Bevor ihr etwas an einer Datei ändern möchtet, ist es wichtig, dass ihr immer mit der aktuellsten Version des Projekts arbeitet, um Änderungen zu berücksichtigen, die andere Personen, die ebenfalls am Projekt arbeiten, übernommen zu haben.

Anhand eines `Pull`s wird immer die jeweils aktuellste Version des Projekts von `GitHub` heruntergeladen, damit der lokale Ordner auf dem neusten Stand ist. Dabei werden alle `commits` und Änderungen, die von anderen Personen vorgenommen wurden, mit der lokalen Version abgeglichen und übernommen. 

Um einen `Pull` durchzuführen, muss man in der Eingabeaufforderung 
```
git pull
```
eingeben. So wird der lokale Ordner aktualisiert und es können Änderungen an den Dateien vorgenommen werden.

*Screenshot*


### Push

Sobald ihr alle eure Änderungen vorgenommen und anhand von `commit` in `git` geladen habt, können diese über die Funktion `Push` auf `GitHub` hochgeladen werden, damit eure Kommiliton:innen widerum ihre lokalen Kopien des Projekts aktualisieren können und eure Veränderungen berücksichtigen.

Um einen `Push` durchzuführen, muss 
```
git push
``` 
in die Eingabeaufforderung eingegeben werden. Somit ist die Version des Projekts auf `GitHub` aktualisiert.

*Screenshot*


# Weitere Funktionen von `GitHub`

Wenn wir uns einmal die Aufbereitung von `GitHub` auf der Webseite anschauen, so finden wir einige Menüpunkte. Im Folgenden sind die wichtigsten kurz aufgeführt.


### Invite a collaborator

Da ihr ein Projekt auf `GitHub` ladet, um mit anderen Personen daran zu arbeiten, möchtet ihr, dass dieses für diese freigegeben werden kann. Wenn ihr also euer `praktikum`-Projekt mit euren Kommiliton:innen teilen wollt, müsst ihr sie als **collaborators** zum Projekt hinzufügen.

Über den Menüpunkt **Settings** könnt ihr links **Manage Access** auswählen und dann über **Invite a collaborator** diejenigen Personen, die mit euch am Projekt arbeiten sollen/dürfen, via *username*, *full name* oder *e-mail* hinzufügen. 

*Screenshot*


#### Als **collaborator** einem Projekt beitreten

Wenn ihr von der Person, die das `GitHub`-Projekt erstellt hat, als **collaborator** hinzugefügt worden seid, erhaltet ihr eine E-Mail mit einem **Einladungs-Link**. Wenn ihr diesen aufruft, könnt ihr über euer `GitHub`-Profil dem Projekt beitreten. Natürlich benötigt ihr dafür zunächst einen Account.

Als nächstes müsstet ihr euch eine lokale Version des bereits bestehenden Projekts auf euren Rechner herunterladen. Dies könnt ihr wie oben unter **Schritt 2** im zweiten Fall beschrieben machen.



### Issues

`Issues` kann man verwenden, um `todos`, `bugs`, `feature requests` und andere Funktionen von `GitHub` zu tracken, also nachzuverfolgen. Sie funktionieren wie Nachrichten, die zwischen den **collaborators** eines Projekts oder zwischen anderen Anwender:innen ausgetauscht werden können. 
Ein `Issue` besteht meist aus einem **Titel** und einer **Beschreibung** des Problems. Diese können mit verschiedenen Farben versehen und somit thematisch eingeordnet werden. Andere **collaborators** können diese `Issues` kommentieren und somit Hilfestellungen oder Feedback geben.

*Screenshot*



### Project boards

Mithilfe von `Project boards` können `Issues` organisiert und priorisiert werden. Für bestimmte Arbeiten oder Checklisten können `Project boards` und mit diesen maßgeschneiderte `workflows` erstellt werden.
`Project boards` können individuell aufbereitet und angerichtet werden, so dass es zu den persönlichen Präferenzen passt. 

*Screenshot?*









# Setup

Clone ist eine Kopie auf den eigenen Computer, sollte also nur einmal durchführbar sein




## Befehle

Unterschied zwische Rebase und Revert
bei einem wird alles was neuer war, als der Zeitpunkt zu dem man zurück geht, gelöscht und ist nicht zugreifbar
bei dem anderen wird der Rückgang zu dem alten Punkt als neuer Punkt im Working Tree angelegt.
