---
title: Tests für abhängige Stichproben - Lösungen
date: '2020-12-17'
slug: gruppenvergleiche-abhaengig-loesungen
categories:
  - BSc2
tags:
  - t-Test
subtitle: ''
summary: ''
authors: [koehler]
lastmod: '2020-12-17T13:15:14+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
expiryDate: '2022-09-15'
publishDate: '2021-12-17'
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p><strong>Daten einlesen</strong></p>
<pre class="r"><code>setwd(&quot;...&quot;)  
load(&quot;fb20.rda&quot;)</code></pre>
<p><strong>Daten aufbereiten</strong></p>
<pre class="r"><code># Lieblingsfach als Faktor - falls es noch keiner war
if(is.factor(fb20$fach) == FALSE){
  fb20$fach &lt;- factor(fb20$fach, 
                      levels = 1:5,
                      labels = c(&#39;Allgemeine&#39;, &#39;Biologische&#39;, &#39;Entwicklung&#39;,
                                 &#39;Klinische&#39;, &#39;Diag./Meth.&#39;))
}

# Wohnort als Faktor - falls es noch keiner war
if(is.factor(fb20$ort) == FALSE){
  fb20$ort &lt;- factor(fb20$ort, 
                     levels = c(1, 2),
                     labels = c(&#39;Frankfurt&#39;, &#39;anderer&#39;))
}

# Geschlecht als Faktor - falls es noch keiner war
if(is.factor(fb20$geschl)==FALSE){
  fb20$geschl &lt;- factor(fb20$geschl, 
                        levels=c(1,2,3), 
                        labels=c(&#39;weiblich&#39;, &#39;maennlich&#39;, &#39;anderes&#39;))
}</code></pre>
<hr />
<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<p>Geben Studierende im gleichen Maße an, dass sie “nicht munter” bzw. “nicht ausgeruht” sind (munter: mdbf10; ausgeruht: mdbf2), wie dass sie sich “schlapp” bzw. “müde” fühlen (schlapp: mdbf5; müde: mdbf7)?</p>
<details>
<summary>
Lösung
</summary>
<p><strong>Daten aufbereiten</strong></p>
<p>Items umpolen</p>
<pre class="r"><code>fb20$mdbf10_r &lt;- -1 * (fb20$mdbf10 - 6) # Item mdbf10 umpolen
fb20$mdbf2_r &lt;- -1 * (fb20$mdbf2 - 6) # Item mdbf2 umpolen</code></pre>
<p>Bedeutung nach der Umpolung:</p>
<p>Item mdbf10_r: Wie “nicht munter” fühlen Sie sich? Hohe Werte = nicht munter</p>
<p>Item mdbf2_r: Wie “nicht ausgeruht” fühlen Sie sich? Hohe Werte = nicht ausgeruht</p>
<p>Skalen mitteln über die jeweiligen Items:</p>
<pre class="r"><code>#umgepolte &quot;wache&quot; Skalen mitteln ueber beide Items
fb20$muede_r &lt;- rowMeans(fb20[, c(&#39;mdbf2_r&#39;, &#39;mdbf10_r&#39;)])
#&quot;muede&quot; Skalen mitteln ueber beide Items
fb20$muede &lt;- rowMeans(fb20[, c(&#39;mdbf5&#39;, &#39;mdbf7&#39;)])</code></pre>
<p>Unterscheiden sich die Gruppen im Mittel nicht, geben die Studierenden auf beiden Skalen im gleichen Maße an, wie wach bzw. müde sie sich fühlen.</p>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: grafisch</strong></p>
<ul>
<li><p>Balkendiagramme (angemessen für Daten mit Rangskalenqualität)</p></li>
<li><p>Je ein Balkendiagramm pro Variable, untereinander dargestellt</p></li>
</ul>
<pre class="r"><code>par(mfrow=c(2,1), mar=c(3,3,3,0))
barplot(table(fb20[, &quot;muede_r&quot;]), ylim = c(0,40), main=&quot;nicht müde&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)
barplot(table(fb20[, &quot;muede&quot;]), ylim = c(0,40), main=&quot;müde&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,1))</code></pre>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: statistisch</strong></p>
<pre class="r"><code>summary(fb20[, &quot;muede_r&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.500   2.000   2.750   2.811   3.500   4.500</code></pre>
<pre class="r"><code>summary(fb20[, &quot;muede&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.500   2.500   2.561   3.000   5.000</code></pre>
<pre class="r"><code>prop.table(table(fb20$muede_r))</code></pre>
<pre><code>## 
##        1.5          2        2.5          3        3.5          4        4.5 
## 0.08163265 0.19387755 0.22448980 0.22448980 0.12244898 0.10204082 0.05102041</code></pre>
<pre class="r"><code>prop.table(table(fb20$muede))</code></pre>
<pre><code>## 
##          1        1.5          2        2.5          3        3.5          4 
## 0.11224490 0.16326531 0.13265306 0.16326531 0.18367347 0.11224490 0.05102041 
##        4.5          5 
## 0.05102041 0.03061224</code></pre>
<p>Werte auf der umgepolten “wach” Skala leicht höher als Werte auf Skala “muede”.</p>
<p><strong>Voraussetzungen für t-Test für abhängige Stichproben</strong></p>
<ol style="list-style-type: decimal">
<li>Die abhängige Variable ist intervallskaliert <span class="math inline">\(\rightarrow\)</span> nicht gegeben <span class="math inline">\(\rightarrow\)</span> Wilcoxon Test für abhängige Stichproben</li>
<li>Die Messwerte innerhalb der Paare dürfen sich gegenseitig beeinflussen/voneinander abhängig sein; außerdem keine Abhängigkeiten zwischen den Messwertpaaren</li>
<li>Die Differenzvariable <em>d</em> muss in der Population normalverteilt sein</li>
</ol>
<p>(2. und 3. nicht mehr relevant, da wir Wilcoxon Test anwenden)</p>
<p><strong>Hypothesen</strong></p>
<p>Hypothesenpaar (inhaltlich):</p>
<p>H0: Studierende geben im gleichen Ausmaß an, dass sie “nicht munter” sind, wie dass sie sich “schlapp/müde” fühlen.<br />
H1: Studenten geben eher an, dass sie “nicht munter” sind, als dass sie sich “schlapp/müde” fühlen bzw. umgekehrt.</p>
<ul>
<li>Art des Effekts: Unterschiedshypothese<br />
</li>
<li>Richtung des Effekts: Ungerichtet<br />
</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypthesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{&quot;nicht-munter&quot;} = \mu_{&quot;schlapp&quot;}\)</span> bzw. <span class="math inline">\(\mu_{d} = 0\)</span></li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_{&quot;nicht-munter&quot;} \ne \mu_{&quot;schlapp&quot;}\)</span> bzw. <span class="math inline">\(\mu_{d} \ne 0\)</span></li>
</ul>
<p><strong>Spezifikation des Signifikanzniveaus</strong></p>
<p><span class="math inline">\(\alpha = .05\)</span></p>
<p><strong>Durchführung des Wilcoxon-Tests für abhängige Stichproben in R</strong></p>
<pre class="r"><code>wilcox.test(x = fb20$muede_r, y = fb20$muede, # die beiden abhaengigen Items  
            paired = T,                       # Stichproben sind abhaengig
            alternative = &quot;two.sided&quot;,        # zweinseitige Testung
            conf.level = .95)                 # alpha = .05</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  fb20$muede_r and fb20$muede
## V = 1709.5, p-value = 0.002088
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p><strong>Formales Berichten des Ergebnisses</strong></p>
<p>Es wurde untersucht, ob Studierende in gleichem Maße angeben, dass sie “nicht munter” bzw. “nicht ausgeruht” sind, wie dass sie sich schlapp bzw. müde fühlen.</p>
<p>Zur Beantwortung der Fragestellung wurde ein zweinseitiger Wilcoxon-Test für abhängige Stichproben durchgeführt. Der Unterschied wurde bei einem Signifikanzniveau von alpha = .05 signifikant (V = 1709.5, <em>p</em> = .002). Somit wird die Nullhypothese verworfen und die Alternativhypothese angenommen: Studenten geben eher an, dass sie “nicht munter” sind (d.h. niedrige Werte auf den Items “munter” und “ausgeruht”), als dass sie sich “schlapp/müde” fühlen.</p>
</details>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<p>Ein Therapeut behauptet, dass eine von ihm entwickelte Meditation die Zufriedenheit von Menschen positiv beeinflusst. Er möchte dies mit wissenschaftlichen Methoden zeigen und misst die Zufriedenheit vor und nach der Meditation (Daten mit Intervallskalenqualität). Es ergeben sich folgende Werte für 18 Personen:</p>
<table>
<thead>
<tr class="header">
<th align="right">Vpn</th>
<th align="right">Vorher</th>
<th align="right">Nachher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">4</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">6</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">3</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">7</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">2</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">8</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">3</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">5</td>
<td align="right">6</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">6</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">4</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">5</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="right">4</td>
<td align="right">6</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="right">3</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="right">7</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="right">7</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="right">6</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="right">4</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="right">18</td>
<td align="right">7</td>
<td align="right">8</td>
</tr>
</tbody>
</table>
<p>Wirkt die Meditation auf die Zufriedenheit?</p>
<details>
<summary>
Lösung
</summary>
<p><strong>Datensatz generieren</strong></p>
<pre class="r"><code>dataMeditation &lt;- data.frame(Vpn = 1:18, Vorher = c(4,6,3,7,2,8,3,5,6,4,5,4,3,7,7,6,4,7), Nachher = c(6,7,8,7,4,7,6,6,8,5,9,6,6,7,6,4,5,8))</code></pre>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: grafisch</strong></p>
<p>Histogramme (weil Intervallskalenqualität):
Je ein Histogramm pro Gruppe, untereinander dargestellt, vertikale Linie für den jeweiligen Mittelwert</p>
<pre class="r"><code>par(mfrow=c(2,1), mar=c(3,2,2,0))
hist(dataMeditation[, &quot;Vorher&quot;], xlim=c(0,10), ylim=c(1,6), main=&quot;Zufriedenheit vor der Meditation&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)
abline(v=mean(dataMeditation[, &quot;Vorher&quot;]), lty=2, lwd=2)
hist(dataMeditation[, &quot;Nachher&quot;], xlim=c(0,10), ylim=c(1,6), main=&quot;Zufriedenheit nach der Meditation&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)
abline(v=mean(dataMeditation[, &quot;Nachher&quot;]), lty=2, lwd=2)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,1))</code></pre>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: statistisch</strong></p>
<pre class="r"><code>summary(dataMeditation[, &quot;Vorher&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.000   4.000   5.000   5.056   6.750   8.000</code></pre>
<pre class="r"><code>summary(dataMeditation[, &quot;Nachher&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.000   6.000   6.000   6.389   7.000   9.000</code></pre>
<pre class="r"><code>#alternativ
library(psych)
describe(dataMeditation[, &quot;Vorher&quot;])</code></pre>
<pre><code>##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 18 5.06 1.76      5    5.06 2.22   2   8     6 -0.02    -1.39 0.42</code></pre>
<pre class="r"><code>describe(dataMeditation[, &quot;Nachher&quot;])</code></pre>
<pre><code>##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 18 6.39 1.38      6    6.38 1.48   4   9     5 -0.04    -0.84 0.32</code></pre>
<p>Mittelwert vorher (<em>M</em> = 5.1, <em>SD</em> = 1.76) ist deskriptiv niedriger als Mittelwert nachher (<em>M</em> = 6.4, <em>SD</em> = 1.38).</p>
<p><strong>Voraussetzungen für t-Test für abhängige Stichproben</strong></p>
<ol style="list-style-type: decimal">
<li>Die abhängige Variable ist intervallskaliert <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Die Messwerte innerhalb der Paare dürfen sich gegenseitig beeinflussen/voneinander abhängig sein; keine Abhängigkeiten zwischen den Messwertpaaren <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Die Differenzvariable <em>d</em> muss in der Population normalverteilt sein <span class="math inline">\(\rightarrow\)</span> ab <em>n</em> =&gt; 30 gegeben, ansonsten grafische Prüfung oder Hintergrundwissen</li>
</ol>
<p><strong>Voraussetzungsprüfung: Normalverteilung von <em>d</em></strong></p>
<pre class="r"><code>par(mar=c(3,3,3,0)) #aendern der Raender (margins) des Plot-Fensters
difference &lt;- dataMeditation[, &quot;Vorher&quot;]-dataMeditation[, &quot;Nachher&quot;]
hist(difference, xlim=c(-6,4), main=&quot;Verteilung der Differenzen&quot;, xlab=&quot;Differenzen&quot;, ylab=&quot;&quot;, las=1,freq=F)
curve(dnorm(x, mean=mean(difference), sd=sd(difference)), col=&quot;blue&quot;, lwd=2, add=T)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,1)) #Zuruecksetzens auf default
qqnorm(difference,las=1)
qqline(difference, col=&quot;blue&quot;)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<p><span class="math inline">\(\Rightarrow\)</span> Differenzen sehen einigermaßen normalverteilt aus</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Unterschiedshypothese<br />
</li>
<li>Richtung des Effekts: Gerichtet <span class="math inline">\(\rightarrow\)</span> gerichtete Hypothesen (Der Wissenschaftler erwartet eine positive Wirkung
# der Meditation auf die Zufriedenheit.)</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hyothesenpaar (inhaltlich):<br />
H0: Die Meditation wirkt sich nicht oder negativ auf die Zufriedenheit aus.
H1: Die Meditation wirkt sich positiv auf die Zufriedenheit aus.</p>
<p>Hypthesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\eta_{vorher} \ge \eta_{nachher}\)</span> bzw. <span class="math inline">\(\mu_{d} \ge 0\)</span></li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\eta_{vorher} &lt; \eta_{nachher}\)</span> bzw. <span class="math inline">\(\mu_{d} &lt; 0\)</span></li>
</ul>
<p><strong>Spezifikation des Signifikanzniveaus</strong></p>
<p><span class="math inline">\(\alpha = .05\)</span></p>
<p><strong>Durchführung des <em>t</em>-Tests für abhängige Stichproben in R</strong></p>
<pre class="r"><code>t.test(x = dataMeditation[, &quot;Vorher&quot;], y  = dataMeditation[, &quot;Nachher&quot;], # die beiden abhaengigen Gruppen
       paired = T,                       # Stichproben sind abhaengig
       alternative = &quot;less&quot;,             # gerichtete Hypothese -&gt; einseitige Testung
       conf.level = .95)                 # alpha = .05</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  dataMeditation[, &quot;Vorher&quot;] and dataMeditation[, &quot;Nachher&quot;]
## t = -3.174, df = 17, p-value = 0.002775
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##        -Inf -0.6025523
## sample estimates:
## mean of the differences 
##               -1.333333</code></pre>
<ul>
<li>Zur Erinnerung: <em>df</em> bei <em>t</em>-test mit abhängigen Stichproben: <em>n</em> - 1 (wobei <em>n</em> die Anzahl der Paare darstellt)</li>
<li><em>t</em>(0.05;17) = -3.174, <em>p</em> &lt; .05 <span class="math inline">\(\rightarrow\)</span> signifikant, H0 wird verworfen, H1 wird angenommen.</li>
</ul>
<p><strong>Schätzung des standardisierten Populationseffekts</strong></p>
<pre class="r"><code>mean_d &lt;- mean(difference)
sd.d.est &lt;- sd(difference) #die geschaetzte SD der Differenzen
d_Meditation &lt;- mean_d/sd.d.est</code></pre>
<p><span class="math inline">\(\Rightarrow\)</span> Der standardisierte Populationseffekt beträgt <em>d2’’</em> = -0.75 und ist laut Konventionen nach Cohen (1988) groß.</p>
<p><strong>Formales Berichten des Ergebnisses</strong></p>
<p>Es wurde in einer Wiederholungsmessung untersucht, ob sich Meditation auf Zufriedenheit auswirkt. Zunächst findet sich deskriptiv ein Unterschied: Vor der Meditation liegt der durchschnittliche Zufriedenheitswert bei 5.06 (<em>SD</em> = 1.76), während er nach der Meditation bei 6.39 (<em>SD</em> = 1.38) liegt.</p>
<p>Zur Beantwortung der Fragestellung wurde ein gerichteter <em>t</em>-Test für abhängige Stichproben durchgeführt. Der Gruppenunterschied ist signifikant (<em>t</em>(17) = -3.17, <em>p</em> &lt; .05), somit wird die Nullhypothese verworfen und die Alternativhypothese angenommen. Die Meditation hat einen Einfluss auf die Zufriedenheit.</p>
<p>Dieser Einfluss ist nach dem standardisierte Populationseffekt von <em>d’’</em> = 0.75 groß.</p>
</details>
</div>
