---
title: Regression - Aufgaben
author: 
date: '2021-01-04'
slug: regression-aufgaben
categories:
  - BSc2
  - Aufgaben
tags:
  - Regression
subtitle: ''
summary: ''
authors: [winkler, schroeder]
lastmod: '2021-01-04T13:18:56+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Vorbereitung
Laden Sie die Daten aus [<i class="fas fa-download"></i> `fb20.rda`](/post/fb20.rda). 
    
***
# Regression
    
## Aufgabe 1
Welche der fünf Persönlichkeitsdimensionen Extraversion (`extra`), Verträglichkeit (`vertr`), Gewissenhaftigkeit (`gewis`), Neurotizsimus (`neuro`) und Intellekt (`intel`) zeigt den höchsten linearen Zusammenhang mit der Lebenszufriedenheit (`lz`)?

  * Erstellen Sie für jeden Zusammenhang je ein Streudiagramm. 
  * Schätzen Sie für jeden Zusammenhang je ein Modell. 
  * Prüfen Sie die Voraussetzungen und interpretieren Sie den standardisierten Koeffizienten des linearen Zusammenhangs zwischen Gewissenhaftigkeit und Lebenszufriedenheit. Wie verändert sich `lz`, wenn sich `gewis` um eine Standardabweichung erhöht?

## Aufgabe 2
Ein paar Studierende wurden nachträglich zum Studiengang Psychologie zugelassen und befinden sich daher nicht im Datensatz. Die neuen Studenten wurden nachträglich befragt und weisen auf der Skala Neurotizismus folgende Werte auf: 1.25; 2.75; 3.5; 4.25; 3.75; 2.15. 

  * Machen Sie eine Vorhersage für die Lebenszufriedenheit für die neuen Studenten.
  * Erstellen Sie ein Streu-Punkt-Diagramm  mit Regressionsgerade für den linearen Zusammenhang zwischen Neurotizismus und Lebenszufriedenheit.
  * Wie viel Prozent der Varianz werden durch das Modell erklärt?

***
