---
title: Konfirmatorische Faktorenanalyse
date: '2021-04-15'
slug: cfa
categories: 
  - MSc1
tags: 
  - lavaan
  - CFA
  - latent
  - SEM
subtitle: ''
summary: ''
authors: [schultze, irmer]
lastmod: '2022-05-17T14:30:02+02:00'
featured: no
header:
  image: "/header/FEII_Sitzung3.jpg"
  caption: "[Courtesy of pxhere](https://pxhere.com/en/photo/478836)"
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="einleitung" class="section level2">
<h2>Einleitung</h2>
<p>In der <a href="/post/efa">letzten Sitzung</a> wurden faktoranalytische Verfahren für Datenexploration behandelt. Die Ergebnisse der EFA sind datengesteuert: welche Items welchen Faktoren zugeordnet werden, wie viele Faktoren genutzt werden, wie stark der Zusammenhang zwischen Item und Faktor ist, das alles sind Dinge, die aus den Daten heraus entschieden werden. In dieser Sitzung betrachten wir das Vorgehen, wenn in der Faktorenanalyse von einem konkreten, theoretisch fundierten Modell ausgegangen wird und dieses anhand empirischer Daten geprüft werden soll. Ganz im Popper’schen Sinn lässt sich nur durch ein solches Vorgehen wissenschaftliche Erkenntnis gewinnen.</p>
<p>Für die Umsetzung der CFA nutzen wir erneut <code>lavaan</code>. In der <a href="/post/lavaan-intro">ersten Sitzung dieses Semesters</a> hatten wir uns den Umgang mit <code>lavaan</code> schon detailliert angesehen. Grob gesagt gehen wir in drei Schritten vor:</p>
<ol style="list-style-type: decimal">
<li>Modellsyntax schreiben und in einem Objekt ablegen</li>
<li>Modell schätzen und Ergebnisse in Objekt ablegen</li>
<li>Ergebnisse im Objekt aus Schritt 2 inspizieren</li>
</ol>
<p>In der ersten Sitzung hatten wir gesehen, dass in <code>lavaan</code> anhand weniger Begriffe das Pfadmodell in Syntax übersetzt wird, um unser Modell schätzbar zu machen. Diese Begriffe waren</p>
<table>
<thead>
<tr class="header">
<th align="center">Bezeichnung</th>
<th align="center">Befehl</th>
<th align="center">Bedeutung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Regression</td>
<td align="center"><code>~</code></td>
<td align="center">wird vorhergesagt durch</td>
</tr>
<tr class="even">
<td align="center">Kovarianz</td>
<td align="center"><code>~~</code></td>
<td align="center">kovariiert mit</td>
</tr>
<tr class="odd">
<td align="center">Intercept</td>
<td align="center"><code>~1</code></td>
<td align="center">wird auf 1 regressiert</td>
</tr>
<tr class="even">
<td align="center">Faktorladung</td>
<td align="center"><code>=~</code></td>
<td align="center">wird gemessen durch</td>
</tr>
<tr class="odd">
<td align="center">Formative Faktoren</td>
<td align="center"><code>&lt;~</code></td>
<td align="center">wird konstruiert durch</td>
</tr>
<tr class="even">
<td align="center">Schwellenparameter</td>
<td align="center"><code>|t...</code></td>
<td align="center">Schwelle Nummer …</td>
</tr>
</tbody>
</table>
<p><a href="/post/lavaan-intro">In der ersten Sitzung</a> hatten wir nur mit <code>~</code>, <code>~1</code> und <code>~~</code> für Regressionen, Intercepts und Residualvarianzen gearbeitet. Heute kommen Faktorladungen dazu.</p>
<p>Wie schon für die letzten beiden Sitzungen, können Sie das komplette R-Skript <a href="/post/FEII_cfa.R"><svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M216 0h80c13.3 0 24 10.7 24 24v168h87.7c17.8 0 26.7 21.5 14.1 34.1L269.7 378.3c-7.5 7.5-19.8 7.5-27.3 0L90.1 226.1c-12.6-12.6-3.7-34.1 14.1-34.1H192V24c0-13.3 10.7-24 24-24zm296 376v112c0 13.3-10.7 24-24 24H24c-13.3 0-24-10.7-24-24V376c0-13.3 10.7-24 24-24h146.7l49 49c20.1 20.1 52.5 20.1 72.6 0l49-49H488c13.3 0 24 10.7 24 24zm-124 88c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm64 0c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20z"/></svg> hier herunterladen</a>.</p>
<p>Diese Sitzung schließt mit einem <a href="#AppendixA">Appendix</a> zur Hierarchie der Messmodelle ab. Wenn Sie ihre inhaltlichen Kenntnisse vertiefen wollen, oder durch ein bisschen zusätzliche Übung Ihre <code>lavaan</code>-Fähigkeiten verbessern möchten, empfehlen wir Ihnen, sich diesen Abschnitt anzugucken!</p>
</div>
<div id="datensatz" class="section level2">
<h2>Datensatz</h2>
<p>Konkret wird es in dieser Sitzung um die Faktorstruktur verschwörungstheoretischer Überzeugungen gehen. Dafür nutzen wir Daten aus der Erhebung zur Validierung der <em>Generic Conspiracist Beliefs Scale</em> (GCBS; Brotherton, French, &amp; Pickering, 2013). Die Daten finden Sie öffentlich zugänglich auf der <a href="http://openpsychometrics.org/_rawdata/GCBS.zip">Open Psychometrics Website</a>. Natürlich können Sie dort den <a href="https://openpsychometrics.org/tests/GCBS/">Fragebogen auch selbst ausfüllen</a>, wenn Sie möchten. Der Fragebogen besteht aus insgesamt 15 Aussagen, die die Probanden jeweils von 1 (“definitely not true”) bis 5 (“definitely true”) hinsichtlich ihres Wahrheitsgehalts einschätzen sollen.</p>
<table>
<colgroup>
<col width="10%" />
<col width="10%" />
<col width="78%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Nr.</th>
<th>Facette</th>
<th>Itemformulierung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td>GM</td>
<td>The government is involved in the murder of innocent citizens and/or well-known public figures, and keeps this a secret</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td>GC</td>
<td>The power held by heads of state is second to that of small unknown groups who really control world politics</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td>EC</td>
<td>Secret organizations communicate with extraterrestrials, but keep this fact from the public</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td>PW</td>
<td>The spread of certain viruses and/or diseases is the result of the deliberate, concealed efforts of some organization</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td>CI</td>
<td>Groups of scientists manipulate, fabricate, or suppress evidence in order to deceive the public</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td>GM</td>
<td>The government permits or perpetrates acts of terrorism on its own soil, disguising its involvement</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td>GC</td>
<td>A small, secret group of people is responsible for making all major world decisions, such as going to war</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td>EC</td>
<td>Evidence of alien contact is being concealed from the public</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td>PW</td>
<td>Technology with mind-control capacities is used on people without their knowledge</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td>CI</td>
<td>New and advanced technology which would harm current industry is being suppressed</td>
</tr>
<tr class="odd">
<td align="center">11</td>
<td>GM</td>
<td>The government uses people as patsies to hide its involvement in criminal activity</td>
</tr>
<tr class="even">
<td align="center">12</td>
<td>GC</td>
<td>Certain significant events have been the result of the activity of a small group who secretly manipulate world events</td>
</tr>
<tr class="odd">
<td align="center">13</td>
<td>EC</td>
<td>Some UFO sightings and rumors are planned or staged in order to distract the public from real alien contact</td>
</tr>
<tr class="even">
<td align="center">14</td>
<td>PW</td>
<td>Experiments involving new drugs or technologies are routinely carried out on the public without their knowledge or consent</td>
</tr>
<tr class="odd">
<td align="center">15</td>
<td>CI</td>
<td>A lot of important information is deliberately concealed from the public out of self-interest</td>
</tr>
</tbody>
</table>
<p>Die 15 Aussagen können auf theoretischer Grundlage fünf verschiedenen Facetten zugeordnet werden, die in der Tabelle mit ihren jeweiligen Abkürzungen eingetragen sind:</p>
<ul>
<li>GM: Government malfeasance</li>
<li>GC: Malevolent global conspiracies</li>
<li>EC: Extraterrestrial cover-up</li>
<li>PW: Personal well-being</li>
<li>CI: Control of information</li>
</ul>
<p>In dieser Sitzung werden wir untersuchen, inwiefern diese theoretische Zuordnung einer empirischen Prüfung standhält.</p>
<p>Zunächst können wir den Datensatz laden und ein bisschen genauer betrachten. Wie schon für die letzten beiden Sitzungen, haben wir den Datensatz bereits im <code>.rda</code>-Format aufbereitet, sodass Sie Ihn direkt in R von dieser laden können:</p>
<pre class="r"><code>load(url(&#39;https://pandar.netlify.com/post/conspiracy_cfa.rda&#39;))</code></pre>
<p>Alternativ können Sie den Datensatz natürlich auch für den lokalen Gebrauch <a href="/post/conspiracy_cfa.rda"><svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M216 0h80c13.3 0 24 10.7 24 24v168h87.7c17.8 0 26.7 21.5 14.1 34.1L269.7 378.3c-7.5 7.5-19.8 7.5-27.3 0L90.1 226.1c-12.6-12.6-3.7-34.1 14.1-34.1H192V24c0-13.3 10.7-24 24-24zm296 376v112c0 13.3-10.7 24-24 24H24c-13.3 0-24-10.7-24-24V376c0-13.3 10.7-24 24-24h146.7l49 49c20.1 20.1 52.5 20.1 72.6 0l49-49H488c13.3 0 24 10.7 24 24zm-124 88c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm64 0c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20z"/></svg> hier herunterladen</a>.</p>
<p>Der Datensatz ist etwas groß, um ihn sich direkt in der Ausgaben anzugucken. Deswegen hier ein kurzer Überblick über seine grundlegenden Eigenschaften:</p>
<pre class="r"><code># Anzahl der Personen
nrow(conspiracy)</code></pre>
<pre><code>## [1] 2495</code></pre>
<pre class="r"><code># Anzahl der Variablen
ncol(conspiracy)</code></pre>
<pre><code>## [1] 19</code></pre>
<pre class="r"><code># Struktur des Datensatzes
str(conspiracy)</code></pre>
<pre><code>## &#39;data.frame&#39;:    2495 obs. of  19 variables:
##  $ Q1    : int  5 5 2 5 5 1 4 5 1 1 ...
##  $ Q2    : int  5 5 4 4 4 1 3 4 1 2 ...
##  $ Q3    : int  3 5 1 1 1 1 3 3 1 1 ...
##  $ Q4    : int  5 5 2 2 4 1 3 3 1 1 ...
##  $ Q5    : int  5 5 2 4 4 1 4 4 1 1 ...
##  $ Q6    : int  5 3 2 5 5 1 3 5 1 5 ...
##  $ Q7    : int  5 5 4 4 4 1 3 5 1 1 ...
##  $ Q8    : int  3 5 2 1 3 1 4 5 1 1 ...
##  $ Q9    : int  4 1 2 4 1 1 2 5 1 1 ...
##  $ Q10   : int  5 4 4 5 5 1 3 5 1 4 ...
##  $ Q11   : int  5 4 2 5 5 1 3 5 1 1 ...
##  $ Q12   : int  5 5 4 5 5 1 2 5 1 1 ...
##  $ Q13   : int  3 4 NA 1 3 1 2 3 1 1 ...
##  $ Q14   : int  5 4 2 4 5 1 3 4 1 1 ...
##  $ Q15   : int  5 5 4 5 5 1 4 5 1 5 ...
##  $ edu   : Factor w/ 3 levels &quot;not highschool&quot;,..: 3 2 3 3 1 3 1 1 2 3 ...
##  $ urban : Factor w/ 3 levels &quot;rural&quot;,&quot;suburban&quot;,..: NA 2 2 1 2 1 2 1 3 3 ...
##  $ gender: Factor w/ 3 levels &quot;male&quot;,&quot;female&quot;,..: NA 2 2 1 2 1 2 1 3 3 ...
##  $ age   : int  28 14 26 25 37 34 17 23 17 28 ...</code></pre>
<p>Neben den bereitsch beschriebenen 15 Items enthält der Datensatz noch Informationen zum Bildungsniveau (<code>edu</code>), Art des Wohnortes (<code>urban</code>), Geschlecht (<code>gender</code>) und Alter (<code>age</code>) der Befragten. Diese Variablen sind in dieser Sitzung aber zunächst irrelevant.</p>
</div>
<div id="Einfaktor" class="section level2">
<h2>Einfaktorielles Modell</h2>
<p>In der Konzeption der verschwörungstheoretischen Überzeugungen nach Brotherton, French und Pickering (2013) wird behauptet, dass die Items 2, 7 und 12 ein gemeinsames Konstrukt - nämlich “Malevolent global conspiracies” - erheben. Hier noch einmal die genaue Formulierung der drei Aussagen:</p>
<table>
<colgroup>
<col width="12%" />
<col width="88%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Nr.</th>
<th>Itemformulierung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">2</td>
<td>The power held by heads of state is second to that of small unknown groups who really control world politics</td>
</tr>
<tr class="even">
<td align="center">7</td>
<td>A small, secret group of people is responsible for making all major world decisions, such as going to war</td>
</tr>
<tr class="odd">
<td align="center">12</td>
<td>Certain significant events have been the result of the activity of a small group who secretly manipulate world events</td>
</tr>
</tbody>
</table>
<p>Es wird also behauptet, dass es eine grundlegende Eigenschaft von Personen gibt, die das Ausmaß bestimmt, in dem Personen diese Aussagen als wahr einschätzen. Mithilfe der CFA können wir versuchen, diese Behauptung zu prüfen.</p>
<p>Als Pfadmodell dargestellt sieht das zunächst so aus:</p>
<p><img src="/post/cfa1.png" style="width:33.0%" />
Hier stellen wir das Modell zunächst ohne Gewichtungen dar - es werden lediglich die Beziehungen/Zusammensetzungen zwischen den Variablen verdeutlicht: die Messungen Q2, Q7 und Q12 setzen sich alle aus der zugrundeliegenden latenten Variable GC und dem itemspezifischen Messfehler zusammen.</p>
<div id="modellsyntax" class="section level3">
<h3>Modellsyntax</h3>
<p>Wie wir es in der ersten Sitzung für die Regression gesehen haben, können wir dieses Pfaddiagramm in <code>lavaan</code> Modellsyntax übersetzen. Zunächst haben wir eine latente Variable, die wir nach Belieben benennen können. Weil es sich anbietet, nennen wir sie <code>GC</code> für “global conspiracy”. Diese latente Variable wirkt sich auf drei manifesten Variablen aus. Bei diesen Variablen haben wir nicht die gleichen Freiheiten in der Benennung, weil es sich bei diesen um manifeste Variablen handelt, die im Datensatz bereits existieren. Daher müssen wir hier auch die Namen verwenden, die im Datensatz für die Variablen genutzt werden. Mit dem <code>=~</code> wird die Beziehung zwischen einer latenten Variable (links) und beliebig vielen manifesten Variablen (rechts) dargestellt. Diese Beziehung wird allgemein in Form von Faktorladungen quantifiziert. Mehrere manifeste Variablen, die der gleichen latenten Variable zugeordnet werden, können mit einem <code>+</code> verbunden werden. Für die Faktorstruktur sieht der Modellsyntax-Abschnitt also so aus:</p>
<pre class="r"><code>&#39;GC =~ Q2 + Q7 + Q12&#39;</code></pre>
<p>Wie schon in der Sitzung zur Regression müssen wir außerdem explizit Residualvarianzen anfordern, weil das Modell sonst behaupten würde, dass die latente Variable eine Varianzaufklärung von 100% an unseren manifesten Variablen leistet. Obwohl das zwar außerordentlich schön für die Entwickler des Fragebogens wäre, wenn es so wäre, ist beinahe jede manifeste Variable in der psychologischen Forschung mit einem gewissen Maß an Messfehler behaftet. Dieser wird in der CFA als Residualvarianz abgebildet. Daher erweitert sich unser Modell um die folgenden drei Zeilen:</p>
<pre class="r"><code>&#39;# Faktorladungen
GC =~ Q2 + Q7 + Q12

# Residualvarianzen
Q2 ~~ Q2
Q7 ~~ Q7
Q12 ~~ Q12&#39;</code></pre>
<p>Um das Modell ein wenig zu gliedern, haben wir mit dem <code>#</code> Kommentare in die Modellsyntax eingefügt, die die einzelnen Abschnitte voneinander abgrenzen. Auch dieses Modell ist noch nicht ganz vollständig. Weil die Varianz der latenten Variable <code>GC</code> nicht explizit angesprochen wird, wird - wie schon bei den Residuen - per Voreinstellung davon ausgegangen, dass diese Varianz 0 ist. Um Varianz auf der latenten Variable zuzulassen, müssen wir also auch diese explizit in das Modell aufnehmen:</p>
<pre class="r"><code>&#39;# Faktorladungen
GC =~ Q2 + Q7 + Q12

# Residualvarianzen
Q2 ~~ Q2
Q7 ~~ Q7
Q12 ~~ Q12

# Latente Varianz
GC ~~ GC&#39;</code></pre>
<p>Dieses Modell müssen wir erneut einem Objekt zuweisen, damit wir es gleich in der <code>lavaan</code>-Funktion ansprechen können. In einer glorreichen Demonstration meines Einfallsreichtums habe ich dieses Objekt <code>mod1</code> benannt - Modell 1.</p>
<pre class="r"><code>mod1 &lt;- &#39;# Faktorladungen
GC =~ Q2 + Q7 + Q12

# Residualvarianzen
Q2 ~~ Q2
Q7 ~~ Q7
Q12 ~~ Q12

# Latente Varianz
GC ~~ GC&#39;</code></pre>
</div>
<div id="modellschätzung-und--ergebnisse" class="section level3">
<h3>Modellschätzung und -ergebnisse</h3>
<p>Sobald wir das Modell erstellt haben, folgen alle weiteren Schritte dem gleichen Prinzip, das wir in der ersten Sitzung für Regressionen gesehen haben. Zunächst wenden wir das Modell mit dem <code>lavaan</code>-Befehl auf den Datensatz an. Dieser Datensatz muss dabei alle Variablen enthalten, die wir als manifeste Variablen in unserem Modell angesprochen haben.</p>
<pre class="r"><code>fit1 &lt;- lavaan(mod1, conspiracy)</code></pre>
<pre><code>## Warning in lav_model_vcov(lavmodel = lavmodel, lavsamplestats = lavsamplestats, : lavaan WARNING:
##     Could not compute standard errors! The information matrix could
##     not be inverted. This may be a symptom that the model is not
##     identified.</code></pre>
<p>Die entstehende Warnung stellt ein ernstzunehmendes Problem dar und wird Ihnen wahrscheinlich häufiger begegnen, wenn Sie Dinge mit <code>lavaan</code> ausprobieren. Die Warnung gibt Ihnen zunächst darüber Auskunft, wo das Problem aufgetreten ist - in diesem Fall in einer <code>lavaan</code>-internen Funktion namens <code>lav_model_vcov</code> - was aber nicht wirklich von Relevanz ist. Viel wichtiger sind die drei Informationen, die im Text der Warnmeldung enthalten sind:</p>
<ol style="list-style-type: decimal">
<li><code>Could not compute standard errors!</code> Es konnten keine Standardfehler bestimmt werden, was bedeutet, dass Sie keinerlei Inferenzstatistik betreiben können.</li>
<li><code>The information matrix could not be inverted.</code> Der technische Grund, aus dem keine Standardfehler bestimmt werden konnten.</li>
<li><code>This may be a symptom that the model is not identified.</code> Die wahrscheinliche Ursache, an der Sie ansetzen sollten, um dieses Problem zu beheben.</li>
</ol>
<p>Wir können uns die entstandenen Ergebnisse angucken, um herauszufinden, worin genau das Problem liegen könnte:</p>
<pre class="r"><code>summary(fit1)</code></pre>
<pre><code>## lavaan 0.6-10 ended normally after 17 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         7
##                                                       
##                                                   Used       Total
##   Number of observations                          2465        2495
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                    NA
##   Degrees of freedom                                -1
##   P-value (Unknown)                                 NA
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   GC =~                                               
##     Q2                1.116 NA                        
##     Q7                1.186 NA                        
##     Q12               1.256 NA                        
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Q2                0.752 NA                        
##    .Q7                0.636 NA                        
##    .Q12               0.416 NA                        
##     GC                1.157 NA</code></pre>
<p>Die folgende Zeile des Outputs zeigt uns, dass <code>lavaan</code> mit seiner Einschätzung vollkommen Recht hatte:</p>
<pre><code>## [...]
##    Degrees of freedom                                -1 
## [...]</code></pre>
<p>In diesem Fall sind die Freiheitsgrade negativ - das Modell ist also <em>global unteridentifiziert</em>. Bevor Sie jetzt direkt weiterlesen, um herauszufinden, wie man dieses Problem behebt, überlegen Sie kurz anhand Ihres Wissens aus dem Theorie-Teil, was genau das Problem sein könnte und wie Sie es beheben würden, wenn dieser Beitrag hier einfach vorbei wäre.</p>
</div>
<div id="Modellidentifikation" class="section level3">
<h3>Modellidentifikation</h3>
<p>Sie wissen inzwischen bestimmt, wo sich das Problem in diesem Fall verbirgt. Aber haben Sie trotzdem etwas Geduld - wir werden uns hier ein generelles Vorgehen in <code>lavaan</code> ansehen, mit dem man solche Probleme auch in komplizierteren Situationen lösen kann.</p>
<p>Zunächst wissen Sie aus der Theorie-Sitzung, dass die Anzahl bekannter Informationen sich einfach als <span class="math inline">\(s = \frac{p(p + 1)}{2}\)</span> berechnen lässt. Dabei ist <span class="math inline">\(s\)</span> die Anzahl bekannter Informationen (Anzahl der Varianzen und Kovarianzen der manifesten Variablen) und <span class="math inline">\(p\)</span> die Anzahl von manifesten Variablen im Modell. In unserem Fall also</p>
<pre class="r"><code>3 * (3 + 1) / 2</code></pre>
<pre><code>## [1] 6</code></pre>
<p>Wir können uns auch genau angucken, welche 6 Informationen wir haben, indem wir uns die Kovarianzmatrix aus unseren Daten (<em>sample statistics</em>) ansehen:</p>
<pre class="r"><code>inspect(fit1, &#39;sampstat&#39;)</code></pre>
<pre><code>## $cov
##     Q2    Q7    Q12  
## Q2  2.193            
## Q7  1.530 2.262      
## Q12 1.621 1.722 2.240</code></pre>
<p>Hier können wir einfach durchzählen:</p>
<pre><code>## $cov
##     Q2 Q7 Q12
## Q2  1        
## Q7  2  4     
## Q12 3  5  6</code></pre>
<p>Die zu schätzenden Parameter (<span class="math inline">\(t\)</span>) können wir im Pfaddiagramm abzählen:</p>
<p><img src="/post/cfa2.png" style="width:33.0%" /></p>
<p>Wenn wir uns nicht unnötig damit belasten möchten die Parameter selbst zu zählen, können wir die Anzahl natürlich auch einfach von <code>lavaan</code> bekommen:</p>
<pre class="r"><code>inspect(fit1, &#39;npar&#39;)</code></pre>
<pre><code>## [1] 7</code></pre>
<p>Welche Parameter das genau sind, die hier geschätzt werden, können wir auch mit <code>inspect</code> erfahren:</p>
<pre class="r"><code>inspect(fit1, &#39;free&#39;)</code></pre>
<pre><code>## $lambda
##     GC
## Q2   1
## Q7   2
## Q12  3
## 
## $theta
##     Q2 Q7 Q12
## Q2  4        
## Q7  0  5     
## Q12 0  0  6  
## 
## $psi
##    GC
## GC 7</code></pre>
<p>Hier sehen wir, wie in <code>lavaan</code> die Modell-Matrizen dargestellt werden:</p>
<ul>
<li><code>$lambda</code>: die Matrix der Faktorladungen (<span class="math inline">\(\Lambda\)</span>)</li>
<li><code>$theta</code>: die Residualkovarianzmatrix (<span class="math inline">\(\Theta\)</span>)</li>
<li><code>$psi</code>: die latente Kovarianzmatrix (<span class="math inline">\(\Psi\)</span>)</li>
</ul>
<p>Die latente Kovarianzmatrix haben wir in der Theoriesitzung (aus einer anderen Tradition in der Literatur kommend) als <span class="math inline">\(\Phi\)</span> bezeichnet - beides sind aber unterschiedliche Bezeichnungen für die gleiche Matrix. Das Ergebnis von <code>inspect</code> ist hier eine Liste dieser drei Matrizen. Wenn wir diese Liste in einem Objekt ablegen, können wir die Matrizen mit dem <code>$</code> auch einzeln inspizieren:</p>
<pre class="r"><code>free &lt;- inspect(fit1, &#39;free&#39;)
free$theta</code></pre>
<pre><code>##     Q2 Q7 Q12
## Q2  4        
## Q7  0  5     
## Q12 0  0  6</code></pre>
<p>In <code>theta</code> ist z.B. die Residualvarianz von Q7 der insgesamt 5. Parameter des Modells.</p>
<p>Im Theorie-Abschnitt haben Sie gehört, dass in Modellen mit latenten Variablen immer entweder eine Faktorladung oder die latente Varianz fixiert werden muss, um der latenten Variable eine Skala zu geben. Entweder wird eine Faktorladung auf 1 gesetzt, um so die Skala der manifesten Variable auf die latente Variable anzuwenden, oder die latente Varianz wird auf 1 fixiert, um die latente Variable in <span class="math inline">\(z\)</span>-Werten interpretierbar zu machen. In der EFA ist diese zweite Variante extrem verbreitet. In der CFA wird Ihnen die erste Variante häufiger begegnen.</p>
<p>Um die erste Faktorladung auf 1 zu fixieren, können wir das <code>lavaan</code>-Modell wie folgt ergänzen:</p>
<pre class="r"><code>mod1 &lt;- &#39;# Faktorladungen
GC =~ 1*Q2 + Q7 + Q12

# Residualvarianzen
Q2 ~~ Q2
Q7 ~~ Q7
Q12 ~~ Q12

# Latente Varianz
GC ~~ GC&#39;</code></pre>
<p>Mit <code>1*</code> legen wir den konkreten Wert der Faktorladung fest. Analog hierzu könnten wir mit <code>2*</code> diese Ladung auf den Wert 2 fixieren. Das gleiche Prinzip gilt in <code>lavaan</code> für alle Modellparameter, z.B. auch für die Varianz der latenten Variable. Wenn wir diese, statt des Wertes der ersten Faktorladung, festlegen, erhalten wir die zweite Möglichkeit, der latente Variable eine Skala zu geben:</p>
<pre class="r"><code>mod1b &lt;- &#39;# Faktorladungen
GC =~ Q2 + Q7 + Q12

# Residualvarianzen
Q2 ~~ Q2
Q7 ~~ Q7
Q12 ~~ Q12

# Latente Varianz
GC ~~ 1*GC&#39;</code></pre>
<p>Auch hier ist die Festlegung auf <code>1</code> üblich, weil diese Zahl viele folgenden Berechnungen dramatisch vereinfacht. Von der puren Anwendung in <code>lavaan</code> her können Sie aber jede beliebige Zahl vor das <code>*</code> schreiben.</p>
</div>
<div id="ErgebnisseZwei" class="section level3">
<h3>Modellschätzung und -ergebnisse - Zweiter Versuch</h3>
<p>Das Modell mit der eingeführten Restriktion, dass die 1. Faktorladung auf 1 fixiert ist (<span class="math inline">\(\lambda_{2} = 1\)</span>), sollte nun nur noch 6 zu schätzende Parameter enthalten. Demzufolge müsste die Warnmeldung, die beim letzten Versuch entstanden ist, verschwinden:</p>
<pre class="r"><code>fit1 &lt;- lavaan(mod1, conspiracy)</code></pre>
<p>So weit, so gut. Wenn wir uns wieder angucken, welche Parameter geschätzt werden mussten, sehen wir,</p>
<pre class="r"><code>inspect(fit1, &#39;free&#39;)</code></pre>
<pre><code>## $lambda
##     GC
## Q2   0
## Q7   1
## Q12  2
## 
## $theta
##     Q2 Q7 Q12
## Q2  3        
## Q7  0  4     
## Q12 0  0  5  
## 
## $psi
##    GC
## GC 6</code></pre>
<p>dass in <code>$lambda</code> nur noch die Ladungen von Q7 und Q12 geschätzt werden müssen. Die Ladung von Q2 ist kein Paramater des Modells mehr, weil wir diese ja auf einen Wert festgelegt haben.</p>
<p>Jetzt können wir uns noch einmal die Ergebnisse angucken:</p>
<pre class="r"><code>summary(fit1)</code></pre>
<pre><code>## lavaan 0.6-10 ended normally after 19 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         6
##                                                       
##                                                   Used       Total
##   Number of observations                          2465        2495
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   GC =~                                               
##     Q2                1.000                           
##     Q7                1.062    0.023   46.881    0.000
##     Q12               1.126    0.023   48.602    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Q2                0.752    0.028   26.494    0.000
##    .Q7                0.636    0.028   22.913    0.000
##    .Q12               0.416    0.026   15.743    0.000
##     GC                1.440    0.062   23.401    0.000</code></pre>
<p>Wir sehen, dass wir jetzt für alle Parameter Standardfehler erhalten und</p>
<pre><code>## [...]
##    Degrees of freedom                                 0 
## [...]</code></pre>
<p>das Modell jetzt 0 Freiheitsgrade hat. Es handelt sich also um ein <em>gerade identifiziertes</em> oder auch <em>saturiertes</em> Modell. Modelle mit <span class="math inline">\(df = 0\)</span> enthalten keine prüfbare Vereinfachung der empirischen Datenlage. Die einzelnen Parameter sind lediglich Umformulierungen von Informationen, die wir schon in den empirischen Daten vorliegen haben. Bei <a href="https://ubffm.hds.hebis.de/Record/HEB366849158">Eid, Gollwitzer &amp; Schmitt (2017)</a> finden Sie auf S. 866 - 867 eine detaillierte Darstellung, wie Sie die Parameter dieses Modells auch händisch bestimmen können.</p>
<p>Welche inhaltlichen Aussagen erlaubt uns diese Umformulierung jetzt? Gucken wir uns mal die Faktorladungen an:</p>
<pre><code>## [...]
##  Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   GC =~                                               
##     Q2                1.000                           
##     Q7                1.062    0.023   46.881    0.000
##     Q12               1.126    0.023   48.602    0.000 
## [...]</code></pre>
<p>In der Ergebnisaufbereitung von <code>lavaan</code> hat sich gegenüber dem Regressionsmodell aus Sitzung 1 wenig geändert. Die Spalten sind nach wie vor Name der Variable, geschätzter Parameter, Standardfehler, <span class="math inline">\(z\)</span>-Wert und <span class="math inline">\(p\)</span>-Wert. Die Faktorladungen sind durch Überschriften gegliedert. In unserem Fall gibt es nur eine latente Variable, weswegen es nur die Überschrift <code>GC =~</code> gibt. Alle darunter stehenden Ladungen beziehen sich also logischerweise auf Faktorladungen von manifesten Variable zu dieser latenten Variable. Für die Ladung der manifesten Variable Q2 sind die Spalten für den Standardfehler, <span class="math inline">\(z\)</span>-Wert und <span class="math inline">\(p\)</span>-Wert leer. Das liegt daran, dass wir diesen Parameter festlegen, es gibt bezüglich seiner Größe also keine Unsicherheit in der Schätzung (die im Standardfehler quantifiziert wird) und demzufolge auch keine Inferenz dazu, ob Sie bedeutsam von 0 verschieden ist. Sie ist per Definition von 0 verschieden, weil wir das - ohne empirische Unsicherheit - so festgelegt haben.</p>
<p>Was bedeuten diese Ladungen aber inhaltlich? Glücklicherweise hält auch für die CFA das beinahe allgemeingültige Mantra der sozialwissenschaftlichen Auswertungsverfahren: “es ist alles nur Regression”. Die Faktorladungen entsprechen hier also dem Regressionsgewicht der manifesten Variable, vorhergesagt durch die latente Variable. (Bitte beachten Sie die Richtung! Häufig wird diese Beziehung fälschlicherweise umgekehrt interpretiert - in der klassischen CFA ist aber die latente Variable die unabhängige Variable und die manifesten Variablen sind die abhängigen Variablen.) Ein Bild:</p>
<p><img src="/post/2021-04-15-cfa_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Die Ausprägung der manifesten Variable wird vorhergesagt durch die Ausprägung der latenten Variable - für <span class="math inline">\(GC = 2\)</span> sagen wir also <span class="math inline">\(Q2 = 2\)</span> vorher, weil die Faktorladung dieses Items auf 1 fixiert ist (<span class="math inline">\(\lambda_{2} = 1\)</span>). Für Q7 ist die Ladung allerdings <span class="math inline">\(\lambda_{7} = 1.062\)</span>, sodass die gelbe Regressionsgerade in der Abbildung ein bisschen steiler verläuft.</p>
<p>Das heißt, dass zwei Personen, die sich in der latenten Variable um eine Einheit unterscheiden, im <em>vorhergesagten</em> Ausmaß der Zustimmung zur Aussage “The power held by heads of state is second to that of small unknown groups who really control world politics” (Q2) ebenfalls um eine Einheit unterscheiden. Bezüglich der Aussage “A small, secret group of people is responsible for making all major world decisions, such as going to war” (Q7) unterscheiden sich die gleichen beiden Personen im vorhergesagten Wert aber um 1.062 Einheiten. Weil der Unterschied auf dem latenten Konstrukt GC sich also stärker in Q7 manifestiert als in Q2 (gleiche Unterschiede in GC führen zu stärkeren Unterschieden in Q7 als in Q2), spricht man davon, dass Q7 stärker auf der latenten Dimension <em>diskriminiert</em>. Daher wird die Faktorladung häufig als <em>Diskriminationsparameter</em> bezeichnet. Durch die Festlegung von <span class="math inline">\(\lambda_2 = 1\)</span> sind die “Einheiten”, von denen hier gesprochen wird, die Einheiten der Skala, die genutzt wurde, um Q2 zu erheben - in unserem Fall also eine 5-Punkt Likert-Skala.</p>
<p>Wie Sie in der Theorie-Sitzung gesehen haben, sind die einzelnen Messgleichungen:</p>
<p><span class="math display">\[
\begin{align}
  Q2 &amp;= \tau_2 + \lambda_2 \cdot GC + \delta_2 \\
  Q7 &amp;= \tau_7 + \lambda_7 \cdot GC + \delta_7 \\
  Q12 &amp;= \tau_{12} + \lambda_{12} \cdot GC + \delta_{12} \\
\end{align}
\]</span></p>
<p>Das sind letztlich also einfache lineare Gleichungen mit einer unabhängigen Variable - wie einfache Regressionen. Weil unsere Vorhersage aber mit Fehlern behaftet ist, ist jede manifeste Variable mit einem Residuum <span class="math inline">\(\delta\)</span> behaftet, deren Varianzen in der <code>lavaan</code>-Zusammenfassung so dargestellt werden:</p>
<pre><code>## [...]
##  Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Q2                0.752    0.028   26.494    0.000
##    .Q7                0.636    0.028   22.913    0.000
##    .Q12               0.416    0.026   15.743    0.000
##     GC                1.440    0.062   23.401    0.000</code></pre>
<p>Wie schon <a href="/post/lavaan-intro">bei der Regression in Sitzung 1</a> wird mit dem <code>.</code> vor dem Variablennamen deutlich gemacht, dass diese Variable in irgendeiner Form im Modell eine abhängige Variable ist. Das heißt, dass es sich bei der berichteten Varianz um eine <em>Residualvarianz</em> handelt. Für <code>GC</code> ist das nicht der Fall, weil - wie gerade besprochen - die latente Variable in der CFA die unabhängige Variable ist.</p>
<p>Was bringt uns das Wissen um die latente Varianz und die Residualvarianzen inhaltlich? Ein Kernkonzept der klassischen Messtheorie (KTT; auch, <strong>k</strong>lassische <strong>T</strong>est<strong>t</strong>heorie) ist die <em>Reliabilität</em>, also das Ausmaß in dem unser Instrument wahre Unterschiede zwischen Personen misst. Für unser Modell lässt sie sich einfach ausdrücken, für Q7 z.B.:</p>
<p><span class="math display">\[\begin{align}
  Rel[Q7] &amp;= \frac{\lambda_7^2 \mathbb{V}ar[GC]}{\mathbb{V}ar[Q7]} \\
  &amp;= \frac{\lambda_7^2 \mathbb{V}ar[GC]}{\lambda_7^2 \mathbb{V}ar[GC] + \mathbb{V}ar[\delta_7]} \\
  &amp;= 1 - \frac{\mathbb{V}ar[\delta_7]}{\lambda_7^2 \mathbb{V}ar[GC] + \mathbb{V}ar[\delta_7]}
\end{align}\]</span></p>
<p>Besonders die erste Version der Reliabilitätsbestimmung sieht dem klassischen <span class="math inline">\(R^2\)</span> einer Regression sehr ähnlich - was daran liegt, dass es das Gleiche ist. Wenn wir also die Reliabilität einer unserer manifesten Variablen bestimmen wollen, können wir entweder händisch die Paramater verrechnen, oder uns das <span class="math inline">\(R^2\)</span> von <code>lavaan</code> ausgeben lassen, so wie wir es in der <a href="/post/cfa">1. Sitzung</a> für die Regression gemacht haben:</p>
<pre class="r"><code>inspect(fit1, &#39;rsquare&#39;)</code></pre>
<pre><code>##    Q2    Q7   Q12 
## 0.657 0.719 0.814</code></pre>
<p>Weil <span class="math inline">\(R^2\)</span> und Reliabilitäten in vielen Fällen von Interesse sind, können wir auch die Modellzusammenfassung um diesen Abschnitt erweitern, indem wir in der <code>summary</code>-Funktion das Zusatzargument <code>rsq</code> auf <code>TRUE</code> setzen. Dann erhalten wir am Ende der Modellzusammenfassung die <span class="math inline">\(R^2\)</span>-Schätzungen:</p>
<pre class="r"><code>summary(fit1, rsq = TRUE)</code></pre>
<pre><code>## [...]
##  R-Square:
##                    Estimate
##     Q2                0.657
##     Q7                0.719
##     Q12               0.814</code></pre>
<p>In diesem Fall ist die Reliabilität von Q7 also 0.719. Das heißt, dass ca. 72% der interindividuellen Unterschiede, die wir bezüglich der Zustimmung zur Aussage von Q7 beobachten können, auf wahre Unterschiede in der latenten Dimension <em>malevolent global conspiracies</em> attribuiert werden können. Die verbleibenden 28% gehen auf Messfehler zurück. Was uns die CFA hier über das Ausmaß der klassischen Reliabilitätsbestimmung, wie Sie sie wahrscheinlich im Bachelorstudium gelernt haben, hinaus ermöglicht, ist, dass wir die Reliabilität jedes einzelnen Items eines Fragebogens bestimmen können, also nicht nur die der gesamten Skala.</p>
</div>
<div id="Mittelwertsstruktur" class="section level3">
<h3>Mittelwertsstruktur</h3>
<p>Wie Ihnen vielleicht aufgefallen ist, war in unseren gesammelten Ergebnissen bisher nirgends die Rede von Intercepts oder Mittelwerten. Das liegt daran, dass wir auch diese explizit in die Modellsyntax aufnehmen müssten. Üblicherweise werden in der CFA die Intercepts aller manifesten Variablen als Parameter aufgenommen, der Mittelwert der latenten Variable aber auf 0 fixiert. Dadurch handelt es sich bei der latenten Variable in der CFA im Normalfall um eine <em>zentrierte Variable</em>.</p>
<p>Wie wir bei der Regression schon gesehen haben, können wir Intercepts und Mittelwerte dadurch anfordern, dass wir Variablen auf eine Konstante (idealerweise die 1) regressieren. Das bedeutet also, dass wir unser Modell um einen weiteren Abschnitt erweitern müssen:</p>
<pre class="r"><code>mod2 &lt;- &#39;
# Faktorladungen
GC =~ 1*Q2 + Q7 + Q12

# Residualvarianzen
Q2 ~~ Q2
Q7 ~~ Q7
Q12 ~~ Q12

# Latente Varianz
GC ~~ GC

# Intercepts
Q2 ~ 1
Q7 ~ 1
Q12 ~ 1&#39;</code></pre>
<p>Wie immer, müssen wir dieses Modell im 2. Schritt auf die Daten anwenden, bevor wir uns Ergebnisse ausgeben lassen können:</p>
<pre class="r"><code>fit2 &lt;- lavaan(mod2, conspiracy)</code></pre>
<p>Mit dem <code>summary</code> Befehl können wir uns wieder die Modellzusammenfassung ansehen. Im Vergleich zum bisherigen <code>fit1</code> kommt ein Abschnitt dazu:</p>
<pre class="r"><code>summary(fit2)</code></pre>
<pre><code>## [...]
##  Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Q2                2.979    0.030   99.880    0.000
##    .Q7                2.673    0.030   88.235    0.000
##    .Q12               2.656    0.030   88.102    0.000
##     GC                0.000                            
## [...]</code></pre>
<p>Wie bei der Regression und bei den Varianzen schon gesehen, markiert der <code>.</code> Variablen, die im Modell abhängige Variablen sind, sodass der dargestellte Wert als <em>Intercept</em> (sprich bedingter Mittelwert) und nicht als <em>Mittelwert</em> interpretiert werden sollte. Wie bei Intercepts in Regressionen auch, ist das hier dargestellte Intercept von Q7 der Wert, den wir erwarten, wenn eine Person auf dem Prädiktor (GC) den Wert 0 hat. Durch die Festlegung des Mittelwerts von GC auf 0 bedeutet das Intercept also, dass es der erwartete Wert einer durchschnittlichen Person ist. Genau genommen ist das dann in diesem Fall also lediglich eine sehr umständliche Variante, doch den Mittelwert von Q7 zu meinen. Wenn wir die Darstellung als Regression um diese Intercepts erweitern, ergibt sich folgendes Bild:</p>
<p><img src="/post/2021-04-15-cfa_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>Die gestrichelte Linie stellt den Mittelwert der latenten Variable dar. Der Punkt, an dem die jeweilige Regressionsgerade diese Linie schneidet, ist also das Intercept. Erneut ist eine berechtigte Frage: “Aber was soll mir das jetzt bringen?” Die Intercepts werden im Rahmen der klassischen Testtheorie als <em>Leichtigkeitsparameter</em> interpretiert. Der Aussage “The power held by heads of state is second to that of small unknown groups who really control world politics” (Q2) weist eine Person mit durchschnittlicher Ausprägung auf der Dimension <em>malevolent global conspiracies</em> einen Wahrheitsgehalt von 2.979 zu (auf einer Skala von 1 bis 5). Die gleiche, durchschnittliche Person schätzt den Wahrheitsgehalt der Aussage “A small, secret group of people is responsible for making all major world decisions, such as going to war” (Q7) auf einer Skala von 1 bis 5 mit 2.673 ein. Q2 wird also in größerem Ausmaß zugestimmt - die Aussage ist <em>leichter</em> zu bejahen, daher die Bezeichnung als <em>Leichtigkeitsparameter</em>. Manchmal wird dieser Parameter auch ins Verhältnis zur Range der Skala gesetzt (also zur Differenz zwischen Maximum und Minimum der Skala) und dann in <span class="math inline">\(\%\)</span> interpretiert. Vielleicht kennen Sie diesen Koeffizienten auch unter dem Namen <em>Itemschwierigkeit</em>. Da allerdings zumeist die Leichtigkeit quantifiziert wird, macht das die Sache kompliziert. Auch müssen wir hier kein Verhältnis zur Range der Skala verwenden, da alle Items auf der gleichen gemessen wurden und damit die Werte direkt vergleichbar sind.</p>
</div>
</div>
<div id="zweifaktorielles-modell" class="section level2">
<h2>Zweifaktorielles Modell</h2>
<p>Wie wir im letzten Abschnitt gesehen haben, hatte das Modell für die Facette <em>malevolent global conspiracies</em> 0 Freiheitsgrade und war deswegen lediglich eine Umformulierung der empirischen Datenlage. Um uns mit Modellen zu beschäftigen, die prüfbare Behauptungen darstellen, können wir zwei Wege beschreiten.</p>
<p>Wir können in das Modell Einschränkungen einführen, die die Beziehung zwischen den drei Items Q2, Q7 und Q12 und der latenten Variable GC präzisieren. Diese Messmodelle der Klassischen Testtheorie werden im <a href="#AppendixA">Appendix</a> besprochen. Wenn Sie Ihre Kenntnis über die CFA und ihre Umsetzung in <code>lavaan</code> also vertiefen wollen, finden Sie dort eine detaillierte Darstellung der hierarchischen Messmodelle und der Einführung von Paramatergleichsetzungen in <code>lavaan</code>.</p>
<p>Die zweite Möglichkeit, um die behauptete Messstruktur des Konstrukts in prüfbare Aussagen zu überführen, ist, dieses gegenüber anderen psychologischen Konstrukten und Aussagen explizit abzugrenzen. Wenn die drei Aussagen in Q2, Q7 und Q12 Manifestierungen der Facette <em>malevolent global conspiracies</em> darstellen, sollte sie in einer CFA z.B. von der Facette <em>control of information</em> (Q5, Q10, Q15) klar unterscheidbar sein. Wenn sie das nicht wären, müssten wir die theoretische Konzeption der verschwörungstheoretischen Überzeugungen als fünfdimensionales Konstrukt revidieren und z.B. mit einer EFA untersuchen, welche Dimensionen sich empirisch unterscheiden lassen. Wie Sie am Titel dieses Abschnitts erkennen konnten, befassen wir uns hier mit diesem Vorgehen.</p>
<div id="vereinfachte-modellsyntax" class="section level3">
<h3>Vereinfachte Modellsyntax</h3>
<p>Im letzten Abschnitt sind wir den beschwerlichen Weg gegangen, das Modell in seiner Gänze in der <code>lavaan</code>-Modellsyntax darzustellen. Wie erwähnt gibt es aber einige Dinge, die in der breiten Masse der CFA-Modelle in gleicher Weise gehandhabt werden: üblicherweise wird die Faktorladung der 1. manifesten Variable auf 1 fixiert. Für alle abhängigen Variablen werden meistens Residualvarianzen geschätzt. Wenn wir latente Variablen definieren, sollen diese auch Varianz haben. Dieses Verhalten kann in <code>lavaan</code> erzeugt werden, sodass wir uns sparen können, alle Elemente im Modell aufzulisten. Dafür können wir ein sparsames Modell definieren und an einen von drei Befehlen weitergeben:</p>
<ul>
<li><code>cfa</code>: enthält Voreinstellungen, die in der Anwendung von CFAs üblich sind</li>
<li><code>sem</code>: macht genau das Gleiche wie <code>cfa</code></li>
<li><code>growth</code>: enthält Voreinstellungen für Wachstumskurvenmodelle, eine spezielle Form der Modellierung von Längsschnittdaten.</li>
</ul>
<p>Warum gibt es <code>cfa</code> und <code>sem</code>? Offiziell sind beide implementiert, weil es in Zukunft passieren könnte, dass unterschiedliche Voreinstellungen für konfirmatorische Faktorenanalysen und Strukturgleichungsmodelle implementiert werden. Derzeit ist das nicht der Fall, sodass beide Funktionen austauschbar verwandt werden können. Ich nutze sie meistens an unterschiedlichen Stellen, um in meinen <code>lavaan</code>-Skripten schnell sehen zu können, was an welcher Stelle passiert.</p>
<p>In jedem Fall funktionieren <code>cfa</code>, <code>sem</code> und <code>growth</code> genauso wie der allgemeine <code>lavaan</code>-Befehl, mit dem wir bisher gearbeitet haben. Der Unterschied besteht lediglich darin, dass Voreinstellungen gesetzt werden, die den Prozess der Modellierung stark abkürzen. Mit der Hilfefunktion <code>?cfa</code> können Sie sich ansehen, welche Voreinstellungen vorgenommen werden. Da steht:</p>
<blockquote>
<p>The cfa function is a wrapper for the more general lavaan function, using the following default arguments: <code>int.ov.free = TRUE</code>, <code>int.lv.free = FALSE</code>, <code>auto.fix.first = TRUE</code> (unless <code>std.lv = TRUE)</code>, <code>auto.fix.single = TRUE</code>, <code>auto.var = TRUE</code>, <code>auto.cov.lv.x = TRUE</code>, <code>auto.efa = TRUE</code>, <code>auto.th = TRUE</code>, <code>auto.delta = TRUE</code>, and <code>auto.cov.y = TRUE</code>.</p>
</blockquote>
<p>Eine Übersicht über alle möglichen Einstellung in <code>lavaan</code> finden Sie mit <code>?lavOptions</code>. Für uns sind folgende Aussagen von zentraler Bedeutung:</p>
<ul>
<li><code>auto.fix.first = TRUE</code>: die erste Faktorladung jeder latenten Variable wird automatisch fixiert</li>
<li><code>auto.var = TRUE</code>: die Varianz latenter Variablen und Residualvarianzen manifester Variablen werden automatisch frei geschätzt</li>
<li><code>auto.cov.lv.x = TRUE</code>: Kovarianzen zwischen exogenen latenten Variablen werden automatisch frei geschätzt.</li>
</ul>
<p>Das heißt, dass dies Dinge sind, die wir in der Modellsyntax nicht mehr explizit ansprechen müssen. Die Syntax des <code>mod1</code> aus dem letzten Abschnitt verkürzt sich daher auf nur eine Zeile:</p>
<pre class="r"><code>mod1_simple &lt;- &#39;GC =~ Q2 + Q7 + Q12&#39;</code></pre>
<p>Wenn Sie dieses Modell an <code>cfa</code> weitergeben, entstehen genau die gleichen Ergebnisse, die wir im <a href="#ErgebnisseZwei">zweiten Anlauf erzeugt hatten</a>. Probieren Sie es gerne aus, um zu prüfen, ob Sie angeschwindelt wurden. Was hierbei erneut fehlt, ist die Mittelwertsstruktur, die nicht per Voreinstellung mit in das Modell aufgenommen wird. Diese können wir aber per Argument von <code>cfa</code> anfordern:</p>
<pre class="r"><code>fit2_simple &lt;- cfa(mod1_simple, conspiracy,
  meanstructure = TRUE)</code></pre>
<p>Dann erhalten wir erneut den zusätzlichen Abschnitt mit den Intercepts, den wir im <a href="#Mittelwertsstruktur">letzten Abschnitt per Hand erzeugt hatten</a>.</p>
</div>
<div id="TwoFactors" class="section level3">
<h3>Modellierung mit zwei latenten Variablen</h3>
<p>Diese neu gefundene Leichtigkeit der Modellierung können wir direkt nutzen, um ein zweifaktorielles Modell für die beiden Facetten <em>malevolent global conspiracies</em> und <em>control of information</em> aufzustellen. Zu unseren bisherigen drei Items (Q2, Q7 und Q12) kommen die folgenden drei dazu:</p>
<table>
<colgroup>
<col width="12%" />
<col width="88%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Nr.</th>
<th>Itemformulierung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">5</td>
<td>Groups of scientists manipulate, fabricate, or suppress evidence in order to deceive the public</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td>New and advanced technology which would harm current industry is being suppressed</td>
</tr>
<tr class="odd">
<td align="center">15</td>
<td>A lot of important information is deliberately concealed from the public out of self-interest</td>
</tr>
</tbody>
</table>
<p>Um die beiden Facetten voneinander abzugrenzen, stellen wir ein Modell mit zwei latenten Variablen auf, welches als Pfaddiagramm so aussieht:</p>
<p><img src="/post/cfa3.png" style="width:66.0%" /></p>
<p>Inhaltlich wird mit diesem Modell behauptet, dass die Zustimmung zu den sechs Aussagen sich auf zwei verschiedene Überzeugungen von Personen zurückführen lässt. Die Erste stellt die Überzeugung dar, dass es eine kleine, elitäre Gruppe von Personen gibt, die das Weltgeschehen im Geheimen steuert. Diese Überzeugung äußert sich in der Zustimmung zu den drei Aussagen in Q2, Q7 und Q12. Die zweite Überzeugung beinhaltet, dass technologischer und wissenschaftlicher Fortschritt absichtlich verschleiert wird, um die Interessen einiger weniger zu schützen. Diese Überzeugung äußert sich dann in der Zustimmung zu den Aussagen in Q5, Q10 und Q15. Zusätzlich behauptet dieses Modell aber auch, dass sich eine Überzeugung bezüglich <em>malevolent global conspiracies</em> <strong>nicht</strong> in der Zustimmung zu den Aussagen in Q5, Q10 oder Q15 wiederfinden lässt. Zusammenhänge der Zustimmung zu den Aussagen in Q12 (“Certain significant events have been the result of the activity of a small group who secretly manipulate world events”) und Q10 (“New and advanced technology which would harm current industry is being suppressed”) sollen nur dadurch entstehen, dass die beiden grundlegenden (latenten) Überzeugungen miteinander zusammenhängen können. Diese latente Korrelation wird im Pfadmodell durch den Doppelpfeil kenntlich gemacht.</p>
<p>Um dieses Modell in <code>lavaan</code> zu implementieren, brauchen wir nur die folgenden Zeilen:</p>
<pre class="r"><code>mod_two &lt;- &#39;
  GC =~ Q2 + Q7 + Q12
  CI =~ Q5 + Q10 + Q15&#39;</code></pre>
<p>Durch die oben besprochenen Voreinstellungen werden die restlichen Modellelemente ergänzt, wenn wir <code>cfa</code> oder <code>sem</code> nutzen, um das Modell zu schätzen.</p>
<pre class="r"><code>fit_two &lt;- cfa(mod_two, conspiracy,
  meanstructure = TRUE)</code></pre>
<p>Wir können auch hier wieder <code>summary</code> und <code>inspect</code> benutzen, um uns detaillierte Informationen über die Ergebnisse zu beschaffen.</p>
<pre class="r"><code># Allgemeiner Überblick
summary(fit_two)</code></pre>
<pre><code>## lavaan 0.6-10 ended normally after 32 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        19
##                                                       
##                                                   Used       Total
##   Number of observations                          2456        2495
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                33.243
##   Degrees of freedom                                 8
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   GC =~                                               
##     Q2                1.000                           
##     Q7                1.054    0.022   47.592    0.000
##     Q12               1.116    0.022   50.392    0.000
##   CI =~                                               
##     Q5                1.000                           
##     Q10               0.842    0.034   25.135    0.000
##     Q15               0.692    0.027   25.850    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   GC ~~                                               
##     CI                0.933    0.043   21.670    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Q2                2.978    0.030   99.764    0.000
##    .Q7                2.669    0.030   88.037    0.000
##    .Q12               2.653    0.030   87.826    0.000
##    .Q5                3.270    0.029  111.062    0.000
##    .Q10               3.504    0.028  125.013    0.000
##    .Q15               4.232    0.022  191.248    0.000
##     GC                0.000                           
##     CI                0.000                           
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Q2                0.733    0.027   26.921    0.000
##    .Q7                0.641    0.026   24.416    0.000
##    .Q12               0.429    0.024   17.965    0.000
##    .Q5                1.047    0.044   23.907    0.000
##    .Q10               1.162    0.041   28.032    0.000
##    .Q15               0.685    0.025   26.977    0.000
##     GC                1.456    0.061   23.721    0.000
##     CI                1.082    0.062   17.499    0.000</code></pre>
<pre class="r"><code># Reliabilität der sechs Aussagen
inspect(fit_two, &#39;rsquare&#39;)</code></pre>
<pre><code>##    Q2    Q7   Q12    Q5   Q10   Q15 
## 0.665 0.716 0.809 0.508 0.398 0.430</code></pre>
<p>Die <code>summary</code> enthält nun den neuen Abschnitt <code>Covariances</code>, der, wie Sie vermutlich erraten können, Kovarianzen zwischen den latenten Variablen enthält. <code>inspect</code> erlaubt uns eine extrem detaillierte Untersuchung unserer Ergebnisse. Ein Blick in die Hilfe mit <code>?inspect</code> verrät, dass wir uns aber auch z.B. mit <code>what = 'cor.lv'</code> die “<strong>cor</strong>relations of <strong>l</strong>atent <strong>v</strong>ariables” anzeigen lassen können:</p>
<pre class="r"><code>inspect(fit_two, &#39;cor.lv&#39;)</code></pre>
<pre><code>##    GC    CI   
## GC 1.000      
## CI 0.743 1.000</code></pre>
</div>
<div id="paramaterEstimates" class="section level3">
<h3>Parametertabelle &amp; erweiterte Zusammenfassung</h3>
<p>Bisher haben wir hauptsächlich mit <code>inspect</code> gearbeitet, um uns die Ergebnisse unserer Modelle detailliert anzugucken. In den allermeisten Fällen ist das auch der sinnvollste Ansatz. Trotzdem ist es immer gut, auch Alternativen zu kennen. Die erste sinnvolle alternative Darstellungsart von Ergebnissen ist die Parametertabelle, die wir in <code>lavaan</code> über <code>paramaterEstimates</code> anfordern können. Für das zweifaktorielle Modell sieht diese so aus:</p>
<pre class="r"><code>parameterEstimates(fit_two)</code></pre>
<pre><code>##    lhs op rhs   est    se       z pvalue ci.lower ci.upper
## 1   GC =~  Q2 1.000 0.000      NA     NA    1.000    1.000
## 2   GC =~  Q7 1.054 0.022  47.592      0    1.010    1.097
## 3   GC =~ Q12 1.116 0.022  50.392      0    1.072    1.159
## 4   CI =~  Q5 1.000 0.000      NA     NA    1.000    1.000
## 5   CI =~ Q10 0.842 0.034  25.135      0    0.776    0.908
## 6   CI =~ Q15 0.692 0.027  25.850      0    0.639    0.744
## 7   Q2 ~~  Q2 0.733 0.027  26.921      0    0.679    0.786
## 8   Q7 ~~  Q7 0.641 0.026  24.416      0    0.590    0.693
## 9  Q12 ~~ Q12 0.429 0.024  17.965      0    0.382    0.476
## 10  Q5 ~~  Q5 1.047 0.044  23.907      0    0.961    1.132
## 11 Q10 ~~ Q10 1.162 0.041  28.032      0    1.081    1.243
## 12 Q15 ~~ Q15 0.685 0.025  26.977      0    0.635    0.735
## 13  GC ~~  GC 1.456 0.061  23.721      0    1.336    1.576
## 14  CI ~~  CI 1.082 0.062  17.499      0    0.961    1.203
## 15  GC ~~  CI 0.933 0.043  21.670      0    0.848    1.017
## 16  Q2 ~1     2.978 0.030  99.764      0    2.920    3.037
## 17  Q7 ~1     2.669 0.030  88.037      0    2.610    2.729
## 18 Q12 ~1     2.653 0.030  87.826      0    2.594    2.712
## 19  Q5 ~1     3.270 0.029 111.062      0    3.212    3.327
## 20 Q10 ~1     3.504 0.028 125.013      0    3.449    3.559
## 21 Q15 ~1     4.232 0.022 191.248      0    4.188    4.275
## 22  GC ~1     0.000 0.000      NA     NA    0.000    0.000
## 23  CI ~1     0.000 0.000      NA     NA    0.000    0.000</code></pre>
<p>Per Voreinstellung bekommen wir damit einen Datensatz, der 9 Spalten hat und aus so vielen Zeilen besteht, wie unser Modell Parameter hat (in diesem Fall 23). Die ersten drei Spalten (lhs, op, rhs) sind dazu da, den Parameter zu kennzeichnen, der in dieser Zeile dargestellt wird. Dafür gibt <code>op</code> den <em>operator</em> - also die Art des Parameters - an. In Zeile eins steht da ein <code>=~</code> also eine Faktorladung. <code>lhs</code> steht für <em>left hand side</em> und gibt an, welche Variable links des <em>operators</em> steht - <code>rhs</code> ist dann logischerweise die <em>right hand side</em>. Dadurch, dass hier in drei Spalten des Datensatzes zwischen den Parametern unterschieden wird, können wir sehr einfach und schnell die uns schon bekannten Verfahren nutzen, um die Parameter herauszufiltern, die uns interessieren. Z.B. können wir uns explizit nur die Intercepts und Mittelwerte aus der Parametertabelle ausgeben lassen. Dazu können wir die gesamte Tabelle in ein Objekt namens <code>para</code> ablegen und dann mit <code>subset</code> oder den eckigen Klammern (oder z.B. <code>filter</code>, falls Sie mit <code>dplyr</code> arbeiten) eine entsprechende Auswahl treffen. Intercepts und Mittelwerte sind z.B. dadurch gekennzeichnet, dass ihr <em>operator</em> <code>~1</code> ist:</p>
<pre class="r"><code># Parameter in Objekt ablegen
para &lt;- parameterEstimates(fit_two)

# Mittelwerte und Intercepts ausgeben
para[para$op == &#39;~1&#39;, ]</code></pre>
<pre><code>##    lhs op rhs   est    se       z pvalue ci.lower ci.upper
## 16  Q2 ~1     2.978 0.030  99.764      0    2.920    3.037
## 17  Q7 ~1     2.669 0.030  88.037      0    2.610    2.729
## 18 Q12 ~1     2.653 0.030  87.826      0    2.594    2.712
## 19  Q5 ~1     3.270 0.029 111.062      0    3.212    3.327
## 20 Q10 ~1     3.504 0.028 125.013      0    3.449    3.559
## 21 Q15 ~1     4.232 0.022 191.248      0    4.188    4.275
## 22  GC ~1     0.000 0.000      NA     NA    0.000    0.000
## 23  CI ~1     0.000 0.000      NA     NA    0.000    0.000</code></pre>
<p>Über die Hilfe zu <code>parameterEstimates</code> können wir wieder sehen, welche Argumente diese Funktion entgegennimmt. Ein hilfreiches Argument ist z.B. <code>standardized = TRUE</code>, mit dem wir <em>zusätzlich</em> zu den normalen Ergebnissen auch noch die standardisierten Modellergebnisse anfordern können.</p>
<p>Wenn Sie die Aufbereitung von <code>summary</code> eigentlich mögen, aber sich wünschen würden, dass es einfach ein paar zusätzliche Informationen gäbe, können Sie auch die <code>summary</code> um zusätzliche Argumente ergänzen. Wir hatten das <a href="#ErgebnisseZwei">vorhin schon für die Varianzaufklärung bzw. Reliabilität gemacht</a> - aber das Prinzip lässt sich auf viele Aspekte der Modellergebnisse erweitern. Im Folgenden ein paar interessante Argumente, um die wir die <code>summary</code> erweitern können:</p>
<ul>
<li><code>rsquare = TRUE</code>: Varianzaufklärung bzw. Reliabilität</li>
<li><code>standardized = TRUE</code>: Standardisierte Parameter</li>
<li><code>ci = TRUE</code>: Konfidenzintervalle um die Parameterschätzer</li>
<li><code>fit.measures = TRUE</code>: Kennwerte zur Modellpassung bzw. -güte.</li>
</ul>
<p>Wenn wir die Ergebniszusammenfassung z.B. um Konfidenzintervalle erweitern, sieht der Abschnitt der Faktorladungen so aus:</p>
<pre class="r"><code>summary(fit_two, ci = TRUE)</code></pre>
<pre><code>## [...]
##  Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##   GC =~                                                                 
##     Q2                1.000                               1.000    1.000
##     Q7                1.054    0.022   47.592    0.000    1.010    1.097
##     Q12               1.116    0.022   50.392    0.000    1.072    1.159
##   CI =~                                                                 
##     Q5                1.000                               1.000    1.000
##     Q10               0.842    0.034   25.135    0.000    0.776    0.908
##     Q15               0.692    0.027   25.850    0.000    0.639    0.744 
## [...]</code></pre>
<p>Was genau es mit den Fit-Statistiken auf sich hat, gucken wir uns im <a href="#ModelFit">nächsten Abschnitt</a> an.</p>
</div>
</div>
<div id="ModelFit" class="section level2">
<h2>Model Fit</h2>
<p>Im <a href="#TwoFactors">letzten Abschnitt hatten wir kurz die inhaltliche Modellimplikation besprochen</a> und dabei festgehalten, dass das Zweifaktorenmodell die Behauptung aufstellt, dass der Zustimmung zu den Aussagen in Q2, Q7 und Q12 eine gemeinsame latente Variable zugrunde liegt und die Zustimmung zu den Aussagen in Q5, Q10 und Q15 von einer anderen, unterscheidbaren latenten Variable abhängt. Wie haltbar ist diese Aussage? Nach klassischer Popper’scher Vorstellung müssen wir eine Theorie aufstellen (unser Modell), diese mit der Empirie abgleichen (unsere Daten) und dann entscheiden, ob unsere Theorie verworfen werden muss oder beibehalten werden kann. Bei konfirmatorischer Faktorenanalyse und Strukturgleichungsmodellierung wird diese Entscheidung anhand des <em>Model Fits</em> getroffen.</p>
<p>Wie Sie in der inhaltlichen Sitzung bereits erfahren haben, wird die Modellpassung über den Vergleich der modellimplizierten und der empirischen Kovarianzmatrix bestimmt. Wenn die empirische Kovarianzmatrix <span class="math inline">\(\mathbf{S}\)</span> zu stark von unserer Modellimplikation <span class="math inline">\(\mathbf{\Sigma(\widehat{\vartheta})}\)</span> abweicht, muss das Modell verworfen werden. Wie die beiden Matrizen aussehen, können wir natürlich über <code>inspect</code> erfahren:</p>
<pre class="r"><code># Empirische Matrix
inspect(fit_two, &#39;sampstat&#39;)$cov</code></pre>
<pre><code>##     Q2    Q7    Q12   Q5    Q10   Q15  
## Q2  2.188                              
## Q7  1.526 2.258                        
## Q12 1.619 1.720 2.241                  
## Q5  1.006 0.998 1.088 2.128            
## Q10 0.787 0.812 0.835 0.876 1.929      
## Q15 0.661 0.644 0.681 0.731 0.686 1.202</code></pre>
<pre class="r"><code># Modellimplizierte Matrix
inspect(fit_two, &#39;cov.ov&#39;)</code></pre>
<pre><code>##     Q2    Q7    Q12   Q5    Q10   Q15  
## Q2  2.188                              
## Q7  1.534 2.258                        
## Q12 1.624 1.712 2.241                  
## Q5  0.933 0.983 1.041 2.128            
## Q10 0.785 0.828 0.876 0.911 1.929      
## Q15 0.645 0.680 0.720 0.748 0.630 1.202</code></pre>
<div id="chisquare" class="section level3">
<h3><span class="math inline">\(\chi^2\)</span> Modeltest</h3>
<p>Den meisten Fit-Statistiken liegt die Fitfunktion <span class="math inline">\(F\)</span> zugrunde. Üblicherweise werden CFAs mit dem Maximum-Likelihood Verfahren geschätzt, sodass diese Fitfunktion als <span class="math inline">\(F_{ML}[\mathbf{\Sigma(\widehat{\vartheta})}, \mathbf{S}]\)</span> notiert wird. Wie Sie an der Notation sehen, gehen in diese Fitfunktion die beiden oben aufgeführten Matrizen ein. Wie im <a href="/post/efa">Beitrag zur EFA</a>, spezifischer im Abschnitt ML-EFA, besprochen, ist das Ziel der Schätzung im Groben, dass die Wahrscheinlichkeit der Daten, gegeben unser Modell, maximiert wird. Um die Multiplikation, die notwendig ist, um die Wahrscheinlichkeiten unabhängiger Zufallsereignisse zu bestimmen, zu umgehen, wird in der Statstik lieber mit Logarithmen gearbeitet. Diese kann man einfach addieren, sodass das Problem vereinfacht wird, ohne es wirklich zu ändern. Der Logarithmus der Likelihood wird dann einfach als LogLikelihood bezeichnet.</p>
<p>Um alle möglichen Fit-Statistiken für ein Modell zu bestimmen, können wir wieder mit <code>inspect</code> arbeiten. Weil hier ein ziemlicher Wust aus Zahlen entsteht, legen wir das Ergebnis erst einmal in einem Objekt ab:</p>
<pre class="r"><code>modelfit &lt;- inspect(fit_two, &#39;fit.measures&#39;)</code></pre>
<p>Um jetzt z.B. die LogLikelihood aus diesem Objekt zu ziehen, können wir diese über eckige Klammern auswählen. Dazu können wir erst einmal gucken, welche Werte in dem Objekt abgespeichert sind:</p>
<pre class="r"><code># Namen der Fitstatistiken
names(modelfit)</code></pre>
<pre><code>##  [1] &quot;npar&quot;                &quot;fmin&quot;                &quot;chisq&quot;              
##  [4] &quot;df&quot;                  &quot;pvalue&quot;              &quot;baseline.chisq&quot;     
##  [7] &quot;baseline.df&quot;         &quot;baseline.pvalue&quot;     &quot;cfi&quot;                
## [10] &quot;tli&quot;                 &quot;nnfi&quot;                &quot;rfi&quot;                
## [13] &quot;nfi&quot;                 &quot;pnfi&quot;                &quot;ifi&quot;                
## [16] &quot;rni&quot;                 &quot;logl&quot;                &quot;unrestricted.logl&quot;  
## [19] &quot;aic&quot;                 &quot;bic&quot;                 &quot;ntotal&quot;             
## [22] &quot;bic2&quot;                &quot;rmsea&quot;               &quot;rmsea.ci.lower&quot;     
## [25] &quot;rmsea.ci.upper&quot;      &quot;rmsea.pvalue&quot;        &quot;rmr&quot;                
## [28] &quot;rmr_nomean&quot;          &quot;srmr&quot;                &quot;srmr_bentler&quot;       
## [31] &quot;srmr_bentler_nomean&quot; &quot;crmr&quot;                &quot;crmr_nomean&quot;        
## [34] &quot;srmr_mplus&quot;          &quot;srmr_mplus_nomean&quot;   &quot;cn_05&quot;              
## [37] &quot;cn_01&quot;               &quot;gfi&quot;                 &quot;agfi&quot;               
## [40] &quot;pgfi&quot;                &quot;mfi&quot;                 &quot;ecvi&quot;</code></pre>
<pre class="r"><code># LogLikelihood
modelfit[&#39;logl&#39;]</code></pre>
<pre><code>##     logl 
## -22500.6</code></pre>
<p>Weil diese Zahl als solche relativ schlecht interpretierbar ist, wurden etliche Möglichkeiten entwickelt, um sie in Effektstärken oder in inferenzstatistische Prüfung der Modellpassung zu überführen. In fast allen dieser Maße wird dabei mit einem <em>unrestringierten</em> Referenzmodell verglichen. “Unrestringiert” heißt hier einfach, dass wir keine Einschränkungen in das Modell einführen - etwas, dass wir im <a href="#Modellidentifikation">Abschnitt zur Modellidentifikation</a> schon gesehen haben und als <em>saturiertes</em> oder <em>gerade identifiziertes</em> Modell bezeichnet hatten. Wie dort besprochen, sind solche Modell nicht prüfbar, weil sie nur eine Umformulierung der Daten darstellen. Wenn wir so etwas aber als Referenz nutzen, um unser Modell damit zu vergleichen, bekommen wir eine Vorstellung davon, wie gut unser Modell ist. Wenn Sie die Namen der Werte in <code>modelfit</code> durchgucken, sehen Sie, dass die LogLikelihood des unrestringierten Modells als <code>unrestricted.logl</code> bezeichnet wird:</p>
<pre class="r"><code># LogLikelihood unrestringiertes Modell
modelfit[&#39;unrestricted.logl&#39;]</code></pre>
<pre><code>## unrestricted.logl 
##         -22483.98</code></pre>
<p>Beinahe als sei es dafür gemacht, folgt die doppelte Differenz dieser beiden LogLikelihoods einer uns bekannten Verteilung (der <span class="math inline">\(\chi^2\)</span>-Verteilung), was uns erlaubt, Inferenzstatistik zu betreiben, weil wir bei bekannten Verteilungen Ablehnungsbereiche definieren können. Die Form der <span class="math inline">\(\chi^2\)</span>-Verteilung hängt, wie z.B. auch die klassische <span class="math inline">\(t\)</span>-Verteilung, von Freiheitsgraden ab. Die Freiheitsgrade, die bestimmen, mit welcher Form der <span class="math inline">\(\chi^2\)</span>-Verteilung wir die Differenz der LogLikelihoods prüfen können, entspricht - erneut beinahe auf magische Weise - genau der Differenz aus gegebenen Informationen und zu schätzenden Parametern des Modells. In <code>modelfit</code> sind diese Freiheitsgrade unter <code>df</code> (<em>degrees of freedom</em>) zu finden:</p>
<pre class="r"><code>modelfit[&#39;df&#39;]</code></pre>
<pre><code>## df 
##  8</code></pre>
<p>Die <span class="math inline">\(\chi^2\)</span>-Verteilung mit 8 Freiheitsgraden sieht so aus:</p>
<p><img src="/post/2021-04-15-cfa_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>Der blau eingefärbte Bereich ist der Ablehnungsbereich bei einem <span class="math inline">\(\alpha\)</span>-Fehlerniveau von 5%. Der kritische Wert liegt hier bei gerundet 15.51. Wenn die doppelte Differenz der LogLikelihoods des unrestringierten und unseres Modells diesen kritischen Wert überschreitet, muss also die Nullhypothese (unser Modell) verworfen werden:</p>
<pre class="r"><code># Empirische Prüfgröße
emp &lt;- 2 * (modelfit[&#39;unrestricted.logl&#39;] - modelfit[&#39;logl&#39;])
emp</code></pre>
<pre><code>## unrestricted.logl 
##          33.24343</code></pre>
<pre class="r"><code># p-Wert
pchisq(q = emp, df = 8, lower.tail = FALSE)</code></pre>
<pre><code>## unrestricted.logl 
##      5.566811e-05</code></pre>
<p>In diesem Fall wird unser Modell also verworfen. Wie Ihnen bestimmt bewusst ist, können wir uns den Prozess der händischen Bestimmung des <span class="math inline">\(p\)</span>-Wertes in <code>lavaan</code> auch sparen, weil der <span class="math inline">\(\chi^2\)</span>-Test sowohl in <code>modelfit</code>, als auch in der <code>summary</code> direkt mit ausgegeben wird:</p>
<pre class="r"><code># Aus inspect:
modelfit[c(&#39;chisq&#39;, &#39;df&#39;, &#39;pvalue&#39;)]</code></pre>
<pre><code>##        chisq           df       pvalue 
## 3.324343e+01 8.000000e+00 5.566811e-05</code></pre>
<pre class="r"><code># Aufruf des lavaan Objekts
fit_two</code></pre>
<pre><code>## lavaan 0.6-10 ended normally after 32 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        19
##                                                       
##                                                   Used       Total
##   Number of observations                          2456        2495
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                33.243
##   Degrees of freedom                                 8
##   P-value (Chi-square)                           0.000</code></pre>
<p>Wir haben uns also leider nicht verrechnet, dieses Modell wird verworfen.</p>
</div>
<div id="deskriptive-und-relative-gütekriterien" class="section level3">
<h3>Deskriptive und relative Gütekriterien</h3>
<p>Wie jeder inferenzstatistischer Test ist auch der <span class="math inline">\(\chi^2\)</span>-Modelltest von der Stichprobengröße abhängig. Komplexe Modelle, die an kleinen Stichproben geprüft werden, müssen nicht verworfen werden, einfache Modelle, die an riesigen Stichproben ausprobiert werden, werden auch bei sehr kleinen Diskrepanzen zwischen Annahme und Realität verworfen. Weil prinzipiell nicht belohnt werden soll, so wenige Informationen aus der Empirie heranzuziehen wie möglich (also eine möglichst kleine Stichprobe zu haben), gibt es diverse Gütekriterien, mit denen versucht wird, die Beurteilung eines Modells von der Größe der Stichprobe unabhängig zu machen.</p>
<p>Die bekanntesten deskriptiven Gütekriterien sind der RMSEA (root mean square error of approximation) und der SRMR (standardized root mean square residual). Der RMSEA ist eine Skalierung von <span class="math inline">\(F_{ML}\)</span> anhand der Stichprobengröße, welcher nur Werte von 0 oder größer annehmen kann. Der SRMR hingegen ist eine standardisierte Summe der Differenzen zwischen den beiden Matrizen <span class="math inline">\(\mathbf{S}\)</span> und <span class="math inline">\(\mathbf{\Sigma(\widehat{\vartheta})}\)</span>, hängt also nicht direkt von <span class="math inline">\(F_{ML}\)</span> ab. Das hat den Vorteil, dass der SRMR auch bei anderen Schätzverfahren zum Einsatz kommen kann und trotzdem über verschiedene Situationen hinweg vergleichbar bleibt. Allerdings haben Studien gezeigt, dass der RMSEA eine höhere Trennschärfe hat, um zwischen “guten” und “schlechten” Modellen zu unterscheiden. Für beide gilt: je höher der Werte, desto schlechter die Modellpassung. Auch diese beiden Kriterien sind in <code>modelfit</code> enthalten:</p>
<pre class="r"><code>modelfit[c(&#39;rmsea&#39;, &#39;srmr&#39;)]</code></pre>
<pre><code>##      rmsea       srmr 
## 0.03584388 0.01364878</code></pre>
<p>Für beide wird häufig das Kriterium von <span class="math inline">\(&lt; .05\)</span> als Daumenregel für gute Modellpassung angenommen. Deskriptiv scheint unser Modell anhand dieser Regeln also sehr gut zu sein.</p>
<p>Als relative Gütekriterien haben Sie in der Theoriesitzung GFI, TLI und CFI kennengelernt. Allen drei ist gemeinsam, dass sie als Vergleichsmodell nicht ein saturiertes bzw. unrestringiertes Modell nutzen, sondern das genaue Gegenteil: das Unabhängigkeitsmodell, in dem alle Korrelationen der beobachteten Variablen auf 0 gesetzt werden. Statt also unser postuliertes Modell mit optimaler Passung zu vergleichen und uns nur unsere Fehler vorzuhalten, betrachten diese Kriterien das schlecht möglichst Modell und geben eine Aussage darüber, wie viel besser unser Modell ist. Auch diese drei Fitkriterien können wir uns natürlich von <code>lavaan</code> ausgeben lassen:</p>
<pre class="r"><code>modelfit[c(&#39;cfi&#39;, &#39;tli&#39;, &#39;gfi&#39;)]</code></pre>
<pre><code>##       cfi       tli       gfi 
## 0.9962118 0.9928971 0.9992813</code></pre>
<p>Nehmen Sie sich einen Moment Zeit, um anhand der gesammelten Informationen zu überlegen, ob Sie dieses Modell beibehalten würden oder nicht.</p>
</div>
<div id="individuelle-modellbeurteilung" class="section level3">
<h3>Individuelle Modellbeurteilung</h3>
<p>Die oben genannten Fitkriterien werden häufig anhand von Daumenregeln beurteilt. Wie bei allen Daumenregeln gilt auch bei diesen, dass sie nicht uneingeschränkt auf alle Situationen anwendbar sind und es meistens zu genaueren Aussagen führt, sich eine spezifische Situation anzugucken. In anderen Worten: wie für die Effektstärkemaße wie Cohens <span class="math inline">\(d\)</span> und <span class="math inline">\(R^2\)</span> gilt auch beim Modelfit, dass Sie die Grenzen aus den Daumenregeln nur dann nutzen sollten, wenn Sie hinsichtlich Ihres Forschungsgegenstandes komplett ahnungslos sind.</p>
<p>Eine Möglichkeit ist es, für eine spezifische Situation einfach spezifische Cut-Off Werte für die Fitstatistiken zu generieren. Die gängigen Cut-Off Werte wurden in Simulationsstudien ermittelt, die bestimmte Konstellationen bezüglich Modelltypen und -komplexität sowie Stichprobengröße machen. Wenn wir genau so eine Simulationsstudie für unsere spezifische Situation durchführen, erhalten wir auch für unsere Situation angepasst Cut-Off Kriterien. Damit wir die Simulation nicht selbst schreiben müssen, können wir einfach die <code>ezCutoffs</code> Funktion aus dem gleichnamigen Paket nutzen:</p>
<pre class="r"><code>library(ezCutoffs)
cutoff &lt;- ezCutoffs(mod_two, conspiracy)</code></pre>
<pre><code>## Data Generation
## 
##   |==================================================| 100% elapsed = 13s  ~  0s
## 
## Model Fitting
## 
##   |==================================================| 100% elapsed = 15s  ~  0s</code></pre>
<p>Die Funktion nimmt ein paar Argumente entgegen:</p>
<ul>
<li><code>model</code>: das Modell, für das wir Cut-Offs generieren möchten</li>
<li><code>data</code>: Falls wir schon Daten haben, können wir sie hier angeben, um einen einfachen Vergleich zwischen empirischen Werten und Cut-Off in einer Tabelle zu haben</li>
<li><code>n_obs</code>: Falls wir noch keine Daten haben, können wir hier angeben, wie groß unsere Stichproben sein soll</li>
</ul>
<p>Das Durchführen dauert ein paar Sekunden, weil per Voreinstellung nun 1000 neue Datensätze erzeugt werden, auf die unser Modell dann auch 1000 mal angewandt werden muss. Darüber hinaus sei gesagt, dass, weil es sich hier um einen Zufallsprozess handelt, die Ergebnisse, die Sie erzeugen, wenn Sie die Analyse auf Ihrem Rechner durchführen, nicht 100%ig deckungsgleich mit denen sein werden, die sie hier sehen.</p>
<p>Um uns die neu entstandenen Cut-Off Werte anzusehen, können wir einfach das Objekt aufrufen:</p>
<pre class="r"><code>cutoff</code></pre>
<pre><code>##       Empirical fit Cutoff (alpha = 0.05)
## chisq   33.24343262          16.089762505
## cfi      0.99621179           0.998770472
## tli      0.99289710           0.997694635
## rmsea    0.03584388           0.020291241
## srmr     0.01547626           0.009364649</code></pre>
<p>Wir sehen hier, dass die Cut-Off Werte, die für unsere Situation erzeugt wurden (dargestellt in der <code>Cutoff (alpha = 0.05)</code> Spalte), sehr viel restriktiver sind als die generellen Leitlinien. Für den RMSEA ergibt sich ein Cut-Off von ca. 0.02, statt der üblichen 0.05, für den SRMR sogar 0.01. Anhand dieser spezifischen Cut-Off Werte muss unser Modell abgelehnt werden.</p>
</div>
<div id="Lokal" class="section level3">
<h3>Lokalisierung von Misfit</h3>
<p>Die letzten beiden Abschnitte haben uns nur gezeigt, <em>dass</em> unser Modell nicht passt, aber noch keine konkrete Aussage über das <em>Warum</em> zugelassen. Wenn wir ganz an den Anfang des Abschnitts zurück denken, dann hatten wir dort die beiden Kovarianzmatrizen gesehen, in denen sich die einzelnen Elemente mitunter ein wenig unterscheiden. <code>lavaan</code> kann uns die Differenz der beiden Matrizen natürlich auch direkt geben, indem wir die <code>residuals</code> der Kovarianzmatrix (<code>$cov</code>) inspizieren:</p>
<pre class="r"><code>inspect(fit_two, &#39;residuals&#39;)$cov</code></pre>
<pre><code>##     Q2     Q7     Q12    Q5     Q10    Q15   
## Q2   0.000                                   
## Q7  -0.008  0.000                            
## Q12 -0.005  0.008  0.000                     
## Q5   0.073  0.014  0.047  0.000              
## Q10  0.001 -0.016 -0.041 -0.035  0.000       
## Q15  0.016 -0.036 -0.038 -0.017  0.056  0.000</code></pre>
<p>Leider haben Varianzen und Kovarianzen die ungünstige Eigenschaft, dass Sie keine leicht interpretierbare Skala haben. Wie immer hilft dann die Standardisierung. Diese können wir mit dem <code>residuals</code>-Befehl anfordern:</p>
<pre class="r"><code>residuals(fit_two, &#39;standardized&#39;)$cov</code></pre>
<pre><code>##     Q2     Q7     Q12    Q5     Q10    Q15   
## Q2   0.000                                   
## Q7  -1.356  0.000                            
## Q12 -1.301  2.764  0.000                     
## Q5   3.629  0.790  3.148  0.000              
## Q10  0.058 -0.784 -2.426 -2.791  0.000       
## Q15  0.951 -2.373 -3.056 -1.898  4.393  0.000</code></pre>
<p>Die einzelnen Einträge können wir jetzt quasi als <span class="math inline">\(z\)</span>-Werte interpretieren: wenn ein Wert vom Betrag also größer als 1.96 ist, ist der Unterschied zwischen Modellimplikation und Empirie an dieser Stelle auf einem <span class="math inline">\(\alpha\)</span>-Fehlerniveau von 5% statistisch bedeutsam. Wir sehen z.B., dass in unserem Modell der Zusammenhang zwischen Q10 und Q15 sehr stark unterschätzt wird (das Residuum ist hier 4.39). Eine detaillierte Untersuchung des lokalen Misfits anhand der Residuen in der Kovarianzmatrix finden Sie im <a href="#Residuals">im Appendix</a>.</p>
<p>Die standardisierten Residuen der Kovarianzmatrizen erlauben uns, direkt und detailliert die Diskrepanz zwischen unserem Modell und den empirischen Daten zu beleuchten. Ein Problem besteht aber darin, dass wir uns dabei die rohe Information in der Kovarianzmatrix angucken, statt in der Sprache des Modells zu sehen, welche Parameter Probleme verursachen. Diesen Weg können wir gehen, wenn wir mit Modifikationsindizes arbeiten.</p>
<p>Um Modifikationsindizes in <code>lavaan</code> zu ermitteln, können wir mit <code>inspect(fit_two, 'modindices')</code> arbeiten. Wie schon bei den Residuen im letzten Abschnitt sind wir dabei aber in den Optionen etwas eingeschränkt, sodass es mehr Sinn macht, den eigens dafür geschaffenen <code>modindices</code>-Befehl zu nutzen. Dieser nimmt ein paar Argumente entgegen, die das Lesen der Ergebnisse erheblich vereinfachen können:</p>
<ul>
<li><code>object</code>: Das Ergebnisobjekt unserer <code>cfa</code></li>
<li><code>sort.</code>: Ob die Ergebnisse nach Größe des Modifikationsindex sortiert sein sollen</li>
<li><code>minimum.value</code>: Grenze die Modifikationsindizes überschreiten müssen, um angezeigt zu werden</li>
<li><code>filter</code>: Parameter, auf die der Output beschränkt werden soll (z.B. <code>'=~'</code> für Faktorladungen)</li>
</ul>
<p>Um ein bisschen besser zu verstehen, was diese Argumente bewirken, gucken wir uns am besten das Ergebnis mal an:</p>
<pre class="r"><code>modindices(fit_two, sort. = TRUE, minimum.value = 5)</code></pre>
<pre><code>##    lhs op rhs     mi    epc sepc.lv sepc.all sepc.nox
## 44 Q10 ~~ Q15 21.450  0.123   0.123    0.138    0.138
## 24  GC =~  Q5 21.450  0.281   0.339    0.232    0.232
## 27  CI =~  Q2  8.004  0.120   0.125    0.084    0.084
## 35  Q7 ~~ Q12  8.004  0.107   0.107    0.203    0.203
## 26  GC =~ Q15  7.315 -0.112  -0.135   -0.123   -0.123
## 42  Q5 ~~ Q10  7.315 -0.103  -0.103   -0.093   -0.093</code></pre>
<p>Die Ergebnistabelle beginnt wieder mit den gleichen drei Spalten, wie die <a href="#paramaterEstimates">Tabelle der Parameter, die wir uns mit <code>paramaterEstimates</code> haben ausgeben lassen</a>. Danach kommt mit <code>mi</code> die Spalte für die Modifikationsindizes. Dieser Index stellt eine Schätzung über die Veränderung des <span class="math inline">\(\chi^2\)</span>-Wertes des Modells dar, wenn wir die Restriktion dieser Zeile lockern würden. Zur Erinnerung: der <span class="math inline">\(\chi^2\)</span>-Wert des Modells ist 33.24. Diesen Wert könnten wir um 21.45 “Punkte” verringern, wenn wir unsere Annahmen über die Residualkovarianz zwischen Q10 und Q15 lockern würden. Im Modell wird die Annahme gemacht, dass die Q10 und Q15 deswegen korreliert sind, weil sie (zusammen mit Q5) <em>einen gemeinsamen</em> Faktor als Ursache haben. Die restliche Varianz in Q10 und Q15 wird als Messfehler definiert, welche im Verständnis der KTT per Definition unkorreliert sind. Der Modifikationsindex zeigt uns hier, dass die Annahme, dass es sich hier um unkorrelierte, pure Messfehler handelt, in der Empirie eventuell nicht haltbar ist.</p>
<p>Die folgenden Spalten beziehen sich allesamt auf den <em>expected parameter change</em> (EPC). Die erste Variante ist unstandardisiert (also in der ersten Zeile eine Kovarianz). Der <code>sepc.lv</code> ist der Wert, wenn wir statt der 1. Faktorladungen die latenten Varianzen auf 1 fixieren würden (das verändert für Residualvarianzen überhaupt nichts). Der <code>sepc.all</code> ist der Wert, wenn alle Variablen im Modell standardisiert sind und entspricht in diesem Fall der Korrelation. Zu guter Letzt ist der <code>sepc.nox</code> der Wert, wenn alle Variablen außer die exogenen manifesten Variablen standardisiert werden (in unserem Fall gibt es keine solche Variablen, also ist der Wert mit <code>sepc.all</code> identisch).</p>
<p>Zusammengefasst heißt das Ergebnis für die 1. Zeile also: wenn wir die Residualkovarianz zwischen Q10 und Q15 zulassen, erwarten wir eine Verbesserung des <span class="math inline">\(\chi^2\)</span>-Wertes um 21.45 Einheiten und die resultierende Residualkorrelation sollte einen Wert von 0.14 annehmen.</p>
<p>Alternativ zur Residualkorrelation zwischen Q10 und Q15 können wir auch die Querladung von Q5 zulassen. Beide Modifikationsindizes sind praktisch identisch. Das liegt daran, dass in beiden Fällen das Gleiche erreicht wird. Der Fehlpassung liegt das Problem zugrunde, dass Q10 und Q15 empirisch stärker korreliert sind, als das Modell zulässt, wie auch die 4.39 zeigt, die wir als standardisiertes Residuum dieser Kovarianz gesehen hatten. Wenn wir die Residualkovarianz zwischen Q10 und Q15 zulassen, wird diesem Punkt direkt Rechnung getragen. Wenn wir die Querladung zulassen, erfolgt das Gleiche indirekt: die Querladung bewirkt, dass der GC Faktor aus Q5 auspartialisiert und der Rest vom CI Faktor beeinflusst wird. Dieser Rest ist höher mit Q10 und Q15 korreliert, sodass deren Korrelation untereinander durch die unkorrlierten Anteile in Q5 nicht mehr nach unten gedrückt werden muss, um einen gemeinsamen Faktor zu erzeugen.</p>
</div>
<div id="modellvergleiche" class="section level3">
<h3>Modellvergleiche</h3>
<p>Wenn wir die Querladung im Modell zulassen, ergibt sich ein anderes Modell als das von uns ursprünglich Postulierte. In Form des Pfaddiagramms sieht das dann so aus:</p>
<p><img src="/post/cfa4.png" style="width:66.0%" /></p>
<p>Wir können dieses Modell wieder in zwei Zeilen definieren:</p>
<pre class="r"><code># Modell
mod_three &lt;- &#39;
GC =~ Q2 + Q7 + Q12 + Q5
CI =~ Q5 + Q10 + Q15&#39;

# Schätzung
fit_three &lt;- cfa(mod_three, conspiracy,
meanstructure = TRUE)</code></pre>
<p>Die Ergebnisse haben sich in einigen Punkten verändert:</p>
<pre class="r"><code>summary(fit_three)</code></pre>
<pre><code>## lavaan 0.6-10 ended normally after 35 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        20
##                                                       
##                                                   Used       Total
##   Number of observations                          2456        2495
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                12.435
##   Degrees of freedom                                 7
##   P-value (Chi-square)                           0.087
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   GC =~                                               
##     Q2                1.000                           
##     Q7                1.054    0.022   47.572    0.000
##     Q12               1.116    0.022   50.417    0.000
##     Q5                0.223    0.042    5.305    0.000
##   CI =~                                               
##     Q5                1.000                           
##     Q10               1.168    0.094   12.483    0.000
##     Q15               0.964    0.078   12.396    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   GC ~~                                               
##     CI                0.649    0.059   11.063    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Q2                2.978    0.030   99.764    0.000
##    .Q7                2.669    0.030   88.037    0.000
##    .Q12               2.653    0.030   87.826    0.000
##    .Q5                3.270    0.029  111.062    0.000
##    .Q10               3.504    0.028  125.013    0.000
##    .Q15               4.232    0.022  191.248    0.000
##     GC                0.000                           
##     CI                0.000                           
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Q2                0.733    0.027   26.942    0.000
##    .Q7                0.643    0.026   24.463    0.000
##    .Q12               0.427    0.024   17.925    0.000
##    .Q5                1.157    0.045   25.657    0.000
##    .Q10               1.097    0.044   25.020    0.000
##    .Q15               0.636    0.028   22.990    0.000
##     GC                1.455    0.061   23.717    0.000
##     CI                0.609    0.086    7.085    0.000</code></pre>
<p>Auffällig ist natürlich vor allem, dass die Faktorladungen sich verändert haben - besonders dass <code>Q5</code> jetzt auch auf den Faktor <code>GC</code> lädt.</p>
<p>Wenn wir uns mit <code>inspect(fit_three, 'fitmeasures')</code> oder <code>fitmeasures(fit_three)</code> die Fitstatistiken dieses Modells ausgeben lassen, erhalten wir im direkten Vergleich mit dem Modell ohne Querladung folgendes Bild:</p>
<table style="width:100%;">
<colgroup>
<col width="19%" />
<col width="18%" />
<col width="12%" />
<col width="7%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="center">LogLikelihood</th>
<th align="center"><span class="math inline">\(\chi^2\)</span></th>
<th align="center"><span class="math inline">\(df\)</span></th>
<th align="center"><span class="math inline">\(p\)</span></th>
<th align="center">RMSEA</th>
<th align="center">SRMR</th>
<th align="center">CFI</th>
<th align="center">TLI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Mit Querladung</td>
<td align="center">-22490.2</td>
<td align="center">12.435</td>
<td align="center">7</td>
<td align="center">0.087</td>
<td align="center">0.018</td>
<td align="center">0.007</td>
<td align="center">0.999</td>
<td align="center">0.998</td>
</tr>
<tr class="even">
<td align="left">Ohne Querladung</td>
<td align="center">-22500.6</td>
<td align="center">33.243</td>
<td align="center">8</td>
<td align="center">0.000</td>
<td align="center">0.036</td>
<td align="center">0.014</td>
<td align="center">0.996</td>
<td align="center">0.993</td>
</tr>
</tbody>
</table>
<p>Wie wir sehen, schneidet das Modell mit Querladung bei jeder Fitstatistik besser ab. Darüber hinaus muss das Modell auch anhand des <span class="math inline">\(\chi^2\)</span>-Tests nicht mehr verworfen werden. Aber ist dieser Unterschied im Vergleich zum Modell ohne Querladung statistisch bedeutsam? Oder statistisch korrekt formuliert: müssen wir die Annahme, dass die Querladung exakt 0 ist (es also keine Querladung gibt) verwerfen? Für den direkten Vergleich zweier geschachtelter Modelle haben Sie im Theorieabschnitt schon den <em>Likelihood-Ratio Test</em> kennengelernt.</p>
<p>Wie der Name verrät, werden bei diesem Test die Likelihoods der beiden Modelle verglichen. Genau genommen passiert bei diesem Test exakt das, was wir schon beim <a href="#chisquare">einfachen <span class="math inline">\(\chi^2\)</span>-Test gesehen haben</a>: ein Modell wird mit einem anderen, weniger restriktiven Modell verglichen, indem die Differenz der beiden LogLikelihoods bestimmt wird. Diese Differenz folgt auch hier der <span class="math inline">\(\chi^2\)</span>-Verteilung, jetzt allerdings mit der Differenz der Freiheitsgrade der beiden Modelle als <span class="math inline">\(df\)</span>.</p>
<p>In diesem Fall ist das Modell mit Querladung das weniger strenge oder <em>unrestringierte</em> Modell (<span class="math inline">\(M_U\)</span>). Das Modell ohne Querladung ist ein Sonderfall dieses Modells, weil es die Querladung auf den Wert 0 <em>restringiert</em> und wird daher als <span class="math inline">\(M_R\)</span> bezeichnet. Ob diese Restriktion beibehalten werden kann, können wir mit dem Likelihood-Ratio oder auch Modelldifferenztest prüfen. In <code>lavaan</code> brauchen wir dafür lediglich beide Ergebnisobjekte und den <code>lavTestLRT</code>-Befehl:</p>
<pre class="r"><code>lavTestLRT(fit_two, fit_three)</code></pre>
<pre><code>## Chi-Squared Difference Test
## 
##           Df   AIC   BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)    
## fit_three  7 45020 45137 12.435                                  
## fit_two    8 45039 45150 33.243     20.808       1  5.077e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Die Tabelle beginnt zunächst mit den Freiheitsgraden <code>df</code> der beiden Modelle. Darauf folgen zwei Informationskriterien, <em>Akaike’s Information Criterion</em> (<code>AIC</code>) und das <em>Bayesian Information Criterion</em> (<code>BIC</code>). Für beide ist zunächst folgende Daumenregel ausreichend: kleinere Werte sind bessere Werte. Dann kommt noch einmal der <span class="math inline">\(\chi^2\)</span>-Wert der einzelnen Modelle (<code>Chisq</code>). Die restlichen drei Spalten befassen sich direkt mit dem Ergebnis des Differenztests: <code>Chisq Diff</code> ist der Unterschied der <span class="math inline">\(\chi^2\)</span>-Werte (bzw. <span class="math inline">\(-2\)</span>-mal die Differenz der LogLikelihoods), <code>Df diff</code> ist der Unterschied der Freiheitsgrade und <code>Pr(&gt;Chisq)</code> ist der <span class="math inline">\(p\)</span>-Wert.</p>
<p>In diesem Fall hat der Modellvergleich einen Freiheitsgrad, weil <code>fit_two</code> genau <em>eine Restriktion</em> gegenüber <code>fit_three</code> vornimmt: die Querladung von Q5 wird auf 0 fixiert. Diese eine Restriktion macht <code>fit_two</code> um einen Freiheitsgrad sparsamer, weil es einen Parameter weniger gibt, der frei geschätzt werden muss.</p>
<p>Der letzten Spalte können wir entnehmen, dass der Modellvergleich signifikant ausfällt. Das bedeutet, dass die Restriktionen in <span class="math inline">\(M_R\)</span> verworfen werden müssen und wir stattdessen <span class="math inline">\(M_U\)</span> nutzen sollten. Wäre der Vergleich nicht bedeutsam ausgefallen, könnten wir - aufgrund des Sparsamkeitsprinzips - <span class="math inline">\(M_R\)</span> beibehalten.</p>
<p>Mit den Modellvergleichen können Sie nun neben dem direkten Test eines Modells, dass aus einer Theorie abgeleitet wird nun auch Modelle vergleichen, die aus konkurrierenden Theorien abgeleitet werden können. Dazu sei allerdings angemerkt, dass in einigen Publikationen der Likelihood-Ratio Test genutzt wird, um zu prüfen, ob z.B. ein Einfaktor-Modell oder ein Zwei-Faktormodell einen Satz von Items besser abbildet. Diese Modellvergleiche sind mit dem LRT als problematisch einzustufen, weil die Likelihood-Differenz bei Restriktionen an den Grenzen des zulässigen Parameterraums (Varianzen gleich 0 setzen, Korrelationen auf 1 setzen, usw.) nicht der postulierten <span class="math inline">\(\chi^2\)</span>-Verteilung folgt.</p>
<p>Außerdem müssen wir an dieser Stelle anmerken, dass wir unser Modell mit Hilfe der Modifikationsindizes datengetrieben verändert haben. Somit verliert diese Analyse an konfirmatorischen Charakter - wir sind hier explorativ vorgegangen. Um die Kreuzladung als mögliche Modellerweiterung zu untersuchen, müssten wir dies erneut an einem unabhängigen (z.B. neu erhobenen) Datensatz untersuchen. Dies wird auch Kreuzvalidierung genannt, da wir die neue Theorie an einem neuen Datensatz einer neuen Validierung unterziehen.</p>
<p>Wie schon für die letzten beiden Sitzungen, können Sie das komplette R-Skript <a href="/post/FEII_cfa.R"><svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M216 0h80c13.3 0 24 10.7 24 24v168h87.7c17.8 0 26.7 21.5 14.1 34.1L269.7 378.3c-7.5 7.5-19.8 7.5-27.3 0L90.1 226.1c-12.6-12.6-3.7-34.1 14.1-34.1H192V24c0-13.3 10.7-24 24-24zm296 376v112c0 13.3-10.7 24-24 24H24c-13.3 0-24-10.7-24-24V376c0-13.3 10.7-24 24-24h146.7l49 49c20.1 20.1 52.5 20.1 72.6 0l49-49H488c13.3 0 24 10.7 24 24zm-124 88c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm64 0c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20z"/></svg> hier herunterladen</a>.</p>
</div>
</div>
<div id="Residuals" class="section level2">
<h2>Appendix A</h2>
<details>
<summary>
Lokalisierung von Misfit in Kovarianzmatrizen
</summary>
<p>Im <a href="#Lokal">Abschnitt zur Lokalisierung von Misfit</a> haben wir die Residuen in Kovarianzmatrizen schon angeschnitten. Hier noch einmal die standardisierten Residuen:</p>
<pre class="r"><code>residuals(fit_two, &#39;standardized&#39;)$cov</code></pre>
<pre><code>##     Q2     Q7     Q12    Q5     Q10    Q15   
## Q2   0.000                                   
## Q7  -1.356  0.000                            
## Q12 -1.301  2.764  0.000                     
## Q5   3.629  0.790  3.148  0.000              
## Q10  0.058 -0.784 -2.426 -2.791  0.000       
## Q15  0.951 -2.373 -3.056 -1.898  4.393  0.000</code></pre>
<p>Um besser interpretieren zu können, was uns die Abweichungen sagen, hilft es, die Matrix in vier grobe Teile aufzuteilen:</p>
<ul>
<li>Die Varianzen der Items in der Diagonale</li>
<li>Die Kovarianzen zwischen den Items, die <em>malevolent global conspiracies</em> angehören</li>
<li>Die Kovarianzen zwischen den Items, die <em>control of information</em> angehören</li>
<li>Die Kovarianzen zwischen den Items, die unterscheidlichen Faktoren angehören</li>
</ul>
<p>Dazu legen wir die Matrix am besten in einem Objekt ab und gucken uns die Teile einzeln an:</p>
<pre class="r"><code># Als Objekt anlegen
resi &lt;- residuals(fit_two, &#39;standardized&#39;)$cov

# Varianzen in der Diagonale
diag(resi)</code></pre>
<pre><code>##            Q2            Q7           Q12            Q5           Q10 
##  2.523304e-08  4.260729e-08  4.338447e-08  8.158212e-10 -8.168390e-08 
##           Q15 
## -9.348543e-09</code></pre>
<p>Die Varianzen können durch das Modell also beinahe perfekt repliziert werden. Ein wenig anders sieht es z.B. bei den Kovarianzen zwischen den Items zu <em>malevolent global conspiracies</em> aus:</p>
<pre class="r"><code>resi[1:3, 1:3]</code></pre>
<pre><code>##                Q2            Q7           Q12
## Q2   2.523304e-08 -1.355963e+00 -1.300967e+00
## Q7  -1.355963e+00  4.260729e-08  2.763595e+00
## Q12 -1.300967e+00  2.763595e+00  4.338447e-08</code></pre>
<p>Hier ist die empirische Kovarianz deutlich größer als die modellimplizierte. Was bedeutet das? Unser Modell behauptet, dass die Kovarianz zwischen Q7 und Q12 einfach die durch die Faktorladungen gewichtete Varianz der latenten Variable ist: <span class="math inline">\(cov(Q7, Q12) = \lambda_7 \cdot \lambda_{12} \cdot var(GC)\)</span>. Das gilt für alle Kovarianzen zwischen den Items Q2, Q7 und Q12. Wenn diese Erwartung nicht der empirischen Beobachtung entspricht, lässt sich das in etwa so interpretieren, dass die Items Q7 und Q12 mehr untereinander gemeinsam haben, als sie mit dem Item Q2 gemeinsam haben. Wenn wir uns die <a href="#Einfaktor">Formulierungen der Aussagen</a> noch einmal vor Augen führen, können wir versuchen, einen inhaltlichen Grund für dieses Problem zu finden.</p>
<p>Auch für die Items der latenten Variable <em>control of information</em> können wir das Ganze genauer inspizieren:</p>
<pre class="r"><code>resi[4:6, 4:6]</code></pre>
<pre><code>##                Q5           Q10           Q15
## Q5   8.158212e-10 -2.791004e+00 -1.898102e+00
## Q10 -2.791004e+00 -8.168390e-08  4.392579e+00
## Q15 -1.898102e+00  4.392579e+00 -9.348543e-09</code></pre>
<p>An welchen Stellen springt Ihnen hier Misfit ins Auge? Wenn Sie die <a href="#TwoFactors">Itemformulierungen</a> betrachten - woran könnte das inhaltlich liegen?</p>
<p>Für ein zweifaktorielles Modell wahrscheinlich relevanter ist der letzte Teil: die Kovarianzen zwischen Items, die nicht zum gleichen Faktor gehören. In der CFA, wie wir sie hier aufgebaut haben, haben wir impliziert, dass Item Q2 und Item Q5 nur deswegen zusammenhängen, weil es einen Zusammenhang zwischen den grundlegenden Überzeugungen <em>malevolent global conspiracies</em> und <em>control of information</em> gibt. Item Q5 fällt allerdings direkt zwei mal negativ auf:</p>
<pre class="r"><code>resi[4:6, 1:3]</code></pre>
<pre><code>##             Q2         Q7       Q12
## Q5  3.62934589  0.7901981  3.147702
## Q10 0.05757449 -0.7841579 -2.426346
## Q15 0.95100604 -2.3732611 -3.055803</code></pre>
<p>Sowohl mit Q2 als auch mit Q12 scheint es höher zu korrelieren, als durch unser Modell abgebildet werden kann. Ein möglicher Grund könnte hier sein, dass Q5 in seiner Formulierung impliziert, dass die Täuschung im Auftrag der kleinen, geheimen Gruppen durchgeführt wird, welche der zentrale Bestandteil des Faktor <em>malevolent global conspiracies</em> sind. Q10 und Q15 hingegen verdeutlichen, dass solche Täuschung aus Selbstinteresse geschieht. Es könnte also sein, dass Q5 nicht eindeutig genug auf <em>control of information</em> zurückzuführen ist, sondern auch Elemente der <em>malevolent global conspiracies</em> enthält und eigentlich eine Querladung auf diesen Faktor zugelassen werden müsste.</p>
</details>
</div>
<div id="AppendixA" class="section level2">
<h2>Appendix B</h2>
<details>
<summary>
Hierarchie der Messmodelle
</summary>
<p>In vielen Bereichen der Psychologie ist es wichtig, nicht nur festzuhalten, dass mehrere beobachtbare Variablen ein gemeinsames latentes Konstrukt erheben, sondern auch sicherzustellen, dass sie dies in gleicher Weise tun. Nehmen wir an, sie kämen in die Situation, für einen, nicht näher benannten, Statistik-lastigen Kurs im Master der Psychologie drei parallele Formen einer Modulprüfung entwickeln zu müssen. In dem Fall würden Sie im Interesse der Kursteilnehmer und -teilnehmerinnen versuchen, sicherzustellen, dass die drei Formen die statistischen Kompetenzen (das latente Konstrukt) auch in gleicher Weise erheben und sich nicht z.B. in der mittleren Schwierigkeit unterscheiden.</p>
<p>Verschiedene Formen der “Gleichheit” dieser drei Messungen werden in der Hierarchie der Messmodelle festgehalten:</p>
<p><img src="/post/mess1.png" style="width:66.0%" /></p>
<p>In der Abbildung sind die fünf typischen Messmodelle der klassischen Testtheorie zu sehen. In der Bezeichnung bezieht sich der Buchstabe <span class="math inline">\(\tau\)</span> auf den zugrundeliegenden, wahren Wert einer manifesten Variable. Anders als die latenten Variablen, die wir bisher betrachtet haben, ist so ein <span class="math inline">\(\tau\)</span> für jede manifeste Variable einzeln definiert, kann aber ohne weitere Modellannahmen nicht empirisch geschätzt werden. Die Namen der Messmodelle beziehen sich darauf, wie die wahren Werte <span class="math inline">\(\tau\)</span> verschiedener manifester Variablen im Verhältnis zueinander stehen. <span class="math inline">\(\tau\)</span>-parallel heißt also z.B., dass die wahren Werte zweier Parallelformen der Statstikprüfung wirklich parallel sind - also in jedweder Hinsicht gleiche Eigenschaften haben. Der Weg, um von einem Messmodell zum nächsten zu kommen, ist stets an den Verbindungen dargestellt.</p>
<p><em>Im Folgenden arbeiten wir mit ein paar fiktiven Daten zu dieser imaginären Prüfung.</em></p>
<pre class="r"><code>load(url(&quot;https://pandar.netlify.app/post/stat_test.rda&quot;))</code></pre>
<p>Der Datensatz enthält lediglich drei Variablen:</p>
<pre class="r"><code>summary(stat_test)</code></pre>
<pre><code>##      test1             test2             test3        
##  Min.   :-1.1672   Min.   :-1.5487   Min.   :-1.2554  
##  1st Qu.: 0.3794   1st Qu.: 0.2927   1st Qu.: 0.3684  
##  Median : 0.8089   Median : 0.8373   Median : 0.9853  
##  Mean   : 0.7867   Mean   : 0.8193   Mean   : 0.9033  
##  3rd Qu.: 1.2571   3rd Qu.: 1.2846   3rd Qu.: 1.4364  
##  Max.   : 2.7485   Max.   : 2.6747   Max.   : 2.5199</code></pre>
<p>Die Werte stellen auf einer Skala von ca. -3 bis 3 die geschätzte Fähigkeit in drei verschiedenen Versionen des Tests dar.</p>
</details>
<details>
<summary>
<span class="math inline">\(\tau\)</span>-kongenerisches Modell
</summary>
<p>Das am weitesten verbreitete Messmodell in der Psychologie ist das <span class="math inline">\(\tau\)</span>-kongenerische Messmodell. Dieses haben wir z.B. auch in den anderen Abschnitten dieser Sitzung gesehen. Für unsere fiktive Statstikprüfung können wir es wie folgt anlegen:</p>
<pre class="r"><code># Modell
mod1 &lt;- &#39;stat =~ test1 + test2 + test3&#39;

# Schätzung
fit1 &lt;- cfa(mod1, stat_test,
  meanstructure = TRUE)</code></pre>
<p>Der Abschnitt zu den Parametern sieht in der Zusammenfassung dann so aus:</p>
<pre class="r"><code>summary(fit1)</code></pre>
<pre><code>## [...]
##  Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   stat =~                                             
##     test1             1.000                           
##     test2             1.087    0.126    8.615    0.000
##     test3             1.265    0.132    9.616    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .test1             0.787    0.064   12.306    0.000
##    .test2             0.819    0.077   10.707    0.000
##    .test3             0.903    0.071   12.724    0.000
##     stat              0.000                           
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .test1             0.169    0.033    5.171    0.000
##    .test2             0.323    0.051    6.373    0.000
##    .test3             0.090    0.041    2.224    0.026
##     stat              0.321    0.064    5.004    0.000 
## [...]</code></pre>
<p>Oder etwas bildlicher ausgedrückt:</p>
<p><img src="/post/2021-04-15-cfa_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>Die Regression der drei Tests auf die latente Variable unterscheidet sich also in der Steigung (Faktorladung) und dem Intercept. Das bedeutet, dass unsere drei Tests unterschiedlich gut darin sind, zwischen Personen zu unterscheiden: wenn Urs eine bessere Fähigkeit auf der latenten Dimension aufweist als Hans, wird er im 3. Test um mehr Punkte besser abschneiden, als im 1. Test. Darüber hinaus sind beide Tests unterschiedlich schwierig: eine durchschnittliche Person wird auf dem 3. Test mehr Punkte erhalten als auf dem 1. Beide Zustände wären äußerst ungünstig, weil Personen (anders als unsere Normierungsstichprobe, die wir hier betrachten) normalerweise nur einen der drei Tests ablegen und Personen, die den 3. Test ablegen, dann im Mittel einen Vorteil hätten.</p>
<p>Mit den Restriktionen der Messmodelle können wir jetzt über Modellvergleiche prüfen, ob diese Unterschiede statistisch bedeutsam oder nur zufällige Schwankungen aufgrund der Stichprobenziehung sind.</p>
</details>
<details>
<summary>
Esentiell <span class="math inline">\(\tau\)</span>-äquivalentes Modell
</summary>
<p>Der erste Schritt, der bei der Restriktion von Messmodellen stets vorgenommen werden muss, ist die Gleichsetzung der Diskriminationsparameter. Nur so kann garantiert werden, dass andere Gleichsetzungen sinnvoll interpretierbar und von der Skala, mit der wir die Ergebnisse beschreiben, unabhängig sind.</p>
<p>Weil wir zur Skalierung unserer latenten Variable die erste Faktorladung auf 1 setzen und das essentiell <span class="math inline">\(\tau\)</span>-äquivalente Messmodell postuliert, dass alle Faktorladungen gleich sein sollen, können wir alle Faktorladungen auf 1 fixieren. Dafür können wir händisch den jeweiligen Parameter festlegen:</p>
<pre class="r"><code># Modell
mod2 &lt;- &#39;stat =~ 1*test1 + 1*test2 + 1*test3&#39;

# Schätzung
fit2 &lt;- cfa(mod2, stat_test,
  meanstructure = TRUE)</code></pre>
<p>Der Abschnitt zu den Parametern sieht in der Zusammenfassung dann so aus:</p>
<pre class="r"><code>summary(fit2)</code></pre>
<pre><code>## [...]
##  Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   stat =~                                             
##     test1             1.000                           
##     test2             1.000                           
##     test3             1.000                           
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .test1             0.787    0.067   11.756    0.000
##    .test2             0.819    0.077   10.605    0.000
##    .test3             0.903    0.068   13.368    0.000
##     stat              0.000                           
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .test1             0.137    0.030    4.618    0.000
##    .test2             0.316    0.049    6.447    0.000
##    .test3             0.147    0.031    4.823    0.000
##     stat              0.400    0.059    6.733    0.000 
## [...]</code></pre>
<p>Alle Faktorladungen sind nun identisch. Das heißt, dass die Linien der unterschiedlichen Tests im Bild parallel verlaufen sollten, weil wir jetzt den Einfluss der latenten Variable auf die manifesten Variablen gleichgesetzt haben:</p>
<p><img src="/post/2021-04-15-cfa_files/figure-html/unnamed-chunk-78-1.png" width="672" /></p>
<p>Das bedeutet, dass sich der Unterschied zwischen Urs und Hans in der statistischen Fähigkeit in allen drei Tests im gleichen Punkteunterschied äußern <em>sollte</em>. Das <em>sollte</em> ist dabei wichtig, weil es natürlich in jedem Einzelfall aufgrund von Messfehlern zu Unterschieden kommen kann, wenn wir den Test aber unendlich häufig durchführen würden, wäre der Unterschied zwischen beiden immer gleich, egal welchen der drei Tests wir nutzen.</p>
<p>Ist diese Annahme haltbar? Wir können sie mit dem Modellvergleich explizit prüfen:</p>
<pre class="r"><code>lavTestLRT(fit1, fit2)</code></pre>
<pre><code>## Chi-Squared Difference Test
## 
##      Df    AIC    BIC Chisq Chisq diff Df diff Pr(&gt;Chisq)  
## fit1  0 675.66 700.75 0.000                                
## fit2  2 677.05 696.56 5.383      5.383       2    0.06778 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Der Test hat 2 Freiheitsgrade, weil wir nun nicht mehr die beiden Ladungen für <code>test2</code> und <code>test3</code> schätzen müssen, sondern diese einen vorgegebenen Wert angenommen haben. Bei einem <span class="math inline">\(\alpha\)</span>-Fehlerniveau von 5% muss diese Annahme also nicht verworfen werden und wir können das sparsamere, essentiell <span class="math inline">\(\tau\)</span>-äquivalente Messmodell für diese drei Tests beibehalten.</p>
<p>Die Annahme der essentielle <span class="math inline">\(\tau\)</span>-Äquivalenz spielt eine wichtige Rolle, wenn Skalen aus Itemsummen oder -mittelwerten bestimmt werden — sie muss mindestens gelten, damit einfaches Aufsummieren oder Mitteln zulässig ist. Genauso ist sie Voraussetzung für das bekannte Reliabilitätsmaß Cronbach’s <span class="math inline">\(\alpha\)</span> (neben bspw. Eindimensionaltität der Skala). Gilt diese Annahme auf essentielle <span class="math inline">\(\tau\)</span>-Äquivalenz nicht, so führen Analysen, die einfache Skalensummen oder -mittelwerte verwenden zu verzerrten Schlüssen und die Reliabilitätsschätzung unterliegt ebenfalls Verzerrungen. Alternativen bilden hier die latente Modellierung und als Skalenreliabilität könnte bspw. McDonald’s <span class="math inline">\(\omega\)</span> verwendet werden.</p>
</details>
<details>
<summary>
<span class="math inline">\(\tau\)</span>-äquivalentes Modell
</summary>
<p>In der Hierarchie der Messmodelle haben wir zwei Möglichkeiten, vorzugehen: wir können im Anschluss an das essentiell <span class="math inline">\(\tau\)</span>-äquivalente Messmodell entweder die Intercepts restringieren und so beim <span class="math inline">\(\tau\)</span>-äquivalenten Messmodell ankommen, oder uns die Residualvarianzen vornehmen und so beim essentiell <span class="math inline">\(\tau\)</span>-parallelen Messmodell angelangen. Wir entscheiden uns hier für den häufiger genutzten linken Weg der Abbildung und beziehen uns zunächst auf die Mittelwertsstruktur:</p>
<pre class="r"><code># Modell
mod3 &lt;- &#39;stat =~ 1*test1 + 1*test2 + 1*test3
  test1 ~ (alp)*1
  test2 ~ (alp)*1
  test3 ~ (alp)*1&#39;

# Schätzung
fit3 &lt;- cfa(mod3, stat_test,
  meanstructure = TRUE)</code></pre>
<p>Mit <code>(...)</code> wird in <code>lavaan</code> einem Parameter ein Label gegeben. Diese Labels können beliebig benannt sein, sie müssen nur mit einem Buchstaben beginnen. In der Zeile <code>test1 ~ (alp)*1</code> wird also das Intercept von <code>test1</code> angefordert und diesem Intercept der Name <code>alp</code> gegeben. In der nächsten Zeile machen wir für <code>test2</code> das Gleiche. Dadurch, dass wir hier den gleichen Namen nutzen werden die beiden Parameter zur Gleichheit gezwungen. In der Zusammenfassung tauchen diese Labels auch wieder auf, um zu verdeutlichen welche Parameter absichtlich gleich sind:</p>
<pre class="r"><code>summary(fit3)</code></pre>
<pre><code>## [...]
##  Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   stat =~                                             
##     test1             1.000                           
##     test2             1.000                           
##     test3             1.000                           
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .test1    (alp)    0.838    0.062   13.564    0.000
##    .test2    (alp)    0.838    0.062   13.564    0.000
##    .test3    (alp)    0.838    0.062   13.564    0.000
##     stat              0.000                           
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .test1             0.141    0.030    4.642    0.000
##    .test2             0.314    0.049    6.401    0.000
##    .test3             0.156    0.032    4.914    0.000
##     stat              0.398    0.059    6.694    0.000 
## [...]</code></pre>
<p>Diese Restriktion können wir erneut mit dem LRT prüfen:</p>
<pre class="r"><code>lavTestLRT(fit2, fit3)</code></pre>
<pre><code>## Chi-Squared Difference Test
## 
##      Df    AIC    BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)  
## fit2  2 677.05 696.56  5.383                                
## fit3  4 678.83 692.77 11.166     5.7829       2    0.05549 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Erneut erhalten wir 2 Freiheitsgrade beim Modellvergleich: jetzt müssen wir statt drei Intercepts nur noch Eines schätzen (den Wert von <code>alp</code>). Und wieder ist bei einem <span class="math inline">\(\alpha\)</span>-Fehlerniveau von 5% der Modellvergleich nicht statistisch bedeutsam, sodass wir auch hier wieder das sparsamere Modell beibehalten können.</p>
<p>Inhaltlich heißt dieses Ergebnis, dass wir für zwei Personen, die die gleiche statistische Fähigkeit haben auch den gleichen Wert in einem Test - egal welchem der drei - <em>erwarten</em>. Auch hier können Messfehler natürlich dazu führen, dass im Einzelfall Unterschiede entstehen. Über unendlich viele Wiederholungen hinweg sind die Erwartungswerte dieser Personen aber gleich. Wichtig ist, dass das nicht nur innerhalb eines Tests gilt, sondern auch über Tests hinweg. Wir können unterschiedlichen Personen also unterschiedliche Tests vorlegen - wenn Sie die gleiche Fähigkeit haben, dann erwarten wir für beide das gleiche Ergebnis. Die Ergebnisse der drei verschiedenen Formen der Modulprüfung sind also vergleichbar. Wenn die Annahme des <span class="math inline">\(\tau\)</span>-äquivalenten Messmodells allerdings nicht hält, sind die Prüfungen nicht direkt vergleichbar.</p>
<p>Auch in der Abbildung zeigt sich jetzt, dass die Tests äquivalent sind:</p>
<p><img src="/post/2021-04-15-cfa_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
</details>
<details>
<summary>
Essentiell <span class="math inline">\(\tau\)</span>-paralleles Modell
</summary>
<p>Im Essentiell <span class="math inline">\(\tau\)</span>-parallelen Modell werden die Restriktionen bezüglich der Intercepts zunächst außer Acht gelassen. Stattdessen wird das essentiell <span class="math inline">\(\tau\)</span>-äquivalente Modell bezüglich der Kovarianzstruktur so restringiert, dass die Varianzzerteilung aller manifester Variablen gleich ist. Das bewirkt inhaltlich, dass alle drei Tests jetzt die gleiche Reliabilität haben.</p>
<p>Wie schon im letzten Abschnitt müssen wir erneut mit Labels arbeiten, nur dass sie sich in diesem Fall auf die Residualvarianzen beziehen:</p>
<pre class="r"><code>mod4 &lt;- &#39;stat =~ 1*test1 + 1*test2 + 1*test3
  test1 ~~ (eps)*test1
  test2 ~~ (eps)*test2
  test3 ~~ (eps)*test3&#39;
fit4 &lt;- cfa(mod4, stat_test,
  meanstructure = TRUE)</code></pre>
<p>Das entstehende Ergebnis können wir uns wieder mit <code>summary</code> angucken. In diesem Fall nehmen wir mit <code>rsq = TRUE</code> die Reliabilitätsschätzungen auf, um meine Behauptung auf den Prüfstand zu stellen:</p>
<pre class="r"><code>summary(fit4, rsq = TRUE)</code></pre>
<pre><code>## [...]
##  Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   stat =~                                             
##     test1             1.000                           
##     test2             1.000                           
##     test3             1.000                           
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .test1             0.787    0.071   11.132    0.000
##    .test2             0.819    0.071   11.593    0.000
##    .test3             0.903    0.071   12.783    0.000
##     stat              0.000                           
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .test1    (eps)    0.200    0.018   10.954    0.000
##    .test2    (eps)    0.200    0.018   10.954    0.000
##    .test3    (eps)    0.200    0.018   10.954    0.000
##     stat              0.399    0.060    6.605    0.000
## 
## R-Square:
##                    Estimate
##     test1             0.666
##     test2             0.666
##     test3             0.666 
## [...]</code></pre>
<p>Um einen Test dieser Restriktion durchführen zu können, ist es wichtig zu bedenken, dass das <span class="math inline">\(\tau\)</span>-äquivalente Modell und das esentiell <span class="math inline">\(\tau\)</span>-parallele Modell nicht direkt miteinander verglichen werden können. Das liegt daran, dass keines der beiden durch die Einführung von Restriktionen in das Andere überführt werden kann. Allerdings kann auch das <span class="math inline">\(\tau\)</span>-parllele Modell durch die Restriktion der Residualvarianzen aus dem essentiell <span class="math inline">\(\tau\)</span>-äqauivalenten Modell gewonnen werden. Daher muss auch hiermit der Modellvergleich erfolgen, um die Zusatzannahme (die Gleichheit der Residualvarianzen) inferenzstatistisch zu prüfen:</p>
<pre class="r"><code>lavTestLRT(fit2, fit4)</code></pre>
<pre><code>## Chi-Squared Difference Test
## 
##      Df    AIC    BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)   
## fit2  2 677.05 696.56  5.383                                 
## fit4  4 685.45 699.38 17.782     12.399       2    0.00203 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Wir sehen in diesem Fall, dass die Annahme gleicher Residualvarianzen (und somit gleicher Reliabilitäten) verworfen werden muss.</p>
</details>
<details>
<summary>
<span class="math inline">\(\tau\)</span>-paralleles Modell
</summary>
<p>Das <span class="math inline">\(\tau\)</span>-parallele Messmodell ist das restriktivste Messmodell. Hier sind Ladungen, Intercepts und Residualvarianzen über die drei Tests hinweg gleich gesetzt. Das bedeutet, dass die beiden Annahmen aus dem <span class="math inline">\(\tau\)</span>-äquivalenten Messmodell und dem essentiell <span class="math inline">\(\tau\)</span>-parallelen Messmodell zusammengeführt werden.</p>
<p>In <code>lavaan</code> sieht das folgendermaßen aus:</p>
<pre class="r"><code>mod5 &lt;- &#39;stat =~ 1*test1 + 1*test2 + 1*test3
  
  test1 ~ (alp)*1
  test2 ~ (alp)*1
  test3 ~ (alp)*1
  
  test1 ~~ (eps)*test1
  test2 ~~ (eps)*test2
  test3 ~~ (eps)*test3&#39;

fit5 &lt;- cfa(mod5, stat_test,
  meanstructure = TRUE)</code></pre>
<p>Erneut können wir den Likelihood-Ratio Test nutzen. Wie auch bei der <code>anova</code>-Funktion, die Sie letztes Semester genutzt haben, um Regressionsmodelle zu vergleichen, können Sie bei <code>lavTestLRT</code> sequentiell mehrere Modelle testen lassen. Für den Überblick über den linken Pfad der Hierarchie:</p>
<pre class="r"><code>lavTestLRT(fit1, fit2, fit3, fit5)</code></pre>
<pre><code>## Chi-Squared Difference Test
## 
##      Df    AIC    BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)   
## fit1  0 675.66 700.75  0.000                                 
## fit2  2 677.05 696.56  5.383     5.3830       2   0.067780 . 
## fit3  4 678.83 692.77 11.166     5.7829       2   0.055495 . 
## fit5  6 685.76 694.12 22.093    10.9271       2   0.004238 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Wir sehen also, dass wir in diesem Fall bei <code>fit3</code> den Schlussstrich ziehen sollten und das <span class="math inline">\(\tau\)</span>-äquivalente Messmodell annehmen können, weil dessen Restriktionen nicht verworfen werden (gegenüber dem Modell mit essentiell <span class="math inline">\(\tau\)</span>-äquivalenten Messungen), aber die zusätzliche Restriktion der gleichen Residualvarianzen bei einem <span class="math inline">\(\alpha\)</span>-Fehlerniveau von 5% abgelehnt wird.</p>
<p><code>fit3</code> und <code>fit4</code> können über den LRT nicht direkt miteinander verglichen werden, weil keins der Beiden ein Sonderfall des Anderen ist - daher stehen Sie in der Hierarchie auch auf der gleichen Stufe. Sie können aber natürlich auch den rechten Pfad prüfen:</p>
<pre class="r"><code>lavTestLRT(fit1, fit2, fit4, fit5)</code></pre>
<pre><code>## Chi-Squared Difference Test
## 
##      Df    AIC    BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)   
## fit1  0 675.66 700.75  0.000                                 
## fit2  2 677.05 696.56  5.383     5.3830       2    0.06778 . 
## fit4  4 685.45 699.38 17.782    12.3994       2    0.00203 **
## fit5  6 685.76 694.12 22.093     4.3106       2    0.11587   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</details>
</div>
<div id="literatur" class="section level2">
<h2>Literatur</h2>
<p><a href="https://ubffm.hds.hebis.de/Record/HEB366849158">Eid, M., Gollwitzer, M., &amp; Schmitt, M. (2017).</a> <em>Statistik und Forschungsmethoden</em> (5. Auflage, 1. Auflage: 2010). Weinheim: Beltz.</p>
<p><a href="https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00279/full">Brotherton, R., French, C. C., &amp; Pickering, A. D. (2013)</a>. Measuring belief in conspiracy theories: the generic conspiracist beliefs scale. <em>Frontiers in Psychology</em>, 4, 279, DOI: 10.3389/fpsyg.2013.00279.</p>
<ul>
<li><small> <em>Blau hinterlegte Autor:innenangaben führen Sie direkt zur universitätsinternen Ressource.</em> </small></li>
</ul>
</div>
