---
title: Tests für unabhängige Stichproben - Aufgaben
date: '2020-12-17'
slug: gruppenvergleiche-unabhaengig-aufgaben
categories:
  - BSc2
tags:
  - t-Test
subtitle: ''
summary: ''
authors: [koehler, buchholz]
lastmod: '2020-12-17T12:58:41+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

**Untersuchen Sie folgende Fragestellungen anhand des fb20-Datensatzes**

**Denken Sie dabei an Folgendes:**

*	Deskriptivstatistische Beantwortung der Fragestellung  
*	Voraussetzungsprüfungen   
*	Spezifikation der Hypothesen und des Signifikanzniveaus  
*	Ggfls. Berechnung der Effektstärke  
*	Formales Berichten des Ergebnisses    

## Aufgabe 1
Unterscheiden sich Studierende, die sich für Allgemeine Psychologie (Variable "fach") interessieren, im Persönlichkeitsmerkmal Intellekt (auch: Offenheit für neue Erfahrungen, "intell") von Studierenden, die sich für Klinische Psychologie interessieren?  

## Aufgabe 2
Sind Studierende, die außerhalb von Frankfurt wohnen ("ort"), zufriedener im Leben ("lz") als diejenigen, die innerhalb von Frankfurt wohnen?  

## Aufgabe 3
Ist die Wahrscheinlichkeit dafür, innerhalb von Frankfurt zu wohnen, die gleiche für weibliche wie für männliche Erstsemester-Studierende der Psychologie?

