---
title: "Deskriptivstatistik für Nominal- und Ordinalskalen"
categories: [BSc2]
date: '2020-09-24'
featured: no
header:
  caption: '[Courtesy of pxhere](https://pxhere.com/en/photo/1227907)'
  image: /header/descriptive_post.jpg
lastmod: '2020-09-24T20:54:18+02:00'
projects: []
slug: deskriptiv-nominal
subtitle: ''
summary: ''
tags: 
  - R 
  - Deskriptivstatistik
authors: [buchholz, nehler]
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<details>
<summary>
Kernfragen dieser Lehreinheit
</summary>
<ul>
<li>Wie werden <strong>Häufigkeitstabellen</strong> erstellt?<br />
</li>
<li>Wie können aus absoluten Häufigkeitstabellen <strong>relative Häufigkeitstabellen</strong> gemacht werden?<br />
</li>
<li>Wie können <strong>Modus und Median</strong> bestimmt werden?<br />
</li>
<li>Auf welche Weise lässt sich der <strong>relative Informationsgehalt</strong> bestimmen, obwohl es dafür in R keine Funktion gibt?<br />
</li>
<li>Welche Befehle können genutzt werden, um <strong>Balken- und Kuchendiagramme</strong> zu erzeugen?<br />
</li>
<li>Welche Möglichkeiten gibt es, um <strong>Grafiken anzupassen</strong>?<br />
</li>
<li>Wie können <strong>Grafiken gespeichert</strong> werden?</li>
<li>Wie können in R <strong>Histogramme</strong> erstellt werden? Wie lassen sich die Kategorienbreiten verändern?</li>
</ul>
</details>
<hr />
<div id="wiederholung-aus-der-vorlesung-skalenniveaus" class="section level2">
<h2>Wiederholung aus der Vorlesung: Skalenniveaus</h2>
<table>
<colgroup>
<col width="6%" />
<col width="24%" />
<col width="16%" />
<col width="20%" />
<col width="34%" />
</colgroup>
<thead>
<tr class="header">
<th>Skala</th>
<th>Aussage</th>
<th>Transformation</th>
<th>Zentrale Lage</th>
<th>Dispersion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nominal</td>
<td>Äquivalenz</td>
<td>eineindeutig</td>
<td>Modus</td>
<td>Relativer Informationsgehalt</td>
</tr>
<tr class="even">
<td>Ordinal</td>
<td>Ordnung</td>
<td>monoton</td>
<td>Median</td>
<td>Interquartilsbereich</td>
</tr>
<tr class="odd">
<td>Intervall</td>
<td>Verhältnis von Differenzen</td>
<td>positiv linear</td>
<td>Mittelwert</td>
<td>Standardabweichung, Varianz</td>
</tr>
<tr class="even">
<td>Verhältnis</td>
<td>Verhältnisse</td>
<td>Ähnlichkeit</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>Absolut</td>
<td>absoluter Wert</td>
<td>Identität</td>
<td>…</td>
<td>…</td>
</tr>
</tbody>
</table>
<hr />
</div>
<div id="vorbereitende-schritte" class="section level2">
<h2>Vorbereitende Schritte</h2>
<p>Nachdem wir in der letzten Sitzung die Arbeit mit dem CSV Format kennen gelernt haben, nutzen wir jetzt die Datei im RDA Format für das Einlesen des Datensatzes. Die Datei können Sie <a href="/post/fb21.rda">hier <i class="fas fa-download"></i> herunterladen</a>. Sie können ihn aber alternativ auch mit dem folgenden Befehl direkt aus dem Internet einladen.</p>
<pre class="r"><code>load(url(&#39;https://pandar.netlify.app/post/fb21.rda&#39;))   # Daten laden
names(fb21)        # Namen der Variablen</code></pre>
<pre><code>##  [1] &quot;prok1&quot;   &quot;prok2&quot;   &quot;prok3&quot;   &quot;prok4&quot;   &quot;prok5&quot;   &quot;prok6&quot;   &quot;prok7&quot;  
##  [8] &quot;prok8&quot;   &quot;prok9&quot;   &quot;prok10&quot;  &quot;nr1&quot;     &quot;nr2&quot;     &quot;nr3&quot;     &quot;nr4&quot;    
## [15] &quot;nr5&quot;     &quot;nr6&quot;     &quot;lz&quot;      &quot;extra&quot;   &quot;vertr&quot;   &quot;gewis&quot;   &quot;neuro&quot;  
## [22] &quot;intel&quot;   &quot;nerd&quot;    &quot;grund&quot;   &quot;fach&quot;    &quot;ziel&quot;    &quot;lerntyp&quot; &quot;geschl&quot; 
## [29] &quot;job&quot;     &quot;ort&quot;     &quot;ort12&quot;   &quot;wohnen&quot;  &quot;uni1&quot;    &quot;uni2&quot;    &quot;uni3&quot;   
## [36] &quot;uni4&quot;</code></pre>
<pre class="r"><code>dim(fb21)          # Anzahl Zeile und Spalten</code></pre>
<pre><code>## [1] 114  36</code></pre>
<p>In der letzten Sitzung haben wir schon einige Befehle für das Screening eines Datensatzes kennen gelernt. Dabei zeigt <code>names</code> alle Variablennamen an, während <code>dim</code> uns Zeilen und Spalten ausgibt. Der Datensatz hat also 114 Beobachtungen auf 36 Variablen.</p>
<hr />
</div>
<div id="nominalskalierte-variablen" class="section level2">
<h2>Nominalskalierte Variablen</h2>
<p>Typische Beispiele für nominalskalierte Variablen in der Psychologie sind das Geschlecht (z.B. Variable “geschl” in <code>fb21</code>), die Experimentalbedingung (z.B. “Experimentalgruppe” und “Kontrollgruppe”). Nominalskalierte Variablen sollten in <code>R</code> als <strong>Faktoren</strong> hinterlegt werden. Faktoren in <code>R</code> sind Vektoren mit einer vorab definierten Menge an vorgegebenen möglichen Ausprägungsmöglichkeiten. Sowohl numerische als auch character-Variablen können als Faktor kodiert werden, was mit jeweiligen Vorteilen einhergeht:</p>
<ul>
<li>für numerische Variablen: es können (aussagekräftige) Labels zugewiesen (“hinterlegt”) werden. Diese werden dann für Tabellen und Grafiken übernommen<br />
</li>
<li>Für character-Variablen: Faktoren können für Analysen verwendet werden (z.B. als Prädiktoren in einer Regression), was für character-Variablen nicht möglich gewesen wäre</li>
</ul>
<p>Jeder numerischen Faktorstufe (level) kann ein Label zugewiesen werden. Faktorstufe und –label bestehen auch dann, wenn die entsprechende Ausprägung empirisch nicht auftritt.</p>
<p><strong>Beispiel 1: Die (numerische) Variable <code>geschl</code> als Faktor aufbereiten</strong></p>
<pre class="r"><code>str(fb21$geschl)</code></pre>
<pre><code>##  int [1:114] 2 1 1 1 NA 1 1 2 3 1 ...</code></pre>
<pre class="r"><code>fb21$geschl</code></pre>
<pre><code>##   [1]  2  1  1  1 NA  1  1  2  3  1  1  1  1  1 NA  1  1  2  1  1  1  2  2  1  2
##  [26]  1  1  1  2  1  1  1  1  2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2
##  [51]  1  2  1  1  2  1  1  1  1  1  2  2  2  2  2  1  1  1  2  2  1  2  1  1  1
##  [76]  1  2  1  1  2  1  2  2  2  1  1  2  1  1  2  1  2  1  1  1  1  2  2  2  1
## [101]  1  1  1  1  1  1  1  1  1  1  1  1  1  1</code></pre>
<p>Die Variable <code>geschl</code> liegt numerisch vor, es treten die Werte 1, 2 und 3 empirisch auf. Die Bedeutung von <code>NA</code> wird <a href="#Fehlend">später</a> betrachtet. Anhand des Kodierschemas (<a href="/post/variablen.pdf"><i class="fas fa-download"></i> Variablenübersicht</a>) kann den Zahlen eine inhaltliche Bedeutung zugewiesen werden. Beispielsweise bedeutet der Wert 1 “weiblich”. Diese <em>Label</em> werden nun im Faktor hinterlegt.</p>
<p>Vorgehensweise:</p>
<ul>
<li>Erstellung einer neuen Variable im Datensatz per Objektzuweisung: <code>datensatz$neueVariable &lt;- factor(...)</code><br />
</li>
<li>Faktor erstellen mit der Funktion <code>factor(Ausgangsvariable, levels = Stufen, labels = Label)</code></li>
<li>Spezifikation der Faktorstufen im Argument <code>levels</code>, also der numerischen Ausprägungen auf der Ursprungsvariable (hier: 1, 2 und 3)<br />
</li>
<li>Spezifikation des Arguments <code>labels</code>, also die Label für die in <code>levels</code> hinterlegten numerischen Stufen (hier: “weiblich”, “männlich”, “anderes”; unbedingt auf gleiche Reihenfolge achten!)</li>
</ul>
<pre class="r"><code>fb21$geschl_faktor &lt;- factor(fb21$geschl,                                   # Ausgangsvariable
                             levels = 1:3,                                  # Faktorstufen
                             labels = c(&quot;weiblich&quot;, &quot;männlich&quot;, &quot;anderes&quot;)) # Label für Faktorstufen
str(fb21$geschl_faktor)</code></pre>
<pre><code>##  Factor w/ 3 levels &quot;weiblich&quot;,&quot;männlich&quot;,..: 2 1 1 1 NA 1 1 2 3 1 ...</code></pre>
<pre class="r"><code>head(fb21$geschl_faktor)</code></pre>
<pre><code>## [1] männlich weiblich weiblich weiblich &lt;NA&gt;     weiblich
## Levels: weiblich männlich anderes</code></pre>
<p><strong>Beispiel 2: Lieblingsfach (numerisch) als Faktor aufbereiten</strong></p>
<p>Analog dazu wird nachfolgend die ebenfalls numerische Variable <code>fach</code> in einen Faktor umgewandelt. Sie wurde wie folgt erhoben:</p>
<p><img src="/post/fb_nominal.png" /></p>
<pre class="r"><code>fb21$fach</code></pre>
<pre><code>##   [1]  2  4  5  5 NA  4  5  5  5  4  1  4  3  3 NA  4  3  3  2  4  1  5  3  4  5
##  [26]  4  2  4  4  4  2  4  2  1  5  4  1 NA  4  4  3  4  3  4  2  4  4  4  1  2
##  [51]  4  4  4  3  1  4  4  4  1  1  4  2  2  2  4  4  4  4  4  4  4  1 NA  1  4
##  [76]  1  4  4  3  1  1  4  3  2  2  2  3  1  3  4  4  3  2  2  1  1  3  1  3  1
## [101]  2  2  3  1  4  2  1 NA  4  1  5  2  4  4</code></pre>
<p>Es treten die Ausprägungen 1 bis 5 empirisch auf. Auch hier werden die Label aus dem Kodierschema zugewiesen.</p>
<pre class="r"><code>fb21$fach &lt;- factor(fb21$fach,
                    levels = 1:5,
                    labels = c(&#39;Allgemeine&#39;, &#39;Biologische&#39;, &#39;Entwicklung&#39;, &#39;Klinische&#39;, &#39;Diag./Meth.&#39;))
str(fb21$fach)</code></pre>
<pre><code>##  Factor w/ 5 levels &quot;Allgemeine&quot;,&quot;Biologische&quot;,..: 2 4 5 5 NA 4 5 5 5 4 ...</code></pre>
<p>Hinweis: In Beispiel 2 wurde die Ursprungsvariable mit dem Faktor überschrieben. Sie ist nun verschwunden, der Datensatz enthält nur noch den Faktor, nicht mehr die numerische Variable.</p>
<p><strong>Beispiel 3: Einen character-Vektor als Faktor aufbereiten</strong></p>
<p>Um einen character-Vektor in einen Faktor umzukodieren, kann die Funktion <code>as.factor()</code> verwendet werden (siehe Skript zur Lehreinheit 1). Die Ausprägungen werden dann automatisch als Labels übernommen. Die Stufen (<code>levels</code>) werden in alphabetischer Reihenfolge vergeben.</p>
<p>Nachfolgend wird zur Illustration die offene Freitextantwort zum Grund für das Psychologiestudium (Variable <code>grund</code>) in einen Faktor umgewandelt.</p>
<pre class="r"><code>str(fb21$grund)                            # Ursprungsvariable: Character</code></pre>
<pre><code>##  chr [1:114] NA NA &quot;123&quot; &quot;Arbeit mit Menschen&quot; NA &quot;Beruf der Eltern &quot; ...</code></pre>
<pre class="r"><code>fb21$grund_faktor &lt;- as.factor(fb21$grund) # Umwandlung in Faktor
str(fb21$grund_faktor)                     # neue Variable: Faktor</code></pre>
<pre><code>##  Factor w/ 94 levels &quot;- interessant&quot;,..: NA NA 2 4 NA 9 38 68 75 17 ...</code></pre>
<p>Die neue Variable ist nun ein Faktor mit 94 Stufen. Das Vorgehen ist nur zur Anschauung gedacht und in diesem speziellen Fall nicht sinnvoll, da jede einzelne Freitextantwort vermutlich nur genau einmal vorkommt und später sowieso nicht (ohne zusätzliche Kodierung) in statistischen Analysen weiterverwendet werden kann.</p>
<p><strong>Hinweise zu den Levels und Labels</strong></p>
<p>Die Reihenfolge von Levels und Labels ergibt sich während der Faktorerstellung:</p>
<ul>
<li>bei numerischen Variablen: entspricht den Ausprägungen der numerischen Ursprungsvariable<br />
</li>
<li>bei character-Variablen: entspricht der alphabetischen Reihenfolge der Ausprägungen auf der Ursprungsvariable</li>
</ul>
<p>Die Labels eines Faktors können mit der Funktion <code>levels()</code> abgerufen werden. Die Reihenfolge kann mithilfe der <code>relevel()</code>-Funktion geändert werden. Dafür muss dasjenige Label angesprochen werden, das die erste Position einnehmen soll (hier: ‘Diag./Meth.’).</p>
<pre class="r"><code>levels(fb21$fach)         # Abruf</code></pre>
<pre><code>## [1] &quot;Allgemeine&quot;  &quot;Biologische&quot; &quot;Entwicklung&quot; &quot;Klinische&quot;   &quot;Diag./Meth.&quot;</code></pre>
<pre class="r"><code>fb21$fach &lt;- relevel(
  fb21$fach,              # Bezugskategorie wechseln
  &#39;Diag./Meth.&#39;)          # Neue Bezugskategorie</code></pre>
<hr />
</div>
<div id="häufigkeitstabellen" class="section level2">
<h2>Häufigkeitstabellen</h2>
<p>Eine deskriptivstatistische Möglichkeit zur Darstellung diskreter (zählbarer) nominalskalierter Variablen sind Häufigkeitstabellen. Diese können in <code>R</code> mit der Funktion <code>table()</code> angefordert werden.</p>
<p><strong>Absolute Häufigkeiten</strong></p>
<pre class="r"><code>table(fb21$fach)</code></pre>
<pre><code>## 
## Diag./Meth.  Allgemeine Biologische Entwicklung   Klinische 
##           9          21          19          16          44</code></pre>
<p>Häufig sind relative Häufigkeiten informativer. Nachfolgend werden zwei Möglichkeiten zur Erstellung von relativen Häufigkeitstabellen in <code>R</code> gezeigt.</p>
<p><strong>Relative Häufigkeiten (manuell)</strong></p>
<p>Relative Häufigkeiten können aus absoluten Häufigkeiten abgeleitet werden: <span class="math inline">\(h_j = \frac{n_j}{n}\)</span>.</p>
<p>Diese einfache Rechenvorschrift (Kategorienhäufigkeit geteilt durch Gesamthäufigkeit) kann auf das gesamte Tabellenobjekt angewendet werden. So wird jede einzelne absolute Kategorienhäufigkeit am Gesamtwert relativiert, es resultiert eine Tabelle der relativen Häufigkeiten.</p>
<pre class="r"><code>tab &lt;- table(fb21$fach) # Absolute Haeufigkeiten
sum(tab)                # Gesamtzahl</code></pre>
<pre><code>## [1] 109</code></pre>
<pre class="r"><code>tab / sum(tab)          # Relative Haeufigkeiten</code></pre>
<pre><code>## 
## Diag./Meth.  Allgemeine Biologische Entwicklung   Klinische 
##  0.08256881  0.19266055  0.17431193  0.14678899  0.40366972</code></pre>
<p><strong>Relative Häufigkeiten (per Funktion)</strong></p>
<p>Alternativ kann die Funktion <code>prop.table()</code> auf das Tabellenobjekt mit den absoluten Häufigkeiten angewendet werden.</p>
<pre class="r"><code>tab &lt;- table(fb21$fach) # Absolute
prop.table(tab)         # Relative</code></pre>
<pre><code>## 
## Diag./Meth.  Allgemeine Biologische Entwicklung   Klinische 
##  0.08256881  0.19266055  0.17431193  0.14678899  0.40366972</code></pre>
<p>Ungefähr 8.26% Ihres Jahrgangs geben als Lieblingsfach “Diagnostik/Methoden” an! Vielleicht können wir ja noch mehr von Ihnen mit dem nächsten Thema begeistern. :-)</p>
<hr />
</div>
<div id="grafiken-in-r" class="section level2">
<h2>Grafiken in <code>R</code></h2>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Die Darstellung als Tabelle wirkt häufig langweilig. Zu viele Tabellen in einem Bericht / einer Arbeit schrecken Leser:innen meist ab. Nachfolgend werden mögliche grafische Darstellungsformen für diskrete nominalskalierte Variablen gezeigt.</p>
<p><strong>Säulen- oder Balkendiagramm</strong></p>
<pre class="r"><code>barplot(tab)</code></pre>
<p>Die Grafik erscheint in der RStudio-Standardansicht “unten rechts” im Reiter “Plots”:</p>
<p><img src="/post/plots_window.PNG" /></p>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen_files/figure-html/unnamed-chunk-13-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><strong>Kuchendiagramm</strong></p>
<pre class="r"><code>pie(tab)</code></pre>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen_files/figure-html/unnamed-chunk-14-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p><strong>Zusatzargumente für Plots</strong></p>
<p>Die Funktionen zur Erstellung sehr simpler Grafiken sind also denkbar einfach - die Grafiken selbst aber zunächst nicht unbedingt hübsch. <code>R</code> bietet diverse Zusatzargumente zur Anpassung der Optik von Grafiken.</p>
<table>
<thead>
<tr class="header">
<th align="right">Argument</th>
<th align="left">Bedeutung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">main</td>
<td align="left">Überschrift</td>
</tr>
<tr class="even">
<td align="right">las</td>
<td align="left">Schriftausrichtung (0, 1, 2, 3)</td>
</tr>
<tr class="odd">
<td align="right">col</td>
<td align="left">Farbenvektor</td>
</tr>
<tr class="even">
<td align="right">horiz</td>
<td align="left">Horizontale Balkenausrichtung (TRUE/FALSE)</td>
</tr>
<tr class="odd">
<td align="right">legend.text</td>
<td align="left">Beschriftung in der Legende</td>
</tr>
<tr class="even">
<td align="right">xlim, ylim</td>
<td align="left">Beschränkung der Achsen</td>
</tr>
<tr class="odd">
<td align="right">xlab, ylab</td>
<td align="left">Beschriftung der Achsen</td>
</tr>
</tbody>
</table>
<p><strong>Farben in <code>R</code></strong></p>
<p><code>R</code> kennt eine ganze Reihe vordefinierter Farben ($N = $ 657) mit teilweise sehr poetischen Namen. Diese können mit der Funktion <code>colors()</code> (ohne Argument) abgerufen werden. Hier sind die ersten 20 Treffer:</p>
<pre class="r"><code>colors()[1:20]</code></pre>
<pre><code>##  [1] &quot;white&quot;         &quot;aliceblue&quot;     &quot;antiquewhite&quot;  &quot;antiquewhite1&quot;
##  [5] &quot;antiquewhite2&quot; &quot;antiquewhite3&quot; &quot;antiquewhite4&quot; &quot;aquamarine&quot;   
##  [9] &quot;aquamarine1&quot;   &quot;aquamarine2&quot;   &quot;aquamarine3&quot;   &quot;aquamarine4&quot;  
## [13] &quot;azure&quot;         &quot;azure1&quot;        &quot;azure2&quot;        &quot;azure3&quot;       
## [17] &quot;azure4&quot;        &quot;beige&quot;         &quot;bisque&quot;        &quot;bisque1&quot;</code></pre>
<p>Die Farben aus der Liste können als Zahl (Index) oder per Name angesprochen werden. Eine vollständige Liste der Farben findet sich zum Beispiel unter <a href="http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf">http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf</a>. Farben können aber auch per RGB-Vektor (Funktion <code>rgb()</code>) oder HEX-Wert angesprochen werden.</p>
<p>Zusätzlich können Farbpaletten verwendet werden. Sie bestehen aus einem Farbverlauf, aus dem einzelne Farben “herausgezogen” werden, wodurch ein zusammengehöriges Farbthema in einer Abbildung entsteht. <code>R</code> liefert einige dieser Paletten: <code>rainbow(...)</code>, <code>heat.colors(...)</code>, <code>topo.colors(...)</code>, … Die Farbpalette wird ebenfalls per <code>col</code>-Argugment spezifiziert. Technisch handelt es sich um eine Funktion, für die als Argument die Anzahl der Farben spezifiziert werden muss, die aus der Palette “gezogen” werden sollen. Beispielsweise werden mit <code>col = rainbow(5)</code> fünf Farben aus der rainbow-Palette gezogen.</p>
<p><strong>Beispiel für angepasste Abbildung</strong></p>
<pre class="r"><code>barplot(tab,
 col = rainbow(5),
 xlab = &#39;Studierende (Anzahl)&#39;,
 main = &#39;Lieblingsfach im 1. Semester&#39;,
 las=1)</code></pre>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p><strong>Grafiken speichern</strong></p>
<p>Es gibt zwei Möglichkeiten, um in <code>R</code> erzeugte Grafiken als Bilddatei zu speichern: manuell und per Funktion.</p>
<p><em>Möglichkeit 1: Manuelles Speichern</em></p>
<p>Klicken Sie auf die Schaltfläche “Export” und dann auf “Save as Image”…</p>
<p><img src="/post/Screenshot-Export.PNG" /></p>
<p>…und spezifizieren Sie dann Dateiname (ggf. Pfad) und Größe/Größenverhältnis.</p>
<p><img src="/post/plot_export_2.PNG" /></p>
<p>Wenn kein Pfad spezifiziert wird, erscheint die Datei in Ihrem aktuellen Arbeitsverzeichnis.</p>
<p><img src="/post/Screenshot-jpeg.PNG" /></p>
<p><em>Möglichkeit 2: Speichern mit der Funktion <code>jpeg("Dateiname.jpg")</code></em></p>
<p>Die Grafikerstellung folgt auf die <code>jpeg()</code>-Funktion und wird mit der Funktion <code>dev.off()</code> abgeschlossen.</p>
<pre class="r"><code>jpeg(&quot;Mein-Boxplot.jpg&quot;, width=15, height=10, units=&quot;cm&quot;, res=150)
barplot(tab,
 col = rainbow(20),
 xlab = &#39;Studierende (Anzahl)&#39;,
 main = &#39;Lieblingsfach im 1. Semester&#39;,
 las=1)
dev.off()</code></pre>
<p>Auch hier gilt: Wenn kein Pfad spezifiziert wurde, liegt die Datei in Ihrem Arbeitsverzeichnis. In der Funktion <code>jpeg()</code> kann mit den Argumenten <code>width</code>, <code>height</code>, <code>units</code> und <code>res</code> Größe, Größenverhältnis und Auflösung gesteuert werden.</p>
<hr />
</div>
<div id="deskriptivstatistische-kennwerte-auf-nominalskalenniveau" class="section level2">
<h2>Deskriptivstatistische Kennwerte auf Nominalskalenniveau</h2>
<p><strong>Modus</strong></p>
<p>Der Modus (<em>Mo</em>) ist ein Maß der zentralen Tendenz, das die häufigste Ausprägung einer Variable anzeigt. Die Häufigkeiten sind ja schon in der Häufigkeitstabelle enthalten. Man könnte den Modus also einfach ablesen. Das gleiche lässt sich allerdings auch anhand von Funktionen tun:</p>
<pre class="r"><code>tab            # Tabelle ausgeben</code></pre>
<pre><code>## 
## Diag./Meth.  Allgemeine Biologische Entwicklung   Klinische 
##           9          21          19          16          44</code></pre>
<pre class="r"><code>max(tab)       # Größte Häufigkeit</code></pre>
<pre><code>## [1] 44</code></pre>
<pre class="r"><code>which.max(tab) # Modus</code></pre>
<pre><code>## Klinische 
##         5</code></pre>
<p>Der Modus der Variable <code>fach</code> lautet also Klinische, die Ausprägung trat 44 mal auf.</p>
<p><strong>Relativer Informationsgehalt</strong></p>
<p>Der relative Informationsgehalt ist ein Dispersionsmaß, das schon auf Nominalskalenniveau funktioniert. Dafür gibt es in <code>R</code> allerdings keine Funktion! Aus Lehreinheit 1 wissen Sie jedoch, dass <code>R</code> als Taschenrechner genutzt werden kann, folglich können beliebig komplexe Gleichungen in <code>R</code> umgesetzt werden. Die Formel zur Berechnung des relativen Informationsgehalts <span class="math inline">\(H\)</span> lautet:</p>
<p><span class="math display">\[H = -\frac{1}{\ln(k)} \sum_{j=1}^k{h_j * \ln h_j} \]</span></p>
<p><span class="math inline">\(n_j\)</span> bezeichnet alle gültigen Antworten und kann als Summe der Häufigkeiten in <code>tab</code> abgelesen werden.</p>
<pre class="r"><code>hj &lt;- prop.table(tab)       # hj erstellen
ln_hj &lt;- log(hj)            # Logarithmus bestimmen
ln_hj                       # Ergebnisse für jede Kategorie</code></pre>
<pre><code>## 
## Diag./Meth.  Allgemeine Biologische Entwicklung   Klinische 
##  -2.4941233  -1.6468254  -1.7469089  -1.9187592  -0.9071582</code></pre>
<pre class="r"><code>summand &lt;- ln_hj * hj       # Berechnung für jede Kategorie
summe &lt;- sum(summand)       # Gesamtsumme
k &lt;- dim(tab)               # Anzahl Kategorien
relinf &lt;- -1/log(k) * summe # Relativer Informationsgehalt
relinf</code></pre>
<pre><code>## [1] 0.9168214</code></pre>
<p>Eine kleine Abkürzung durch Einsparen der Schritte am Ende könnte hier folgendermaßen mittels Pipe erreicht werden:</p>
<pre class="r"><code>relinf &lt;- (ln_hj * hj) |&gt; sum() * (-1/log(k))  # Relativer Informationsgehalt
relinf</code></pre>
<pre><code>## [1] 0.9168214</code></pre>
<p>Eine alternative Schreibweise, die ohne Zwischenschritte auskommt, dafür aber stark verschachtelt ist, lautet:</p>
<pre class="r"><code>- 1/log(dim(table(fb21$fach))) * sum(prop.table(table(fb21$fach)) * log(prop.table(table(fb21$fach))))</code></pre>
<pre><code>## [1] 0.9168214</code></pre>
<p>Wie man hier sieht, stößt die Schachtelung ohne das Speichern von Zwischenergebnissen oder das nutzen der Pipe schnell an die Grenzen der Übersichtlichkeit.</p>
<p>In allen drei Varianten kommen wir aber zum gleichen Schluss: der relative Informationsgehalt der Variable <code>fach</code> beträgt 0.917. Da der mögliche Wertebereich zwischen 0 (für alle Personen selbe Kategorie) und 1 (für alle Kategorien gleich viele Personen) variiert, kann hier von einer starken Verteilung der Personen ausgegangen werden.</p>
<hr />
</div>
<div id="ordinalskalierte-variablen" class="section level2">
<h2>Ordinalskalierte Variablen</h2>
<p>In diesem Abschnitt lernen Sie deskriptivstatistische Kennwerte für ordinalskalierte Variablen kennen. Aus der Vorlesung wissen Sie schon, dass Median und Interquartilsabstand (IQB) nur für die Klasse der geordneten Kategorien (auch “Rangklassen”) sinnvoll sind, nicht für singuläre Daten (“Rangwerte”).</p>
<p>Zunächst aber eine Wiederholung: Wie Sie aus der Vorlesung wissen, können die in der Tabelle am Anfang dieses Dokuments aufgeführten statistischen Kennwerte (Zentrale Lage, Dispersion) auch für Skalenniveaus genutzt werden, die “weiter unten” in der Tabelle stehen. Für ordinalskalierte Variablen (Rangklassen) kann also auch der Modus berechnet werden.</p>
<p>Nachfolgend soll mit Item 4 des Prokrastinationsfragebogens gearbeitet werden. Es wurde wie folgt erhoben:</p>
<p><img src="/post/fb_prok1.PNG" /></p>
<p>Es treten die Werte 1 bis 4 empirisch auf, außerdem gibt es 2 fehlende Werte (dargestellt als <code>NA</code>):</p>
<pre class="r"><code>fb21$prok4</code></pre>
<pre><code>##   [1]  3  2  2 NA  2  3  4  1  4  1  1  3  2  3  4 NA  2  2  3  2  2  2  3  2  2
##  [26]  2  2  3  2  2  2  3  3  2  3  3  2  2  2  2  3  3  3  4  3  1  2  3  3  4
##  [51]  2  3  2  2  2  3  3  4  3  4  2  3  2  1  2  4  2  2  1  1  4  2  2  2  1
##  [76]  2  3  2  3  3  1  2  1  3  3  4  2  1  2  3  3  3  3  3  1  2  3  4  3  3
## [101]  4  1  4  2  1  3  2  1  1  4  4  3  1  1</code></pre>
<p>Wiederholung:</p>
<pre class="r"><code>table(fb21$prok4)               # Absolute Haeufigkeiten</code></pre>
<pre><code>## 
##  1  2  3  4 
## 18 42 37 15</code></pre>
<pre class="r"><code>prop.table(table(fb21$prok4))   # Relative Haeufigkeiten</code></pre>
<pre><code>## 
##         1         2         3         4 
## 0.1607143 0.3750000 0.3303571 0.1339286</code></pre>
<pre class="r"><code>which.max(table(fb21$prok4))    # Modus</code></pre>
<pre><code>## 2 
## 2</code></pre>
</div>
<div id="Fehlend" class="section level2">
<h2>Fehlende Werte</h2>
<p>Fehlende Werte (dargestellt als <code>NA</code>) in empirischen Untersuchungen können aus vielen Gründen auftreten:</p>
<ul>
<li>Fragen überlesen / nicht gesehen<br />
</li>
<li>Antwort verweigert<br />
</li>
<li>Unzulässige Angaben gemacht (im Papierformat)<br />
</li>
<li>Unleserliche Schrift (im Papierformat)</li>
<li>…</li>
</ul>
<p>Für statistische Analysen sind fehlende Werte ein Problem, weil sie außerhalb der zulässigen Antworten liegen.</p>
<p><strong>Fehlende Werte in <code>R</code></strong></p>
<p>Fehlende Werte werden im Datensatz als <code>NA</code> dargestellt. In <code>R</code> kann man solche Fälle auf zwei unterschiedlichen Ebenen berücksichtigen:</p>
<ul>
<li>Global: <code>na.omit(datensatz)</code>
<ul>
<li>Entfernt <em>alle</em> Beobachtungen, die auf <em>irgendeiner</em> Variable einen fehlenden Wert haben<br />
</li>
<li>Häufig auch “listenweiser Fallausschluss” genannt<br />
</li>
</ul></li>
<li>Lokal: <code>na.rm = TRUE</code>
<ul>
<li>Das Argument <code>na.rm</code> ist in vielen Funktionen für univariate Statistiken enthalten<br />
</li>
<li>Per Voreinstellung wird <code>NA</code> als Ergebnis produziert, wenn fehlende Werte vorliegen<br />
</li>
<li>Fehlende Werte werden nur für diese eine Analyse ausgeschlossen, wenn sie auf der darin untersuchten Variable keinen Wert haben - Datensatz bleibt erhalten</li>
</ul></li>
</ul>
<hr />
</div>
<div id="deskriptivstatistische-kennwerte-ab-ordinalskalenniveau" class="section level2">
<h2>Deskriptivstatistische Kennwerte ab Ordinalskalenniveau</h2>
<p><strong>Median für ordinalskalierte Variablen</strong></p>
<pre class="r"><code>median(fb21$prok4)                 # Ohne Argument für NA: funktioniert nicht</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code>median(fb21$prok4, na.rm = TRUE)   # Expliziter Ausschluss: funktioniert</code></pre>
<pre><code>## [1] 2</code></pre>
<p>Der Median für die Variable <code>prok4</code> beträgt also 2.</p>
<p><strong>Quantile und IQB</strong></p>
<p>Für eine Beschreibung der Dispersion wird häufig der Interquartilsbereich (IQB) genutzt. IQB ist der Bereich zwischen dem 1. und dem 3. Quartil. Auch dafür gibt es keine Funktion in <code>R</code>, das Dispersionsmaß kann aber einfach “per Hand” selbst berechnet werden:</p>
<p><span class="math display">\[IQB = Q_3 - Q_1\]</span></p>
<p>Um die Quartile oder jedes beliebige andere Quantil einer Verteilung zu erhalten, kann die Funktion <code>quantile()</code> verwendet werden:</p>
<pre class="r"><code>quantile(fb21$prok4,
         c(.25, .5, .75),                   # Quartile anfordern
         na.rm = T)</code></pre>
<pre><code>## 25% 50% 75% 
##   2   2   3</code></pre>
<p>Zur Berechnung des IQB wird nun die Differenz aus drittem und erstem Quartil gebildet:</p>
<pre class="r"><code>quantile(fb21$prok4, .75, na.rm=T) - quantile(fb21$prok4, .25, na.rm=T)</code></pre>
<pre><code>## 75% 
##   1</code></pre>
<p>Der IQB der Variable <code>prok4</code> beträgt 1.</p>
<hr />
</div>
<div id="boxplots" class="section level2">
<h2>Boxplots</h2>
<p>Eine geeignete grafische Darstellungsform für (mindestens) ordinalskalierte Daten ist der Boxplot. Er kann über die Funktion <code>boxplot()</code> angefordert werden:</p>
<pre class="r"><code>boxplot(fb21$prok4)</code></pre>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Zur Erinnerung:</p>
<ul>
<li>Box: Quartile</li>
<li>Schwarzer Balken: Median</li>
<li>Whisker: der jeweils extremste empirische Wert im Bereich <code>Q3 + 1.5*IQB</code> für das Maximum bzw. <code>Q1 - 1.5*IQB</code> für das Minimum<br />
</li>
<li>Noch extremere Werte werden als Punkte dargestellt</li>
</ul>
<p>In diesem Beispiel betragen Median und Q3 jeweils 2, sodass sich die entsprechenden Linien überlagern. Ein Beispiel für einen “schöneren” Boxplot (ohne Überlagerung) ist dieses:</p>
<pre class="r"><code>boxplot(fb21$nr6)</code></pre>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Auch ein Boxplot kann grafisch angepasst werden. Nachfolgend sehen Sie ein Beispiel, in dem möglichst viel verändert wurde, um die verschiedenen Möglichkeiten aufzuzeigen. Nicht alle Veränderungen sind unbedingt sinnvoll.</p>
<pre class="r"><code>boxplot(fb21$nr6,
        horizontal = TRUE,
        main = &quot;WS 2021/2022: Item nr6&quot;,
        xlab = &quot;Ausprägung&quot;,
        las = 1,
        width = 2,
        border = &quot;red&quot;,
        col = &quot;pink1&quot;)</code></pre>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p><img src="/post/2021-09-21-deskriptivstatistik-fuer-nominal-und-ordinalskalen_files/figure-html/unnamed-chunk-30-1.png" width="672" style="display: block; margin: auto;" /></p>
<hr />
</div>
