---
title: Tests für unabhängige Stichproben - Lösungen
date: '2020-12-17'
slug: gruppenvergleiche-unabhaengig-loesungen
categories:
  - BSc2
tags:
  - t-Test
subtitle: ''
summary: ''
authors: [koehler, buchholz]
lastmod: '2020-12-17T13:15:14+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
expiryDate: '2022-09-15'
publishDate: '2021-12-10'
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p><strong>Daten einlesen</strong></p>
<pre class="r"><code>setwd(&quot;...&quot;)  
load(&quot;fb20.rda&quot;)</code></pre>
<p><strong>Daten aufbereiten</strong></p>
<pre class="r"><code># Lieblingsfach als Faktor - falls es noch keiner war
if(is.factor(fb20$fach) == FALSE){
  fb20$fach &lt;- factor(fb20$fach, 
                      levels = 1:5,
                      labels = c(&#39;Allgemeine&#39;, &#39;Biologische&#39;, &#39;Entwicklung&#39;,
                                 &#39;Klinische&#39;, &#39;Diag./Meth.&#39;))
}

# Wohnort als Faktor - falls es noch keiner war
if(is.factor(fb20$ort) == FALSE){
  fb20$ort &lt;- factor(fb20$ort, 
                     levels = c(1, 2),
                     labels = c(&#39;Frankfurt&#39;, &#39;anderer&#39;))
}

# Geschlecht als Faktor - falls es noch keiner war
if(is.factor(fb20$geschl)==FALSE){
  fb20$geschl &lt;- factor(fb20$geschl, 
                        levels=c(1,2,3), 
                        labels=c(&#39;weiblich&#39;, &#39;maennlich&#39;, &#39;anderes&#39;))
}</code></pre>
<hr />
<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<p>Unterscheiden sich Studierende, die sich für Allgemeine Psychologie (Variable “fach”) interessieren, im Persönlichkeitsmerkmal Intellekt (auch: Offenheit für neue Erfahrungen, “intell”) von Studierenden, die sich für Klinische Psychologie interessieren? Normalverteilung des Merkmals in der Population darf angenommen werden.</p>
<details>
<summary>
Lösung
</summary>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: grafisch</strong></p>
<pre class="r"><code>data1 &lt;- fb20[ (which(fb20$fach==&quot;Allgemeine&quot;|fb20$fach==&quot;Klinische&quot;)), ]
data1$fach &lt;- droplevels(data1$fach)
boxplot(data1$intel ~ data1$fach,
        xlab=&quot;Interessenfach&quot;, ylab=&quot;Intellekt&quot;, 
        las=1, cex.lab=1.5, 
        main=&quot;Interessenfach und Intellekt&quot;)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: statistisch</strong></p>
<pre class="r"><code># Überblick

library(psych)
describeBy(data1$intel, data1$fach)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: Allgemeine
##    vars  n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 23 3.72 0.39   3.75    3.72 0.37   3 4.5   1.5    0    -0.72 0.08
## ------------------------------------------------------------ 
## group: Klinische
##    vars  n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 28  3.6 0.66   3.75    3.57 0.56 2.5   5   2.5 0.29    -0.37 0.12</code></pre>
<pre class="r"><code># Berechnung der empirischen Standardabweichung

intel.A &lt;- data1$intel[(data1$fach==&quot;Allgemeine&quot;)]
sigma.A &lt;- sd(intel.A)
n.A &lt;- length(intel.A[!is.na(intel.A)])
sd.A &lt;- sigma.A * sqrt((n.A-1) / n.A)
sd.A </code></pre>
<pre><code>## [1] 0.3780984</code></pre>
<pre class="r"><code>intel.B &lt;- data1$intel[(data1$fach==&quot;Klinische&quot;)]
sigma.B &lt;- sd(intel.B)
n.B &lt;- length(intel.B[!is.na(intel.B)])
sd.B &lt;- sigma.B * sqrt((n.B-1) / n.B)
sd.B</code></pre>
<pre><code>## [1] 0.6455178</code></pre>
<p>Mittelwert der Allgemeinen Psychologen (<em>M</em> = 3.72, <em>SD</em> = 0.38) unterscheidet sich deskriptivstatistisch vom Mittelwert der Klinischen (<em>M</em> = 3.6, <em>SD</em> = 0.65).</p>
<p><strong>Voraussetzungsprüfung: Normalverteilung</strong></p>
<pre class="r"><code>par(mfrow=c(1,2))
intel.A &lt;- data1[which(data1$fach==&quot;Allgemeine&quot;), &quot;intel&quot;]
hist(intel.A, xlim=c(1,6), main=&quot;Intellekt (Allgemeine Psy.)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, prob=T)
curve(dnorm(x, mean=mean(intel.A, na.rm=T), sd=sd(intel.A, na.rm=T)), col=&quot;blue&quot;, lwd=2, add=T)
qqnorm(intel.A)
qqline(intel.A, col=&quot;blue&quot;)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p><span class="math inline">\(\rightarrow\)</span> Entscheidung: Normalverteilung wird für Gruppe 1 (Allgemeine Psycholgie) angenommen</p>
<pre class="r"><code>par(mfrow=c(1,2))
intel.B &lt;- data1[which(data1$fach==&quot;Klinische&quot;), &quot;intel&quot;]
hist(intel.B, xlim=c(1,6), main=&quot;Intellekt (Klinische Psy.)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, prob=T)
curve(dnorm(x, mean=mean(intel.B, na.rm=T), sd=sd(intel.B, na.rm=T)), col=&quot;blue&quot;, lwd=2, add=T)
qqnorm(intel.B)
qqline(intel.B, col=&quot;blue&quot;)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p><span class="math inline">\(\rightarrow\)</span> Entscheidung: Normalverteilung wird für Gruppe 2 (Klinische Psycholgie) nicht angenommen</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Unterschiedshypothese<br />
</li>
<li>Richtung des Effekts: Ungerichtet <span class="math inline">\(\rightarrow\)</span> ungerichtete Hypothesen<br />
</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypthesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{Allgemeine} = \mu_{Klinische}\)</span></li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_{Allgemeine} \ne \mu_{Klinische}\)</span></li>
</ul>
<p><strong>Spezifikation des Signifikanzniveaus</strong></p>
<p><span class="math inline">\(\alpha = .05\)</span></p>
<p><strong>Durchführung des Wilcoxon-Tests</strong></p>
<pre class="r"><code>wilcox.test(data1$intel ~ data1$fach,  # abhängige Variable ~ unabhängige Variable
       paired = F,                     # Stichproben sind unabhängig 
       alternative = &quot;two.sided&quot;,      # zweiseitige Testung 
       conf.level = .95)               # alpha = .05 </code></pre>
<pre><code>## Warning in wilcox.test.default(x = c(4, 3.5, 4, 3.5, 3.5, 4.25, 4, 3.75, :
## cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  data1$intel by data1$fach
## W = 370, p-value = 0.362
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p><strong>Formales Berichten des Ergebnisses</strong></p>
Es wurde untersucht, ob sich Studierende, die sich für Allgemeine Psychologie interessieren, im Persönlichkeitsmerkmal Intellekt (auch: Offenheit für neue Erfahrungen) von Studierenden, die sich für Klinische Psychologie interessieren, unterscheiden. Deskriptiv liegt ein solcher Unterschied vor: Die Mittelwerte betragen 3.72 (Allgemeine, <em>SD</em> = 0.38) und 3.60 (Klinische, <em>SD</em> = 0.65). Der entsprechende Wilcoxon-Test zeigt jedoch ein nicht signifikantes Ergebnis (<em>W</em> = 370, <em>p</em> = .362).
</details>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<p>Sind Studierende, die außerhalb von Frankfurt wohnen (“ort”), zufriedener im Leben (“lz”) als diejenigen, die innerhalb von Frankfurt wohnen?</p>
<details>
<summary>
Lösung
</summary>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: grafisch</strong></p>
<pre class="r"><code>boxplot(fb20$lz ~ fb20$ort,
        xlab=&quot;Wohnort&quot;, ylab=&quot;Lebenszufriedenheit&quot;, 
        las=1, cex.lab=1.5, 
        main=&quot;Wohnort und Lebenszufriedenheit&quot;)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: statistisch</strong></p>
<pre class="r"><code>library(psych)
describeBy(fb20$lz, fb20$ort)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: Frankfurt
##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 40 5.05 1.13    5.4    5.14 0.89 2.4   7   4.6 -0.65    -0.09 0.18
## ------------------------------------------------------------ 
## group: anderer
##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 48 5.17 1.13    5.3     5.2 1.04 2.8   7   4.2 -0.29    -0.98 0.16</code></pre>
<pre class="r"><code>summary(fb20[which(fb20$ort==&quot;Frankfurt&quot;), &quot;lz&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    2.40    4.35    5.40    5.05    5.65    7.00       1</code></pre>
<pre class="r"><code>summary(fb20[which(fb20$ort==&quot;anderer&quot;), &quot;lz&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   2.800   4.400   5.300   5.167   6.000   7.000       1</code></pre>
<p>Mittelwert der Nicht-Frankfurter ist deskriptiv höher als der der Frankfurter.</p>
<p><strong>Voraussetzungsprüfung: Normalverteilung</strong></p>
<pre class="r"><code>par(mfrow=c(1,2))
lz.F &lt;- fb20[which(fb20$ort==&quot;Frankfurt&quot;), &quot;lz&quot;]
hist(lz.F, xlim=c(1,9), main=&quot;Lebenzufriedenheit\n(Frankfurter)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, prob=T)
curve(dnorm(x, mean=mean(lz.F, na.rm=T), sd=sd(lz.F, na.rm=T)), col=&quot;red&quot;, lwd=2, add=T)
qqnorm(lz.F)
qqline(lz.F, col=&quot;red&quot;)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><span class="math inline">\(\rightarrow\)</span> Entscheidung: Normalverteilung wird angenommmen</p>
<pre class="r"><code>par(mfrow=c(1,2))
lz.a &lt;- fb20[which(fb20$ort==&quot;anderer&quot;), &quot;lz&quot;]
hist(lz.a, xlim=c(1,9), main=&quot;Lebenszufriedenheit\n(Nicht-Frankfurter)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, prob=T)
curve(dnorm(x, mean=mean(lz.a, na.rm=T), sd=sd(lz.a, na.rm=T)), col=&quot;red&quot;, lwd=2, add=T)
qqnorm(lz.a)
qqline(lz.a, col=&quot;red&quot;)</code></pre>
<p><img src="/post/2021-09-20-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><span class="math inline">\(\rightarrow\)</span> Entscheidung: Normalverteilung wird angenommmen</p>
<p><strong>Voraussetzungsprüfung: Varianzhomogenität</strong></p>
<pre class="r"><code>library(car)
leveneTest(fb20$lz ~ fb20$ort)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.4317 0.5129
##       86</code></pre>
<p><em>F</em>(1,86) = 0.43, <em>p</em> = .513 <span class="math inline">\(\rightarrow\)</span> Das Ergebnis ist nicht signifikant, die <span class="math inline">\(H_0\)</span> wird beibehalten und Varianzhomogenität angenommen.</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Unterschiedshypothese<br />
</li>
<li>Richtung des Effekts: Gerichtet <span class="math inline">\(\rightarrow\)</span> gerichtete Hypothesen<br />
</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypthesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\eta_{Frankfurter} \ge \eta_{nicht-Frankfurter}\)</span><br />
</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\eta_{Frankfurter} &lt; \eta_{nicht-Frankfurter}\)</span></li>
</ul>
<p><strong>Spezifikation des Signifikanzniveaus</strong></p>
<p><span class="math inline">\(\alpha = .05\)</span></p>
<p><strong>Durchführung des <em>t</em>-Tests</strong></p>
<pre class="r"><code>levels(fb20$ort)</code></pre>
<pre><code>## [1] &quot;Frankfurt&quot; &quot;anderer&quot;</code></pre>
<pre class="r"><code>t.test(fb20$lz ~ fb20$ort,           # abhängige Variable ~ unabhängige Variable
       paired = F,                   # Stichproben sind unabhängig 
       alternative = &quot;less&quot;,         # einseitige Testung: Gruppe1 (Frankfurter) &lt; Gruppe2 (Nicht-Frankfurter) 
       var.equal = T,                # Varianzhomogenität ist gegeben (-&gt; Levene-Test)
       conf.level = .95)             # alpha = .05 </code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  fb20$lz by fb20$ort
## t = -0.48201, df = 86, p-value = 0.3155
## alternative hypothesis: true difference in means between group Frankfurt and group anderer is less than 0
## 95 percent confidence interval:
##       -Inf 0.2857945
## sample estimates:
## mean in group Frankfurt   mean in group anderer 
##                5.050000                5.166667</code></pre>
<p><strong>Formales Berichten des Ergebnisses</strong></p>
<p>Es wurde untersucht, ob außerhalb von Frankfurt wohnende Studierende zufriedener im Leben sind als die in Frankfurt wohnenden. Deskriptiv zeigt sich tatsächlich, dass die Nicht-Frankfurter zufriedener sind (<em>M</em> = 5.17, <em>SD</em> = 1.13) als die Frankfurter (<em>M</em> = 5.05, <em>SD</em> = 1.13). Der <em>t</em>-Test zeigt jedoch ein nicht signifikantes Ergebnis (<em>t</em>(<em>df</em> = 86, eins.) = -.48, <em>p</em> = .316). Die Nullhypothese konnte nicht verworfen werden und wird beibehalten. Die Studierenden sind gleich zufrieden, unabhängig von deren Wohnort.</p>
</details>
</div>
<div id="aufgabe-3" class="section level2">
<h2>Aufgabe 3</h2>
<p>Ist die Wahrscheinlichkeit dafür, innerhalb von Frankfurt zu wohnen, die gleiche für weibliche wie für männliche Erstsemester-Studierende der Psychologie?</p>
<details>
<summary>
Lösung
</summary>
<p>Beide Variablen sind nominalskaliert <span class="math inline">\(\rightarrow \chi^2\)</span>-Test</p>
<p><strong>Voraussetungen</strong></p>
<ol style="list-style-type: decimal">
<li>Die einzelnen Beobachtungen sind voneinander unabhängig <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Jede Person lässt sich eindeutig einer Kategorie bzw. Merkmalskombination zuordnen <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Zellbesetzung für alle <span class="math inline">\(n_{ij}\)</span> &gt; 5 <span class="math inline">\(\rightarrow\)</span> Prüfung anhand von Häufigkeitstabelle</li>
</ol>
<pre class="r"><code>fb20$geschlecht &lt;- fb20$geschl[fb20$geschl==&quot;weiblich&quot;|fb20$geschl==&quot;maennlich&quot;]
fb20$geschlecht &lt;- droplevels(fb20$geschlecht)
tab &lt;- table(fb20$geschlecht, fb20$ort)
tab</code></pre>
<pre><code>##            
##             Frankfurt anderer
##   weiblich         33      37
##   maennlich         8      12</code></pre>
<p><span class="math inline">\(\rightarrow n_{ij}\)</span> &gt; 5 in allen Zellen gegeben</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Zusammenhangshypothese</li>
<li>Richtung des Effekts: Ungerichtet</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hyothesenpaar (inhaltlich):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Weibliche und männliche Studierende der Psychologie wohnen mit gleicher Wahrscheinlichkeit innerhalb bzw. außerhalb von Frankfurt.<br />
</li>
<li><span class="math inline">\(H_1\)</span>: Weibliche und männliche Studierende der Psychologie unterscheiden sich in der Wahrscheinlichkeit, innerhalb bzw. außerhalb von Frankfurt zu wohnen.</li>
</ul>
<p>Hypothesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\pi_{ij} = \pi_{i\bullet} \cdot \pi_{\bullet j}\)</span><br />
</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\pi_{ij} \neq \pi_{i\bullet} \cdot \pi_{\bullet j}\)</span></li>
</ul>
<p><strong>Durchführung des <span class="math inline">\(\chi^2\)</span>-Test in R</strong></p>
<pre class="r"><code>chisq.test(tab, correct=FALSE)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tab
## X-squared = 0.31999, df = 1, p-value = 0.5716</code></pre>
<p><span class="math inline">\(\chi^2 = 0.320, df = 1, p = .572 \rightarrow H_0\)</span></p>
<p><strong>Effektstärke Phi (<span class="math inline">\(\phi\)</span>)</strong></p>
<pre class="r"><code>library(psych)
phi(tab)</code></pre>
<pre><code>## [1] 0.06</code></pre>
<p><strong>Ergebnisinterpretation</strong></p>
<p>Es wurde untersucht, ob sich männliche und weibliche Studierende in ihrem Wohnort (Frankfurt vs. außerhalb) unterscheiden. Zur Beantwortung der Fragestellung wurde ein Vierfelder-Chi-Quadrat-Test für unabhängige Stichproben berechnet. Der Zusammenhang zwischen Wohnort und Geschlecht ist nicht signifikant (<span class="math inline">\(\chi^2(1) = 0.320, p = .572\)</span>), somit wird die Nullhypothese beibehalten. Der Effekt ist von vernachlässigbarer Stärke (<span class="math inline">\(\phi = .06\)</span>). Männliche und weibliche Studierende wohnen also mit gleicher Wahrscheinlichkeit in Frankfurt bzw. außerhalb von Frankfurt.</p>
</details>
</div>
