---
title: Korrelation
author: 
date: '2021-01-04'
slug: korrelation
categories:
  - BSc2
tags:
  - Korrelation
subtitle: ''
summary: ''
authors: [nehler, winkler, schroeder]
lastmod: '2021-01-04T13:13:57+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<details>
<summary>
Kernfragen dieser Lehreinheit
</summary>
<ul>
<li>Wie können Kreuztabellen in R erstellt werden? Welche Varianten gibt es, relative Häufigkeitstabellen zu erstellen?</li>
<li>Wie kann ein gemeinsames Balkendiagramm für zwei Variablen erstellt werden?</li>
<li>Welche zwei Varianten gibt es, Varianzen und Kovarianzen zu bestimmen?</li>
<li>Wie kann die Produkt-Moment-Korrelation, die Rang-Korrelation nach Spearman und Kendalls <span class="math inline">\(\tau\)</span> bestimmt werden?</li>
<li>Wie wird bei der Berechnung von Korrelationen mit fehlenden Werten umgegangen?</li>
</ul>
</details>
<hr />
<div id="datensatz-laden" class="section level2">
<h2>Datensatz laden</h2>
<p>Zu Beginn laden wir wie gewohnt den Datensatz (Sie können den Datensatz <a href="/post/fb20.rda">hier <i class="fas fa-download"></i> herunterladen</a>) und erstellen, falls nötig, Labels und Skalenwerte.</p>
<pre><code>## Error in setwd(&quot;C:/Users/Nutzer/Documents/Lehre/Statistik&quot;): kann Arbeitsverzeichnis nicht wechseln</code></pre>
<pre class="r"><code>setwd(...) #auf Pfad mit Datensatz</code></pre>
<pre class="r"><code>load(&quot;fb20.rda&quot;)

#Labels
fb20$fach &lt;- factor(fb20$fach, levels = 1:5, labels = c (&#39;Allgemeine&#39;, &#39;Biologische&#39;, &#39;Entwicklung&#39;, &#39;Klinische&#39;, &#39;Diag./Meth.&#39;))
fb20$ziel &lt;- factor(fb20$ziel, levels = 1:4, labels = c (&#39;Wirtschaft&#39;, &#39;Therapie&#39;, &#39;Forschung&#39;, &#39;Andere&#39;))

#Rekodierung
fb20$mdbf4_r &lt;- -1 * (fb20$mdbf4 - 6)
fb20$mdbf11_r &lt;- -1 * (fb20$mdbf11 - 6)
fb20$mdbf5_r &lt;- -1 * (fb20$mdbf5 - 6)
fb20$mdbf7_r &lt;- -1 * (fb20$mdbf7 - 6)
fb20$mdbf3_r &lt;- -1 * (fb20$mdbf3 - 6)
fb20$mdbf9_r &lt;- -1 * (fb20$mdbf5 - 9)

#Skalenwerte
gut &lt;- fb20[,c(&#39;mdbf1&#39;,&#39;mdbf4_r&#39;,&#39;mdbf8&#39;,&#39;mdbf11_r&#39;)]
fb20$gs &lt;- rowMeans(gut)
wach &lt;- fb20[,c(&#39;mdbf2&#39;,&#39;mdbf5_r&#39;,&#39;mdbf7_r&#39;,&#39;mdbf10&#39;)]
fb20$wm &lt;- rowMeans(wach)
ruhig &lt;- fb20[,c(&#39;mdbf3_r&#39;,&#39;mdbf6&#39;,&#39;mdbf9_r&#39;,&#39;mdbf12&#39;)]
fb20$ru &lt;- rowMeans(ruhig)</code></pre>
<hr />
</div>
<div id="häufigkeitstabellen" class="section level2">
<h2>Häufigkeitstabellen</h2>
<p>Die Erstellung von <em>Häufigkeitstabellen</em> zur Darstellung univariater Häufigkeiten haben Sie schon kennengelernt. Dies funktioniert mit einfachen Befehlen für die Häufigkeiten und die zugehörigen relativen Prozentzahlen.</p>
<pre class="r"><code>tab&lt;-table(fb20$fach)                 #Absolut
tab</code></pre>
<pre><code>## 
##  Allgemeine Biologische Entwicklung   Klinische Diag./Meth. 
##          23          13          23          28           6</code></pre>
<pre class="r"><code>prop.table(tab)                       #Relativ</code></pre>
<pre><code>## 
##  Allgemeine Biologische Entwicklung   Klinische Diag./Meth. 
##  0.24731183  0.13978495  0.24731183  0.30107527  0.06451613</code></pre>
<p>Die Erweiterung für den bivariaten Fall ist dabei nicht schwierig und wird als <em>Kreuztabelle</em> bezeichnet. Sie liefert die Häufigkeit von Kombinationen von Ausprägungen in mehreren Variablen. In den Zeilen wird eine Variable abgetragen und in den Spalten die zweite. Im Unterschied zum univariaten Fall muss im <code>table()</code> Befehl nur die zweite interessierende Variable zusätzlich genannt werden. Tabellen können beliebig viele Dimensionen haben, werden dann aber sehr unübersichtlich.</p>
<pre class="r"><code>tab&lt;-table(fb20$fach,fb20$ziel)       #Kreuztabelle
tab</code></pre>
<pre><code>##              
##               Wirtschaft Therapie Forschung Andere
##   Allgemeine           9        4         5      5
##   Biologische          1        3         8      1
##   Entwicklung          4        6        10      3
##   Klinische            0       22         4      2
##   Diag./Meth.          2        2         2      0</code></pre>
<p>In eine Kreuztabelle können Randsummen mit dem <code>addmargins()</code> Befehl hinzugefügt werden. Randsummen erzeugen in der letzten Spalte bzw. Zeile die univariaten Häufigkeitstabellen der Variablen.</p>
<pre class="r"><code>addmargins(tab)                       #Randsummen hinzufügen</code></pre>
<pre><code>##              
##               Wirtschaft Therapie Forschung Andere Sum
##   Allgemeine           9        4         5      5  23
##   Biologische          1        3         8      1  13
##   Entwicklung          4        6        10      3  23
##   Klinische            0       22         4      2  28
##   Diag./Meth.          2        2         2      0   6
##   Sum                 16       37        29     11  93</code></pre>
<p>Auch für die Kreuztabelle ist die Möglichkeit der Darstellung der Häufigkeiten in Relation zur Gesamtzahl der Beobachtungen gegeben.</p>
<pre class="r"><code>prop.table(tab)                       #Relative Häufigkeiten</code></pre>
<pre><code>##              
##               Wirtschaft   Therapie  Forschung     Andere
##   Allgemeine  0.09677419 0.04301075 0.05376344 0.05376344
##   Biologische 0.01075269 0.03225806 0.08602151 0.01075269
##   Entwicklung 0.04301075 0.06451613 0.10752688 0.03225806
##   Klinische   0.00000000 0.23655914 0.04301075 0.02150538
##   Diag./Meth. 0.02150538 0.02150538 0.02150538 0.00000000</code></pre>
<p>22 von insgesamt 93 (23.66%) wollen therapeutisch arbeiten <em>und</em> interessieren sich bisher am meisten für die klinische Psychologie.</p>
<p><code>prob.table()</code> kann allerdings nicht nur an der Gesamtzahl relativiert werden, sondern auch an der jeweiligen Zeilen- oder Spaltensumme. Dafür gibt man im Argument <code>margin</code> für Zeilen <code>1</code> oder für Spalten <code>2</code> an.</p>
<pre class="r"><code>prop.table(tab, margin = 1)           #relativiert an Zeilen</code></pre>
<pre><code>##              
##               Wirtschaft   Therapie  Forschung     Andere
##   Allgemeine  0.39130435 0.17391304 0.21739130 0.21739130
##   Biologische 0.07692308 0.23076923 0.61538462 0.07692308
##   Entwicklung 0.17391304 0.26086957 0.43478261 0.13043478
##   Klinische   0.00000000 0.78571429 0.14285714 0.07142857
##   Diag./Meth. 0.33333333 0.33333333 0.33333333 0.00000000</code></pre>
<p>Von 28 Personen, die sich am meisten für klinische Psychologie interessieren, wollen 78.57% (nämlich 22 Personen) später therapeutisch arbeiten.</p>
<pre class="r"><code>prop.table(tab, margin = 2)           #relativiert an Spalten</code></pre>
<pre><code>##              
##               Wirtschaft   Therapie  Forschung     Andere
##   Allgemeine  0.56250000 0.10810811 0.17241379 0.45454545
##   Biologische 0.06250000 0.08108108 0.27586207 0.09090909
##   Entwicklung 0.25000000 0.16216216 0.34482759 0.27272727
##   Klinische   0.00000000 0.59459459 0.13793103 0.18181818
##   Diag./Meth. 0.12500000 0.05405405 0.06896552 0.00000000</code></pre>
<p>Von 37 Personen, die später therapeutisch arbeiten wollen, interessieren sich 59.46% (nämlich 22 Personen) für die klinische Psychologie.</p>
<p><code>addmargins()</code>und <code>prop.table()</code> können beliebig kombiniert werden.
<code>prop.table(addmargins(tab))</code> behandelt die Randsummen als eigene Kategorie (inhaltlich meist unsinnig!).
<code>addmargins(prop.table(tab))</code> liefert die Randsummen der relativen Häufigkeiten.</p>
<pre class="r"><code>addmargins(prop.table(tab))</code></pre>
<pre><code>##              
##               Wirtschaft   Therapie  Forschung     Andere        Sum
##   Allgemeine  0.09677419 0.04301075 0.05376344 0.05376344 0.24731183
##   Biologische 0.01075269 0.03225806 0.08602151 0.01075269 0.13978495
##   Entwicklung 0.04301075 0.06451613 0.10752688 0.03225806 0.24731183
##   Klinische   0.00000000 0.23655914 0.04301075 0.02150538 0.30107527
##   Diag./Meth. 0.02150538 0.02150538 0.02150538 0.00000000 0.06451613
##   Sum         0.17204301 0.39784946 0.31182796 0.11827957 1.00000000</code></pre>
<hr />
</div>
<div id="balkendiagramme" class="section level2">
<h2>Balkendiagramme</h2>
<p>Grafisch kann eine solche Kreuztabelle durch gruppierte Balkendiagramme dargestellt werden. Das Argument <code>beside</code> sorgt für die Anordnung der Balken (bei <code>TRUE</code> nebeneinander, bei <code>FALSE</code> übereinander). Das Argument <code>legend</code> nimmt einen Vektor für die Beschriftung entgegen. Die Reihen des Datensatzes bilden dabei stets eigene Balken, während die Spalten die Gruppierungsvariable bilden. Deshalb müssen als Legende die Namen der Reihen <code>rownames()</code> unserer Tabelle <code>tab</code> ausgewählt werden.</p>
<pre class="r"><code>barplot (tab,
         beside = TRUE,
         col = c(&#39;mintcream&#39;,&#39;olivedrab&#39;,&#39;peachpuff&#39;,&#39;steelblue&#39;,&#39;maroon&#39;),
         legend = rownames(tab))</code></pre>
<p><img src="/post/2021-09-20-korrelation_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<hr />
</div>
<div id="varianz-kovarianz-und-korrelation" class="section level2">
<h2>Varianz, Kovarianz und Korrelation</h2>
<p>In der Vorlesungen haben Sie gelernt, dass es für <em>Kovarianzen</em> und <em>Varianzen</em> empirische und geschätzte Werte gibt. R berechnet standardmäßig für die Varianz und Kovarianz die <em>Populationsschätzer</em>, verwendet also folgende Formeln für Varianz</p>
<p><span class="math display">\[\hat{\sigma}^2_{X} = \frac{\sum_{m=1}^n (y_m - \bar{y})^2}{n-1}\]</span></p>
<p>und Kovarianz.</p>
<p><span class="math display">\[\hat{\sigma}_{XY} = \frac{\sum_{m=1}^n (x_m - \bar{x}) \cdot (y_m - \bar{y})}{n-1}\]</span></p>
<p>Die Funktionen für die Varianz ist dabei <code>var()</code>. Im Folgenden wird diese für die Variablen <code>gs</code> (Gut vs. Schlecht) und <code>gewis</code> (Gewissenhaftigkeit) aus dem Datensatz bestimmt. Als Argumente müssen jeweils die Variablennamen verwendet werden.</p>
<pre class="r"><code>var(fb20$lz)                            #Varianz Lebenszufriedenheit</code></pre>
<pre><code>## [1] NA</code></pre>
<p>Wie bereits in vergangenen Sitzungen gesehen führen fehlende Werte zu der Ausgabe <code>NA</code>. Um dies zu beheben, wird im univariaten Fall <code>na.rm = TRUE</code> zum Ausschluss verwendet.</p>
<pre class="r"><code>var(fb20$gs, na.rm = TRUE)               #Varianz Gut vs. Schlecht</code></pre>
<pre><code>## [1] 0.5708813</code></pre>
<pre class="r"><code>var(fb20$gewis, na.rm = TRUE)            #Varianz Gewissenhaftigkeit</code></pre>
<pre><code>## [1] 0.4195837</code></pre>
<p>Die Funktion <code>cov()</code> wird für die Kovarianz verwendet und benötigt als Argumente die Variablen.</p>
<pre class="r"><code>cov(fb20$gs, fb20$gewis)                #Kovarianz Gut vs. Schlecht und Gewissenhaftigkeit</code></pre>
<pre><code>## [1] NA</code></pre>
<p>Natürlich haben auch bei der Kovarianzberechnung fehlende Werte einen Einfluss. Zur Bewältigung des Problems gibt es das Argument <code>use</code>. Bei Zusammenhangsmaßen gibt es in R mehrere Möglichkeiten für den Umgang mit fehlenden Werten, die sich nur unterscheiden, wenn mehr als zwei Variablen korreliert werden:</p>
<ul>
<li><em>Paarweiser Fallausschluss</em>: Personen, die auf (mindestens) einer von zwei Variablen <code>NA</code> haben, werden von der Berechnung ausgeschlossen.</li>
<li><em>Listenweiser Fallausschluss</em>: Personen, die auf (mindestens) einer von allen Variablen <code>NA</code> haben, werden von der Berechnung ausgeschlossen.</li>
<li><em>na.or.complete</em>: Zeilen, die einen fehlenden Wert (NA) enthalten, werden bei den Berechnungen ignoriert. Das entspricht der Angabe von na.rm = TRUE.</li>
</ul>
<p>Am besten lässt sich der Unterschied in einer <em>Kovarianzmatrix</em> veranschaulichen. Hier werden alle Varianzen und Kovarianzen von einer Menge an Variablen berechnet und in einer Tabelle darstellt. Dafür muss ein Datensatz erstellt werden, der nur die interessierenden Variablen enthält. Zu unseren beiden Variablen nehmen wir als drittes noch die Lebenszufriedenheit (<code>lz</code>) auf.</p>
<pre class="r"><code>drei &lt;- fb20[, c(&#39;gs&#39;,&#39;lz&#39;,&#39;gewis&#39;)]         #Datensatzreduktion
cov(drei)                                    #Kovarianzmatrix</code></pre>
<pre><code>##       gs lz     gewis
## gs    NA NA        NA
## lz    NA NA        NA
## gewis NA NA 0.4195837</code></pre>
<p>Da die fehlenden Werte nicht entfernt wurden, gibt R kein Ergebnis aus.
Nun folgt die Gegenüberstellung der beiden betrachteten Möglichkeiten zum Ausschluss.</p>
<pre class="r"><code>cov(drei, use = &#39;pairwise&#39;)             #Paarweiser Fallausschluss</code></pre>
<pre><code>##              gs        lz     gewis
## gs    0.5708813 0.4592885 0.1401384
## lz    0.4592885 1.3153640 0.1981305
## gewis 0.1401384 0.1981305 0.4195837</code></pre>
<pre class="r"><code>cov(drei, use = &#39;complete&#39;)             #Listenweiser Fallausschluss</code></pre>
<pre><code>##              gs        lz     gewis
## gs    0.5547644 0.4592885 0.1533116
## lz    0.4592885 1.3179822 0.2038607
## gewis 0.1533116 0.2038607 0.3884194</code></pre>
<p>Wie wir sehen unterscheiden sich die Werte voneinander, da beim listenweisen Fallausschluss noch mehr Personen von Beginn an von der Berechnung ausgeschlossen werden.</p>
<p>Der Zusammenhang zwischen zwei Variablen kann in einem <em>Scatterplot</em> bzw. <em>Streupunktdiagramm</em> dargestellt werden. Dafür kann man die <code>plot()</code> Funktion nutzen. Als Argumente können dabei <code>x</code> für die Variable auf der x-Achse, <code>y</code> für die Variable auf der y-Achse, <code>xlim</code>, <code>ylim</code> für eventuelle Begrenzungen der Achsen und <code>pch</code> für die Punktart angegeben werden.</p>
<pre class="r"><code>plot(x = fb20$gs, y = fb20$gewis)</code></pre>
<p><img src="/post/2021-09-20-korrelation_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Wie in der Vorlesung besprochen sind für verschiedene Skalenniveaus Zusammenhangsmaße verfügbar, die im Gegensatz zur Kovarianz auch eine Vergleichbarkeit zwischen zwei Zusammenhangswerten sicherstellen. Für zwei metrisch skalierte Variablen gibt es dabei die <em>Produkt-Moment-Korrelation</em>. In der Funktion <code>cor()</code> werden dabei die Argumente <code>x</code> und <code>y</code> für die beiden betrachteten Variablen benötigt. <code>use</code> beschreibt weiterhin den Umgang mit fehlenden Werten.</p>
<pre class="r"><code>cor(x = fb20$gs, y = fb20$gewis, use = &#39;pairwise&#39;)</code></pre>
<pre><code>## [1] 0.283576</code></pre>
<p>Bei einer positiven Korrelation gilt „je mehr Variable x… desto mehr Variable y" bzw. umgekehrt, bei einer negativen Korrelation „je mehr Variable x… desto weniger Variable y" bzw. umgekehrt. Korrelationen sind immer ungerichtet, das heißt, sie enthalten keine Information darüber, welche Variable eine andere bedingt - beide Variablen sind gleichberechtigt. Korrelationen und Regressionen liefern keine Hinweise auf Kausalitäten. Sie sagen beide etwas über den Zusammenhang zweier Variablen aus.</p>
<p>In R können wir uns auch eine <em>Korrelationsmatrix</em> ausgeben lassen. Dies geschieht äquivalent zu der Kovarianzmatrix mit dem Datensatz als Argument in der <code>cor()</code> Funktion. In der Diagonale stehen die Korrelationen der Variable mit sich selbst - also 1 - und in den restlichen Feldern die Korrelationen der Variablen untereinander.</p>
<pre class="r"><code>cor(drei, use = &#39;pairwise&#39;)</code></pre>
<pre><code>##              gs        lz     gewis
## gs    1.0000000 0.5371264 0.2835760
## lz    0.5371264 1.0000000 0.2799681
## gewis 0.2835760 0.2799681 1.0000000</code></pre>
<p>Die Stärke des korrelativer Zusammenhangs wird mit dem Korrelationskoeffizienten ausgedrückt, der zwischen -1 und +1 liegt.
Die default Einstellung bei <code>cor()</code>ist die <em>Produkt-Moment-Korrelation</em>, also die Pearson-Korrelation.</p>
<pre class="r"><code>cor(fb20$extra, fb20$lz, use = &quot;na.or.complete&quot;,method = c(&quot;pearson&quot;))</code></pre>
<pre><code>## [1] 0.2154227</code></pre>
<p>Achtung! Die Pearson-Korrelation hat gewisse Voraussetzungen, die vor der Durchführung überprüft werden sollten!</p>
<p><strong>Voraussetzungen Pearson-Korrelation:</strong></p>
<ol style="list-style-type: decimal">
<li>Skalenniveau: intervallskalierte Daten <span class="math inline">\(\rightarrow\)</span> ok (Ratingskalen werden meist als intervallskaliert aufgefasst)<br />
</li>
<li>Linearität: Zusammenhang muss linear sein <span class="math inline">\(\rightarrow\)</span> Grafische Überprüfung (Scatterplot)<br />
</li>
<li>Normalverteilung <span class="math inline">\(\rightarrow\)</span> QQ-Plot, Histogramm oder Shapiro-Wilk-Test</li>
</ol>
<p><strong>zu 3. Normalverteilung</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> QQ-Plot, Histogramm &amp; Shapiro-Wilk-Test</p>
<pre class="r"><code>#QQ
qqnorm(fb20$extra)
qqline(fb20$extra)</code></pre>
<p><img src="/post/2021-09-20-korrelation_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code>qqnorm(fb20$lz)
qqline(fb20$lz)</code></pre>
<p><img src="/post/2021-09-20-korrelation_files/figure-html/unnamed-chunk-21-2.png" width="672" /></p>
<pre class="r"><code>#Histogramm
par(mfrow = c(2,1))   #damit beide Histogrammme in einer Grafik angezeigt werden, siehe Sitzung 12)
hist(fb20$extra, prob = T, ylim = c(0, 1))
curve(dnorm(x, mean = mean(fb20$extra, na.rm = T), sd = sd(fb20$extra, na.rm = T)), col = &quot;blue&quot;, add = T)  
hist(fb20$lz, prob = T, ylim = c(0,1))
curve(dnorm(x, mean = mean(fb20$lz, na.rm = T), sd = sd(fb20$lz, na.rm = T)), col = &quot;blue&quot;, add = T)</code></pre>
<p><img src="/post/2021-09-20-korrelation_files/figure-html/unnamed-chunk-21-3.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1,1))

#Shapiro
shapiro.test(fb20$extra)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb20$extra
## W = 0.97493, p-value = 0.05771</code></pre>
<pre class="r"><code>shapiro.test(fb20$lz)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb20$lz
## W = 0.96784, p-value = 0.01847</code></pre>
<p><span class="math inline">\(p &lt; \alpha\)</span> <span class="math inline">\(\rightarrow\)</span> H1: Normalverteilung kann nicht angenommen werden. Somit ist diese Voraussetzung verletzt. Daher muss die Rangkorrelation nach Spearman genutzt werden. Dies geschieht über <code>method = "spearman"</code>.</p>
<p><strong>Rangkorrelation in R</strong></p>
<pre class="r"><code>r1 &lt;- cor(fb20$extra,fb20$lz,
          method = &quot;spearman&quot;,     #Pearson ist default
          use = &quot;complete.obs&quot;) 

r1</code></pre>
<pre><code>## [1] 0.2346132</code></pre>
<pre class="r"><code>r1^2                               #R^2, Anteil an erklärter Varianz</code></pre>
<pre><code>## [1] 0.05504334</code></pre>
<p><strong>Interpretation des deskriptiven Zusammenhangs:</strong><br />
Es handelt sich um eine positive Korrelation von <em>r</em> = .23. Der Effekt ist nach Cohens (1988) Konvention als schwach zu bewerten. Je höher die Ausprägung in Extraversion, desto höher ist die Ausprägung in der Lebenszufriedenheit.</p>
<p><strong>Exkurs: Cohens (1988) Konvention zur Interpretation von <span class="math inline">\(|r|\)</span>:</strong></p>
<ul>
<li>~ .10: schwacher Effekt<br />
</li>
<li>~ .30: mittlerer Effekt<br />
</li>
<li>~ .50: starker Effekt</li>
</ul>
<p>Als letzte Variante gibt es noch Kendalls <span class="math inline">\(\tau\)</span> als Möglichkeit der “method” bei Korrelationen. Diese kann man mit <code>kendall</code> ansprechen.</p>
<pre class="r"><code>cor(fb20$extra, fb20$lz, use = &#39;pairwise&#39;, method = &#39;kendall&#39;)</code></pre>
<pre><code>## [1] 0.1783819</code></pre>
<p><strong>Signifikanztestung des Korrelationskoeffizienten:</strong>
Nachedem der Korrelationskoeffizient berechnet wurde, muss dieser noch auf Signifikanz geprüft werden.</p>
<ul>
<li>H0: <span class="math inline">\(\rho = 0\)</span> <span class="math inline">\(\rightarrow\)</span> es gibt keinen Zusammenhang zwischen Extraversion und Lebenszufriedenheit</li>
<li>H1: <span class="math inline">\(\rho \neq 0\)</span> <span class="math inline">\(\rightarrow\)</span> es gibt einen Zusammenhang zwischen Extraversion und Lebenszufriedenheit</li>
</ul>
<pre class="r"><code>cor.test(fb20$extra, fb20$lz, 
         alternative = &quot;two.sided&quot;, 
         method = &quot;spearman&quot;,       #Da Voraussetzungen für Pearson verletzt
         use = &quot;complete.obs&quot;)</code></pre>
<pre><code>## Warning in cor.test.default(fb20$extra, fb20$lz, alternative = &quot;two.sided&quot;, :
## Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  fb20$extra and fb20$lz
## S = 112849, p-value = 0.0214
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.2346132</code></pre>
<p><span class="math inline">\(p &lt; \alpha\)</span> <span class="math inline">\(\rightarrow\)</span> H1. Die Korrelation ist mit einer Irrtumswahrscheinlichkeit von 5% signifikant von 0 verschieden. –&gt; Bei der Rangkorrelation kann der exakte p-Wert jedoch nicht berechnet werden. Wenn die Voraussetzungen für die Pearson-Korrelation erfüllt wären, würde das Ganze so aussehen:</p>
<pre class="r"><code>cor.test(fb20$extra, fb20$lz, 
         alternative = &quot;two.sided&quot;, 
         method = &quot;pearson&quot;,       
         use = &quot;complete.obs&quot;)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  fb20$extra and fb20$lz
## t = 2.1388, df = 94, p-value = 0.03504
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.01561103 0.39868959
## sample estimates:
##       cor 
## 0.2154227</code></pre>
<p><strong>Ergebnisinterpretation:</strong>
Es wurde untersucht, ob Extraversion und Lebenszufriedenheit miteinander zusammenhängen. Der Pearson-Korrelationskoeffizient beträgt .22 und ist statistisch signifikant (<em>t</em> = 2.1388, <em>p</em> = .04). Folglich wird die Nullhypothese verworfen: Extraversion und Lebenszufriedenheit weisen einen signifikanten Zusammenhang auf.</p>
</div>
<div id="wie-können-zusammenhangsmaße-für-ordinalskalierte-daten-berechnet-werden" class="section level2">
<h2>Wie können Zusammenhangsmaße für ordinalskalierte Daten berechnet werden?</h2>
<p>Hierfür müssen wir das Paket <code>rococo</code> installieren, das verschiedene Konkordanz-basierte Zusammenhangsmaße enthält. Die Installation muss dem Laden des Paketes logischerweise vorausgestellt sein. Wenn R einmal geschlossen wird, müssen alle Zusatzpakete neu geladen, jedoch nicht neu installiert werden.</p>
<pre class="r"><code>install.packages(&#39;rococo&#39;)          #installieren</code></pre>
<pre class="r"><code>library(rococo)                     #laden</code></pre>
<pre><code>## Warning: Paket &#39;rococo&#39; wurde unter R Version 4.1.1 erstellt</code></pre>
<p>Wir erhalten hier als Message den Hinweis, unter welcher Version das Paket erstellt wurde.
Übersichte über Pakete kann man mit <code>??</code>erhalten.</p>
<pre class="r"><code>??rococo</code></pre>
<p>Dank dem neuen Paket können wir nun den Koeffizienten <span class="math inline">\(\hat{\gamma}\)</span> zum Zusammenhang zwischen Entspannung (<code>mdbf12</code>) und Gut Fühlen (<code>mdbf8</code>) berechnen. Die beiden Variablen wurden ursprünglich auf einer Skala von 1 (<em>überhaupt nicht</em>) bis 5 (<em>sehr</em>) (also auf Ordinalskalenniveau) erfasst.</p>
<pre class="r"><code>rococo(fb20$mdbf12, fb20$mdbf8)</code></pre>
<pre><code>## [1] 0.7339647</code></pre>
<p>Die Funktion heißt hier zufälligerweise genau gleich wie das Paket. Wenn man nur Informationen über die Funktion statt das Paket sucht, geht das anhand von <code>?</code>.</p>
<pre class="r"><code>?rococo</code></pre>
<hr />
</div>
