---
title: Korrelation und Regression - Aufgaben
author: 
date: '2021-01-04'
slug: korrelation-und-regression-aufgaben
categories:
  - BSc2
tags:
  - Korrelation
  - Regression
subtitle: ''
summary: ''
authors: [winkler]
lastmod: '2021-01-04T13:18:56+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Vorbereitung
Laden Sie die Daten aus [<i class="fas fa-download"></i> `fb20.rda`](/post/fb20.rda). 

***
# Korrelation

## Aufgabe 1

In der Befragung am Anfang des Semesters wurde gefragt, ob Sie neben der Uni einen Nebenjob (`job`) ausüben und in welcher Wohnsituation Sie sich befinden (`wohnen`). Erstellen Sie für diese beiden Variablen eine Kreuztabelle mit Randsummen.

  * Stellen Sie zunächst sicher, dass die Variablen als Faktoren vorliegen und die Kategorien beider Variablen korrekt bezeichnet sind. 
  * Wie viele Personen wohnen in einer WG und haben keinen Nebenjob? 
  * Was ist der relative Anteil aller Teilnehmer/innen, die bei ihren Eltern wohnen?
  * Welcher Anteil der Personen, die alleine wohnen, gehen einer Nebentätigkeit nach?

## Aufgabe 2

Erstellen Sie für diese Kombination an Variablen ein gruppiertes Balkendiagramm.

  * Achten Sie darauf, dass die Balken nebeneinander stehen.
  * Nutzen Sie für die Personen mit und ohne Nebenjob unterschiedliche Farben und fügen Sie eine Legende hinzu, die das verdeutlicht.


## Aufgabe 3

Welche der fünf Persönlichkeitsdimensionen Extraversion (`extra`), Verträglichkeit (`vertr`), Gewissenhaftigkeit (`gewis`), Neurotizismus (`neuro`) und Intellekt (`intel`) ist am stärksten mit der Lebenszufriedenheit korreliert (`lz`)?

  * Überprüfen Sie die Voraussetzungen für die Pearson Korrelation.
  * Erstellen Sie für diese Frage eine Korrelationsmatrix, die alle Korrelationen enthält. Verwenden Sie die Funktion `round()` (unter Betrachtung der Hilfe), um die Werte auf zwei Nachkommastellen zu runden und die Tabelle dadurch übersichtlicher darzustellen.
  * Wie würden Sie das Ausmaß dieser Korrelation nach den Richtlinien von Cohen (1988) einschätzen?
  * Ist der Korrelationskoeffizienten von Lebenszufriedenheit und Gewissenhaftigkeit signifikant?


## Aufgabe 4

Das Paket `psych` enthält vielerlei Funktionen, die für die Analyse von Datensätzen aus psychologischer Forschung praktisch sind. Eine von ihnen (`describe()`) erlaubt es, gleichzeitig verschiedene Deskriptivstatistiken für Variablen zu erstellen.

  * Installieren und laden Sie das Paket `psych`.
  * Nutzen Sie den neugewonnen Befehl `describe()`, um sich gleichzeitig die verschiedenen Deskriptivstatistiken für Lebenszufriedenheit (`lz`) ausgeben zu lassen. 
  * `describe()` kann auch genutzt werden, um gleichzeitig Deskriptivstatistiken für verschiedene Variablen zu berechnen. Nutzen Sie diese Funktionalität, um sich gleichzeitg die univariaten Deskriptivstatistiken für die fünf Persönlichkeitsdimensionen ausgeben zu lassen.
    
***
# Regression
    
## Aufgabe 5
Welche der fünf Persönlichkeitsdimensionen Extraversion (`extra`), Verträglichkeit (`vertr`), Gewissenhaftigkeit (`gewis`), Neurotizsimus (`neuro`) und Intellekt (`intel`) zeigt den höchsten linearen Zusammenhang mit der Lebenszufriedenheit (`lz`)?

  * Erstellen Sie für jeden Zusammenhang je ein Streudiagramm. 
  * Schätzen Sie für jeden Zusammenhang je ein Modell. 
  * Prüfen Sie die Voraussetzungen und interpretieren Sie den standardisierten Koeffizienten des linearen Zusammenhangs zwischen Gewissenhaftigkeit und Lebenszufriedenheit. Wie verändert sich `lz`, wenn sich `gewis` um eine Standardabweichung erhöht?

## Aufgabe 6
Ein paar Studierende wurden nachträglich zum Studiengang Psychologie zugelassen und befinden sich daher nicht im Datensatz. Die neuen Studenten wurden nachträglich befragt und weisen auf der Skala Neurotizismus folgende Werte auf: 1.25; 2.75; 3.5; 4.25; 3.75; 2.15. 

  * Machen Sie eine Vorhersage für die Lebenszufriedenheit für die neuen Studenten.
  * Erstellen Sie ein Streu-Punkt-Diagramm  mit Regressionsgerade für den linearen Zusammenhang zwischen Neurotizismus und Lebenszufriedenheit.
  * Wie viel Prozent der Varianz werden durch das Modell erklärt?

***
