---
title: SmartGit
date: '2021-07-21'
slug: smartgit
categories:
  - "gitintro"
tags: []
subtitle: ''
summary: ''
authors: [nehler, rouchi]
featured: no
header:
  image: ""
  caption: ""
projects: []
publishDate: '2021-08-01'
---


Da das Benutzen des Terminals nicht unbedingt praktisch oder auf den ersten Blick einleuchtend ist, wollen wir uns in diesem Kapitel `SmartGit` anschauen, eine benutzerfreundliche und anschaulich aufbereitete Benutzeroberfläche, mit der wir problemlos auf `Git` zugreifen können. Dazu schauen wir uns zunächst an, wie wir mit `SmartGit` arbeiten können.


# SmartGit Setup

Damit ihr `SmartGit` auf euren Rechnern verwenden könnt, müsst ihr zunächst das Programm herunterladen. Dies könnt ihr [hier](https://www.syntevo.com/smartgit/) für verschiedene Betriebssysteme machen. Folgt den Anweisungen eures Computers, bis die Installation von `SmartGit` erfolgreich abgeschlossen ist. 

Sobald ihr `SmartGit` installiert habt und das Programm öffnet, werdet ihr gefragt, ob ihr ein lokales `repository` öffnen oder neu erstellen wollt, oder aber ob ihr ein bereits bestehendes clonen möchtet. Für unser Beispiel mit dem Praktikums-Ordner, den wir bereits im ersten Teil lokal erstellt und im zweiten Teil auf `GitHub` hochgeladen haben, möchten wir dieses bereits bestehende `repository` in unser `SmartGit` laden. Deswegen wählen wir hier die zweite Option.

*Screenshot*

Bei den Einstellungen für `SmartGit` müsst ihr den Nutzungsbedingungen zustimmen und unter `License type` außerdem auswählen, dass ihr das Programm für "Non-commercial use only", also wissenschaftliche Zwecke verwendet, sodass ihr nicht für die Nutzung zahlen müsst.

*Screenshot*

Als nächstes müsst ihr euch unter `User Information` einen Nutzernamen geben sowie eine E-Mail-Adresse angeben, über die ihr euer `SmartGit` konfiguriert. Hier gebt ihr am Besten euren Nutzernamen und die E-Mail-Adresse an, mit denen ihr bereits euer `GitHub`-Profil erstellt habt! 

Jetzt müsst ihr noch die Option
```
Use SmartGit as SSH client
```
auswählen. Einen `Hosting Provider` braucht ihr nicht, diese Seite des Setups könnt ihr einfach überspringen. 
Nach einigen letzten Einverständniserklärungen ist das Setup von `SmartGit` abgeschlossen und ihr könnt das Programm nun mit euren `repositories` verknüpfen!


#### Bereits bestehendes `GitHub`-repository mit `SmartGit` clonen

Um euren auf `GitHub` geladenen Praktikums-Ordner mit `SmartGit` zu verknüpfen, müsst ihr zunächst in der Menüleiste auf `Repository` klicken und dann auf `Clone`. In dem Fenster, was sich daraufhin öffnet, könnt ihr einfach die URL eures repositories (die ihr über `GitHub` anfordern könnt) in das entsprechende Feld kopieren. 

*Screenshot*

Beim nächsten Fenster gebt ihr die Option
```
Don't use a master password
```
ein und müsst euch dann noch über euren `GitHub`-Account anmelden.

Beim Unterpunkt `Selection`, der sich als nächstes öffnen sollte, sollten sowohl bei
```
Include submodules
```
als auch bei
```
Fetch all Heads and Tags
```
die Häkchen gesetzt sein.

*Screenshot*

Als nächstes könnt ihr einen Ordner auswählen, in den eure Daten von `GitHub` geladen werden sollen. Falls ihr den Ordner bereits lokal auf eurem Rechner gespeichert habt, wie wir es im letzten Teil gelernt haben, könnt ihr hier einfach den Ordner auswählen. Falls ihr das Projekt zum ersten Mal auf euren Rechner ladet, könnt ihr über die Ordneransicht einen Ordner auf eurem Rechner erstellen, in den das `repository` geladen werden soll.

Nachdem das Cloning abgeschlossen ist, solltet ihr auf der linken Seite eurer `SmartGit`-Ansicht den Praktikums-Ordner unter `Repositories` sehen können.

*Screenshot*

Jetzt könnt ihr ganz einfach über `SmartGit` mit `GitHub` kommunizieren und eure Änderungen an den Dateien im Ordner leichter und übersichtlicher committen und pushen als über das Terminal.


#### Neues `repository` erstellen

Ein neues `repository` mit `SmartGit` zu erstellen, ist sehr einfach! Dazu müsst ihr in der Menüleiste zunächst auf `Repository` klicken und dann auf
```
Add or create...
```

In dem Fenster, was sich jetzt öffnet, könnt ihr entweder einen Ordner auswählen, den ihr bereits erstellt habt - beispielsweise unseren bekannten Praktikums-Ordner - oder über "Neuer Ordner" einen neuen erstellen.
Nach einem Klick auf `OK` ist euer `repository` erstellt und ihr könnt mit nun Dateien erstellen, hinzufügen und mit euren Veränderungen loslegen!

*Screenshot*



# Basics

Jetzt wo wir `SmartGit` erfolgreich installiert und mit unserem Praktikums-Ordner verknüpft haben, stellt sich die Frage, worfür und wie wir `SmartGit` am Besten verwenden. Hierzu folgen nun ein paar der wichtigsten Basics.

### Benutzeroberfläche

Wir schauen uns zunächst die Oberfläche von `SmartGit` genauer an, um uns einen Überblick zu verschaffen. 

*Screenshot*

Auf der linken Seite sehen wir unsere `Repositories` - theoretisch können wir hier alle reinladen, an denen wir uns beteiligen. Darunter sehen wir die verschiedenen `Branches` eines Projekts. 

In der Mitte des Bildschirms sehen wir den `Workflow` also alle `commits`, die jemals an unserem Projekt durchgeführt wurden. Dabei stehen jeweils der Name der Person, die den commit durchgeführt hat sowie das Änderungsdatum. So können wir auf einen Blick nachvollziehen, wer wann was an unserem Projekt verändert hat.

Auf der rechten Seite des Bildschirms sehen wir unten eine Übersicht über alle unsere Dateien, die wir seit dem letzten `Pull` lokal verändert haben. Sie erscheinen hier ganz automatisch.


### `Commit`

Wenn wir eine Datei verändert haben und diese Änderung committen wollen, müssen wir in unserem `Files`-Feld rechts unten einmal mit Rechtsklick auf die zu committende Datei klicken. Es öffnet sich ein Fenster mit vielen Auswahlmöglichkeiten.

*Screenshot*

Wir wählen die Option `Commit`. In dem neuen Fenster, was erscheint, können wir im unteren Feld unsere `Commit Message` eingeben und diejenigen Dateien mit einem Haken versehen, für die wir unser commit durchführen wollen.
Wenn die Nachricht verfasst ist, reicht ein Klick auf `Commit` und die Änderungen wurden angenommen. Alternativ könnte man hier auch auf `Commit & Push` klicken, dann wird unser lokaler Ordner direkt auf `GitHub` gepusht. Für den Fall, dass wir noch weitere Änderungen an anderen Dateien unseres Projekts vornehmen wollen, reicht hier `Commit` aus. 


### `Push` & `Pull`

Anstatt eine ganze Zeile in das Terminal eingeben zu müssen, um unsere lokale Kopie des repositories mit der Version auf `GitHub` abzugleichen, reicht bei `SmartGit` ein einfacher Klick auf `Pull`, dem großen Button oben auf der linken Seite. Hierbei klickt ihr einmal auf den Button und anschließend auf `Pull`. Jetzt müsste sich euer Workflow in der Mitte des Bildschirms verändert haben, sodass ihr alle Änderungen seit eurem letzten `Push` sehen könnt und ihr könnt jetzt an der aktuellsten Version des Projekts weiterarbeiten.

*Screenshot*

Ähnlich funktioniert das Ganze, wenn wir mit unseren Änderungen fertig sind und den Ordner auf `GitHub` mit unserem lokalen Ordner aktualisieren wollen. Dazu klicken wir einfach auf den Button `Push` und dann können wir diese Aktion nochmals bestätigen.

*Screenshot*


#### Weitere Funktionen

Über `Discard`, können wir Änderungen, die wir an den Dateien vorgenommen haben, verwerfen und würden somit wieder zu der Version der Datei zurückkehren, die wir von `GitHub` gepullt haben.


`Fetch` ist euch vielleicht schon beim Befehl `Pull` als Option aufgefallen. Dort konntet ihr euch zwischen `Pull` und `Fetch Only` entscheiden. 
Der Unterschied zwischen den beiden Optionen besteht darin, dass beim `Fetch` lediglich die Informationen darüber abgerufen werden, ob seit unserem letzten `Push` Veränderungen an dem Projekt vorgenommen wurden und welche genau das sind.
Bei `Pull` hingegen werden sowohl diese Information abgerufen als auch alle Veränderungen auf unseren lokalen Ordner übertragen. Somit arbeiten wir direkt mit den veränderten Dateien weiter, während wir bei `Fetch` noch auf unserem eigenen letzten Stand bleiben.
