---
title: Zusatz - Lösungen
author:
date: '2021-11-29'
slug: zusatz-loesungen
categories:
  - BSc2
  - Loesungen
tags:
  - R Deskriptivstatistik
subtitle: ''
summary: ''
authors: [cezanne, mueller, nehler]
lastmod: '2023-01-23T18:41:43+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
header:
  image: "/header/PsyBSc2_extra.png"
  caption: "[Courtesy of pxhere](https://pxhere.com/en/photo/753544)"
projects: []
---



<p>Hier finden Sie die Lösungen zu den Zusatzaufgaben!</p>
<hr />
<p>Zunächst wollen wir nochmal Übungen mit einem kleinen, ausgedachten Datensatz durchführen. Stellen Sie sich dafür vor, dass Sie im Rahmen Ihres Studiums haben eine Untersuchung mit 10 Studierenden durchgeführt. Dabei haben Sie das Alter (in ganzen Zahlen), das Geschlecht (weiblich, männlich, divers), die deutsche Lieblingsstadt (Berlin, Hamburg, München, Frankfurt, Dresden), sowie die generelle Lebenszufriedenheit, gemessen mit 5 Items, erhoben.</p>
<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<p>Laden Sie die folgenden 3 Vektoren und den Datensatz in Ihr Environment.</p>
<ul>
<li>Welche Klasse haben die Vektoren?</li>
<li>Wie lauten die Dimensionen des Datensatzes?</li>
</ul>
<pre class="r"><code>#demographische Daten:
geschlecht &lt;- c(1, 2, 2, 1, 1, 1, 3, 2, 1, 2)   
alter &lt;- c(20, 21, 19, 19, 20, 23, 22, 21, 19, 25)
stadt &lt;- c(2, 1, 1, 4, 3, 2, 5, 4, 1, 3) 

#Lebenszufriedenheit:
lz_items &lt;- data.frame(lz1 = c(3, 4, 4, 2, 1, 4, 3, 5, 4, 3), lz2 = c(2, 2, 3, 2, 4, 1, 2, 3, 2, 2), lz3 = c(5, 3, 4, 4, 3, 5, 2, 4, 3, 4), lz4 = c(2, 1, 3, 2, 2, 3, 2, 4, 2, 1), lz5 = c(4, 4, 3, 3, 1, 4, 3, 4, 5, 3)) </code></pre>
<details>
<summary>
Lösung
</summary>
<p>An dieser Stelle zunächst eine generelle Anmerkung: Für einige der nachfolgenden Aufgaben wird es - wie eigentlich fast immer in <code>R</code> - mehrere Lösungswege geben. Die hier gezeigten Wege sind also exemplarische Vorlagen.</p>
<pre class="r"><code>class(geschlecht)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre class="r"><code>class(alter)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre class="r"><code>class(stadt)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre class="r"><code>dim(lz_items)</code></pre>
<pre><code>## [1] 10  5</code></pre>
<p>Die einzelnen Vektoren gehören alle zur Klasse numeric, da sie nur Zahlen beinhalten. Die Dimensionen des Datensatzes zu den <code>lz_items</code> betragen 10 Zeilen und 5 Spalten (in dem Fall die Anzahl der Lebenszufriedenheites-Items).</p>
</details>
<ul>
<li>Führen Sie die Vektoren und den Datensatz zusammen zu einem gemeinsamen Datensatz mit dem Namen <code>data</code>. Wie viele Variablen hat der neue Datensatz, wieviele Proband:innen liegen vor?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data &lt;- data.frame(geschlecht, alter, stadt, lz_items)
dim(data)</code></pre>
<pre><code>## [1] 10  8</code></pre>
<p>In <code>dim</code> wäre die Anzahl der Proband:innen, also die Anzahl der Zeilen, der erste Wert. Es liegen also 10 Proband:innen vor. Der zweite Wert beschreibt die Anzahl der Variablen. Hier haben wir demnach um 8 Variablen.</p>
</details>
<ul>
<li>Wandeln Sie die Variable <code>geschlecht</code> und die Variable <code>stadt</code> in Faktoren um. Dabei sind die Zahlen in der Reihenfolge im Beschreibungstesxt zugeordnet (Beispiel: <code>1</code> bei Geschlecht wäre <code>weiblich</code>). Überschreiben Sie die alten Variablen und überprüfen Sie die Umwandlung.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data$geschlecht &lt;- factor(data$geschlecht, levels = 1:3, labels = c(&quot;weiblich&quot;, &quot;männlich&quot;, &quot;divers&quot;))
str(data$geschlecht)</code></pre>
<pre><code>##  Factor w/ 3 levels &quot;weiblich&quot;,&quot;männlich&quot;,..: 1 2 2 1 1 1 3 2 1 2</code></pre>
<pre class="r"><code>data$stadt &lt;- factor(data$stadt, levels = 1:5, labels = c(&quot;Berlin&quot;, &quot;Hamburg&quot;, &quot;München&quot;, &quot;Frankfurt&quot;, &quot;Dresden&quot;))
str(data$stadt)</code></pre>
<pre><code>##  Factor w/ 5 levels &quot;Berlin&quot;,&quot;Hamburg&quot;,..: 2 1 1 4 3 2 5 4 1 3</code></pre>
</details>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<p>Nun wollen wir die Extraktion von bestimmten Datenpunkten nochmal üben.</p>
<ul>
<li>Welche deutsche Lieblingsstadt hat Person 4 angegeben?</li>
<li>Welches Geschlecht haben Person 7 und 8 angekreuzt?</li>
<li>Wie lauten die Lebenszufriedenheits-Werte von Person 2 und 3 auf allen Items?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data[4, &quot;stadt&quot;]</code></pre>
<pre><code>## [1] Frankfurt
## Levels: Berlin Hamburg München Frankfurt Dresden</code></pre>
<pre class="r"><code>data[c(7, 8), &quot;geschlecht&quot;]</code></pre>
<pre><code>## [1] divers   männlich
## Levels: weiblich männlich divers</code></pre>
<pre class="r"><code>data[c(2, 3), c(4:8)]</code></pre>
<pre><code>##   lz1 lz2 lz3 lz4 lz5
## 2   4   2   3   1   4
## 3   4   3   4   3   3</code></pre>
<ul>
<li>Wir sehen, dass Person 4 die Stadt Frankfurt angegeben hat.</li>
<li>Person 7 hat das Geschlecht divers angegeben und Person 8 männlich.</li>
<li>In der ausgegebenen Tabelle werden die Lebenszufriedenheits-Werte von Person 2 und 3 auf allen Items ausgegeben.</li>
</ul>
</details>
</div>
<div id="aufgabe-3" class="section level2">
<h2>Aufgabe 3</h2>
<p>Im Folgenden soll nicht nur extrahiert, sondern auch ersetzt werden.</p>
<ul>
<li>Ihnen fällt auf, dass die Angabe der 3. Person in Item <code>lz2</code> und <code>lz4</code> nicht korrekt sind. Die korrekten Werte betragen 2 (für <code>lz2</code>) und 1 (für <code>lz4</code>). Wandeln Sie die Angaben im Datensatz entsprechend um.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data[3, &quot;lz2&quot;] &lt;- 2
data[3, &quot;lz4&quot;] &lt;- 1</code></pre>
</details>
<ul>
<li>Person 6 hat zudem ein falsches Alter angegeben (eigentlich 24). Welches Alter steht noch im Datensatz? Korrigieren Sie es entsprechend.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data[6, &quot;alter&quot;]</code></pre>
<pre><code>## [1] 23</code></pre>
<p>Das Alter der Person 6, das im Datensatz steht, beträgt 23. Hier muss also das richtige Alter (24 Jahre) zugeordnet werden.</p>
<pre class="r"><code>data[6, &quot;alter&quot;] &lt;- 24</code></pre>
</details>
</div>
<div id="aufgabe-4" class="section level2">
<h2>Aufgabe 4</h2>
<p>Bei Item <code>lz2</code> und <code>lz4</code> handelt es sich um invertierte Items. Wandeln Sie die Items entsprechend um, sodass einheitlich eine hohe Ausprägung für eine hohe Lebenszufriedenheit steht. Überschreiben Sie dabei die Ursprungsvariablen. Die Variablen hatten 5 mögliche Antwortkategorien.</p>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data$lz2 &lt;- -1 * (data$lz2 - 6)
data$lz4 &lt;- -1 * (data$lz4 - 6)</code></pre>
</details>
</div>
<div id="aufgabe-5" class="section level2">
<h2>Aufgabe 5</h2>
<p>Datenextraktion kann auch mit logischer Überprüfung kombiniert werden. Bearbeiten Sie dafür folgende Fragestellungen</p>
<ul>
<li>Haben Person 1 und Person 5 dasselbe Alter und Geschlecht?</li>
<li>Haben Person 2 und Person 10 dasselbe Geschlecht und dieselbe Lieblingsstadt angegeben?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data[1, c(&quot;alter&quot;, &quot;geschlecht&quot;)] == data[5, c(&quot;alter&quot;, &quot;geschlecht&quot;)]</code></pre>
<pre><code>##   alter geschlecht
## 1  TRUE       TRUE</code></pre>
<pre class="r"><code>data[2, c(&quot;geschlecht&quot;, &quot;stadt&quot;)] == data[10, c(&quot;geschlecht&quot;, &quot;stadt&quot;)]</code></pre>
<pre><code>##   geschlecht stadt
## 2       TRUE FALSE</code></pre>
<p>Natürlich könnte man die Vergleiche auch jeweils einzeln durchführen, doch mit diesem Code geht es etwas schneller. Wenn man das und als verbindendes Element verstehen will (beide Werte müssen gleich sein), müsste man es folgendermaßen lösen.</p>
<pre class="r"><code>data[1, &quot;alter&quot;] == data[5,&quot;alter&quot;] &amp; data[1, &quot;geschlecht&quot;] == data[5, &quot;geschlecht&quot;]</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>data[2, &quot;geschlecht&quot;] == data[10, &quot;geschlecht&quot;] &amp; data[2,  &quot;stadt&quot;] == data[10, &quot;stadt&quot;]</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>Dabei wird nur <code>TRUE</code> als Resultat ausgegeben, wenn beide durch <code>&amp;</code> verbundene Aussagen als <code>TRUE</code> gewertet werden. Da, wie wir bereits gesehen haben, die Angabe in <code>stadt</code> nicht gleich ist beim zweiten Vergleich, erhalten wir hier ein <code>FALSE</code>.</p>
</details>
</div>
<div id="aufabe-6" class="section level2">
<h2>Aufabe 6</h2>
<p>Der Datensatz enthält noch nicht die vollständige Menge an erhobenen Informationen. Sie hatten zusätzlich die Lieblingsfarbe der Versuchspersonen erhoben:</p>
<pre class="r"><code>farbe &lt;- c(1, 2, 1, 1, 3, 4, 2, 2, 1, 4)  #1 = blau, 2 = rot, 3 = grün, 4 = schwarz</code></pre>
<ul>
<li>Diese Angaben fehlen jedoch in <code>data</code>. Fügen Sie diese neue Spalte mit den entsprechenden Labels dem Datensatz hinzu.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data$farbe &lt;- farbe
data$farbe &lt;- factor(data$farbe, levels = 1:4, labels = c(&quot;blau&quot;, &quot;rot&quot;, &quot;grün&quot;, &quot;schwarz&quot;))
str(data$farbe)</code></pre>
<pre><code>##  Factor w/ 4 levels &quot;blau&quot;,&quot;rot&quot;,&quot;grün&quot;,..: 1 2 1 1 3 4 2 2 1 4</code></pre>
</details>
</div>
<div id="aufgabe-7" class="section level2">
<h2>Aufgabe 7</h2>
<p>Nach einiger Zeit können Sie noch 3 weitere Proband:innen von der Teilnahme überzeugen. Fügen Sie diese zusätzlich an den Datensatz an. Die aufgeführten Zeilen wurden bereits invertiert.</p>
<pre class="r"><code>c(&quot;weiblich&quot;, 21, &quot;Frankfurt&quot;, 4, 4, 3, 4, 4, &quot;blau&quot;)
c(&quot;männlich&quot;, 19, &quot;Dresden&quot;, 2, 5, 2, 4, 3, &quot;schwarz&quot;)
c(&quot;weiblich&quot;, 20, &quot;Berlin&quot;, 1, 5, 1, 5, 1, &quot;blau&quot;)</code></pre>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data[11, ] &lt;- c(&quot;weiblich&quot;, 21, &quot;Frankfurt&quot;, 4, 4, 3, 4, 4, &quot;blau&quot;)
data[12, ] &lt;- c(&quot;männlich&quot;, 19, &quot;Dresden&quot;, 2, 5, 2, 4, 3, &quot;schwarz&quot;)
data[13, ] &lt;- c(&quot;weiblich&quot;, 20, &quot;Berlin&quot;, 1, 5, 1, 5, 1, &quot;blau&quot;)</code></pre>
<p>Hier sollte es am einfachsten sein, die neuen Personen manuell an den Datensatz anzufügen. Dabei starten wir natürlich mit der nächsten Zeile nach der vorherigen Anzahl. In diesem Fall hatten wir schon 10 Personen erhoben, starten also mit 11.</p>
</details>
</div>
<div id="aufgabe-8" class="section level2">
<h2>Aufgabe 8</h2>
<p>Schauen Sie sich die Struktur Ihres Datensatzes an. Was fällt Ihnen auf? Passen Sie den Datensatz ggf. wieder an seine ursprüngliche Struktur an.</p>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>str(data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    13 obs. of  9 variables:
##  $ geschlecht: Factor w/ 3 levels &quot;weiblich&quot;,&quot;männlich&quot;,..: 1 2 2 1 1 1 3 2 1 2 ...
##  $ alter     : chr  &quot;20&quot; &quot;21&quot; &quot;19&quot; &quot;19&quot; ...
##  $ stadt     : Factor w/ 5 levels &quot;Berlin&quot;,&quot;Hamburg&quot;,..: 2 1 1 4 3 2 5 4 1 3 ...
##  $ lz1       : chr  &quot;3&quot; &quot;4&quot; &quot;4&quot; &quot;2&quot; ...
##  $ lz2       : chr  &quot;4&quot; &quot;4&quot; &quot;4&quot; &quot;4&quot; ...
##  $ lz3       : chr  &quot;5&quot; &quot;3&quot; &quot;4&quot; &quot;4&quot; ...
##  $ lz4       : chr  &quot;4&quot; &quot;5&quot; &quot;5&quot; &quot;4&quot; ...
##  $ lz5       : chr  &quot;4&quot; &quot;4&quot; &quot;3&quot; &quot;3&quot; ...
##  $ farbe     : Factor w/ 4 levels &quot;blau&quot;,&quot;rot&quot;,&quot;grün&quot;,..: 1 2 1 1 3 4 2 2 1 4 ...</code></pre>
<p>Es fällt auf, dass unsere <code>numeric</code> Variablen jetzt als <code>chr</code> angezeigt werden. Sie sollten also zurücktransformiert werden.</p>
<pre class="r"><code>data$alter &lt;- as.numeric(data$alter)
data$lz1 &lt;- as.numeric(data$lz1)
data$lz2 &lt;- as.numeric(data$lz2)
data$lz3 &lt;- as.numeric(data$lz3)
data$lz4 &lt;- as.numeric(data$lz4)
data$lz5 &lt;- as.numeric(data$lz5)</code></pre>
</details>
</div>
<div id="aufgabe-9" class="section level2">
<h2>Aufgabe 9</h2>
<p>Erstellen Sie eine neue Variable <code>lz_ges</code> im Datensatz <code>data</code>, die die Antworten auf den lz-Items bestmöglich zusammenfasst.</p>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>data$lz_ges &lt;- rowMeans(data[, 4:8])
data$lz_ges   </code></pre>
<pre><code>##  [1] 4.0 4.0 4.0 3.4 2.2 4.2 3.2 3.6 4.0 3.8 3.8 3.2 2.6</code></pre>
</details>
</div>
<div id="aufgabe-10" class="section level2">
<h2>Aufgabe 10</h2>
<p>Speichern Sie den Datensatz als RDA-Datei unter dem Namen <code>Data_lz</code> lokal in ihrem Praktikums-Ordner ab. Lassen Sie sich erst den Pfad des aktuellen Working Directory ausgeben, und ändern Sie diesen ggf.</p>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>getwd()
setwd(&quot;...&quot;)
save(data, file = &quot;Data_lz.rda&quot;)</code></pre>
</details>
</div>
<div id="aufgabe-11" class="section level2">
<h2>Aufgabe 11</h2>
<p>Nachdem nun der Datensatz auf dem finalen Niveau ist, sollen Sie erste deskriptivstatistische Werte bestimmen.</p>
<ul>
<li>Wieviele Proband:innen haben die Farbe “schwarz” als Lieblingsfarbe ausgewählt?</li>
<li>Was ist der Modus der Variable <code>farbe</code>? Wie hoch ist die Häufigkeit?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>table(data$farbe)            # Häufigkeiten</code></pre>
<pre><code>## 
##    blau     rot    grün schwarz 
##       6       3       1       3</code></pre>
<pre class="r"><code>which.max(table(data$farbe)) # Modus</code></pre>
<pre><code>## blau 
##    1</code></pre>
<pre class="r"><code>max(table(data$farbe))       # Ausprägung</code></pre>
<pre><code>## [1] 6</code></pre>
<ul>
<li>3 Proband:innen haben die Farbe “schwarz” als Lieblingsfarbe ausgewählt.</li>
<li>Der Modus der Variable <code>farbe</code> ist blau und kommt 6 mal vor.</li>
</ul>
</details>
</div>
<div id="aufgabe-12" class="section level2">
<h2>Aufgabe 12</h2>
<p>Betrachten wir statt der Variable <code>farbe</code> nun die Variable <code>geschlecht</code>.</p>
<ul>
<li>Lassen Sie sich die absolute Häufigkeit in der für Menschen ungünstigeren grafischen Darstellungsform ausgeben.</li>
<li>Wie hoch ist der relative Anteil der Versuchspersonen, die “männlich” angegeben haben?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>pie(table(data$geschlecht))</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code>prop.table(table(data$geschlecht))</code></pre>
<pre><code>## 
##   weiblich   männlich     divers 
## 0.53846154 0.38461538 0.07692308</code></pre>
<p>Der relative Anteil der Versuchspersonen, die “männlich” angegeben haben, beträgt 0.385.</p>
</details>
</div>
<div id="aufgabe-13" class="section level2">
<h2>Aufgabe 13</h2>
<p>Berechnen Sie den relativen Informationsgehalt für die Variable <code>stadt</code>. Was bedeutet das Ergebnis?</p>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>bruch &lt;- -(1/log(5))
hj &lt;- prop.table(table(data$stadt))
summe &lt;- sum(hj * log(hj))
bruch * summe</code></pre>
<pre><code>## [1] 0.9723626</code></pre>
Das Maximum des relativen Informationsgehaltes ist bei 1. Dieses steht für eine Gleichverteilung auf alle möglichen Ausprägungen, also alle Kategorien. Daher ist unser Ergebnis ein Hinweise auf eine recht gleichmäßige Verteilung der Lieblingsstadt in Deutschland, denn für die Variable <code>stadt</code> ergibt sich ein relativer Informationsgehalt von 0.972.
</details>
</div>
<div id="aufgabe-14" class="section level2">
<h2>Aufgabe 14</h2>
<p>Betrachten wir nun ein einzelnes Item (<code>lz3</code>) aus dem Fragebogen zur Lebenszufriedenheit.</p>
<ul>
<li>Berechnen Sie ein geeignetes Maß der zentralen Tendenz.</li>
<li>Geben Sie den Interquartilsbereich an.</li>
<li>Überprüfen Sie Ihre Angabe, indem Sie sich einen Boxplot ausgeben lassen.</li>
<li>Berechnen Sie zudem den Interquartilsabstand.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>median(data$lz3)</code></pre>
<pre><code>## [1] 3</code></pre>
<pre class="r"><code>quantile(data$lz3, c(.25, .75))</code></pre>
<pre><code>## 25% 75% 
##   3   4</code></pre>
<pre class="r"><code>boxplot(data$lz3)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre class="r"><code>quantile(data$lz3, .75) - quantile(data$lz3, .25)</code></pre>
<pre><code>## 75% 
##   1</code></pre>
<ul>
<li>Der Median für <code>lz3</code> beträgt 3.</li>
<li>Der Interquartilsbereich erstreckt sich vom Wert 3 bis zum Wert 4.</li>
<li>Der Interquartilsabstand beträgt 1.</li>
</ul>
</details>
</div>
<div id="aufgabe-15" class="section level2">
<h2>Aufgabe 15</h2>
<p>Anstatt nur einer Variable soll nun der gesamte Skalenwert <code>lz_ges</code> betrachtet werden.</p>
<ul>
<li>Berechnen Sie ein sinnvolles Maß der zentralen Tendenz.</li>
<li>Bestimmen Sie ein passendes Streuungsmaß.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>mean(data$lz_ges)</code></pre>
<pre><code>## [1] 3.538462</code></pre>
<pre class="r"><code>#Varianz (beide Wege)
var(data$lz_ges) * (12 / 13)</code></pre>
<pre><code>## [1] 0.3346746</code></pre>
<pre class="r"><code>sum((data$lz_ges - mean(data$lz_ges))^2) / 13</code></pre>
<pre><code>## [1] 0.3346746</code></pre>
<ul>
<li>Das arithmetische Mittel beträgt 3.538.</li>
<li>Die Varianz beträgt 0.335.</li>
</ul>
</details>
</div>
<div id="aufgabe-16" class="section level2">
<h2>Aufgabe 16</h2>
<p>Legen wir die ausgedachten Werte nun beiseite. Löschen Sie die Inhalte Ihres Environments und laden Sie sich den Datensatz <code>fb22</code> in das Environment. Dies können sie lokal von ihrem PC, aber auch mittels der URL von der PandaR-Website machen. Eventuell haben Sie ihn ja auch aktiv in Ihrem Environment. Der Datensatz sollte 159 Versuchspersonen enthalten. Der Basisdatensatz hatte 36 Variablen, aber kann natürlich mehr enthalten, falls Sie weitere erstellt und abgespeichert haben.</p>
<pre class="r"><code>rm(list = ls())
load(url(&#39;https://pandar.netlify.app/post/fb22.rda&#39;))</code></pre>
<p>Wandeln Sie zum Start die Variable <code>lerntyp</code> in einen Faktor um. Die Labels lauten in dieser Reihenfolge: <code>c(alleine, Gruppe, Mischtyp)</code>. Erstellen Sie dafür keine neuen Spalten, sondern überschreiben Sie die bereits bestehenden. Überprüfen Sie im Nachhinein die Umwandlung.</p>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>fb22$lerntyp &lt;- factor(fb22$lerntyp, levels = 1:3, labels = c(&quot;alleine&quot;, &quot;Gruppe&quot;, &quot;Mischtyp&quot;))

str(fb22$lerntyp)</code></pre>
<pre><code>##  Factor w/ 3 levels &quot;alleine&quot;,&quot;Gruppe&quot;,..: 1 1 1 1 1 NA 3 2 3 1 ...</code></pre>
</details>
</div>
<div id="aufgabe-17" class="section level2">
<h2>Aufgabe 17</h2>
<p>Erstellen Sie ein Balkendiagramm mit der Variable <code>lerntyp</code>. Geben Sie der Grafik einen Titel, eine Achsenbeschriftung, sowie ein fesches, hippes farbliches Design.</p>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>colours &lt;- c(&quot;#CFB1B3&quot;, &quot;#BC7B7D&quot;, &quot;#DAB457&quot;)  #HEX-Werte (Paletten auf Pinterest)
colours2 &lt;- c(&quot;#B7C5D5&quot;, &quot;#D6EDEC&quot;, &quot;#E7E8ED&quot;)

table_lerntyp &lt;- table(fb22$lerntyp)

barplot(table_lerntyp, main = &quot;Lerntypen Jahrgang 2022&quot;, ylab = &quot;Anzahl Studierende&quot;, col = colours)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<pre class="r"><code>barplot(table_lerntyp, main = &quot;Lerntypen Jahrgang 2022&quot;, ylab = &quot;Anzahl Studierende&quot;, col = colours2)</code></pre>
<img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-28-2.png" width="672" />
</details>
</div>
<div id="aufgabe-18" class="section level2">
<h2>Aufgabe 18</h2>
<p>Betrachten Sie die Variablen <code>prok4</code> und <code>prok10</code>. Liegen NAs vor? Wenn ja, wieviele? Überprüfen Sie dies mit Ihnen bekannten Befehlen.</p>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>sum(is.na(fb22$prok4))</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="r"><code>sum(is.na(fb22$prok10))</code></pre>
<pre><code>## [1] 0</code></pre>
<ul>
<li>Die Variable <code>prok4</code> enthält 2 fehlende Werte.</li>
<li>Die Variable <code>prok10</code> enthält 0 fehlende Werte.</li>
</ul>
</details>
</div>
<div id="aufgabe-19" class="section level2">
<h2>Aufgabe 19</h2>
<p>Die beiden Variablen sollen weiter betrachtet werden. Entfernen Sie bei Analysen (falls nötig) die fehlenden Werte.</p>
<ul>
<li>Bestimmen Sie das Maß der zentralen Tendenz für die beiden Variablen. Werden die Proband:innen-Angaben bei Variable <code>prok4</code> und <code>prok10</code> in derselben Kategorie in zwei gleichgroße Hälften geteilt?</li>
<li>In welchem Bereich liegen die mittleren 50% der Angaben in den beiden Variablen <code>prok4</code> und <code>prok10</code>?</li>
<li>Lassen Sie sich dies zusätzlich grafisch ausgeben.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p>Da wir gefunden haben, dass in <code>prok10</code> keine fehlenden Werte vorliegen, können wir die Befehle ohne die Ergänzung <code>na.rm = T</code> durchführen.</p>
<pre class="r"><code>median(fb22$prok4, na.rm = T)</code></pre>
<pre><code>## [1] 3</code></pre>
<pre class="r"><code>median(fb22$prok10)</code></pre>
<pre><code>## [1] 3</code></pre>
<pre class="r"><code>quantile(fb22$prok4, c(.25, .75), na.rm = T)</code></pre>
<pre><code>## 25% 75% 
##   2   3</code></pre>
<pre class="r"><code>quantile(fb22$prok10, c(.25, .75))</code></pre>
<pre><code>## 25% 75% 
##   2   4</code></pre>
<ul>
<li>Der Median von <code>prok4</code> liegt bei 3, bei <code>prok10</code> liegt er bei 3.</li>
<li>Die mittleren 50% der Angaben in Variable <code>prok4</code> reicht vom Wert 2 bis zum Wert 3, bei der Variable <code>prok10</code> reicht er von 2 bis 4.</li>
</ul>
<pre class="r"><code>boxplot(fb22$prok4)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<pre class="r"><code>boxplot(fb22$prok10)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-31-2.png" width="672" /></p>
</details>
</div>
<div id="aufgabe-20" class="section level2">
<h2>Aufgabe 20</h2>
<p>Nun betrachten wir den Skalenwert, der unter <code>gewis</code> abgelegt ist. Dieser steht für die Persönlichkeitseigenschaft Gewissenhaftigkeit.</p>
<ul>
<li>Was ist der niedrigste, was ist der höchste Wert der Variable?</li>
<li>Wie hoch ist die mittlere Ausprägung?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>range(fb22$gewis)</code></pre>
<pre><code>## [1] 2 5</code></pre>
<pre class="r"><code>mean(fb22$gewis)</code></pre>
<pre><code>## [1] 3.883648</code></pre>
<ul>
<li>Der niedrigste Gewissenhaftigskeitswert liegt bei 2, der höchste bei 5.</li>
<li>Die mittlere Ausprägung der Gewissenhaftigkeit liegt bei 3.884.</li>
</ul>
</details>
</div>
<div id="aufgabe-21" class="section level2">
<h2>Aufgabe 21</h2>
<p>Ist Ihr Jahrgang im Mittel, rein deskriptiv betrachtet, gewissenhafter (<code>gewis</code>) oder extravertierter (<code>extra</code>)? In welcher der beiden Variablen variieren die Angaben stärker? Gehen Sie für die Beantwortung davon aus, dass die Skalen gleich genormt sind.</p>
<details>
<summary>
Lösung
</summary>
<p>Zunächst sollten wir überprüfen, ob es fehlende Werte auf den Skalen gibt.</p>
<pre class="r"><code>sum(is.na(fb22$gewis))</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>sum(is.na(fb22$extra))</code></pre>
<pre><code>## [1] 0</code></pre>
<p>Das ist offensichtlich nicht der Fall. Daher können wir die Befehle auch ohne den ergänzenden Teil durchführen.</p>
<pre class="r"><code>mean(fb22$gewis)</code></pre>
<pre><code>## [1] 3.883648</code></pre>
<pre class="r"><code>mean(fb22$extra)</code></pre>
<pre><code>## [1] 3.378931</code></pre>
<pre class="r"><code>var(fb22$gewis) * (158/159)</code></pre>
<pre><code>## [1] 0.4361477</code></pre>
<pre class="r"><code>var(fb22$extra) * (158/159)</code></pre>
<pre><code>## [1] 0.4951693</code></pre>
<p>Der Mittelwert von <code>gewis</code> liegt bei 3.884, der von <code>extra</code> bei 3.379. Unter den getroffenen Annahmen ist Ihre Gruppe gewissenhafter. Auch die Streuung ist deskriptiv auf der Extraversion größer. Hier liegt sie bei 0.495, während sie bei der Gewissenheit bei 0.436 liegt.</p>
</details>
</div>
<div id="aufgabe-22" class="section level2">
<h2>Aufgabe 22</h2>
<p>Verträglichkeit ist in <code>vertr</code> abgelegt.</p>
<ul>
<li>Lassen Sie sich das Histogramm ausgeben.</li>
<li>Zentrieren Sie die Variable <code>vertr</code>. Legen Sie dafür eine neue Spalte in <code>fb22</code> an mit dem Namen <code>vertr_z</code> und lassen Sie sich erneut ein Histogramm ausgeben. Was hat sich verändert?</li>
<li>Standardisieren Sie die Variable <code>vertr</code> und speichern Sie diese ebenfalls unter einer neuen Spalte mit dem Namen <code>vertr_st</code> ab. Was ist nun anders beim Histogramm?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>hist(fb22$vertr)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Dieses Histogramm soll erstmal zum Vergleich dienen. Wir sehen die ursprünglichen Skalenwerte.</p>
<pre class="r"><code>fb22$vertr_z &lt;- scale(fb22$vertr, scale = F)
hist(fb22$vertr_z)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>Durch die Zentrierung verändert sich die Form erstmal nicht. Der Mittelwert der Werte wird auf 0 gesetzt. Optisch äußert sich das dadurch, dass die Werte auf der x-Achse nun andere sind.</p>
<pre class="r"><code>fb22$vertr_st &lt;- scale(fb22$vertr, scale = T)
hist(fb22$vertr_st)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Die Standardisierung setzt die Standardabweichung auf 1. Aufgrund der neuen Wertestruktur wird natürlich auch die Kategorienanzahl geändert.</p>
</details>
</div>
<div id="aufgabe-23" class="section level2">
<h2>Aufgabe 23</h2>
<p>Vergleichen Sie deskriptiv das Maß der zentralen Tendenz der Variable <code>extra</code> zwischen den Teilnehmenden, die <code>alleine</code> und <code>Gruppen</code> in der bevorzugten Lernform angegeben hatten. Welche der beiden Gruppen hat die höhere Ausprägung? Welche der beiden Gruppen ist im Mittel nerdier (<code>nerd</code>)?</p>
<details>
<summary>
Lösung
</summary>
<p>Da wir zwei Analysen durchführen wollen, wäre es eine gute Möglichkeit, die Personen in reduzierten Datensätzen abzulegen. Dies kann mittels der Funktion <code>subset</code> gelöst werden.</p>
<pre class="r"><code>fb22_alleine &lt;- subset(fb22, subset = lerntyp == &quot;alleine&quot;)
fb22_gruppe &lt;- subset(fb22, subset = lerntyp == &quot;Gruppe&quot;)</code></pre>
<p>Über das Argument <code>subset</code> geben wir an, in welcher Variable (<code>lerntyp</code>) die Auswahl stattfindet und anschließend legen wir die Auswahl der einzelnen Gruppen über das bereits bekannte <code>==</code> fest.</p>
<p>Eine andere Möglichkeit wäre die Verwendung der logischen Auswahl anhand eckiger Klammern.</p>
<pre class="r"><code>fb22_alleine &lt;- fb22[fb22$lerntyp == &quot;alleine&quot;,]
fb22_gruppe &lt;- fb22[fb22$lerntyp == &quot;Gruppe&quot;,]</code></pre>
<p>Nun können Mittelwerte für die beiden Gruppen bestimmt werden. Beachten Sie, dass die Ergänzung von <code>na.rm</code> nur auf dem zweiten demonstrierten Weg wichtig ist. Dort können Personen mit einem Eintrag nicht richtig zugeordnet werden und sind daher in den beiden Datensätzen erhalten - allerdings nicht mit ihren richtigen Werten sondern mit überall <code>NA</code>. Die Funktion <code>subset</code> nimmt diese Fälle hingegen nicht mit auf.</p>
<pre class="r"><code>mean(fb22_alleine$extra, na.rm = T)</code></pre>
<pre><code>## [1] 3.085821</code></pre>
<pre class="r"><code>mean(fb22_gruppe$extra, na.rm = T)</code></pre>
<pre><code>## [1] 4.125</code></pre>
<pre class="r"><code>mean(fb22_alleine$nerd, na.rm = T)</code></pre>
<pre><code>## [1] 3.226368</code></pre>
<pre class="r"><code>mean(fb22_gruppe$nerd, na.rm = T)</code></pre>
<pre><code>## [1] 2.75</code></pre>
Personen, die gerne in Gruppen lernen, weisen einen Mittelwert von 4.125 auf. Sie sind rein deskriptiv extravertierter als Personen, die lieber alleine lernen. Diese haben hier einen Mittelwert von 3.086. Umgekehrtes gilt in unserer Stichprobe hingegen für die Nerdiness. Hier haben Personen, die in Gruppen lernen, einen Wert von 2.75 und Personen, die lieber alleine lernen, einen Wert von 3.226.
</details>
</div>
<div id="aufgabe-24" class="section level2">
<h2>Aufgabe 24</h2>
<p>Etwa 75% Prozent der Psychologiestudierenden in Deutschland sind weiblich. Sie treffen zufällig auf 15 Psychologiestudierende.</p>
<ul>
<li>Wie wahrscheinlich ist es, dass genau 9 der Personen weiblich sind?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>dbinom(9, 15, 0.75)</code></pre>
<pre><code>## [1] 0.09174777</code></pre>
Die Wahrscheinlichkeit beträgt 9.17%.
</details>
<ul>
<li>Wie wahrscheinlich ist es, dass mindestens 11 der Personen weiblich sind?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>1- pbinom(10, 15, 0.75)</code></pre>
<pre><code>## [1] 0.6864859</code></pre>
<pre class="r"><code>#Alternativ:
pbinom(10, 15, 0.75, lower.tail = F)</code></pre>
<pre><code>## [1] 0.6864859</code></pre>
Die Wahrscheinlichkeit beträgt 68.65%.
</details>
<ul>
<li>Stellen Sie die Verteilungsfunktion der kummulierten Wahrscheinlichkeit aller Werte in einem Plot dar.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>X &lt;- 0:15
wk &lt;- pbinom(X, 15, 0.75)
plot(x = X, y = wk, typ = &quot;h&quot;, xlab = &quot;Anzahl Frauen&quot;, ylab = &quot;kummulierte Wahrscheinlichkeit&quot;)</code></pre>
<img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-43-1.png" width="672" />
</details>
</div>
<div id="aufgabe-25" class="section level2">
<h2>Aufgabe 25</h2>
<p>In Deutschland liegt die Gewissenhaftigkeit (<code>gewis</code>) bei Frauen im Mittel bei <em>µ</em> = 3.73.</p>
<ul>
<li>Sind Frauen, die Psychologie studieren, im Mittel gewissenhafter als Frauen in der Allgemeinbevölkerung? Stellen Sie die Hypothesen auf und führen Sie einen geeigneten Test durch.</li>
<li>Geben Sie zudem das 99%-ige Konfidenzintervall und die Effektgröße an.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><strong>Hypothesen</strong></p>
<p><span class="math inline">\(H_0\)</span>: Die durchschnittliche Gewissenhaftigkeit der Frauen, die Psychologie studieren, ist gleich oder geringer als die der Frauen in der Allgemeinbevölkerung.</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(\geq\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p><span class="math inline">\(H_1\)</span>: Die durchschnittliche Gewissenhaftigkeit der Frauen, die Psychologie studieren, ist höher als die der Frauen in der Allgemeinbevölkerung.</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(&lt;\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p>Wir testen zuerst ob unsere Variable <code>Geschlecht</code> bereits als Faktor vorliegt. Wenn nicht wandeln wir sie in einen Faktor um.</p>
<pre class="r"><code>load(url(&#39;https://pandar.netlify.app/post/fb22.rda&#39;))
is.factor(fb22$geschl)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>fb22$geschl &lt;- factor(fb22$geschl,
                      levels = 1:3, 
                      labels = c(&quot;weiblich&quot;, &quot;männlich&quot;, &quot;anderes&quot;))</code></pre>
<p>Nun erstellen wir ein <code>subset</code>, indem nur die weiblichen Teilnehmenden des <code>fb22</code> Datensatzes enthalten sind.</p>
<pre class="r"><code>fb22_frauen &lt;- subset(fb22, geschl == &quot;weiblich&quot;)</code></pre>
<p><strong>t-Test</strong></p>
<p>Da wir einen Stichprobenmittelwert mit einem Populationsmittelwert vergleichen wollen und die Varianz in der Population nicht vorliegt, führen wir einen Einstichproben-t-Test durch.</p>
<pre class="r"><code>t.test(fb22_frauen$gewis, mu = 3.73, alternative = &quot;greater&quot;, conf.level = .99)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  fb22_frauen$gewis
## t = 4.7902, df = 124, p-value = 2.333e-06
## alternative hypothesis: true mean is greater than 3.73
## 99 percent confidence interval:
##  3.858015      Inf
## sample estimates:
## mean of x 
##     3.982</code></pre>
<p>Mit einer Irrtumswahrscheinlichkeit von 5% kann die <span class="math inline">\(H_0\)</span> verworfen und die <span class="math inline">\(H_1\)</span> angenommen werden. Die weiblichen Psychologie-Studierenden haben verglichen mit der Gesamtbevölkerung der Frauen höhere Gewissenhaftswerte.
Das 99%-ige Konfidenzintervall liegt zwischen 3.86 und <span class="math inline">\(\infty\)</span> (außerhalb des definierten Wertebereichs). Das bedeutet, dass in 99% der Fälle in einer wiederholten Ziehung aus der Grundgesamtheit die mittleren Verträglichkeitswerte zwischen 3.86 und <span class="math inline">\(\infty\)</span> (außerhalb des definierten Wertebereichs) liegen.</p>
<p><strong>Effektgröße</strong></p>
<p>Für das Effektgrößemaß berechnen wir <strong>Cohen’s d</strong>.</p>
<pre class="r"><code>mean_gewis_frauen &lt;- mean(fb22_frauen$gewis, na.rm = T)
sd_gewis_frauen &lt;- sd(fb22_frauen$gewis, na.rm = T)
mean_gewis_population &lt;- 3.73
d &lt;- abs((mean_gewis_frauen - mean_gewis_population)/sd_gewis_frauen)</code></pre>
<p>Die Effektgröße ist mit 0.43 als groß einzustufen.</p>
</details>
</div>
<div id="aufgabe-26" class="section level2">
<h2>Aufgabe 26</h2>
<p>Unterscheiden sich Personen, die gerne alleine lernen von Personen, die es bevorzugen in Gruppen zu lernen oder ein Mischtyp sind (<code>lerntyp</code>), in ihrer Extraversion (<code>extra</code>)? Schauen Sich sich die Daten graphisch an und führen sie nach Voraussetzungsprüfung einen geeigneten Test durch.</p>
<details>
<summary>
Lösung
</summary>
<p>Zuerst schauen wir uns an ob die Variable <code>Lerntyp</code> bereits als Faktor vorliegt und wandeln sie gegebenenfalls um.</p>
<pre class="r"><code>is.factor(fb22$lerntyp)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>fb22$lerntyp &lt;- factor(fb22$lerntyp, 
                       levels = 1:3, 
                       labels = c(&quot;alleine&quot;, &quot;Gruppe&quot;, &quot;Mischtyp&quot;))</code></pre>
<p>Nun wollen wir eine neue Variable erstellen, in der die Personen, die gerne in der Gruppe lernen oder ein Mischtyp sind, zusammengefasst werden.</p>
<pre class="r"><code>fb22$lerntyp_neu &lt;- fb22$lerntyp == &quot;alleine&quot;
fb22$lerntyp_neu &lt;- as.numeric(fb22$lerntyp_neu) #Umwandlung in Numeric, da der Variablen Typ nun Logical ist
fb22$lerntyp_neu &lt;- factor(fb22$lerntyp_neu, 
                           levels = 0:1, 
                           labels = c(&quot;Gruppe oder Mischtyp&quot;, &quot;alleine&quot;))</code></pre>
<p>Jetzt können wir uns die Extraversion der Gruppen deskriptiv in einem Boxplot darstellen lassen.</p>
<pre class="r"><code>boxplot(fb22$extra ~ fb22$lerntyp_neu, xlab = &quot;Lerntyp&quot;, ylab = &quot;Extraversion&quot;) </code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>Deskriptiv lässt sich ein Mittelwertsunterschied feststellen. Diesen wollen wir aber nun noch inferenzstatistisch überprüfen. Dafür überprüfen wir die Voraussetzungen eines t-Tests für unabhängige Stichproben. Wir können annehmen, dass die abhängige Variable intervallskaliert ist und dass die einzelnen Messwerte voneinander unabhängig sind. Wir müssen nun noch die Normalverteilung der Extraversion in den Gruppen und die Homoskedastizität überprüfen.</p>
<p><strong>Prüfung der Normalverteilung</strong></p>
<p>Wir nutzen dafür die qqPlot Funktion aus dem <code>car</code> Paket.</p>
<pre class="r"><code>library(car)</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre class="r"><code>qqPlot(fb22$extra[fb22$lerntyp_neu == &quot;alleine&quot;])</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<pre><code>## [1]  7 38</code></pre>
<pre class="r"><code>qqPlot(fb22$extra[fb22$lerntyp_neu == &quot;Gruppe oder Mischtyp&quot;])</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-52-2.png" width="672" /></p>
<pre><code>## [1] 12 32</code></pre>
<p>Die Abweichungen sind nicht zu weit. Trotzdem führen wir zur weiteren Absicherung noch den Shapiro-Test durch.</p>
<pre class="r"><code>shapiro.test(fb22$extra[fb22$lerntyp_neu == &quot;alleine&quot;])</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb22$extra[fb22$lerntyp_neu == &quot;alleine&quot;]
## W = 0.98369, p-value = 0.5273</code></pre>
<pre class="r"><code>shapiro.test(fb22$extra[fb22$lerntyp_neu == &quot;Gruppe oder Mischtyp&quot;])</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb22$extra[fb22$lerntyp_neu == &quot;Gruppe oder Mischtyp&quot;]
## W = 0.98029, p-value = 0.2395</code></pre>
<p>Keiner der Tests ist signifikant, sodass wir die Normalverteilungsannahme beibehalten.</p>
<p><strong>Homoskedastizität</strong></p>
<p>Diese überprüfen wir mittels Levene-Test.</p>
<pre class="r"><code>leveneTest(fb22$extra ~ fb22$lerntyp_neu)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1  0.0049 0.9445
##       147</code></pre>
<p>Das Ergebnis ist nicht signifikant, sodass wir die <span class="math inline">\(H_0\)</span> nicht ablehnen und die Homoskedastizität der Varianzen annehmen können.
Damit sind alle Voraussetzungen eines t-Tests erfüllt.</p>
<pre class="r"><code>t.test(fb22$extra ~ fb22$lerntyp_neu, var.equal = T)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  fb22$extra by fb22$lerntyp_neu
## t = 4.6444, df = 147, p-value = 7.506e-06
## alternative hypothesis: true difference in means between group Gruppe oder Mischtyp and group alleine is not equal to 0
## 95 percent confidence interval:
##  0.2922374 0.7251452
## sample estimates:
## mean in group Gruppe oder Mischtyp              mean in group alleine 
##                           3.594512                           3.085821</code></pre>
<p>Der deskriptive Unterschied der Mittelwerte lässt sich somit auch inferenzstatistisch feststellen, denn mit einer Irrtumswahrscheinlichkeit von 5% kann die <span class="math inline">\(H_0\)</span> verworfen und die <span class="math inline">\(H_1\)</span> angenommen werden. Die Teilnehmenden, die lieber alleine lernen, unterscheiden sich von den Teilnehmenden, die lieber in der Gruppe lernen oder ein Mischtyp sind, in ihrer Extraversion (t(<em>df</em> = 147, zweis.) = 4.64, <em>p</em> = &lt;.001).</p>
</details>
</div>
<div id="aufgabe-27" class="section level2">
<h2>Aufgabe 27</h2>
<p>Haben Studierende, die bei ihren Eltern wohnen (<code>wohnen</code>), mit gleicher Wahrscheinlichkeit einen Nebenjob (<code>job</code>) wie Studierende, die nicht bei ihren Eltern wohnen?</p>
<ul>
<li>Prüfen Sie die Voraussetungen für einen Chi-Quadrat-Test.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p>Als erstes müssen wir den Datensatz aufbereiten.</p>
<pre class="r"><code>is.factor(fb22$wohnen)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>is.factor(fb22$job)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>fb22$wohnen &lt;- factor(fb22$wohnen, levels = 1:4, labels = c(&quot;WG&quot;, &quot;bei Eltern&quot;, &quot;alleine&quot;, &quot;sonstiges&quot;))
fb22$job &lt;- factor(fb22$job, levels = 1:2, labels = c(&quot;nein&quot;, &quot;ja&quot;))

fb22$wohnen_bei_Eltern &lt;- fb22$wohnen == &quot;bei Eltern&quot; #wir erstellen eine Variable, die angibt, ob eine Personen bei den Eltern wohnt oder nicht</code></pre>
<p>Die Voraussetzungen, dass die einzelnen Beobachtungen voneinander unabhängig sind und jede Person eindeutig einer Merkmalskombination zuordbar ist, ist durch das Studiendesign erfüllt. Wir müssen aber noch prüfen, ob jede Zelle mit mehr als fünf Personen gefüllt ist.</p>
<pre class="r"><code>tab &lt;- table(fb22$wohnen_bei_Eltern, fb22$job)
tab</code></pre>
<pre><code>##        
##         nein ja
##   FALSE   62 30
##   TRUE    35 21</code></pre>
<p>Die Voraussetzungen für einen Chi-Quadrat-Test sind erfüllt.</p>
</details>
<ul>
<li>Berechnen Sie die erwarteten Häufigkeiten der Zellen und treffen Sie eine Signifikanzentscheidung.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p>Für die Erwarteten Häufigkeiten brauchen wir die Randsummen. Diese erhalten wir mit dem Befehl <code>addmargins</code>.</p>
<pre class="r"><code>tab_mar &lt;- addmargins(tab)
tab_mar</code></pre>
<pre><code>##        
##         nein  ja Sum
##   FALSE   62  30  92
##   TRUE    35  21  56
##   Sum     97  51 148</code></pre>
<p>Die erwarteten Häufigkeiten der Zellen erhalten wir wie folgt:</p>
<pre class="r"><code>n &lt;- tab_mar[3,3]

erwartet_11 &lt;- (tab_mar[1,3]*tab_mar[3,1])/n
erwartet_12 &lt;- (tab_mar[1,3]*tab_mar[3,2])/n
erwartet_21 &lt;- (tab_mar[2,3]*tab_mar[3,1])/n
erwartet_22 &lt;- (tab_mar[2,3]*tab_mar[3,2])/n

erwartet &lt;- data.frame(nein = c(erwartet_11, erwartet_21), ja = c(erwartet_12, erwartet_22))
erwartet</code></pre>
<pre><code>##      nein      ja
## 1 60.2973 31.7027
## 2 36.7027 19.2973</code></pre>
<p>Für die Signifikanzentscheidung berechnen wir den empirischen Chi-Quadrat-Wert und den zugehörigen p-Wert.</p>
<pre class="r"><code>chi_quadrat_Wert &lt;- (tab[1,1]-erwartet[1,1])^2/erwartet[1,1]+
  (tab[1,2]-erwartet[1,2])^2/erwartet[1,2]+
  (tab[2,1]-erwartet[2,1])^2/erwartet[2,1]+
  (tab[2,2]-erwartet[2,2])^2/erwartet[2,2]

chi_quadrat_Wert</code></pre>
<pre><code>## [1] 0.368761</code></pre>
<pre class="r"><code>pchisq(chi_quadrat_Wert, 1, lower.tail = F) #Freiheitsgrad beträgt 1</code></pre>
<pre><code>## [1] 0.5436804</code></pre>
<p>Somit ist der Test nicht signifikant und es lässt sich feststellen, dass das Wohnen bei den Eltern nicht damit zusammen hängt, ob ein Nebenjob ausgeübt wird.</p>
<p>Wir können unser Ergebnis auch noch mit dem Befehl <code>chisq.test()</code> überprüfen und sehen, dass dieser das gleiche Ergebnis liefert.</p>
<pre class="r"><code>chisq.test(tab, correct = F)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tab
## X-squared = 0.36876, df = 1, p-value = 0.5437</code></pre>
</details>
</div>
<div id="aufgabe-28" class="section level2">
<h2>Aufgabe 28</h2>
<p>Weichen Psychologie-Studierende, die einen Nebenjob haben, in ihrem Intellekt (<code>intel</code>) von Psychologie-Studierenden, die keinen Nebenjob haben, ab.</p>
<ul>
<li>Führen Sie nach Voraussetzungsprüfung einen geeigneten Test durch.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p>Wir beginnen die Voraussetzungen des t-Tests für unabhängige Stichproben zu überprüfen. Die Voraussetzungen der Intervallskaliertheit der unabhängigen Variable und die Unabhängigkeit der einzelnen Messwerte ist per Untersuchungsdesign erfüllt. Wir wollen nun also die Normalverteilung des Merkmals in der Grundgesamtheit der Gruppen überprüfen.</p>
<pre class="r"><code>#Wir überprüfen erst wieder, ob die Variable Nebenjob als Faktor vorliegt
is.factor(fb22$job)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>library(car)
qqPlot(fb22$intel[fb22$job == &quot;nein&quot;])</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<pre><code>## [1] 30 79</code></pre>
<pre class="r"><code>qqPlot(fb22$intel[fb22$job == &quot;ja&quot;])</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-62-2.png" width="672" /></p>
<pre><code>## [1] 49 46</code></pre>
<pre class="r"><code>shapiro.test(fb22$intel[fb22$job == &quot;nein&quot;])</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb22$intel[fb22$job == &quot;nein&quot;]
## W = 0.96409, p-value = 0.009372</code></pre>
<pre class="r"><code>shapiro.test(fb22$intel[fb22$job == &quot;ja&quot;])</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb22$intel[fb22$job == &quot;ja&quot;]
## W = 0.93146, p-value = 0.005113</code></pre>
<p>Die Normalverteilungsannahme ist nicht erfüllt. Wir können also keinen t-Test durchführen. Wir überprüfen nun die Voraussetzungen des Wilcoxon-Tests.
Wir überprüfen optisch, ob die Messwerte der beiden Gruppen ungefähr der selben Verteilung folgen.</p>
<pre class="r"><code>hist(fb22$intel[fb22$job == &quot;ja&quot;])</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<pre class="r"><code>hist(fb22$intel[fb22$job == &quot;nein&quot;])</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-63-2.png" width="672" />
Dies kann angenommen werden. Zuletzt überprüfen wir noch die Gleichheit der Streuung in beiden Gruppen mittels Levene-Test.</p>
<pre class="r"><code>leveneTest(fb22$intel ~ fb22$job)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1  0.0088 0.9254
##       147</code></pre>
<p>Wir können von Varianzhomogenität ausgehen und somit einen Wilcoxon-Test durchführen.</p>
<pre class="r"><code>wilcox.test(fb22$lz ~ fb22$ort)</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  fb22$lz by fb22$ort
## W = 2775, p-value = 0.3029
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Das Ergebnis des zweiseitigen Wilcoxon-Tests ist nicht signifikant (<em>W</em> = 2775, <em>p</em> = 0.303 ). Die Nullhypothese konnte nicht verworfen werden und wird beibehalten. Wir gehen also davon aus, dass sich Psychologie-Studierende, die einen Nebenjob haben und Psychologie-Studierende, die keinen Nebenjob haben, sich nicht in ihrem Intellekt unterscheiden.</p>
</details>
</div>
<div id="aufgabe-29" class="section level2">
<h2>Aufgabe 29</h2>
<p>Unterscheidet sich im Durchschnitt die Nerdiness (<code>nerd</code>) von Psychologiestudierenden von ihrem Intellekt (<code>intel</code>)?</p>
<ul>
<li>Stellen sie die Hypothesen auf.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><span class="math inline">\(H_0\)</span>: Die durchschnittliche Nerdiness von Psychologoiestudierenden unterscheidet sich nicht von ihrem Intellekt.</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(=\)</span> <span class="math inline">\(\mu_1\)</span></p>
<p><span class="math inline">\(H_1\)</span>: Die durchschnittliche Nerdiness von Psychologoiestudierenden unterscheidet sich von ihrem Intellekt.</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_0\)</span> <span class="math inline">\(≠\)</span> <span class="math inline">\(\mu_1\)</span></p>
</details>
<ul>
<li>Begründen Sie weshalb Sie welchen Test benutzen wollen.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p>Da die Nerdiness- und Intellekt-Werte, die verglichen werden sollen, immer von der selben Person stammen, sind die Werte voneinander abhängig. Daher wollen wir einen t-Test für abhängige Stichproben durchführen. Die Werte sind intervallskaliert, voneinander abhängig und die Differenzvariable ist normalverteilt, da wir bei einer Stichprobe von n ≥ 30 direkt davon ausgehen können. Somit sind alle Voraussetzungen für den t-Test erfüllt.</p>
</details>
<ul>
<li>Führen Sie den Test durch und berechnen Sie gegebenfalls eine Effektgröße.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>t.test(fb22$nerd, fb22$intel, paired = T)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  fb22$nerd and fb22$intel
## t = -7.0571, df = 158, p-value = 5.052e-11
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -0.5923110 -0.3332655
## sample estimates:
## mean difference 
##      -0.4627883</code></pre>
<p>Der Gruppenunterschied ist signifikant (<em>t</em>(158) = -7.06 , <em>p</em> &lt; .001), somit wird die Nullhypothese verworfen. Psychologiestudierende weisen unterschiedliche Werte auf der Skala Nerdiness und auf der Skala Intellekt auf.</p>
<p><strong>Effektstärke:</strong></p>
<pre class="r"><code>library(&quot;effsize&quot;)
cohen.d(fb22$nerd, fb22$intel, paired = T, within = F)</code></pre>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: -0.559661 (medium)
## 95 percent confidence interval:
##      lower      upper 
## -0.7274678 -0.3918542</code></pre>
<p>Der Effekt ist mit -0.56 als mittel bis groß einzuschätzen.</p>
</details>
</div>
<div id="aufgabe-30" class="section level2">
<h2>Aufgabe 30</h2>
<p>Hängt die Gewissenhaftigkeit (<code>gewis</code>) positiv mit der Anzahl an geschriebenen Wörtern zusammen, die als Begründung (<code>grund</code>) für die Wahl des Psychologiestudiums angegeben wurde? Überprüfen Sie die Voraussetzungen für das gewählte Zusammenhangsmaß.</p>
<p><strong>Tipp:</strong> Mit folgendem Befehl lässt sich die Anzahl an Wörtern einer Eingabe berechnen:</p>
<pre class="r"><code>library(stringr) #falls noch nicht installiert: install.packages(&quot;stringr&quot;)
str_count(&quot;Wie viele Wörter hat dieser Satz?&quot;, &quot;\\w+&quot;)</code></pre>
<pre><code>## [1] 6</code></pre>
<details>
<summary>
Lösung
</summary>
<p>Als erstes erstellen wir eine Variable mit der Anzahl an geschriebenen Wörtern.</p>
<pre class="r"><code>fb22$woerter_grund &lt;- str_count(fb22$grund, &quot;\\w+&quot;)</code></pre>
<p>Nun schauen wir uns den Zusammenhang der Variablen in einem Scatterplot an.</p>
<pre class="r"><code>plot(x = fb22$woerter_grund, y = fb22$gewis)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>Wir schließen einen nicht linearen Zusammenhang nicht aus und überprüfen nun die Normalverteilung der Variablen.</p>
<pre class="r"><code>library(car)
qqPlot(fb22$gewis)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
<pre><code>## [1] 54 80</code></pre>
<pre class="r"><code>qqPlot(fb22$woerter_grund)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-71-2.png" width="672" /></p>
<pre><code>## [1] 136  93</code></pre>
<p>Die Normalverteilungsannahme ist nicht erfüllt. Daher können wir keine Pearson-Produkt-Moment Korrelation berechnen und berechnen stattdessen die Rangkorrelation nach Spearman, die nicht an die Normalverteilungsannahme gebunden ist.</p>
<pre class="r"><code>cor.test(fb22$woerter_grund, fb22$gewis, method = &quot;spearman&quot;, alternative = &quot;greater&quot;)</code></pre>
<pre><code>## Warning in cor.test.default(fb22$woerter_grund, fb22$gewis, method =
## &quot;spearman&quot;, : Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  fb22$woerter_grund and fb22$gewis
## S = 466277, p-value = 0.3041
## alternative hypothesis: true rho is greater than 0
## sample estimates:
##       rho 
## 0.0432278</code></pre>
<p>Es besteht kein positiver Zusammenhang zwischen Gewissenhaftigkeit und der Anzahl an geschriebenen Wörter bei der Begründung für das Psychologiestudium.</p>
</details>
</div>
<div id="aufgabe-31" class="section level2">
<h2>Aufgabe 31</h2>
<p>Lässt sich Prokrastination durch Gewissenhaftigkeit (<code>gewis</code>) vorsagen?
(Falls noch nicht geschehen, berechnen sie den Skalenwert der Prokrastination)</p>
<pre class="r"><code>fb22$prok2_r &lt;- -1 * (fb22$prok2 - 5)
fb22$prok3_r &lt;- -1 * (fb22$prok3 - 5)
fb22$prok5_r &lt;- -1 * (fb22$prok5 - 5)
fb22$prok7_r &lt;- -1 * (fb22$prok7 - 5)
fb22$prok8_r &lt;- -1 * (fb22$prok8 - 5)

fb22$prok_ges &lt;- fb22[, c(&#39;prok1&#39;, &#39;prok2_r&#39;, &#39;prok3_r&#39;,
                          &#39;prok4&#39;, &#39;prok5_r&#39;, &#39;prok6&#39;,
                          &#39;prok7_r&#39;, &#39;prok8_r&#39;, &#39;prok9&#39;, 
                          &#39;prok10&#39;)] |&gt; rowMeans()</code></pre>
<ul>
<li>Stellen Sie die Regressionsgerade auf und prüfen sie die Voraussetzungen.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p>Die einzige Voraussetzung, die wir vor der Aufstellung des Regressionsmodell prüfen können, ist der lineare Zusammenhang der Variablen mit Hilfe eines Scatterplot.</p>
<pre class="r"><code>plot(fb22$gewis, fb22$prok_ges, xlab = &quot;Gewissenhaftigkeit&quot;, ylab = &quot;Prokrastination&quot;, 
     main = &quot;Zusammenhang zwischen Gewissenhaftigkeit und Prokrastination&quot;, pch = 19)
lines(loess.smooth(fb22$gewis, fb22$prok_ges), col = &#39;blue&#39;)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>Die Voraussetzung ist erfüllt. Wir können nun also unser Regressionsmodell aufstellen.</p>
<pre class="r"><code>fm &lt;- lm(prok_ges ~ 1 + gewis, data = fb22)</code></pre>
<p>Nun prüfen wir die anderen Voraussetungen.</p>
<pre class="r"><code>par(mfrow = c(2, 2)) #vier Abbildungen gleichzeitig
plot(fm)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-76-1.png" width="672" /></p>
<p>Der Q-Q-Plot oben rechts deutet auf Normalverteilung hin. Die rote Anpassungslinie des Scale-Location Plots unten links ist annähernd parallel zur x-Achse, sodass wir von Varianzhomogenität ausgehen können. Da auch der vierte Plot unten rechts nicht auf potentiell problematische einflussreiche Datenpunkte hindeutet, sind alle Vorausetzungen erfüllt.</p>
<pre class="r"><code>fm</code></pre>
<pre><code>## 
## Call:
## lm(formula = prok_ges ~ 1 + gewis, data = fb22)
## 
## Coefficients:
## (Intercept)        gewis  
##      4.0282      -0.3922</code></pre>
Die Regressionsgleichung lautet also <span class="math inline">\(y_i\)</span> = 4.028 - 0.392*<span class="math inline">\(x_i\)</span> + <span class="math inline">\(e_i\)</span>.
</details>
<ul>
<li>Prüfen Sie nun die Signifikanz der Koeffizienten mit einem 99%-Konfidenzintervall.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>confint(fm, level = .99)</code></pre>
<pre><code>##                  0.5 %     99.5 %
## (Intercept)  3.4658771  4.5906215
## gewis       -0.5352757 -0.2490569</code></pre>
<p>In keiner der Intervalle ist die Null enthalten, sodass wir davon ausgehen können, dass die beiden Koeffizienten tatsächlich von Null verschieden sind.</p>
</details>
<ul>
<li>Wie viel Prozent der Varianz von Prokrastination lässt sich durch die Gewissenhaftigkeit aufklären?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>summary(fm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = prok_ges ~ 1 + gewis, data = fb22)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.24783 -0.35371 -0.05175  0.33846  1.04629 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.02825    0.21564  18.680  &lt; 2e-16 ***
## gewis       -0.39217    0.05487  -7.147 3.27e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4524 on 155 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.2478, Adjusted R-squared:  0.243 
## F-statistic: 51.07 on 1 and 155 DF,  p-value: 3.273e-11</code></pre>
<pre class="r"><code>summary(fm)$r.squared</code></pre>
<pre><code>## [1] 0.2478399</code></pre>
<p>Durch die Gewissenhaftigkeit kann 24.78% der Varianz von Prokrastination erklärt werden.</p>
</details>
<ul>
<li>Eine Person hat einen Gewissenhaftswert von 3.2. Welchen Prokrastinationswert sagt, dass Modell für diese Person voraus?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>fm$coefficients[1] + 3.2*fm$coefficients[2]</code></pre>
<pre><code>## (Intercept) 
##    2.773317</code></pre>
<pre class="r"><code>#Alternativ:
predict(fm, newdata = data.frame(gewis = 3.2))</code></pre>
<pre><code>##        1 
## 2.773317</code></pre>
Das Modell sagt einen Prokrastinationswert von 2.77 voraus.
</details>
</div>
<div id="aufgabe-32" class="section level2">
<h2>Aufgabe 32</h2>
<p>In Aufgabe 6 haben wir herausgefunden, dass sich die Werte von Nerdiness und Intellekt von Psychologie-Studierenden unterscheiden. Die gefundene Effektgröße betrug d = -0.56. Wir wollen nun eine Poweranalyse durchführen, indem wir die Studie 10^4 mal wiederholen.
Nutzen Sie den Seed 4321 (<code>set.seed(4321)</code>).</p>
<ul>
<li>Führen Sie eine Simulation durch, um die empirische Power des t-Tests zu bestimmen.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>d &lt;- -0.56 #Effektstärke
N &lt;- 159 #Anzahl der Teilnehmenden von fb22
set.seed(4321)
tH1 &lt;- replicate(n = 10^4, expr = {X &lt;- rnorm(159) 
                                   Y &lt;- rnorm(159) + d #Normalverteilte Stichproben mit Mittelwertsunterschied von d Standardabweichungen
                                   ttestH1 &lt;- t.test(X, Y, var.equal = TRUE, paired = T) #Paired = T, da es sich um einen t-Test für abhängige Stichproben handelt
                                   ttestH1$p.value})
mean(tH1 &lt; .05 )</code></pre>
<pre><code>## [1] 0.9989</code></pre>
Die Power des Tests beträgt 99.89%.
</details>
<ul>
<li>Wie hoch ist die Wahrscheinlichkeit eines <span class="math inline">\(\beta\)</span>-Fehlers?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>1 - mean(tH1 &lt; .05 )</code></pre>
<pre><code>## [1] 0.0011</code></pre>
<p>Die Wahrscheinlichkeit eines <span class="math inline">\(\beta\)</span>-Fehlers beträgt 0.11%.</p>
</details>
<ul>
<li>Angenommen wir wollen das <span class="math inline">\(\alpha\)</span>-Niveau verändern. Wie würde sich das auf die Power des Tests auswirken? Simulieren sie diesmal den empirischen t-Wert und erstellen Sie einen Powerplot für <span class="math inline">\(\alpha\)</span> = 0.001, <span class="math inline">\(\alpha\)</span> = 0.01, <span class="math inline">\(\alpha\)</span> = 0.025, <span class="math inline">\(\alpha\)</span> = 0.05, <span class="math inline">\(\alpha\)</span> = 0.1.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>set.seed(4321)
tH1 &lt;- replicate(n = 10^4, expr = {X &lt;- rnorm(159) 
                                   Y &lt;- rnorm(159) + d 
                                   ttestH1 &lt;- t.test(X, Y, var.equal = TRUE, paired = T)
                                   ttestH1$statistic})
power &lt;- c(mean(abs(tH1) &gt; qt(p = 1- 0.001/2, df = N)), mean(abs(tH1) &gt; qt(p = 1- 0.01/2, df = N)), mean(abs(tH1) &gt; qt(p = 1- 0.025/2, df = N)), mean(abs(tH1) &gt; qt(p = 1- 0.05/2, df = N)), mean(abs(tH1) &gt; qt(p = 1- 0.1/2, df = N)))

x &lt;- c(.001, 0.01, 0.025, 0.05, 0.1)
plot(x = x, y = power, type = &quot;b&quot;, main = &quot;Power vs. Alpha&quot;)</code></pre>
<p><img src="/post/2021-11-19-zusatz-loesungen_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>Wir sehen das je größer das <span class="math inline">\(\alpha\)</span>-Niveau ist, desto höher ist unsere Power. Mit unserer Stichprobengröße von n = 159 haben wir selbst bei einem hypothetischen <span class="math inline">\(\alpha\)</span>-Niveau von 0.1% noch eine Power von knapp 95%.</p>
</details>
</div>
