---
title: gganimate
date: '2021-07-03'
slug: ggplotting-gganimate
categories: ["ggplotting"]
tags: []
subtitle: 'Animierte Grafiken in ggplot'
summary: ''
authors: [schultze]
lastmod: '2021-07-03T22:00:00+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
header:
  image: "/header/ggplotting_gganimate.jpg"
  caption: "[Courtesy of pxhere](https://pxhere.com/en/photo/46495)"
projects: []
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>In den bisherigen Abschnitten haben wir unsere Abbildungen und Grafiken auf drei Dimensionen beschränkt: x, y und die Farbe. Der immense Vorteil am fortschreitenden Übergang dahingehend, dass wir Forschungsergebnisse nicht mehr ausschließlich in Printmedien darstellen ist, dass eine vierte Dimension öffnen können (die Zeit) um mehr Informationen in einer Abbildung zu vermitteln. Dabei ist die Grundidee, dass wir eigentlich nicht <em>einen</em> Plot erstellen, sondern stattdessen sehr viele, die als einzelne Bilder zu einem Film zusammengefügt werden. Zwei zentrale Fragen, die man sich stellen sollte bevor man anfängt Daten zu animieren sind dabei “Gewinnt der Betrachter bzw. die Betrachterin dabei zusätzliche Information?” und “Ist es den Aufwand wert?”.</p>
<div id="vorbereitende-schritte" class="section level2">
<h2>Vorbereitende Schritte</h2>
<p>Wie schon in den <a href="/extras#ggplotting">beiden vorherigen Abschnitten</a> nutzen wir auch hier wieder <a href="/post/ggplotting-daten">den von uns vorbereiteten Ausschnitt</a> aus den Gapminder Daten, der sich auf Bildungsausgaben und den UNDP Bildungsindex fokussiert. Wie auch bisher können wir dafür die Daten direkt von dieser Website laden:</p>
<pre class="r"><code>load(url(&#39;https://pandar.netlify.com/post/edu_exp.rda&#39;))</code></pre>
<p>Naheliegenderweise benötigen wir auch in diesem Beitrag wieder <code>ggplot2</code>:</p>
<pre class="r"><code>library(ggplot2)</code></pre>
<p>Außerdem können wir die Theme und die Farbpalette aus <a href="/post/ggplotting-themes">dem letzten Abschnitt</a> wieder benutzen. Dafür habe ich beide in einem .R-Skript festgehalten, sodass wir die Datei auf dieser Website direkt aus R ansprechen können:</p>
<pre class="r"><code>source(url(&#39;https://pandar.netlify.com/post/ggplotting-theme-source.R&#39;))</code></pre>
<p>Nach dieser kurzen Vorbereitung können wir uns direkt in die Animationen stürzen!</p>
</div>
<div id="informationsgewinn-durch-animation" class="section level2">
<h2>Informationsgewinn durch Animation</h2>
<p>Nehmen wir für die Frage “Gewinnt der Betrachter bzw. die Betrachterin dabei zusätzliche Information?” mal ein Negativbeispiel:</p>
<p><img src="/post/ggplotting_gganimate1.gif" /></p>
<p>Was wir hier sehen ist die animierte Variante dessen, was wir im <a href="/post/ggplotting-intro">ggplot Intro</a> als “normalen” Plot erzeugt hatten. Hier werden die Ausgaben für das primäre Bildungssystem im Vergleich der fünf Länder (Vereinigtes Königreich, Frankreich, Italien, Spanien und Polen) über die Jahre zwischen 1998 und 2018 dargestellt. Die Abbildung hat zwar den Vorteil die Spannung aufrecht zu erhalten, während wir uns wundern wie es wohl weitergeht, aber vergleichen wir diese Abbildung mal mit der ursprünglichen:</p>
<p><img src="/post/2021-07-05-ggplotting-gganimate_files/figure-html/static-linedraw-1.png" width="672" /></p>
<p>Im direkten Vergleich hat sie sogar einen wesentlichen Nachteil: wir haben wenig Gelegenheit die gesamte Information zu betrachten, wenn wir im Jahr 2018 angekommen sind. Wir können zwar am Ende der Animation durch das 2-sekündige Standbild einen kurzen Überblick erhaschen, aber der Fokus wird vom Ersteller (in diesem Fall mir) auf die Entwicklung gelenkt und lässt kaum detaillierte Inspektion der Daten durch die Betrachtenden zu. In Dingen der Aufmerksamkeitslenkung kann diese Abbildung also durchaus nützlich sein, wenn wir aber das Ziel haben unsere Information sachlich und transparent zu vermitteln, gewinnen wir durch die Animation in diesem Fall nichts.</p>
<p>Das Problem liegt hier dabei, dass die Variable, die wir für die Animation benutzen (<code>Year</code>) bereits auf der x-Achse abgetragen ist. Wir gewinnen also keine vierte Dimension in den Daten, sondern nutzen die Erste doppelt. Stattdessen sollten wir uns auf Situationen konzentrieren, in denen wir durch die Animation eine weitere Variable in unsere Abbildung aufnehmen können, die für die Information die wir zu vermitteln versuchen einen Mehrwert hat.</p>
</div>
<div id="statische-grundlage" class="section level2">
<h2>Statische Grundlage</h2>
<p>Nehmen wir das Beispiel aus dem <a href="/post/ggplotting-themes">Beitrag zur Verwendung von Themes und Farben</a>. Dort hatten wir für ein spezifisches Jahr (2013) die Ausgaben für Grundschulbildung und den Education Index gegenübergestellt:</p>
<pre class="r"><code>subset(edu_exp, Year == 2013) |&gt;
  ggplot(aes(x = Primary, y = Index, color = Wealth)) +
    geom_point() +
    labs(x = &#39;Spending on Primary Eduction&#39;,
    y = &#39;UNDP Education Index&#39;,
    color = &#39;Country Wealth\n(GDP per Capita)&#39;) +
    ggtitle(&#39;Impact of Primary Education Investments&#39;, subtitle = &#39;Data for 2013&#39;) +
    theme_pandar() + scale_color_pandar()</code></pre>
<pre><code>## Warning: Removed 101 rows containing missing values (geom_point).</code></pre>
<p><img src="/post/2021-07-05-ggplotting-gganimate_files/figure-html/og-scatter-1.png" width="672" /></p>
<p>Zur Erinnerung: hier werden zuerst die Daten für 2013 mittels <code>subset()</code> ausgewählt und dann über die Pipe <code>|&gt;</code> and <code>ggplot()</code> weitergereicht. Dort verwenden wir die Ausgaben (<code>Primary</code>) als x und den Bildungsindex (<code>Index</code>) als y. Zusätzlich färben wir die Punkte nach Wohlstandsgruppe des Landes (<code>Wealth</code>). Diese Daten stellen wir dann als Punkte dar (<code>geom_point()</code>). Mit <code>labs()</code> werden unsere drei Ästhetiken dann noch etwas detaillierter beschriftet und mit <code>ggtitle()</code> noch ein passender Titel hinzugefügt. Zu guter Letzte können wir mit <code>theme_pandar()</code> und <code>scale_color_pandar()</code> die optische Aufbereitung aufrufen, die wir im letzten Beitrag erstellt haben.</p>
<p>Wie sofort ersichtlich wird ist das Problem, dass die drei Dimensionen, die uns in einem statischen Plot zur Verfügung stehen (x, y und die Farbe) schon mit Informationen belegt. Für die Darstellung einer vierten Variable (der in <code>Year</code> festgehaltenen Zeit) können wir uns einer Animation bedienen. Wenn wir nämlich versuchen alle Daten gleichzeitig darzustellen, wird das Ganze ein wenig unübersichtlich:</p>
<pre class="r"><code>static &lt;- ggplot(edu_exp, aes(x = Primary, y = Index, color = Wealth)) +
  geom_point() +
  labs(x = &#39;Spending on Primary Eduction&#39;,
  y = &#39;UNDP Education Index&#39;,
  color = &#39;Country Wealth\n(GDP per Capita)&#39;) +
  ggtitle(&#39;Impact of Primary Education Investments&#39;) +
  theme_pandar() + scale_color_pandar()
static</code></pre>
<pre><code>## Warning: Removed 2641 rows containing missing values (geom_point).</code></pre>
<p><img src="/post/2021-07-05-ggplotting-gganimate_files/figure-html/static-scatter-1.png" width="672" /></p>
<p>Mit faceting könnten wir versuchen das Problem zu lösen, allerdings geht uns dabei die intuitive Darstellung des Zeitverlaufs verloren:</p>
<pre class="r"><code>static + facet_wrap(~ Year, scales = &#39;free&#39;)</code></pre>
<pre><code>## Warning: Removed 2641 rows containing missing values (geom_point).</code></pre>
<p><img src="/post/2021-07-05-ggplotting-gganimate_files/figure-html/faceted-scatter-1.png" width="672" /></p>
<p>Leider sehen wir schon hier, dass die Datenlage für 1997 sehr dünn ist und für das Jahr 2017 aus irgendeinem Grund vor allem die Informationen aus wohlhabenden Ländern fehlen. Daher schließen wir diese beiden Jahre für die Folgenden Animationen zunächst aus:</p>
<pre class="r"><code>trimmed &lt;- subset(edu_exp, Year &lt; 2017 &amp; Year &gt; 1997)
static &lt;- ggplot(trimmed, aes(x = Primary, y = Index, color = Wealth)) +
  geom_point() +
  labs(x = &#39;Spending on Primary Eduction&#39;,
  y = &#39;UNDP Education Index&#39;,
  color = &#39;Country Wealth\n(GDP per Capita)&#39;) +
  ggtitle(&#39;Impact of Primary Education Investments&#39;) +
  theme_pandar() + scale_color_pandar()</code></pre>
</div>
<div id="grundidee-von-gganimate" class="section level2">
<h2>Grundidee von <code>gganimate</code></h2>
<p>Um uns Animationen in der <em>relativ</em> intuitiven Schreibweise von <code>ggplot2</code> zu ermöglichen, hat Thomas Lin Pedersen das Paket <a href="https://gganimate.com/articles/gganimate.html">gganimate</a> erstellt. Dabei besteht die Grundidee des Pakets darin, aus einem ggplot anhand einer differenzierenden Variable mehrere ggplots zu machen. Letztendlich ist das Vorgehen also das Gleiche wie beim Faceting, nur dass wir hier die entstandenen Grafiken nicht in ein Raster anordnen, sondern einfach nacheinander anzeigen (und so die Illusion einer Animation erwecken). Dabei ist das Vorgehen recht einfach: wie erstellen mit <code>ggplot()</code> eine statische Abbildung und fügen dieser mit <code>+</code> einfach Befehle zur Erstellung von Animationen hinzu. Dabei werden in <code>gganimate</code> im Wesentlichen drei große Animationen unterschieden:</p>
<ul>
<li><code>enter_</code>-Befehle steuern das Verhalten, wenn Daten <em>auftauchen</em>. <code>enter_fade</code> z.B. bewirkt, dass eine Geometrie anhand des Übergangs von komplett durchsichtig zu komplett undurchsichtig im klassischen “fade-in” erscheint.</li>
<li><code>exit_</code>-Befehle verhalten sich genauso, steuern aber das Verhalten, wenn Daten <em>verschwinden</em>.</li>
<li><code>transition_</code>-Befehle steuern die <em>Übergänge</em> zwischen Datenzuständen. In unserem Fall z.B. sind die Daten von Spanien im Jahr 2008 und 2009 unterschiedlich:</li>
</ul>
<pre class="r"><code>subset(trimmed, Year %in% c(2008, 2009) &amp; geo == &#39;esp&#39;)</code></pre>
<pre><code>##      geo Country Wealth Region Year Population Expectancy Income  Primary
## 1125 esp   Spain   High europe 2008   46068811      81.25  34164 20.00129
## 1126 esp   Spain   High europe 2009   46583566      81.66  32653 21.27594
##      Secondary Tertiary    Index
## 1125  25.37782 26.80364 61.33333
## 1126  27.61234 28.60976 62.00000</code></pre>
<p><code>transition_</code>-Befehle steuern wie zwischen diesen Daten der Pfad interpoliert werden soll. <code>enter_</code> und <code>exit_</code> funktionieren im Grunde identisch zueinander, weswegen sie auch in einer gemeinsamen Hilfe dokumentiert sind, die mit <code>?enter_exit</code> angesprochen werden kann. Das hat den Vorteil, dass wir dort alle Möglichkeiten auf einen Blick sehen. In den allermeisten Fällen werden mit diesen beiden Animationsarten aber Feinheiten geregelt, während der Kern der Animation über die Darstellung von Übergängen passiert.</p>
<p>Wenn wir uns für eine Animation des Übergangs zwischen Datenzuständen (in unserem Fall die Jahre) ausgesucht haben, muss das in mehrere Plots übersetzt und diese Plots am Ende zu einer Animation zusammengefügt werden. Dabei ist eins der gängigsten Formate, um animierte Bilder zu präsentieren das gif (Graphics Interchange Format, gesprochen <em>gif</em>). Dieses Format ist nichts weiter als eine Aneinanderreihung von Bildern, die dann (meistens in Schleife) abgespielt werden. <code>gganimate</code> bietet aber eine Reihe verschiedener Renderer, mit denen unterschiedliche Datenformate erzeugt werden können (siehe <code>?renderers</code> für eine Übersicht). Diese beiden Schritte übernimmt in <code>gganimate</code> die <code>animate</code>-Funktion. Diese kann entweder direkt angewandt werden, um eine animierte Grafik in RStudio anzuzeigen oder - besser - um die Animation in einem Objekt abzulegen, die man dann mit <code>anim_save()</code> abspeichern kann. Hierbei macht besonders das Speichern Sinn, weil das Animieren von Grafiken mitunter mehrere Minuten in Anspruch nehmen kann. So aufwändig erstellte Plots durch einen Misclick zu verwerfen kann durchaus einiges an Frustrationen erzeugen (besonders wenn man einen Text wie diesen verfasst).</p>
<p>Zusammengefasst ist das Vorgehen also:</p>
<ol style="list-style-type: decimal">
<li>statische Grafik mit <code>ggplot()</code> erstellen,</li>
<li>mit <code>transition_</code>, <code>enter_</code> und/oder <code>exit_</code> die gewünschten Animationen hinzufügen,</li>
<li>mit <code>animate()</code> die Animation vornehmen und</li>
<li>zu guter Letzt mit <code>anim_save()</code> die Animation speichern.</li>
</ol>
</div>
<div id="animierter-scatterplot-erster-versuch" class="section level2">
<h2>Animierter Scatterplot: Erster Versuch</h2>
<p>Um mit <code>gganimate</code> arbeiten zu können, muss das Paket natürlich installiert sein. Wenn wir unsere Animationen als gifs speichern wollen kann es außerdem notwendig sein <code>gifski</code> zu installieren, das den enstprechenden Renderer liefert:</p>
<pre class="r"><code>install.packages(&#39;gganimate&#39;)
install.packages(&#39;gifski&#39;)</code></pre>
<p>Für das Laden reicht es aber dann aus nur <code>gganimate</code> aufzurufen, weil der Renderer nur intern angesprochen wird:</p>
<pre class="r"><code>library(&#39;gganimate&#39;)</code></pre>
<p>Weil die Darstellung von Zeitverläufen der häufigste Anwendungsfall für die Animation ist, hat sie in <code>gganimate</code> sogar eine eigene Übergangsfunktion: <code>transistion_time()</code>. Diese können wir benutzen, um die Übergänge zwischen verschiedenen Zeitpunkten in unseren Daten zu animieren. Den statischen Plot hatten wir oben bereits als <code>static</code> abglegt. Die Funktion nimmt natürlich die Zeitvariable als Argument entgegen, anhand derer die Animation betrieben wird:</p>
<pre class="r"><code>fluid &lt;- static + transition_time(Year)</code></pre>
<p>Diese Animation können wir dann an <code>animate()</code> weitergeben, bevor wir schlussendlich mit <code>anim_save()</code> die Abbildung abspeichern:</p>
<pre class="r"><code>animated &lt;- animate(fluid)
anim_save(&#39;step1.gif&#39;, animated)</code></pre>
<p>Das Ergebnis dieses Versuchs sollte jetzt so aussehen:</p>
<p><img src="/post/ggplotting_gganimate2_step1.gif" /></p>
</div>
<div id="animierter-scatterplot-mehr-versuche" class="section level2">
<h2>Animierter Scatterplot: Mehr Versuche</h2>
<p>Noch ist das Ergebnis nicht wirklich zufriedenstellend. Der leichte Stroboskop-Effekt ist nicht so hübsch und einige der Verbindungen zwischen Punkten stammen zumindest augenscheinlich nicht von den gleichen Ländern. Der Grund für das zweite Problem liegt darin, dass der Datensatz für einige Ländern recht “löchrig” ist, also bei weitem nicht in allen Jahren die Ausgaben und/oder der UNDP Bildungsindex ermittelt wurden. Wenn wir uns z.B. die Daten aus Indien angucken, sehen wir direkt, dass die Daten nur in ausgewählten Jahren vorliegen:</p>
<pre class="r"><code>subset(trimmed, geo == &#39;ind&#39;, select = c(&#39;Country&#39;, &#39;Wealth&#39;, &#39;Year&#39;, &#39;Primary&#39;, &#39;Index&#39;))</code></pre>
<pre><code>##      Country     Wealth Year  Primary    Index
## 1661   India Lower Mid. 1998       NA 26.66667
## 1662   India Lower Mid. 1999 12.18634 28.00000
## 1663   India Lower Mid. 2000 14.84075 29.33333
## 1664   India Lower Mid. 2001 13.73107 30.00000
## 1665   India Lower Mid. 2002       NA 30.66667
## 1666   India Lower Mid. 2003 11.35044 31.33333
## 1667   India Lower Mid. 2004       NA 31.33333
## 1668   India Lower Mid. 2005       NA 32.00000
## 1669   India Lower Mid. 2006       NA 32.66667
## 1670   India Lower Mid. 2007       NA 33.33333
## 1671   India Lower Mid. 2008       NA 34.66667
## 1672   India Lower Mid. 2009  7.58993 35.33333
## 1673   India Lower Mid. 2010  7.49038 36.00000
## 1674   India Lower Mid. 2011  9.03030 36.00000
## 1675   India Lower Mid. 2012  9.40785 37.33333
## 1676   India Lower Mid. 2013  9.79172 38.66667
## 1677   India Lower Mid. 2014       NA 40.66667
## 1678   India Lower Mid. 2015       NA 42.00000
## 1679   India Lower Mid. 2016       NA 42.66667</code></pre>
<p>Wie wir schon für <code>ggplot2</code> gesehen haben, ist die Grundüberzeugung auch in der Umsetzung von <code>gganimate</code>, dass es leichter ist hier direkt Daten anzupassen, statt Veränderungen an der Darstellung vorzunehmen. Für unseren Fall heißt das, dass wir die Zeilen mit fehlenden Werten entfernen müssen. Dadurch werden die Übergänge zwischen den verbleibenden Jahren animiert, statt die Daten auszublenden. So würde für Indien dann der Übergang von 2003 zu 2009 als langsamer Verlauf zwischen (11.35, 31.33) und (7.59, 35.33) angezeigt werden.</p>
<pre class="r"><code>nomiss &lt;- subset(trimmed, !(is.na(Primary) | is.na(Index)))

subset(nomiss, geo == &#39;ind&#39;, select = c(&#39;Country&#39;, &#39;Wealth&#39;, &#39;Year&#39;, &#39;Primary&#39;, &#39;Index&#39;))</code></pre>
<pre><code>##      Country     Wealth Year  Primary    Index
## 1662   India Lower Mid. 1999 12.18634 28.00000
## 1663   India Lower Mid. 2000 14.84075 29.33333
## 1664   India Lower Mid. 2001 13.73107 30.00000
## 1666   India Lower Mid. 2003 11.35044 31.33333
## 1672   India Lower Mid. 2009  7.58993 35.33333
## 1673   India Lower Mid. 2010  7.49038 36.00000
## 1674   India Lower Mid. 2011  9.03030 36.00000
## 1675   India Lower Mid. 2012  9.40785 37.33333
## 1676   India Lower Mid. 2013  9.79172 38.66667</code></pre>
<p>Z.B. die Daten für Indien sind jetzt auf die wenigen Zeilen reduziert, in denen beide Variablen vorliegen, die wir auf x- und y-Achse abtragen.</p>
<p>Das zweite Problem - dass einige Übergänge eventuell zwischen Ländern stattfinden, die nicht die selben sind - müssen wir schon in der Erstellung des statischen Plots beheben. Bisher enthält unser ggplot keinerlei Angaben dazu, wie Daten des gleichen Landes einander zugeordnet werden können. Um hier sicher zu gehen, dass immer alle Punkte zueinander gehören, zwischen denen ein Übergang animiert wird, können wir mit dem <code>group</code> Argument eine Gruppierungsvariable hinzufügen:</p>
<pre class="r"><code>static &lt;- ggplot(nomiss, aes(x = Primary, y = Index, color = Wealth, group = Country)) +
  geom_point() +
  labs(x = &#39;Spending on Primary Eduction&#39;,
  y = &#39;UNDP Education Index&#39;,
  color = &#39;Country Wealth\n(GDP per Capita)&#39;) +
  ggtitle(&#39;Impact of Primary Education Investments&#39;) +
  theme_pandar() + scale_color_pandar()</code></pre>
<p>An der statischen Abbildung ändert sich dadurch nichts, es wird lediglich Information darüber hinterlegt, dass <code>Country</code> eine Gruppierung darstellt, die kennzeichnet dass Zeilen das Datensatzes zueinander gehören. Mit diesen Anpassungen können wir einen zweiten Versuch starten:</p>
<pre class="r"><code>fluid &lt;- static + transition_time(Year)
animated &lt;- animate(fluid)
anim_save(&#39;step2.gif&#39;, animated)</code></pre>
<p><img src="/post/ggplotting_gganimate2_step2.gif" /></p>
<p>Auch das wirkt durch das abrupte erscheinen und verschwinden von einzelnen Datenpunkten noch sehr unruhig. Um das ein wenig abzuschwächen, können wir die vorhin erwähnten <code>enter_</code> und <code>exit_</code>-Funktionen nutzen, um das Punkte allmälich ein- und auszublenden. Dazu nutze ich hier die <code>_fade</code> Variante der beiden:</p>
<pre class="r"><code>fluid &lt;- static + transition_time(Year) +
  enter_fade(alpha = .1) + exit_fade(alpha = .1)</code></pre>
<p>Um nicht für jede Vorschau immer die gesamte Animation zu durchlaufen, können wir mit <code>plot()</code> auch einfach spezifische Frames ansehen:</p>
<pre class="r"><code>plot(fluid, 2)</code></pre>
<p><img src="/post/2021-07-05-ggplotting-gganimate_files/figure-html/frame-preview1-1.png" width="672" /></p>
<p>Hier sehen wir uns den 2. Frame der Animation an. Per Voreinstellung werden in <code>gganimate</code> 100 Frames bei 10 FPS (frames per second) erstellt, sodass die Standard-Animation stets 10 Sekunden lang ist. Wie wir sehen können, erscheinen hier gerade einige Punkte, während manche schon wieder verschwinden. In voller Umsetzung sieht das Ganze dann so aus:</p>
<p><img src="/post/ggplotting_gganimate2_step3.gif" /></p>
</div>
<div id="feinschliff-funktionalität" class="section level2">
<h2>Feinschliff-Funktionalität</h2>
<p>Im letzten Abschnitt haben wir uns angeguckt wie Daten ein- und ausgeblendet werden und wie der Übergang zwischen verschiedenen Zuständen erzeugt werden kann. Um den Übergang zwischen den Zuständen noch zu verfeinern, können wir mit den <code>shadow_</code>-Funktionen arbeiten. Mit <code>shadow_trail</code> ergibt sich z.B. Folgendes:</p>
<pre class="r"><code>fluid &lt;- static + transition_time(Year) +
  enter_fade(alpha = .1) + exit_fade(alpha = .1) +
  shadow_wake(.5)</code></pre>
<p>Um von der Preview-Funktionaliät Gebrauch zu machen:</p>
<pre class="r"><code>plot(fluid, 44)</code></pre>
<p><img src="/post/2021-07-05-ggplotting-gganimate_files/figure-html/frame-preview2-1.png" width="672" /></p>
<p>Wie man sieht, ist es sehr leicht möglich mit solchen Anpassungen die Abbildung “ein wenig” chaotisch werden zu lassen. Aber natürlich variiert das von Situation zu Situation - hier, wie bei allen Dingen in R, lohnt es sich einfach verschiedene Dinge auszuprobieren! Dazu bietet <code>gganimate</code> im Wesentlich drei “Schatten” <code>shadow_mark()</code>, <code>shadow_trail()</code> und das schon gesehene <code>shadow_wake()</code>.</p>
<p>Über dieses explizite Hinzufügen von Übergangseffekten hinaus, können wir auch bestimmen, wie zwischen zwei Situationen gewechselt wird. Im Moment gehen die Punkte linear ineinander überm aber über <code>ease_aes()</code> können wir eine vielzahl von Übergangsfunktionen definieren. Dabei geht es vor allem um die Beschleunigung mit der Punktetransition stattfindet (<code>linear</code>, <code>quadratic</code>, <code>cubic</code> und so weiter). Jede der Funktionen kann entweder als Beschleunigung (<code>-in</code>) oder als Bremse (<code>-out</code>) oder als beides (<code>in-out</code>) benutzt werden. So können wir z.B. <code>elastic-in</code> benutzen um diese Transition zu erzeugen:</p>
<pre class="r"><code>fluid &lt;- static + transition_time(Year) +
  enter_fade(alpha = .1) + exit_fade(alpha = .1) +
  ease_aes(&#39;elastic-in&#39;)</code></pre>
<p><img src="/post/ggplotting_gganimate2_step3b.gif" /></p>
<p>Die dritte Anpassung bezieht sich auf die Achsen. Generell ist es empfehlenswert global fixierte Achsen zu nutzen, um die Darstellung der Daten vergleichbar zu halten. Nichts desto trozt sind sich verändernde Achsen bei manchen Abbildungen sehr beliebt und manchmal auch außerordentlich sinnvoll. Wenn wir z.B. die Entwicklung der Einwohnerzahlen der Länder betrachten würden, wäre es nicht sonderlich hilfreich für 1800 die gleich Skalierung wie für 2020 zu nutzen. Für unseren Plot können wir z.B. Folgendes tun:</p>
<pre class="r"><code>fluid &lt;- static + transition_time(Year) +
  enter_fade(alpha = .1) + exit_fade(alpha = .1) +
  view_follow()</code></pre>
<p>Dadurch verändern sich während unserer Animation die Ober- und Untergrenzen der dargestellten x- und y-Skalen. Das wirkt besonders in unserem Fall etwas ungünstig, weil sehr extreme Werte nur kurz und vereinzelt auftauchen. Das liegt höchstwahrscheinlich an der Definition der <code>Primary</code> Variable, die am GDP relativiert wird und demzufolge bei Wirtschaftskrisen sehr schnell in die Höhe springt.</p>
<p><img src="/post/ggplotting_gganimate2_step4.gif" /></p>
<p>Eine letzte Option, mit der wir den Plot noch verfeinern können ist mit der Kennzeichnung der aktuellen Situation. Im Verlauf unserer Animation vergehen Jahre, allerdings erfahren wir nirgendwo, welches Jahr wir aktuell sehen. Dazu hat <code>gganimate</code> eine eigene Funktionalität: die <code>transition_</code>-Funktionen geben alle spezifische Platzhalter aus, die wir in der Animation verwenden können (diese sind in der jeweiligen Hilfe immer unter “Label Variables” gelistet). Für das von uns genutzte <code>transition_time()</code> ist dieser Platzhalter <code>frame_time</code> in dem die aktuelle Ausprägung der Variable hinterlegt wird, die wir als Zeitvariable genutzt haben. Diese können wir benutzen, um z.B. im Verlauf der Animation den Titel oder andere Beschriftungen anzupassen. In unserem Fall bietet es sich an, den Untertitel mit der Jahreszahl zu versehen. Dafür können wir wieder <code>ggplot</code>-Elemente hinzufügen. In diesem Fall überschreiben wir mit dem neuen <code>ggtitle()</code> den Titel den wir bereits in <code>static</code> definiert hatten:</p>
<pre class="r"><code>fluid &lt;- static + transition_time(Year) +
  enter_fade(alpha = .1) + exit_fade(alpha = .1) +
  ggtitle(&#39;Impact of Primary Education Investments&#39;, &#39;Year: {frame_time}&#39;)</code></pre>
<p>Nach der Animation durch <code>animate()</code> sieht diese Abbildung dann so aus:</p>
<p><img src="/post/ggplotting_gganimate2_step5.gif" /></p>
</div>
<div id="animations-optionen" class="section level2">
<h2>Animations-Optionen</h2>
<p>Alle Optionen, die wir bisher besprochen haben beziehen sich auf neue Elemente, die dem Plot hinzugefügt werden. Über diese Dinge hinaus, können wir in <code>gganimate</code> aber auch direkt an den Einstellungen der Animation als Ganzes herumbasteln. Wie schon erwähnt sind Animationen per Voreinstellung 100 Frames lang und laufen bei 10 FPS. In einigen Fällen können 10 Sekunden zu wenig sein, um die Gesamtheit der Daten angemessen darzustellen. Dafür haben wir drei Argumente, die wir in der <code>animate</code>-Funktion nutzen können, um die FPS und die Dauer der Animation nach unseren Vorlieben anzupassen:</p>
<ul>
<li><code>nframes</code>: Die Gesamtzahl der Frames.</li>
<li><code>fps</code>: Frames pro Sekunde.</li>
<li><code>duration</code>: Länge der Animation in Sekunden.</li>
</ul>
<p>Wenn wir alle drei Argumente nutzen kann es zu widersprüchlichen Informationen kommen, sodass im Normalfall <code>nframes</code> und <code>fps</code> gesetzt werden. Wenn wir z.B. die Animationslänge bei gleichbeinden FPS verdoppeln möchten, können wir dies mit</p>
<pre class="r"><code>animated &lt;- animate(fluid,
  nframes = 200, fps = 10)</code></pre>
<p>erreichen. Darüber hinaus können wir über das Argument <code>renderer</code> auch bestimmen, auf welche Art die Animation erzeugt und in welchem Format sie am Ende vorliegen soll. <code>?renderers</code> gibt dabei eine Übersicht.</p>
<p>Eine Anpassung, über die wir bereits gesprochen haben, aber deren Umsetzung in <code>gganimate</code> bisher verheimlicht blieb ist die Nutzung von Anfangs- und Endpausen, um einen besseren Eindruck von Ausgangslage und aktueller Situation zu vermitteln. Dafür können wir mit <code>start_pause</code> und <code>end_pause</code> die Anzahl der Frames festlegen, die wir in dieser Pause verbringen möchten:</p>
<pre class="r"><code>animated &lt;- animate(fluid,
  nframes = 200, fps = 10,
  start_pause = 20,
  end_pause = 20)</code></pre>
<p>So ermöglicht die Animation jetzt sich erst einen Eindruck von dem zu machen, was man in 1998 vorfindet und abschließend die Lage in 2017 zu beurteilen:</p>
<p><img src="/post/ggplotting_gganimate2_step6.gif" /></p>
</div>
<div id="bar-chart-races" class="section level2">
<h2>Bar Chart Races</h2>
<p>Eine außerordentlich beliebte, sehr einfache Animation sind Bar Chart Races. Vor einiger Zeit erfreuten sich diese Animationen auch auf YouTube einer außerordentlichen Beliebtheit, weil man mit Ihnen letztlich jeder Konkurrenzsituation über Zeit sehr übersichtlich darstellen kann (<a href="https://youtu.be/BQovQUga0VE">dieses 5-minütige Video</a> mit einem Bar Chart Race der 15 wertvollsten Marken hat z.B. 9 Millionen Views). Wir können versuchen mit unseren neu gefundenen Kenntnissen über Plot-Animationen ein solches Rennen nachzubauen.</p>
<p>Zunächst benötigen wir zusätzlich zu unserer eigentlichen abhängigen Variablen (in diesem Beispiel nutzen wir den Education Index) eine Rangreihe anhand derer wir dir Länder sortieren können. Allerdings muss diese Rangreihe innerhalb der einzelnen Jahre ermittelt werden, sodass wir etwas umständlich mit <code>ave()</code> arbeiten müssen. Eine beliebte Alternative zur Erstellung von Werten in gruppierten Daten stellt die <code>group_by</code>-Funktionalität im Datenmanagement-Paket <code>dplyr</code> dar.</p>
<pre class="r"><code>edu_exp$Index_Rank &lt;- ave(-edu_exp$Index, edu_exp$Year, FUN = function(x) rank(x, ties.method = &#39;first&#39;))</code></pre>
<p>Wir bilden hier also für den <em>negativen</em> <code>Index</code> (damit die Rangreihe den Ländern mit dem höchsten <code>Index</code> den niedrigsten Rangplatz, also die 1, zuweist) innerhalb der einzelnen Jahre (<code>Year</code>) mit der Funktion <code>rank()</code> eine Rangreihe, bei der Gleichstände alphabetisch aufgelöst werden. Für das Jahr 1997 bekommen wir also z.B. folgende Top 10:</p>
<pre class="r"><code>subset(edu_exp, Index_Rank &lt; 11 &amp; Year == 1997)</code></pre>
<pre><code>##      geo        Country Wealth   Region Year Population Expectancy Income
## 169  aus      Australia   High     asia 1997   18387205      78.63  32055
## 1135 est        Estonia   High   europe 1997    1409678      70.17  13733
## 1282 gbr United Kingdom   High   europe 1997   58307320      77.24  30340
## 1765 isr         Israel   High     asia 1997    5566551      78.11  25054
## 2752 nor         Norway   High   europe 1997    4420266      78.27  54769
## 2815 nzl    New Zealand   High     asia 1997    3752355      77.19  26212
## 2941 plw          Palau   High     asia 1997      18016         NA  13722
## 3466 svn       Slovenia   High   europe 1997    1987457      75.15  20094
## 3487 swe         Sweden   High   europe 1997    8868857      79.37  32441
## 3907 usa  United States   High americas 1997  271713634      76.58  41463
##       Primary Secondary Tertiary    Index Index_Rank
## 169        NA        NA       NA 78.66667          3
## 1135 18.12812        NA 38.25692 73.33333         10
## 1282       NA        NA       NA 76.66667          6
## 1765       NA        NA       NA 78.66667          4
## 2752 37.94443  18.13375 46.01137 79.33333          2
## 2815 17.44218  21.57709       NA 77.33333          5
## 2941       NA        NA       NA 74.00000          8
## 3466       NA        NA       NA 76.00000          7
## 3487       NA        NA       NA 74.00000          9
## 3907       NA        NA       NA 84.66667          1</code></pre>
<p>Damit wir unserer Abbildung auch die Information aus den Farben nicht ungenutzt lassen, können wir in dieser die Regionen kodieren. Dafür müssen wir diese, wie schon mit <code>Wealth</code> passiert, in einen schön gelabelten <code>factor</code> umwandelnd:</p>
<pre class="r"><code>edu_exp$Region &lt;- factor(edu_exp$Region,
  levels = c(&#39;europe&#39;, &#39;asia&#39;, &#39;americas&#39;, &#39;africa&#39;),
  labels = c(&#39;Europe&#39;, &#39;Asia&#39;, &#39;Americas&#39;, &#39;Africa&#39;))</code></pre>
<p>Weil wir in unserem Plot nicht alle Länder der Erde gleichzeitig darstellen wollen, sondern ein “Rennen” darstellen, beschränken wir unsere Daten auf die Top 10 pro Jahr:</p>
<pre class="r"><code>top10 &lt;- subset(edu_exp, Index_Rank &lt; 11)</code></pre>
<p>Unseren statischen Plot können wir wieder stückweise erstellen. Zunächst die Grundkomponenten:</p>
<pre class="r"><code>static &lt;- ggplot(top10,
  aes(y = Index_Rank, x = Index, fill = Region, group = Country))</code></pre>
<p>Auf der y-Achse werden also die Ränge abgetragen, auf der x-Achse der tatsächliche Wert. Die Färbung soll den vier Regionen entsprechen und damit wir die Zuweisung der Datenpunkte über die Zeit zueinander korrekt machen, nutzen wir wieder das Land als Gruppierungsvariable.</p>
<pre class="r"><code>static &lt;- static + 
  geom_rect(aes(ymin = Index_Rank - .4, ymax = Index_Rank + .4,
  xmin = 0, xmax = Index))</code></pre>
<p>Weil es sich um Bar Chart Race handelt, nutzen wir <code>geom_rect()</code> um Rechtecke zu erstellen. Dieser werden durch die in <code>ggplot()</code> schon von uns festgelegte y-Ästhetik auf der y-Achse and ihrem Rang platziert - hier wird zudem festgesetzt, dass sie +/- 0,4 Ränge um ihren Rang breit sein sollen. Darüber hinaus sollen sie auf der x-Achse von 0 bis zu ihrer <code>Index</code> Ausprägung gehen.</p>
<pre class="r"><code>static &lt;- static +
  geom_text(hjust = &#39;right&#39;, aes(label = Country), color = &#39;white&#39;)</code></pre>
<p>Damit wir in der Animation erkennen, welches Land welches ist beschriften wir die Datenpunkte an den Stellen x (<code>Index</code>) und y (<code>Index_Rank</code>) mit einem Label, in diesem Fall der Ausprägung der Variable <code>Country</code>. Damit der Text vollständig im Balken liegt machen wir ihn mit <code>hjust = 'right'</code> rechtsbündig.</p>
<pre class="r"><code>static &lt;- static +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_reverse()</code></pre>
<p>Damit die Balken bis an die eingezeichnete x-Achse gehen, setzen wir die voreingestellte “Erweiterung” des Plots nach links und rechts außer Kraft. Außerdem invertieren wir y-Achse, damit die Länder auf dem 1. Platz oben und die auf dem 10. Platz unten stehen.</p>
<pre class="r"><code>static &lt;- static +
  ggtitle(&#39;Top Spots in the Education Race&#39;) +
  labs(y = element_blank(), x = &#39;UNDP Education Index&#39;) +
  theme_pandar() + scale_fill_pandar(drop = FALSE) +
  theme(axis.text.y = element_blank())</code></pre>
<p>Dann, zu guter Letzt, unsere Beschriftungen der Achsen und Titel. Die y-Achse lassen wir unbeschriftet (wir weisen das leere Element zu). Außerdem verwenden wir noch die von uns definierte Theme und die Farbskala. Bei Letzterer stellen wir noch ein, dass wir Regionen <em>nicht</em> aus der Farbzuweisung entfernen möchten, wenn sie nicht auftauchen. Zum Abschluss unterdrücken wir die voreingestellte Kennzeichnung der Werte an der y-Achse (auch dafür überschreiben wir was auch immer passieren würde einfach mit dem leeren Element in <code>element_blank()</code>).</p>
<p>Das Balkendiagramm mit sich überlagenden Daten für alle Jahre sieht vorhersehbar chaotisch aus, sodass wir besser wieder das Faceting nutzen, um uns einen kurzen Überblick zu verschaffen:</p>
<pre class="r"><code>static + facet_wrap(~ Year, scales = &#39;free&#39;)</code></pre>
<p><img src="/post/2021-07-05-ggplotting-gganimate_files/figure-html/static-barchartrace-1.png" width="672" /></p>
<p>Anders als im letzten Beispiel nutzen wir nicht <code>transition_time()</code> um unsere Animation zu betreiben, sondern stattdessen <code>transition_states()</code>. Das liegt daran, dass unsere Abbildung nicht Verläufe von Datenpunkten abbildet, sondern zwischen distinkten Zuständen wechselt. Diese Funktion erlaubt uns außerdem festzulegen, wie lange in einem Zustand (bei uns das Jahr) verweilt werden soll (<code>state_length</code>), im Verhältnis zu der Animation der Übergänge (<code>transition_length</code>). Damit die Übergänge flüssig aussehen, verwende ich hier ein Verhältnis von 1 zu 30. Außerdem können wir über <code>wrap = FALSE</code> festlegen, dass die Animation nicht am Ende versuchen soll in den Ausgangszustand zurückzukehren.</p>
<pre class="r"><code>fluid &lt;- static + 
  transition_states(Year, transition_length = 30, state_length = 1,
    wrap = FALSE)</code></pre>
<p>Wie schon beim letzten Beispiel bietet es sich an, die aktuelle Jahreszahl im Verlauf der Animation einzublenden. Bei <code>transition_states()</code> wird der dafür benötigte Platzhalter <code>closest_state</code> genannt:</p>
<pre class="r"><code>fluid &lt;- fluid + 
  ggtitle(&#39;Top Spots in the Education Race&#39;, subtitle = &#39;Year: {closest_state}&#39;)</code></pre>
<p>Abschließend müssen wir noch entscheiden, was mit Balken von Ländern passieren soll, die entweder neu in die Top 10 einsteigen oder aus dieser herausfallen. In beiden Fällen macht es Sinn, dass die Balken von unten kommen, bzw. nach unten verschwinden:</p>
<pre class="r"><code>fluid &lt;- fluid + 
  enter_drift(y_mod = -1) + exit_drift(y_mod = -1)</code></pre>
<p>Wir können auch gleichzeitig mehrere <code>enter_</code> und <code>exit_</code> Animationen miteinander verbinden. Z.B. können die nach verschwindenden Balken auch ausblassen und die neu entstehenden langsam an Farbe gewinnen:</p>
<pre class="r"><code>fluid &lt;- fluid + 
  enter_fade(alpha = .1) + exit_fade(alpha = .1)</code></pre>
<p>Wenn wir uns jetzt z.B. den 12. Frame der Animation angucken, ergibt sich folgendes Bild:</p>
<pre class="r"><code>plot(fluid, 12)</code></pre>
<p><img src="/post/2021-07-05-ggplotting-gganimate_files/figure-html/frame-barchartrace-1.png" width="672" /></p>
<p>Soweit, so gut. Diese Grafik können wir wieder an <code>animate()</code> übergeben. Weil die Animation der ein- und austretenden Balken und der Positionswechsel möglichst flüssig aussehen sollen, erhöhe in diesem Fall die FPS auf 20. Außerdem füge ich am Ende 1 Sekunde Pause ein und verlängere die Gesamtanimationsdauer auf 15 Sekunden, damit die Animation nicht zu hektisch wird:</p>
<pre class="r"><code>animated &lt;- animate(fluid,
  fps = 20, duration = 15,
  end_pause = 20)</code></pre>
<p>Abschließend sieht die Animation so aus:</p>
<p><img src="/post/ggplotting_gganimate3.gif" /></p>
<hr />
<p>Die hier entstandenen Grafiken sind zwar animiert, aber erlauben dennoch keine Datenexploration die unabhängige von der lenkenden Hand des Erstellers oder der Erstellerin ist. Wie solche Grafiken erstellt werden können sehen wir im kommenden Abschnitt zu <a href="/post/ggplotting_plotly">plotly</a>.</p>
</div>
