---
title: Simulation und Poweranalyse - Lösungen
author: 
date: '2021-09-21'
slug: simulation-loesungen
categories:
  - BSc2
  - Loesungen
tags:
  - Simulation
  - Poweranalyse
subtitle: ''
summary: ''
authors: [irmer]
lastmod: '2021-12-15T13:13:57+01:00'
featured: no
header:
  image: "/header/BSc2_Sim_Power.jpg"
  caption: "[Courtesy of pxhere](https://pxhere.com/en/photo/674621)"
projects: []
expiryDate: '2022-09-15'
publishDate: '2022-02-14'
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<div id="lineare-beziehungen-zwischen-variablen-korrelationstest-unter-h_1" class="section level3">
<h3>Lineare Beziehungen zwischen Variablen: Korrelationstest unter <span class="math inline">\(H_1\)</span></h3>
<p>Wir wollen uns ebenfalls die Power für den Korrelationstest ansehen. Dazu müssen wir allerdings korrelierte Variablen generieren. Um das hinzubekommen, müssen wir einige Eigenschaften der Normalverteilung ausnutzen: bspw. dass die Summe zweier normalverteilter Zufallsvariablen wieder normalverteilt ist. Für zwei unabhängige (unkorrelierte) standard-normalverteilte Zufallsvariablen <span class="math inline">\(X\)</span> und <span class="math inline">\(Z\)</span>, ist die Zufallsvariable <span class="math inline">\(Y\)</span>, die folgendermaßen gebildet wird</p>
<p><span class="math display">\[Y:= \rho X + \sqrt{1-\rho^2}Z,\]</span>
wieder standard-normalverteilt und um den Korrelationskoeffizienten <span class="math inline">\(\rho\)</span> korreliert mit <span class="math inline">\(X\)</span>. Wir können also relativ einfach zwei korrelierte Variablen generieren. Wie in der Sitzung verwenden wir <span class="math inline">\(N=20\)</span>:</p>
<pre class="r"><code>N &lt;- 20

set.seed(12345)
X &lt;- rnorm(N)
Z &lt;- rnorm(N)
Y &lt;- 0.5*X + sqrt(1 - 0.5^2)*Z
cor(X, Y) # empirische Korrelation</code></pre>
<pre><code>## [1] 0.579799</code></pre>
<pre class="r"><code>sd(X) </code></pre>
<pre><code>## [1] 0.8339354</code></pre>
<pre class="r"><code>sd(Y)</code></pre>
<pre><code>## [1] 1.232089</code></pre>
<p>Falls Sie die oben genutzte Formel zur Generierung korrelierter Zufallsvariablen überprüfen wollen, dann setzen Sie doch einmal <code>N = 10^6</code> (also eine Stichprobe von 1 Mio). Dann sollte die empirische Korrelation sehr nah an der theoretischen liegen. Auch sollten dann die empirischen Standardabweichungen sehr nah an der 1 liegen.</p>
<p>Verwenden Sie für diese Aufgabe stets den Seed 12345 (<code>set.seed(12345)</code>).</p>
<ul>
<li>Betrachten Sie das Modell für eine Stichprobe von <code>N = 10^6</code>. Berichten Sie die empirische Korrelation sowie die empirischen Standardabweichungen.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>N &lt;- 10^6

set.seed(12345)
X &lt;- rnorm(N)
Z &lt;- rnorm(N)
Y &lt;- 0.5*X + sqrt(1 - 0.5^2)*Z
cor(X, Y) # empirische Korrelation</code></pre>
<pre><code>## [1] 0.4994574</code></pre>
<pre class="r"><code>sd(X) </code></pre>
<pre><code>## [1] 1.001315</code></pre>
<pre class="r"><code>sd(Y)</code></pre>
<pre><code>## [1] 0.9994427</code></pre>
<p>Die Korrelation liegt bei $_{XY}=$0.4995 und liegt damit sehr nah an der theoretischen (wahren) 0.5. Die beiden Standardabweichungen liegen bei <span class="math inline">\(\hat{\sigma}_X=\)</span> 1.0013 und <span class="math inline">\(\hat{\sigma}_Y=\)</span> 0.9994 und damit beide sehr nah an der theoretischen (wahren) 1.</p>
</details>
<ul>
<li>Untersuchen Sie die Power des Korrelationstests für eine Korrelation von <span class="math inline">\(\rho=0.5\)</span> und <span class="math inline">\(N = 20\)</span>. Führen Sie eine Simulationsstudie durch. Wie groß ist die Power?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>N &lt;- 20
set.seed(12345)
pcor_H1 &lt;- replicate(n = 10000, expr = {X &lt;- rnorm(N)
                                        Z &lt;- rnorm(N)
                                        Y &lt;- 0.5*X + sqrt(1 - 0.5^2)*Z
                                        cortestH1 &lt;- cor.test(X, Y)
                                        cortestH1$p.value})
mean(pcor_H1 &lt; 0.05) # empirische Power</code></pre>
<pre><code>## [1] 0.6385</code></pre>
<p>Die Power des Korrelationstests für eine Korrelation von 0.5 für <span class="math inline">\(N=20\)</span> liegt bei 63.85%.</p>
</details>
<ul>
<li>Stellen Sie die Verteilung der empirischen Korrelationen (für <span class="math inline">\(\rho=0.5\)</span> und <span class="math inline">\(N=20\)</span>) unter der <span class="math inline">\(H_1\)</span> dar.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>set.seed(12345)
cors_H1 &lt;- replicate(n = 10000, expr = {X &lt;- rnorm(N)
                                        Z &lt;- rnorm(N)
                                        Y &lt;- 0.5*X + sqrt(1 - 0.5^2)*Z
                                        cor(X, Y)})
summary(cors_H1)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -0.4293  0.3791  0.5080  0.4889  0.6177  0.8997</code></pre>
<pre class="r"><code>hist(cors_H1, breaks = 50)</code></pre>
<p><img src="/post/2021-09-21-simulation-und-poweranalyse-loesungen_files/figure-html/unnamed-chunk-4-1.png" width="672" />
Die Verteilung der Korrelationen ist nicht normalverteilt. Die Verteilung ist links-schief/rechts-steil. Wir erkennen, dass Korrelationen zwischen -0.4293 und 0.8997 liegen. Die mittlere Korrelation liegt bei 0.4889, der Median der Korrelationen liegt bei 0.508. Die zentralen Tendenzen liegt also sehr nah an der theoretischen Korrelation von 0.5.</p>
</details>
</div>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<div id="lineare-beziehungen-zwischen-variablen-korrelationstest-unter-h_1-für-ungleiche-varianzen" class="section level3">
<h3>Lineare Beziehungen zwischen Variablen: Korrelationstest unter <span class="math inline">\(H_1\)</span> für ungleiche Varianzen</h3>
<p>Wiederholen Sie die Analyse. Verändern Sie diesmal die Varianz der beiden Variablen <code>X</code>und <code>Y</code>. <code>X</code> soll eine Varianz von 9 haben (multiplizieren Sie dazu <code>X</code> mit 3, nachdem Sie <code>Y</code> mit Hilfe von <code>X</code> und <code>Z</code> generiert haben), und <code>Y</code> soll eine Varianz von 0.25 haben (multiplizieren Sie dazu <code>Y</code> mit 0.5, nachdem Sie <code>Y</code> mit Hilfe von <code>X</code> und <code>Z</code> generiert haben).</p>
<ul>
<li>Betrachten Sie das Modell für eine Stichprobe von <code>N = 10^6</code>. Berichten Sie die empirische Korrelation sowie die empirischen Standardabweichungen.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>N &lt;- 10^6

set.seed(12345)
X &lt;- rnorm(N)
Z &lt;- rnorm(N)
Y &lt;- 0.5*X + sqrt(1 - 0.5^2)*Z
X_new &lt;- 3*X
Y_new &lt;- 0.5*Y
cor(X_new, Y_new) # empirische Korrelation</code></pre>
<pre><code>## [1] 0.4994574</code></pre>
<pre class="r"><code>sd(X_new) </code></pre>
<pre><code>## [1] 3.003945</code></pre>
<pre class="r"><code>sd(Y_new)</code></pre>
<pre><code>## [1] 0.4997214</code></pre>
<p>Die Korrelation liegt bei $<em>{X</em>Y_}=$0.4995 und liegt damit sehr nah an der theoretischen (wahren) 0.5. Insbesondere ist diese Korrelation gleich der Korrelation zwischen X und Y von oben! Das liegt daran, dass die Varianz die Korrelation nicht beeinflusst. Die beiden Standardabweichungen liegen bei <span class="math inline">\(\hat{\sigma}_{X_\text{new}}=\)</span> 3.0039 und <span class="math inline">\(\hat{\sigma}_{Y_\text{new}}=\)</span> 0.4997 und damit beide sehr nah an der theoretischen (wahren) dran. Diese entsprechen gerade den Vorfaktoren, die wir dran multipliziert haben. Also 3 für <span class="math inline">\(X_\text{new}\)</span> und 0.5 für <span class="math inline">\(Y_\text{new}\)</span>.</p>
</details>
<ul>
<li>Führen Sie eine Simulationsstudie durch (für <span class="math inline">\(\rho=0.5\)</span> und <span class="math inline">\(N=20\)</span>). Wie verändert sich die Power des Tests durch die veränderten Varianzen?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>N &lt;- 20
set.seed(12345)
pcor_H1_new &lt;- replicate(n = 10000, expr = {X &lt;- rnorm(N)
                                            Z &lt;- rnorm(N)
                                            Y &lt;- 0.5*X + sqrt(1 - 0.5^2)*Z
                                            X_new &lt;- 3*X
                                            Y_new &lt;- 0.5*Y
                                            cortestH1 &lt;- cor.test(X_new, Y_new)
                                            cortestH1$p.value})
mean(pcor_H1_new &lt; 0.05) # empirische Power</code></pre>
<pre><code>## [1] 0.6385</code></pre>
<p>Die Power des Korrelationstests für eine Korrelation von 0.5 für <span class="math inline">\(N=20\)</span> und Variablen mit Varianzen von 9 und 0.25 liegt bei 63.85%. Diese Power ist identisch zur Power zuvor. Das zeigt uns, dass die Power des Korrelationstests unter Voraussetzung der Normalverteilung nur von der Korrelationsgröße, aber nicht von der Varianz der Variablen, abhängt. (Natürlich dürfen wir nicht eine Variable mit 0 multiplizieren, da das zu einer Konstanten führt, die immer eine Korrelation von 0 mit allen anderen Zufallsvariablen hat.)</p>
</details>
</div>
</div>
<div id="aufgabe-3" class="section level2">
<h2>Aufgabe 3</h2>
<div id="type-i-error-und-power-zu-einem-alpha-niveau-von-0.1-des-t-test" class="section level3">
<h3>Type I-Error und Power zu einem <span class="math inline">\(\alpha\)</span>-Niveau von <span class="math inline">\(0.1\%\)</span> des <span class="math inline">\(t\)</span>-Test</h3>
<p>Wir wollen nun die die Power des <span class="math inline">\(t\)</span>-Tests für ein anderes <span class="math inline">\(\alpha\)</span>-Fehlerniveau bestimmen. Wiederholen Sie also die Poweranalysen aus der Sitzung für den <span class="math inline">\(\alpha\)</span>-Fehler und die Power für ein <span class="math inline">\(\alpha\)</span>-Fehlerniveau von <span class="math inline">\(0.1\%\)</span>.</p>
<p>Nutzen Sie den Seed 12345 (<code>set.seed(12345)</code>).</p>
<ul>
<li>Führen Sie eine Simulation durch, um das empirische <span class="math inline">\(\alpha\)</span>-Niveau des <span class="math inline">\(t\)</span>-Tests zu bestimmen für <span class="math inline">\(N=20\)</span>. Vergleichen Sie das Ergebnis mit dem Ergebnis aus der Sitzung.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>N &lt;- 20
set.seed(12345)
pt_H0 &lt;- replicate(n = 10000, expr = {X &lt;- rnorm(N)
                                      Y &lt;- rnorm(N) 
                                      ttestH1 &lt;- t.test(X, Y, var.equal = TRUE)
                                      ttestH1$p.value})
mean(pt_H0 &lt; 0.001) # empirischer Alpha-Fehler</code></pre>
<pre><code>## [1] 0.0011</code></pre>
<p>Der empirische <span class="math inline">\(\alpha\)</span>-Fehler liegt bei 0.11% und liegt damit sehr nah an dem vorgegebenem Niveau von <span class="math inline">\(\alpha = 0.1\%\)</span>. In der Sitzung hatten wir einen empirischen <span class="math inline">\(\alpha\)</span>-Fehler, der sehr nah an den theoretischen <span class="math inline">\(5\%\)</span> lag. Der Unterschied ist zu erwarten, da wir das vorgegebene <span class="math inline">\(\alpha\)</span>-Fehlerniveau verändert haben!</p>
</details>
<ul>
<li>Führen Sie eine Simulation durch, um die empirische Power des <span class="math inline">\(t\)</span>-Tests zu bestimmen für <span class="math inline">\(N=20\)</span>, <span class="math inline">\(d = 0.5\)</span> und <span class="math inline">\(\alpha = 0.1\%\)</span>. Vergleichen Sie das Ergebnis mit dem Ergebnis aus der Sitzung. Was bedeutet dies für die Wahl der Irrtumswahrscheinlichkeit?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>set.seed(12345)
pt_H1 &lt;- replicate(n = 10000, expr = {X &lt;- rnorm(N)
                                      Y &lt;- rnorm(N) + 0.5
                                      ttestH1 &lt;- t.test(X, Y, var.equal = TRUE)
                                      ttestH1$p.value})
mean(pt_H1 &lt; 0.001) # empirische Power</code></pre>
<pre><code>## [1] 0.0362</code></pre>
<p>Die empirische Power liegt bei 3.62%. Dieser Wert fällt nun deutlich geringer aus, als die 33.5%, die wir in der Sitzung beobachtet hatten. Dies zeigt nochmal deutlich auf, dass wenn wir unsere Irrtumswahrscheinlichkeit drastisch reduzieren wollen, wir in Kauf nehmen, dass die Power einen Effekt zu finden, wenn dieser da ist, deutlich eingeschränkt wird!</p>
<p>Sie können sich die Power auch für andere Irrtumswahrscheinlichkeiten anschauen, indem Sie die <code>0.001</code> ersetzen durch Ihre gewünschte Irrtumswahrscheinlichkeit!</p>
</details>
</div>
</div>
<div id="aufgabe-4" class="section level2">
<h2>Aufgabe 4</h2>
<div id="power-plots-für-den-t-test" class="section level3">
<h3>Power-Plots für den <span class="math inline">\(t\)</span>-Test</h3>
<p>Wir wollen nun die Power des <span class="math inline">\(t\)</span>-Tests für unterschiedliche Effektgrößen untersuchen. In den beiden Gruppen soll jeweils eine Varianz von 1 herrschen. Verändern Sie also den Code der Sitzung nur hinsichtlich der Effektgröße. Das <span class="math inline">\(\alpha\)</span>-Fehlerniveau soll wieder bei <span class="math inline">\(5\%\)</span> liegen.</p>
<p>Nutzen Sie den Seed 12345 (<code>set.seed(12345)</code>).</p>
<ul>
<li>Erstellen Sie einen Power-Plot für die folgenden Effekte <span class="math inline">\(d = 0, 0.25, 0.5, 0.75, 1,\)</span> und <span class="math inline">\(1.25\)</span> bei einer Stichprobengröße von <span class="math inline">\(N = 20\)</span>. Stellen Sie die Effektgröße auf der x-Achse dar.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p><img src="/post/2021-09-21-simulation-und-poweranalyse-loesungen_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Dem Plot ist zu entnehmen, dass die Power mit steigender Effektgröße ansteigt.</p>
</details>
<ul>
<li>Welcher Effekt muss mindestens bestehen, damit die Power bei <span class="math inline">\(80\%\)</span> liegt?</li>
</ul>
<details>
<summary>
Lösung
</summary>
<p>Diesem Plot ist nun zu entnehmen, dass eine Mittelwertsdifferenz von größer 0.8 nötig ist, damit die Power hinreichend groß ist. Außerdem wird in diesem Plot auch ersichtlich, dass wenn die Mittelwertsdifferenz 0 ist, dann sind wir gerade im Fall der <span class="math inline">\(H_0\)</span> gelandet. Die Power sollte hier dann nur bei <span class="math inline">\(5\%\)</span> liegen. Falls wir negative Mittelwertsdifferenzen gewählt hätten, dann wäre der Plot identisch, nur an der x-Achse gespiegelt.</p>
</details>
</div>
</div>
<div id="aufgabe-5" class="section level2">
<h2>Aufgabe 5</h2>
<div id="powervergleich-t-test-vs.-wilcoxon-test" class="section level3">
<h3>Powervergleich: <span class="math inline">\(t\)</span>-Test vs. Wilcoxon-Test</h3>
<p>Wir wollen nun die Power des <span class="math inline">\(t\)</span>-Tests mit der Power des Wilcoxon-Test vergleichen. Der Wilcoxon-Test ist flexibler anzuwenden, da er weniger Annahmen aufweist. Untersuchen Sie, wie sich dies auf die Power auswirkt. Das <span class="math inline">\(\alpha\)</span>-Fehlerniveau soll wieder bei <span class="math inline">\(5\%\)</span> liegen.</p>
<p>Nutzen Sie den Seed 12345 (<code>set.seed(12345)</code>).</p>
<ul>
<li>Verwenden Sie das gleiche Setting wie aus der Sitzung und bestimmen Sie die Power des Wilcoxon-Tests für <span class="math inline">\(N=20\)</span>, <span class="math inline">\(d = 0.5\)</span> und <span class="math inline">\(\alpha = 5\%\)</span>. Vergleichen Sie das Ergebnis mit dem Ergebnis aus der Sitzung.</li>
</ul>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>N &lt;- 20
set.seed(12345)
pt_H1_t &lt;- replicate(n = 10000, expr = {X &lt;- rnorm(N)
                                      Y &lt;- rnorm(N) + 0.5
                                      ttestH1 &lt;- t.test(X, Y, var.equal = TRUE)
                                      ttestH1$p.value})
mean(pt_H1_t &lt; 0.05) # empirische Power des t-Tests</code></pre>
<pre><code>## [1] 0.335</code></pre>
<pre class="r"><code>set.seed(12345)
pt_H1_W &lt;- replicate(n = 10000, expr = {X &lt;- rnorm(N)
                                      Y &lt;- rnorm(N) + 0.5
                                      wilcoxonH1 &lt;- wilcox.test(X, Y)
                                      wilcoxonH1$p.value})
mean(pt_H1_W &lt; 0.05) # empirische Power des Wilcoxon-Tests</code></pre>
<pre><code>## [1] 0.3198</code></pre>
<p>Die empirische Power liegt des <span class="math inline">\(t\)</span>-Tests liegt bei 33.5%.
Die empirische Power liegt des Wilcoxon-Tests liegt bei 31.98%. Damit fällt die Power des Wilcoxon-Test marginal geringer aus, als die des <span class="math inline">\(t\)</span>-Tests. Dies lässt sich dadurch erklären, dass die Intervallskala mehr statistische Informationen trägt. Allerdings ist der <span class="math inline">\(t\)</span>-Test anfälliger gegen Verstöße von Modellannahmen!</p>
<p>Bspw. mit solchen Fragen beschäftigen sich Methodiker aus verschiedensten Disziplinen. Wenn Sie sich dafür interessieren, fragen Sie doch gerne in einer der beiden Abteilungen nach!</p>
</details>
</div>
</div>
