---
title: Korrelation - Lösungen
author: 
date: '2021-01-04'
slug: korrelation-loesungen
categories:
  - BSc2
  - Loesungen
tags:
  - Korrelation
subtitle: ''
summary: ''
authors: [winkler, schroeder]
lastmod: '2021-01-04T13:34:32+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
expiryDate: '2022-09-15'
publishDate: '2022-01-14'
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="vorbereitung" class="section level2">
<h2>Vorbereitung</h2>
<p>Laden Sie die Daten aus <a href="/post/fb20.rda"><i class="fas fa-download"></i> <code>fb20.rda</code></a>.</p>
<pre class="r"><code>setwd(...) #auf eigenen Pfad</code></pre>
<pre class="r"><code>load(&quot;fb20.rda&quot;)</code></pre>
<hr />
</div>
<div id="korrelation" class="section level1">
<h1>Korrelation</h1>
<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<p>In der Befragung am Anfang des Semesters wurde gefragt, ob Sie neben der Uni einen Nebenjob (<code>job</code>) ausüben und in welcher Wohnsituation Sie sich befinden (<code>wohnen</code>). Erstellen Sie für diese beiden Variablen eine Kreuztabelle mit Randsummen.</p>
<ul>
<li>Stellen Sie zunächst sicher, dass die Variablen als Faktoren vorliegen und die Kategorien beider Variablen korrekt bezeichnet sind.</li>
</ul>
<pre class="r"><code>#Labels
fb20$job &lt;- factor(fb20$job, levels = c(1, 2),
  labels = c(&#39;nein&#39;, &#39;ja&#39;))
fb20$wohnen &lt;- factor(fb20$wohnen, levels = 1:4,
     label = c(&#39;WG&#39;, &#39;bei Eltern&#39;, &#39;alleine&#39;, &#39;sonstiges&#39;))

str(fb20$job)</code></pre>
<pre><code>##  Factor w/ 2 levels &quot;nein&quot;,&quot;ja&quot;: 2 1 1 2 1 1 1 1 1 NA ...</code></pre>
<pre class="r"><code>str(fb20$wohnen)</code></pre>
<pre><code>##  Factor w/ 4 levels &quot;WG&quot;,&quot;bei Eltern&quot;,..: 1 4 2 1 1 2 3 2 1 NA ...</code></pre>
<ul>
<li>Wie viele Personen wohnen in einer WG und haben keinen Nebenjob?</li>
</ul>
<pre class="r"><code># Kreuztabelle absolut
tab &lt;- table(fb20$job, fb20$wohnen)
addmargins(tab)</code></pre>
<pre><code>##       
##        WG bei Eltern alleine sonstiges Sum
##   nein 10         25      17         6  58
##   ja    9         14       4         4  31
##   Sum  19         39      21        10  89</code></pre>
<p>10 Personen wohnen in einer WG und haben keinen Nebenjob.</p>
<ul>
<li>Was ist der relative Anteil aller Teilnehmer/innen, die bei ihren Eltern wohnen?</li>
</ul>
<pre class="r"><code># Relative Haeufigkeiten, mit Randsummen
addmargins(prop.table(tab))</code></pre>
<pre><code>##       
##                WG bei Eltern    alleine  sonstiges        Sum
##   nein 0.11235955 0.28089888 0.19101124 0.06741573 0.65168539
##   ja   0.10112360 0.15730337 0.04494382 0.04494382 0.34831461
##   Sum  0.21348315 0.43820225 0.23595506 0.11235955 1.00000000</code></pre>
<p>43.82% aller Teilnehmer/innen wohnen bei ihren Eltern.</p>
<ul>
<li>Welcher Anteil der Personen, die alleine wohnen, gehen einer Nebentätigkeit nach?</li>
</ul>
<pre class="r"><code># Relative Haeufigkeiten, an wohnen normiert
prop.table(tab, 2)</code></pre>
<pre><code>##       
##               WG bei Eltern   alleine sonstiges
##   nein 0.5263158  0.6410256 0.8095238 0.6000000
##   ja   0.4736842  0.3589744 0.1904762 0.4000000</code></pre>
<p>19.05% aller Teilnehmer/innen, die alleine wohnen, gehen einer Nebentätigkeit nach.</p>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<p>Erstellen Sie für diese Kombination an Variablen ein gruppiertes Balkendiagramm.</p>
<ul>
<li>Achten Sie darauf, dass die Balken nebeneinander stehen.</li>
<li>Nutzen Sie für die Personen mit und ohne Nebenjob unterschiedliche Farben und fügen Sie eine Legende hinzu, die das verdeutlicht.</li>
</ul>
<pre class="r"><code># Gruppiertes Balkendiagramm
barplot(tab,
  beside = TRUE,             # nebeneinander
  col = c(&#39;blue&#39;, &#39;orange&#39;), # Farben definieren: Blau und Orange
  legend = rownames(tab))    # Legende einfuegen</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="aufgabe-3" class="section level2">
<h2>Aufgabe 3</h2>
<p>Welche der fünf Persönlichkeitsdimensionen Extraversion (<code>extra</code>), Verträglichkeit (<code>vertr</code>), Gewissenhaftigkeit (<code>gewis</code>), Neurotizismus (<code>neuro</code>) und Intellekt (<code>intel</code>) ist am stärksten mit der Lebenszufriedenheit korreliert (<code>lz</code>)?</p>
<ul>
<li>Überprüfen Sie die Voraussetzungen für die Pearson Korrelation.</li>
</ul>
<p><strong>Voraussetzungen Pearson-Korrelation:</strong></p>
<ol style="list-style-type: decimal">
<li>Skalenniveau: intervallskalierte Daten <span class="math inline">\(\rightarrow\)</span> ok<br />
</li>
<li>Linearität: Zusammenhang muss linear sein <span class="math inline">\(\rightarrow\)</span> Grafische überprüfung (Scatterplot)</li>
</ol>
<pre class="r"><code># Scatterplot
plot(fb20$extra, fb20$lz, 
  xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>plot(fb20$vertr, fb20$lz, 
  xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<pre class="r"><code>plot(fb20$gewis, fb20$lz, 
  xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-8-3.png" width="672" /></p>
<pre class="r"><code>plot(fb20$neuro, fb20$lz, 
  xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-8-4.png" width="672" /></p>
<pre class="r"><code>plot(fb20$intel, fb20$lz, 
  xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-8-5.png" width="672" />
3. Normalverteilung <span class="math inline">\(\rightarrow\)</span> QQ-Plot, Histogramm oder Shapiro-Wilk-Test</p>
<p><strong>zu 3. Normalverteilung</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> QQ-Plot, Histogramm &amp; Shapiro-Wilk-Test</p>
<pre class="r"><code>#Shapiro
shapiro.test(fb20$extra)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb20$extra
## W = 0.97493, p-value = 0.05771</code></pre>
<pre class="r"><code>shapiro.test(fb20$vertr)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb20$vertr
## W = 0.92572, p-value = 3.422e-05</code></pre>
<pre class="r"><code>shapiro.test(fb20$gewis)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb20$gewis
## W = 0.94789, p-value = 0.0006967</code></pre>
<pre class="r"><code>shapiro.test(fb20$neuro)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb20$neuro
## W = 0.97094, p-value = 0.02857</code></pre>
<pre class="r"><code>shapiro.test(fb20$intel)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb20$intel
## W = 0.97127, p-value = 0.03028</code></pre>
<pre class="r"><code>shapiro.test(fb20$lz)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  fb20$lz
## W = 0.96784, p-value = 0.01847</code></pre>
<p><span class="math inline">\(p &lt; \alpha\)</span> <span class="math inline">\(\rightarrow\)</span> H1: Normalverteilung kann nicht angenommen werden. Somit ist diese Voraussetzung verletzt. Daher muss die Rangkorrelation nach Spearman genutzt werden.</p>
<ul>
<li>Erstellen Sie für diese Frage eine Korrelationsmatrix, die alle Korrelationen enthält. Verwenden Sie die Funktion <code>round()</code> (unter Betrachtung der Hilfe), um die Werte auf zwei Nachkommastellen zu runden und die Tabelle dadurch übersichtlicher darzustellen.</li>
</ul>
<pre class="r"><code># Variablen in neuem Datensatz ablegen
big5lz &lt;- fb20[, c(&#39;lz&#39;, &#39;extra&#39;, &#39;vertr&#39;, &#39;gewis&#39;, &#39;neuro&#39;, &#39;intel&#39;)]
# Korrelationstabelle erstellen und runden
round(cor(big5lz, use = &quot;pairwise&quot;, method = &quot;spearman&quot;),2)</code></pre>
<pre><code>##          lz extra vertr gewis neuro intel
## lz     1.00  0.23 -0.02  0.27 -0.26  0.18
## extra  0.23  1.00  0.07  0.13  0.05  0.26
## vertr -0.02  0.07  1.00  0.16  0.08  0.10
## gewis  0.27  0.13  0.16  1.00 -0.08  0.24
## neuro -0.26  0.05  0.08 -0.08  1.00 -0.10
## intel  0.18  0.26  0.10  0.24 -0.10  1.00</code></pre>
<ul>
<li>Wie würden Sie das Ausmaß dieser Korrelation nach den Richtlinien von Cohen (1988) einschätzen?</li>
</ul>
<p>Die größte Korrelation mit der Lebenszufriedenheit hat die Gewissenhaftigkeit. Nach den Richtlinien ist diese mit 0.27 einem positiven mittleren Effekt, der ungeähr 0.3 beträgt, zuzuordnen.</p>
<ul>
<li>Ist der Korrelationskoeffizienten von Lebenszufriedenheit und Gewissenhaftigkeit signifikant?</li>
</ul>
<pre class="r"><code>cor.test(fb20$lz, fb20$gewis, 
         alternative = &quot;two.sided&quot;, 
         method = &quot;spearman&quot;,       
         use = &quot;complete.obs&quot;)</code></pre>
<pre><code>## Warning in cor.test.default(fb20$lz, fb20$gewis, alternative = &quot;two.sided&quot;, :
## Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  fb20$lz and fb20$gewis
## S = 107277, p-value = 0.007253
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.2724035</code></pre>
<p><span class="math inline">\(p &lt; \alpha\)</span> <span class="math inline">\(\rightarrow\)</span> H1. Die Korrelation ist mit einer Irrtumswahrscheinlichkeit von 5% signifikant von 0 verschieden.</p>
</div>
<div id="aufgabe-4" class="section level2">
<h2>Aufgabe 4</h2>
<p>Das Paket <code>psych</code> enthält vielerlei Funktionen, die für die Analyse von Datensätzen aus psychologischer Forschung praktisch sind. Eine von ihnen (<code>describe()</code>) erlaubt es, gleichzeitig verschiedene Deskriptivstatistiken für Variablen zu erstellen.</p>
<ul>
<li>Installieren und laden Sie das Paket <code>psych</code>.</li>
</ul>
<pre class="r"><code># Paket installieren
install.packages(&#39;psych&#39;)</code></pre>
<pre class="r"><code># Paket laden
library(psych)</code></pre>
<pre><code>## Warning: Paket &#39;psych&#39; wurde unter R Version 4.1.1 erstellt</code></pre>
<ul>
<li>Nutzen Sie den neugewonnen Befehl <code>describe()</code>, um sich gleichzeitig die verschiedenen Deskriptivstatistiken für Lebenszufriedenheit (<code>lz</code>) ausgeben zu lassen.</li>
</ul>
<pre class="r"><code>describe(big5lz$lz)</code></pre>
<pre><code>##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 96 5.04 1.15    5.2    5.09 1.19 2.4   7   4.6 -0.43    -0.51 0.12</code></pre>
<ul>
<li><code>describe()</code> kann auch genutzt werden, um gleichzeitig Deskriptivstatistiken für verschiedene Variablen zu berechnen. Nutzen Sie diese Funktionalität, um sich gleichzeitg die univariaten Deskriptivstatistiken für die fünf Persönlichkeitsdimensionen ausgeben zu lassen.</li>
</ul>
<pre class="r"><code>describe(big5lz[,-1]) #Spalte für `lz` wird ausgeschlossen</code></pre>
<pre><code>##       vars  n mean   sd median trimmed  mad  min max range  skew kurtosis   se
## extra    1 98 3.46 0.69   3.50    3.46 0.74 2.00   5  3.00 -0.04    -0.76 0.07
## vertr    2 98 4.31 0.53   4.50    4.34 0.74 3.00   5  2.00 -0.41    -0.90 0.05
## gewis    3 98 4.08 0.65   4.00    4.12 0.74 2.00   5  3.00 -0.62     0.08 0.07
## neuro    4 98 3.47 0.76   3.50    3.51 0.74 1.75   5  3.25 -0.34    -0.55 0.08
## intel    5 98 3.72 0.60   3.75    3.72 0.37 2.25   5  2.75  0.02    -0.07 0.06</code></pre>
<hr />
</div>
</div>
<div id="regression" class="section level1">
<h1>Regression</h1>
<div id="aufgabe-5" class="section level2">
<h2>Aufgabe 5</h2>
<p>Welche der fünf Persönlichkeitsdimensionen Extraversion (<code>extra</code>), Verträglichkeit (<code>vertr</code>), Gewissenhaftigkeit (<code>gewis</code>), Neurotizsimus (<code>neuro</code>) und Intellekt (<code>intel</code>) zeigt den höchsten linearen Zusammenhang mit der Lebenszufriedenheit (<code>lz</code>)?</p>
<ul>
<li>Erstellen Sie für jeden Zusammenhang je ein Streudiagramm.
<strong><code>extra</code>:</strong></li>
</ul>
<pre class="r"><code>plot(fb20$extra, fb20$lz, xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p><strong><code>vertr</code>:</strong></p>
<pre class="r"><code>plot(fb20$vertr, fb20$lz, xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p><strong><code>gewis</code>:</strong></p>
<pre class="r"><code>plot(fb20$gewis, fb20$lz, xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p><strong><code>neuro</code>:</strong></p>
<pre class="r"><code>plot(fb20$neuro, fb20$lz, xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p><strong><code>intel</code>:</strong></p>
<pre class="r"><code>plot(fb20$intel, fb20$lz, xlim = c(0, 6), ylim = c(0, 7), pch = 19)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<ul>
<li>Schätzen Sie für jeden Zusammenhang je ein Modell.
<strong><code>extra</code>:</strong></li>
</ul>
<pre class="r"><code>fme &lt;- lm(lz ~ extra, fb20)
lm(formula = lz ~ 1 + extra, data = fb20)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ 1 + extra, data = fb20)
## 
## Coefficients:
## (Intercept)        extra  
##      3.8119       0.3538</code></pre>
<pre class="r"><code>coef(fme) </code></pre>
<pre><code>## (Intercept)       extra 
##    3.811938    0.353777</code></pre>
<pre class="r"><code>summary(fme)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ extra, data = fb20)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.9155 -0.5954  0.1267  0.7498  2.0152 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.8119     0.5835   6.533 3.28e-09 ***
## extra         0.3538     0.1654   2.139    0.035 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.126 on 94 degrees of freedom
##   (2 Beobachtungen als fehlend gelöscht)
## Multiple R-squared:  0.04641,    Adjusted R-squared:  0.03626 
## F-statistic: 4.575 on 1 and 94 DF,  p-value: 0.03504</code></pre>
<pre class="r"><code>formula(fme)</code></pre>
<pre><code>## lz ~ extra</code></pre>
<p><strong><code>vertr</code>:</strong></p>
<pre class="r"><code>fmv &lt;- lm(lz ~ vertr, fb20)
lm(formula = lz ~ 1 + vertr, data = fb20) </code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ 1 + vertr, data = fb20)
## 
## Coefficients:
## (Intercept)        vertr  
##     5.38964     -0.08204</code></pre>
<pre class="r"><code>coef(fmv) </code></pre>
<pre><code>## (Intercept)       vertr 
##  5.38963502 -0.08203851</code></pre>
<pre class="r"><code>summary(fmv)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ vertr, data = fb20)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.6000 -0.7846  0.1693  0.8449  2.0206 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  5.38964    0.96132   5.607 2.06e-07 ***
## vertr       -0.08204    0.22097  -0.371    0.711    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.152 on 94 degrees of freedom
##   (2 Beobachtungen als fehlend gelöscht)
## Multiple R-squared:  0.001464,   Adjusted R-squared:  -0.009159 
## F-statistic: 0.1378 on 1 and 94 DF,  p-value: 0.7113</code></pre>
<pre class="r"><code>formula(fmv)</code></pre>
<pre><code>## lz ~ vertr</code></pre>
<p><strong><code>gewis</code>:</strong></p>
<pre class="r"><code>fmg &lt;- lm(lz ~ gewis, fb20)
lm(formula = lz ~ 1 + gewis, data = fb20) #Koeffizienten anzeigen, alternativ mit coef</code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ 1 + gewis, data = fb20)
## 
## Coefficients:
## (Intercept)        gewis  
##      2.9038       0.5204</code></pre>
<pre class="r"><code>coef(fmg) </code></pre>
<pre><code>## (Intercept)       gewis 
##   2.9037996   0.5203693</code></pre>
<pre class="r"><code>summary(fmg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ gewis, data = fb20)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8455 -0.7256  0.2147  0.7696  2.1351 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.9038     0.7623   3.809 0.000249 ***
## gewis         0.5204     0.1840   2.827 0.005733 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.107 on 94 degrees of freedom
##   (2 Beobachtungen als fehlend gelöscht)
## Multiple R-squared:  0.07838,    Adjusted R-squared:  0.06858 
## F-statistic: 7.995 on 1 and 94 DF,  p-value: 0.005733</code></pre>
<pre class="r"><code>formula(fmg)</code></pre>
<pre><code>## lz ~ gewis</code></pre>
<p><strong><code>neuro</code>:</strong></p>
<pre class="r"><code>fmn &lt;- lm(lz ~ neuro, fb20)
lm(formula = lz ~ 1 + neuro, data = fb20) </code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ 1 + neuro, data = fb20)
## 
## Coefficients:
## (Intercept)        neuro  
##      6.3692      -0.3848</code></pre>
<pre class="r"><code>coef(fmn) </code></pre>
<pre><code>## (Intercept)       neuro 
##   6.3692259  -0.3848105</code></pre>
<pre class="r"><code>summary(fmn)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ neuro, data = fb20)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.1996 -0.8464  0.1700  0.8055  1.8738 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   6.3692     0.5298  12.021   &lt;2e-16 ***
## neuro        -0.3848     0.1493  -2.577   0.0115 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.114 on 94 degrees of freedom
##   (2 Beobachtungen als fehlend gelöscht)
## Multiple R-squared:  0.06601,    Adjusted R-squared:  0.05607 
## F-statistic: 6.643 on 1 and 94 DF,  p-value: 0.01151</code></pre>
<pre class="r"><code>formula(fmn)</code></pre>
<pre><code>## lz ~ neuro</code></pre>
<p><strong><code>intel</code>:</strong></p>
<pre class="r"><code>fmi &lt;- lm(lz ~ intel, fb20)
lm(formula = lz ~ 1 + intel, data = fb20) </code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ 1 + intel, data = fb20)
## 
## Coefficients:
## (Intercept)        intel  
##       3.893        0.307</code></pre>
<pre class="r"><code>coef(fmi) </code></pre>
<pre><code>## (Intercept)       intel 
##   3.8930403   0.3069787</code></pre>
<pre class="r"><code>summary(fmi)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ intel, data = fb20)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.9512 -0.8675  0.2709  0.8099  2.3395 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.8930     0.7317   5.320    7e-07 ***
## intel         0.3070     0.1941   1.581    0.117    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.138 on 94 degrees of freedom
##   (2 Beobachtungen als fehlend gelöscht)
## Multiple R-squared:  0.02591,    Adjusted R-squared:  0.01555 
## F-statistic:   2.5 on 1 and 94 DF,  p-value: 0.1172</code></pre>
<pre class="r"><code>formula(fmi)</code></pre>
<pre><code>## lz ~ intel</code></pre>
<p>Wenn wir die Koeffizienten der Modelle vergleichen, sehen wir, dass <code>gewis</code> den größten linearen Zusammenhang mit <code>lz</code> aufweist</p>
<ul>
<li>Prüfen Sie die Voraussetzungen und interpretieren Sie den standardisierten Koeffizienten des linearen Zusammenhangs zwischen Gewissenhaftigkeit und Lebenszufriedenheit. Wie verändert sich <code>lz</code>, wenn sich <code>gewis</code> um eine Standardabweichung erhöht?</li>
</ul>
<div id="voraussetzungen" class="section level3">
<h3>Voraussetzungen:</h3>
<ol style="list-style-type: decimal">
<li>Linearität: Zusammenhang muss linear sein <span class="math inline">\(\rightarrow\)</span> Grafische Überprüfung (Scatterplot)<br />
</li>
<li>Varianzhomogenität (Homoskedastizität) der Fehler: der Fehler jedes Wertes der UV hat annährend die gleiche Varianz<br />
</li>
<li>Normalverteilung der Fehlervariablen<br />
</li>
<li>Unabhängigkeit der Fehler</li>
</ol>
<p>Die Voraussetzungen 2-4 können erst geprüft werden, nachdem das Modell schon gerechnet wurde, weil sie sich auf die Fehler (Residuen: Differenz aus beobachtetem und vorhergesagtem Wert für y) beziehen!</p>
<p><strong>zu 1. Linearität: Zusammenhang muss linear sein <span class="math inline">\(\rightarrow\)</span> Grafische Überprüfung (Scatterplot)</strong></p>
<pre class="r"><code>plot(fb20$gewis, fb20$lz, xlab = &quot;Gewissenhaftigkeit&quot;, ylab = &quot;Lebenszufriedenheit&quot;, 
     main = &quot;Zusammenhang zwischen Gewissenhaftigkeit und Lebenszufriedenheit&quot;, xlim = c(0, 6), ylim = c(0, 7), pch = 19)
lines(loess.smooth(fb20$gewis, fb20$lz), col = &#39;blue&#39;)    #beobachteter, lokaler Zusammenhang
fmg &lt;- lm(lz ~ gewis, fb20)                              #Modell erstellen und ablegen
abline(fmg, col = &quot;red&quot;)                                  #Modellierter linearer Zusammenhang in zuvor erstellten Plot einzeichnen</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p><strong>zu Voraussetzungen 2-4:</strong></p>
<pre class="r"><code>par(mfrow = c(2, 2)) #Vier Abbildungen gleichzeitig
plot(fmg)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 1)) #wieder auf eine Abbildung zurücksetzen</code></pre>
<p>In diesem Fall ist alles weitestgehend erfüllt.</p>
<pre class="r"><code>sfmg &lt;- lm(scale(lz) ~ scale(gewis), fb20)
sfmg</code></pre>
<pre><code>## 
## Call:
## lm(formula = scale(lz) ~ scale(gewis), data = fb20)
## 
## Coefficients:
##  (Intercept)  scale(gewis)  
##    -0.007837      0.293899</code></pre>
<p>Wenn sich die Variable <code>gewis</code> um eine Standardabweichung verändert, verändert sich das Kriterium <code>lz</code> um 0,294 Standardabweichungen.</p>
</div>
</div>
<div id="aufgabe-6" class="section level2">
<h2>Aufgabe 6</h2>
<p>Ein paar Studierende wurden nachträglich zum Studiengang Psychologie zugelassen und befinden sich daher nicht im Datensatz. Die neuen Studenten wurden nachträglich befragt und weisen auf der Skala Neurotizismus folgende Werte auf: 1.25; 2.75; 3.5; 4.25; 3.75; 2.15.</p>
<ul>
<li>Machen Sie eine Vorhersage für die Lebenszufriedenheit für die neuen Studenten.</li>
</ul>
<pre class="r"><code>new &lt;- data.frame(neuro = c(1.25, 2.75, 3.5, 4.25, 3.75, 2.15))
predict(fmn, newdata = new)</code></pre>
<pre><code>##        1        2        3        4        5        6 
## 5.888213 5.310997 5.022389 4.733781 4.926187 5.541883</code></pre>
<ul>
<li>Erstellen Sie ein Streu-Punkt-Diagramm mit Regressionsgerade für den linearen Zusammenhang zwischen Neurotizismus und Lebenszufriedenheit.</li>
</ul>
<pre class="r"><code>plot(fb20$neuro, fb20$lz, xlim = c(0, 6), ylim = c(0, 7), pch = 19)
abline(fmn, col = &quot;red&quot;)</code></pre>
<p><img src="/post/2021-09-20-korrelation-loesungen_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<ul>
<li>Wie viel Prozent der Varianz werden durch das Modell erklärt?</li>
</ul>
<pre class="r"><code>summary(fmn)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lz ~ neuro, data = fb20)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.1996 -0.8464  0.1700  0.8055  1.8738 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   6.3692     0.5298  12.021   &lt;2e-16 ***
## neuro        -0.3848     0.1493  -2.577   0.0115 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.114 on 94 degrees of freedom
##   (2 Beobachtungen als fehlend gelöscht)
## Multiple R-squared:  0.06601,    Adjusted R-squared:  0.05607 
## F-statistic: 6.643 on 1 and 94 DF,  p-value: 0.01151</code></pre>
<p>R² = 0.066 –&gt; 6,6% der Varianz von <code>lz</code> werden durch das Modell erklärt. Determinationskoeffizient <span class="math inline">\(R^2\)</span> ist signifikant.</p>
<hr />
</div>
</div>
