---
title: Korrelation - Aufgaben
author: 
date: '2021-11-19'
slug: korrelation-aufgaben
categories:
  - BSc2
  - Aufgaben
tags:
  - Korrelation
subtitle: ''
summary: ''
authors: [winkler, schroeder]
lastmod: '2021-12-13T13:18:56+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Vorbereitung
Laden Sie den Datensatz `fb21` wie gewohnt ein.

***
# Korrelation

## Aufgabe 1

In der Befragung am Anfang des Semesters wurde gefragt, ob Sie neben der Uni einen Nebenjob (`job`) ausüben und in welcher Wohnsituation Sie sich befinden (`wohnen`). Erstellen Sie für diese beiden Variablen eine Kreuztabelle mit Randsummen.

  * Stellen Sie zunächst sicher, dass die Variablen als Faktoren vorliegen und die Kategorien beider Variablen korrekt bezeichnet sind. 
  * Wie viele Personen wohnen in einer WG und haben keinen Nebenjob? 
  * Was ist der relative Anteil aller Teilnehmer/innen, die bei ihren Eltern wohnen?
  * Welcher Anteil der Personen, die alleine wohnen, gehen einer Nebentätigkeit nach?

## Aufgabe 2

Erstellen Sie für diese Kombination an Variablen ein gruppiertes Balkendiagramm.

  * Achten Sie darauf, dass die Balken nebeneinander stehen.
  * Nutzen Sie für die Personen mit und ohne Nebenjob unterschiedliche Farben und fügen Sie eine Legende hinzu, die das verdeutlicht.


## Aufgabe 3

Welche der fünf Persönlichkeitsdimensionen Extraversion (`extra`), Verträglichkeit (`vertr`), Gewissenhaftigkeit (`gewis`), Neurotizismus (`neuro`) und Intellekt (`intel`) ist am stärksten mit der Lebenszufriedenheit korreliert (`lz`)?

  * Überprüfen Sie die Voraussetzungen für die Pearson Korrelation.
  * Erstellen Sie für diese Frage eine Korrelationsmatrix, die alle Korrelationen enthält. Verwenden Sie die Funktion `round()` (unter Betrachtung der Hilfe), um die Werte auf zwei Nachkommastellen zu runden und die Tabelle dadurch übersichtlicher darzustellen.
  * Wie würden Sie das Ausmaß dieser Korrelation nach den Richtlinien von Cohen (1988) einschätzen?
  * Ist der Korrelationskoeffizient von Lebenszufriedenheit und Gewissenhaftigkeit statistisch signifikant?

## Aufgabe 4
Berechnen sie die Pearson Korrelation, die Spearman Korrelation, Kendall's Tau sowie $\hat{\gamma}$ für den Zusammenhang von `prok1` und `prok6`.

## Aufgabe 5

Das Paket `psych` enthält vielerlei Funktionen, die für die Analyse von Datensätzen aus psychologischer Forschung praktisch sind. Eine von ihnen (`describe()`) erlaubt es, gleichzeitig verschiedene Deskriptivstatistiken für Variablen zu erstellen.

  * Installieren und laden Sie das Paket `psych`.
  * Nutzen Sie den neugewonnen Befehl `describe()`, um sich gleichzeitig die verschiedenen Deskriptivstatistiken für Lebenszufriedenheit (`lz`) ausgeben zu lassen. 
  * `describe()` kann auch genutzt werden, um gleichzeitig Deskriptivstatistiken für verschiedene Variablen zu berechnen. Nutzen Sie diese Funktionalität, um sich gleichzeitg die univariaten Deskriptivstatistiken für die fünf Persönlichkeitsdimensionen ausgeben zu lassen.
    
***
