---
title: Git-Intro
date: '2021-06-13'
slug: gitintro
categories:
  - "gitintro"
tags: []
subtitle: ''
summary: ''
authors: [nehler, rouchi]
featured: no
header:
  image: ""
  caption: ""
projects: []
publishDate: '2021-07-11'
---


# Warum Git?

Stellt euch die typische Ordnerstruktur eine/r Studierenden bei der Abgabge einer Haus- oder Abschlussarbeit vor. Die einzelnen Dateien heißen wohl in den meisten Fällen "finale_version", "finale_version2" und "wirklich_finale_version". Neben der Verwendung einer großen Menge an Speicherplatz kann dies auch dazu führen, dass man sich fragt, welche Version wirklich die letzte war.  Bei Auswertungs-Skripten von Daten ist dies wohl nicht sehr unterschiedlich. Mit Git wollen wir euch eine Möglichkeit zeigen, wie diese Menge an verschiedenen Daten nicht entstehen muss und sogar die Änderungen durch Ergänzungen oder Korrekturen stets dokumentiert und benannt werden können. Es muss also nur ein einzlenes Dokument geben, zu dem man die Historie jederzeit nachvollziehen kann.


## Einführung

Ganz grundlegend ist `git` also eine Software, die der Versionsverwaltung dient. Zur Zeit ist es das weltweit am meisten eingesetzte Verwaltungssystem und gilt auch in der Softwareentwicklung als state-of-the-art. Es wurde von Linux-Kernel-Entwickler Linus Torvalds entwickelt und auch für das Management des Linux-Codes verwendet. Ein Vorteil besteht dabei trotzdem darin, dass es plattformunabhängig ist (auf allen Betriebssystemen eingesetzt werden kann). Außerdem wurde es unter der freien GNU-GPLv2-Lizenz veröffentlicht und kann dadurch - wie auch `R` - von uns kostenlos verwendet werden. Dabei braucht man zunächst auch keine Unterstützung eines Servers - die Software läuft auf dem eigenen PC als lokale Versionskontrolle. Natürlich kann man zur Kollaboration auch eine Online-Variante verwenden, doch dies wird in späteren Teilen des Git-Tutorials gezeigt. `git` ist ein schnelles und leistungsfähiges Programm. Zunächst ist ein Invest in das Erlernen der Befehle und Strukturen unvermeidlich, doch danach kann es den Alltag in der Erstellung von Skripten stark vereinfachen.

Die Anwendung von `git` wollen wir natürlich in einem Beispiel erläutern. Abschlussarbeiten schreiben die meisten Psychologiestudierenden typischerweise in Word, für das `git` jedoch nicht optimiert ist. Ein Worddokument kann zwar problemlos in einem git-Ordner existieren, aber die Änderungen nicht gut getracked werden. Für eine optimale Verwendung im Rahmen einer Abschlussarbeit müsste diese zunächst in einem .txt-Dokument geschrieben und erst zum Abschluss in ein Worddokument kopiert werden. Im Gegensatz zu Word ist die Verwendung von Latex optimiert, falls jemand es verwendet - Latex ist kein Teil dieses Tutorials (eventuell wird es später hierfür ein eigenes geben). Der sofortige Einsatz im Rahmen unseres Studiums ist bei R-Skripten möglich, weshalb wir uns in diesem Beispiel an einer (oberflächlichen) Erstellung orientieren.

# Setup

Damit ihr `git` mit eurem  Computer verwenden könnt, muss zunächst natürlich das Programm installiert und aufbereitet werden. Hier also eine schrittweise Einleitung zum **Setup**:


### Schritt 1: `git` installieren

Zunächst einmal muss `git` auf dem lokalen Rechner installiert werden. Das Programm könnt ihr [hier](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) herunterladen. Auf dieser Seite gibt es verschiedene Anleitungen für die Installation mit den Softwareprogrammen Windows, macOS und Linux - je nachdem was für einen Rechner ihr habt.

Sobald `git` installiert ist, könnt ihr über das Terminal eures PCs darauf zugreifen. Bei Windows-Rechnern kann man über das Start-Menü nach `cmd` suchen und kann so die **Eingabeaufforderung** aufrufen. Bei macOS & Linux kann einfach nach **Terminal** gesucht werden. Im Folgenden reden wir von **Terminal**, wenn wir uns auf die Eingabeaufforderung beziehen.

Das Terminal sieht ungefähr folgendermaßen aus:

*Screenshot Terminal*

Es wurden für `git` im Laufe der Jahre auch einige benutzerfreundlichere Oberflächen erstellt. Wir wollen zunächst die Basics trotzdem mit dem Terminal bearbeiten, da es wichtig ist, nachvollziehen zu können wie `git` funktioniert und was im Hintergrund passiert. In SmartGit wird ein Programm mit  benutzerfreundlichere Oberfläche in einem späteren Tutorial beschrieben.

Wenn ihr `git` installiert habt, könnt ihr 

```
git --version
```
in das Terminal eingeben, um zu sehen, ob die Installation funktioniert habt und welche Version ihr nutzt.


Damit andere erkennen können, wer welche Änderung an `git`-Dateien vorgenommen hat, ist es zunächst einmal wichtig, dass ihr euch einen Usernamen gebt. Das geht über

```
git config --global user.name "DeinName"
```

Die Konfigurationen können dann mit diesem Befehl betrachtet werden. Der Name sollte nun unter `user.name` erscheinen.

```
git config --list
```

*Screenshot mit allen vorherigen Befehlen auf einmal*





### Schritt 2: Lokales `git repository` erstellen

Damit ein neues lokales `git`-Projekt auf dem Rechner angelegt werden kann, muss zuerst ein sogenanntes `repository` erstellt werden. Das können wir direkt in der Eingabeaufforderung tun.

Über den folgenden Befehl können wir vom aktuellen Ordner aus, in dem wir uns in der Dateistruktur im Terminal befinden, in einen Ordner wechseln, wo unser Projekt angelegt werden soll. 

```
cd Dateipfad
```

Für unsere Zwecke möchten wir ein Projekt anlegen, das wir für das Statistik-Praktikum im Bachelor benötigen. Wir haben beispielsweise eine Umfrage durchgeführt und wollen anhand von R unsere Daten auswerten. Damit wir später mit unseren Kommiliton:innen zusammen an den Daten arbeiten und alle Änderungen nachvollziehen können, wollen wir einen `git`-Ordner erstellen. Wir könnten hierin mehrere Dateien speichern - beispielsweise unsere R-Skripte oder ein Kodierungssheet für eine Variablenübersicht unserer Daten.

Über den folgenden Befehl können wir den Ordner "praktikum" nun erstellen.

```
mkdir praktikum
```
Nun kann man mittels des bereits verwendeten `cd` in den Ordner navigieren, den wir gerade für unser Projekt angelegt haben.
```
cd ./praktikum
``` 
Natürlich könnte der Ordner auch im normalen Dateiexplorer erstellt werden. Für den Start mit `git` ist es jedoch entscheidend wichtig, im Terminal über `cd` in den Praktikumsordner zu gelangen.

Um den Ordner als `git`-Ordner zu initialisieren, muss ein Befehl in das Terminal eingegeben werden. Diese Initialisierung ist notwendig, da eine Installation von `git` nicht gleich bedeutet, dass jeder Ordner automatisch von dem Programm getracked wird. Die Projekte, auf die es angewendet werden soll, werden vom Benutzenden durch die Initialisierung gekennzeichnet.

```
git init
``` 

Jetzt habt ihr den Ordner für die Auswertung auf euren Rechnern erstellt. Dieser ist mit `git` verknüpft und somit können alle `git`-Befehle im Terminal auf ihm ausgeführt werden.

*Screenshot*


### Schritt 3: Eine neue Datei dem `repository` hinzufügen

Anhand von R-Studio können wir jetzt Skripte für unsere Datenaus- und aufbereitung erstellen. Das R-Skript für die Datenauswertung nennen wir `Datenauswertung.R`. Diese können wir einfach in unseren Ordner `praktikum` ablegen.
Über 
```
git status
```
können wir abrufen, welche Dateien in unserem Ordner liegen und an welchen Dateien welche Veränderungen vorgenommen wurden.
Hier erscheint eine Warnmeldung. `git` teilt uns mit, dass in unserem Ordner "untracked files" vorliegen. Wie wir das beheben können, schauen wir uns gleich im Abschnitt zum `staging environment` an.

*Screenshot für beide Befehle*

Jetzt haben wir `git` installiert, können über die Eingabeaufforderung darauf zugreifen und haben unser Projekt "praktikum" lokal auf unserem Rechner erstellt und ihm R-Dateien hinzugefügt. Jetzt wäre noch wichtig zu lernen, wie man grundlegende Funktionen von `git` nutzen kann.



# Basics

Im Folgenden werden die wichtigsten Befehle und Konzepte von `git` erläutert, damit das Programm effektiv genutzt werden kann.


### Commit

Ein `commit`ist mehr oder weniger wie die Aufzeichnung von Veränderungen, die seit dem letzten Mal am `repository` vorgenommen wurden. Im Prinzip wird dieses verändert (indem eine Datei hinzugefügt oder verändert wird) und dann wird `git` dazu aufgefordert, diese Veränderungen in einen `commit` zu verwandeln.
Mithilfe von `commits` könnte man bei Dateien beispielsweise zu dem Stand von jedem vorherigen `commit` zurückkehren. Wenn ihr beispielsweise eurem R-Skript `Datenauswertung.R` einen Befehl hinzufügt und diesen speichern wollt, müsst ihr die Änderungen commiten, damit diese auf das `repository` übertragen werden. Falls ihr die Änderungen am Skript rückgängig machen wollt, könnt ihr zum Zustand vor dem letzten `commit` zurückkehren. Es handelt sich hier also um eine Art Zwischenspeicherung von Änderungen an den lokalen Dateien.


### Staging environment

Um `git` mitzuteilen, welche Veränderungen von welchen Dateien in ein `commit` umgesetzt werden sollen, wird das `staging environment` benötigt. Die Staging Area hält alle Änderungen, die im nächsten `commit` enthalten sein werden.
Um eine Datei zu einem `commit` hinzuzufügen, muss dieses zunächst ins `staging environment` geladen werden. Dies geht über 
```
git add Datenauswertung.R
```
Mithilfe von 
```
git status
```
sieht man jetzt, dass das R-Skript in das `staging environment` geladen wurde. Jetzt kann ein `commit`erstellt werden!

*Screenshot*


#### Ein `commit` erstellen

Um ein `commit` zu erstellen, muss 
```
git commit -m "commit-Nachricht"
```
in das Terminal eingegeben werden. Die `commit`-Nachricht sollte sich darauf beziehen, was der `commit` beinhaltet, also welche Änderungen vorgenommen wurden. Hierbei bietet es sich an, eine präzise Beschreibung der Änderungen zu hinterlassen, damit man zu einem späteren Zeitpunkt nachvollziehen kann, was gemacht wurde. Wie es geändert wurde kann man sich in dem Änderungstracker anschauen.

*Screenshot*


#### Beispiel: Datei verändern

Anhand unserer Datei `Datenauswertung.R` schauen wir uns jetzt an, wie wir vorgenommene Änderungen in unserem `git`-Projekt commiten können.

Zunächst können wir in die `R`-Datei gehen und etwas am Skript verändern. Beispielsweise können wir einen Boxplot für unsere `variable1` erstellen. Dafür müssen folgende Schritte erfolgen:

 1. Änderung an der `R`-Datei vornehmen
 2. mit `git add Datenauswertung.R` die veränderte Datei in das `staging environment` laden
 3. mit `git commit -m "Add boxplot"` die Veränderungen an der Datei commiten
 
Jetzt wurden alle Veränderungen an der Datei in `git` übertragen.

*Screenshot*


### `commit`-History

Um nachvollziehen zu können, welche Änderungen an welchen Datein vorgenommen wurden, kann man über
```
git log
```
eine Übersicht über alle vergangenen `commit`s abrufen. Anhand der `commit`-Nachrichten kann nachvollzogen werden, zu welchem Zeitpunkt was verändert wurde.

*Screenshot*

Jetzt könnten wir noch weitere Dateien für unser Statistik-Praktikum erstellen, diese in unseren Ordner "praktikum" laden und Veränderungen mithilfe von `git` nachverfolgen. Zusätzlich zur Datenauswertung, könnten wir Kodierungssheets, Abbildungen oder Textdateien in unser Projekt laden.

Mit diesen Basic-Funktionen von `git` kann man einfach lokale Projekte erstellen, diesen Dateien hinzufügen und Änderungen mithilfe von `commits` nachverfolgen. Um lokale Projekte mit anderen Personen teilen zu können oder gemeinsam an diesen arbeiten zu können, kann `GitHub` genutzt werden. Dazu mehr in der nächsten Sitzung.





