---
title: Tests für abhängige Stichproben - Lösungen
date: '2022-12-13'
slug: gruppenvergleiche-abhaengig-loesungen
categories:
  - BSc2
tags:
  - t-Test
subtitle: ''
summary: ''
authors: [koehler, buchholz]
lastmod: '2022-12-22T13:15:14+01:00'
featured: no
header:
  image: "/header/BSc2_test_abh_stpr.jpg"
  caption: "[Courtesy of pxhere](https://pxhere.com/en/photo/449195)"
projects: []
expiryDate: '2023-09-15'
publishDate: '2023-01-06'
---



<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<p>Unterscheidet sich im Durchschnitt die Angabe von Psychologiestudierenden zu ihrer Prokrastinationstendenz, wenn sie positiv formulierte Items (prok1, prok4, prok6, prok9, prok10) beantworten im Vergleich zu negativ formulierten Items (prok2, prok3, prok5, prok7 und prok8)?</p>
<details>
<summary>
Lösung
</summary>
<pre class="r"><code>setwd(&quot;...&quot;)
load(&quot;fb22.rda&quot;)</code></pre>
<p>Die Skala “Prokrastination” soll bei hohen Werten eine höhere Prokrastinationstendenz darstellen. Um zu vergleichen, ob die Zustimmung je nach Itemformulierung (pos. vs. neg.) anders ausfällt, müssen wir die negativ formulierten Items zunächst rekodieren (wurde im Seminar bereits durchgeführt).</p>
<pre class="r"><code>fb22$prok2_r &lt;- -1 * (fb22$prok2 - 5)
fb22$prok3_r &lt;- -1 * (fb22$prok3 - 5)
fb22$prok5_r &lt;- -1 * (fb22$prok5 - 5)
fb22$prok7_r &lt;- -1 * (fb22$prok7 - 5)
fb22$prok8_r &lt;- -1 * (fb22$prok8 - 5)</code></pre>
<p>Anschließend bilden wir für jede Person ihren Mittelwert auf den positiv formulierten Items sowie ihren Mittelwert auf den negativ formulierten Items.</p>
<pre class="r"><code># Skalenbildung
prokrast_pos &lt;- fb22[, c(&#39;prok1&#39;, &#39;prok4&#39;,  &#39;prok6&#39;,
                         &#39;prok9&#39;, &#39;prok10&#39;)]
prokrast_pos$mean &lt;- rowMeans(prokrast_pos,na.rm = T)

prokrast_neg &lt;- fb22[, c(&#39;prok2_r&#39;, &#39;prok3_r&#39;,
                         &#39;prok5_r&#39;, &#39;prok7_r&#39;,
                         &#39;prok8_r&#39;)]
prokrast_neg$mean &lt;- rowMeans(prokrast_neg,na.rm = T)</code></pre>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: grafisch</strong></p>
<p>Je ein Histogramm pro Skala, untereinander dargestellt, vertikale Linie für den jeweiligen Mittelwert</p>
<pre class="r"><code>par(mfrow=c(2,1), mar=c(3,2,2,0))
hist(prokrast_pos$mean, xlim=c(0,4), ylim=c(1,60), main=&quot;Prokrastinationstendenz positiv formulierte Items&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)
abline(v=mean(prokrast_pos$mean), lty=2, lwd=2)
hist(prokrast_neg$mean, xlim=c(0,4), ylim=c(1,60), main=&quot;Prokrastinationstendenz negativ formulierte Items&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)
abline(v=mean(prokrast_neg$mean), lty=2, lwd=2)</code></pre>
<p><img src="/post/2022-12-13-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,1))</code></pre>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: statistisch</strong></p>
<pre class="r"><code>summary(prokrast_pos$mean)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.200   2.200   2.800   2.684   3.200   4.000</code></pre>
<pre class="r"><code>summary(prokrast_neg$mean)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.200   2.000   2.400   2.323   2.600   4.000</code></pre>
<pre class="r"><code>#alternativ
library(psych)
describe(prokrast_pos$mean)</code></pre>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 159 2.68 0.64    2.8    2.68 0.59 1.2   4   2.8 0.09    -0.55 0.05</code></pre>
<pre class="r"><code>describe(prokrast_neg$mean)</code></pre>
<pre><code>##    vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 159 2.32 0.52    2.4    2.31 0.59 1.2   4   2.8 0.31     0.14 0.04</code></pre>
<p>Mittelwert positiv (<em>M</em> = 2.68, <em>SD</em> = 0.64) ist deskriptiv höher als Mittelwert negativ (<em>M</em> = 2.32, <em>SD</em> = 0.52).</p>
<p><strong>Voraussetzungen für t-Test für abhängige Stichproben</strong></p>
<ol style="list-style-type: decimal">
<li>Die abhängige Variable ist intervallskaliert <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Die Messwerte innerhalb der Paare dürfen sich gegenseitig beeinflussen/voneinander abhängig sein; keine Abhängigkeiten zwischen den Messwertpaaren <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Die Differenzvariable <em>d</em> muss in der Population normalverteilt sein <span class="math inline">\(\rightarrow\)</span> ab <span class="math inline">\(n \ge 30\)</span> gegeben, ansonsten grafische Prüfung oder Hintergrundwissen</li>
</ol>
<p><strong>Voraussetzungsprüfung: Normalverteilung von <em>d</em></strong></p>
<pre class="r"><code>par(mar=c(3,3,3,0)) #ändern der Ränder (margins) des Plot-Fensters
difference &lt;- prokrast_pos$mean-prokrast_neg$mean
hist(difference, 
     breaks = 15,
     xlim=c(-2,2), 
     ylim = c(0,1), 
     main=&quot;Verteilung der Differenzen&quot;, 
     xlab=&quot;Differenzen&quot;, ylab=&quot;&quot;, las=1,freq=F)
curve(dnorm(x, mean=mean(difference), sd=sd(difference)), col=&quot;blue&quot;, lwd=2, add=T)</code></pre>
<p><img src="/post/2022-12-13-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,1)) #Zurücksetzen auf default
qqnorm(difference,las=1)
qqline(difference, col=&quot;blue&quot;)</code></pre>
<p><img src="/post/2022-12-13-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<p><span class="math inline">\(\Rightarrow\)</span> Differenzen sehen einigermaßen normalverteilt aus</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Unterschiedshypothese<br />
</li>
<li>Richtung des Effekts: Ungerichtet <span class="math inline">\(\rightarrow\)</span> ungerichtete Hypothese</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypothesenpaar (inhaltlich):<br />
H0: Studierende geben in gleichem Ausmaß ihre Prokrastinationstendenz an, d.h. die Richtung der Itemformulierung ist irrelevant.</p>
<p>H1: Studierende geben nicht im gleichen Ausmaß ihre Prokrastinationstendenz an, d.h. die Richtung der Itemformulierung hat einen Einfluss.</p>
<p>Hypothesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_\text{positiv} = \mu_\text{negativ}\)</span> bzw. <span class="math inline">\(\mu_{d} = 0\)</span></li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_\text{positiv} \ne \mu_\text{negativ}\)</span> bzw. <span class="math inline">\(\mu_{d} \ne 0\)</span></li>
</ul>
<p><strong>Spezifikation des Signifikanzniveaus</strong></p>
<p><span class="math inline">\(\alpha = .05\)</span></p>
<p><strong>Durchführung des <em>t</em>-Tests für abhängige Stichproben in R</strong></p>
<pre class="r"><code>t.test(x = prokrast_pos$mean, y  = prokrast_neg$mean, 
       paired = T,                       # Stichproben sind abhängig
       alternative = &quot;two.sided&quot;,        # ungerichtete Hypothese 
       conf.level = .95)                 # alpha = .05</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  prokrast_pos$mean and prokrast_neg$mean
## t = 8.7105, df = 158, p-value = 3.85e-15
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.2789052 0.4424784
## sample estimates:
## mean difference 
##       0.3606918</code></pre>
<ul>
<li>Zur Erinnerung: <em>df</em> bei <em>t</em>-test mit abhängigen Stichproben: <em>n</em> - 1</li>
<li><em>t</em>(0.05;158) = 8.71, <em>p</em> &lt; .001 <span class="math inline">\(\rightarrow\)</span> signifikant, H0 wird verworfen.</li>
</ul>
<p><strong>Schätzung des standardisierten Populationseffekts</strong></p>
<pre class="r"><code>mean_d &lt;- mean(difference)
sd.d.est &lt;- sd(difference) #die geschätzte SD der Differenzen
d_prok &lt;- mean_d/sd.d.est
d_prok</code></pre>
<pre><code>## [1] 0.6907852</code></pre>
<p><span class="math inline">\(\Rightarrow\)</span> Der standardisierte Populationseffekt beträgt <em>d2’’</em> = 0.69 und ist laut Konventionen nach Cohen (1988) groß.</p>
<p><strong>Formales Berichten des Ergebnisses</strong></p>
<p>Es wurde untersucht, ob Psychologiestudierende in Anbhängigkeit der Itemformulierung in unterschiedlichem Maße angeben, dass sie prokrastinieren. Es findet sich deskriptiv ein Unterschied: Bei den positiv formulierten Items liegt der durchschnittliche Prokrastinationswert bei 2.68 (<em>SD</em> = 0.64), während er bei negativ formulierten Items bei 2.32 (<em>SD</em> = 0.52) liegt.</p>
<p>Zur Beantwortung der Fragestellung wurde ein ungerichteter <em>t</em>-Test für abhängige Stichproben durchgeführt. Der Unterschied ist signifikant (<em>t</em>(158) = 8.71, <em>p</em> &lt; .001), somit wird die Nullhypothese verworfen. Die Itemformulierung scheint einen Einfluss auf die angegebene Prokrastinationstendenz zu haben.</p>
<p>Dieser Einfluss ist nach dem standardisierten Populationseffekt von <em>d’’</em> = 0.69 groß.</p>
<p>Anmerkung: Hierbei ist zu bedenken, dass es neben der Richtung der Itemformulierung natürlich noch andere (bei unserer Erhebung nicht kontrollierte) Eigenheiten der Items geben kann, die zu Unterschieden führen (z. B. wie extrem bzw. schwierig die Items formuliert sind).</p>
</details>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<p>Ein Therapeut behauptet, dass eine von ihm entwickelte Meditation die Zufriedenheit von Menschen positiv beeinflusst. Er möchte dies mit wissenschaftlichen Methoden zeigen und misst die Zufriedenheit vor und nach der Meditation. Es ergeben sich folgende Werte für 18 Personen:</p>
<table>
<thead>
<tr class="header">
<th align="right">Vpn</th>
<th align="right">Vorher</th>
<th align="right">Nachher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">4.1</td>
<td align="right">4.0</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">5.9</td>
<td align="right">7.2</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">4.4</td>
<td align="right">8.1</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">7.8</td>
<td align="right">6.2</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">2.4</td>
<td align="right">4.1</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">8.8</td>
<td align="right">7.7</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">3.1</td>
<td align="right">5.5</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">5.0</td>
<td align="right">6.9</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">6.0</td>
<td align="right">8.2</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">4.5</td>
<td align="right">5.4</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">5.8</td>
<td align="right">9.1</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="right">4.4</td>
<td align="right">5.6</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="right">3.2</td>
<td align="right">6.8</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="right">7.3</td>
<td align="right">7.5</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="right">7.4</td>
<td align="right">6.4</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="right">6.3</td>
<td align="right">4.9</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="right">4.3</td>
<td align="right">6.1</td>
</tr>
<tr class="even">
<td align="right">18</td>
<td align="right">7.1</td>
<td align="right">7.9</td>
</tr>
</tbody>
</table>
<p>Wirkt die Meditation positiv auf die Zufriedenheit?</p>
<details>
<summary>
Lösung
</summary>
<p><strong>Datensatz generieren</strong></p>
<pre class="r"><code>dataMeditation &lt;- data.frame(Vpn = 1:18, 
                             Vorher = c(4.1,5.9,4.4,7.8,2.4,8.8,3.1,5.0,6.0,4.5,5.8,4.4,3.2,7.3,7.4,6.3,4.3,7.1), 
                             Nachher = c(4.0,7.2,8.1,6.2,4.1,7.7,5.5,6.9,8.2,5.4,9.1,5.6,6.8,7.5,6.4,4.9,6.1,7.9))</code></pre>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: grafisch</strong></p>
<p>Histogramme (weil Intervallskalenqualität):
Je ein Histogramm pro Gruppe, untereinander dargestellt, vertikale Linie für den jeweiligen Mittelwert</p>
<pre class="r"><code>par(mfrow=c(2,1), mar=c(3,2,2,0))
hist(dataMeditation[, &quot;Vorher&quot;], xlim=c(0,10), ylim=c(1,6), main=&quot;Zufriedenheit vor der Meditation&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)
abline(v=mean(dataMeditation[, &quot;Vorher&quot;]), lty=2, lwd=2)
hist(dataMeditation[, &quot;Nachher&quot;], xlim=c(0,10), ylim=c(1,6), main=&quot;Zufriedenheit nach der Meditation&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)
abline(v=mean(dataMeditation[, &quot;Nachher&quot;]), lty=2, lwd=2)</code></pre>
<p><img src="/post/2022-12-13-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,1))</code></pre>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: statistisch</strong></p>
<pre class="r"><code>summary(dataMeditation[, &quot;Vorher&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.400   4.325   5.400   5.433   6.900   8.800</code></pre>
<pre class="r"><code>summary(dataMeditation[, &quot;Nachher&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.000   5.525   6.600   6.533   7.650   9.100</code></pre>
<pre class="r"><code>#alternativ
library(psych)
describe(dataMeditation[, &quot;Vorher&quot;])</code></pre>
<pre><code>##    vars  n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 18 5.43 1.79    5.4    5.41 1.78 2.4 8.8   6.4 0.12    -1.14 0.42</code></pre>
<pre class="r"><code>describe(dataMeditation[, &quot;Nachher&quot;])</code></pre>
<pre><code>##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 18 6.53 1.44    6.6    6.53 1.63   4 9.1   5.1 -0.14    -1.05 0.34</code></pre>
<p>Mittelwert vorher (<em>M</em> = 5.43, <em>SD</em> = 1.79) ist deskriptiv niedriger als Mittelwert nachher (<em>M</em> = 6.53, <em>SD</em> = 1.44).</p>
<p><strong>Voraussetzungen für t-Test für abhängige Stichproben</strong></p>
<ol style="list-style-type: decimal">
<li>Die abhängige Variable ist intervallskaliert <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Die Messwerte innerhalb der Paare dürfen sich gegenseitig beeinflussen/voneinander abhängig sein; keine Abhängigkeiten zwischen den Messwertpaaren <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Die Differenzvariable <em>d</em> muss in der Population normalverteilt sein <span class="math inline">\(\rightarrow\)</span> ab <span class="math inline">\(n \ge 30\)</span> gegeben, ansonsten grafische Prüfung oder Hintergrundwissen</li>
</ol>
<p><strong>Voraussetzungsprüfung: Normalverteilung von <em>d</em></strong></p>
<pre class="r"><code>par(mar=c(3,3,3,0)) #ändern der Ränder (margins) des Plot-Fensters
difference2 &lt;- dataMeditation[, &quot;Vorher&quot;]-dataMeditation[, &quot;Nachher&quot;]
hist(difference2, xlim=c(-6,4), main=&quot;Verteilung der Differenzen&quot;, xlab=&quot;Differenzen&quot;, ylab=&quot;&quot;, las=1,freq=F)
curve(dnorm(x, mean=mean(difference2), sd=sd(difference2)), col=&quot;blue&quot;, lwd=2, add=T)</code></pre>
<p><img src="/post/2022-12-13-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,1)) #Zurücksetzen auf default
qqnorm(difference2,las=1)
qqline(difference2, col=&quot;blue&quot;)</code></pre>
<p><img src="/post/2022-12-13-tests-fuer-abhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-17-2.png" width="672" /></p>
<p><span class="math inline">\(\Rightarrow\)</span> Differenzen sehen nicht normalverteilt aus</p>
<p><span class="math inline">\(\Rightarrow\)</span> Durchführung des Wilcoxon-Tests für abhängige Stichproben, da die Voraussetzungen hierfür erfüllt sind.</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Unterschiedshypothese<br />
</li>
<li>Richtung des Effekts: Gerichtet <span class="math inline">\(\rightarrow\)</span> gerichtete Hypothesen (Der Wissenschaftler erwartet eine positive Wirkung der Meditation auf die Zufriedenheit.)</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypothesenpaar (inhaltlich):<br />
H0: Die Meditation wirkt sich nicht oder negativ auf die Zufriedenheit aus.</p>
<p>H1: Die Meditation wirkt sich positiv auf die Zufriedenheit aus.</p>
<p>Hypothesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\eta_\text{vorher} \ge \eta_\text{nachher}\)</span> bzw. <span class="math inline">\(\mu_{d} \ge 0\)</span></li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\eta_\text{vorher} &lt; \eta_\text{nachher}\)</span> bzw. <span class="math inline">\(\mu_{d} &lt; 0\)</span></li>
</ul>
<p><strong>Spezifikation des Signifikanzniveaus</strong></p>
<p><span class="math inline">\(\alpha = .05\)</span></p>
<p><strong>Inferenzstatistik: Wilcoxon-Test für abhängige Stichproben</strong></p>
<pre class="r"><code>wilcox.test(x = dataMeditation[, &quot;Vorher&quot;], y  = dataMeditation[, &quot;Nachher&quot;], # die beiden abhängigen Gruppen
       paired = T,                       # Stichproben sind abhängig
       alternative = &quot;less&quot;,             # gerichtete Hypothese -&gt; einseitige Testung
       conf.level = .95)                 # alpha = .05</code></pre>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  dataMeditation[, &quot;Vorher&quot;] and dataMeditation[, &quot;Nachher&quot;]
## V = 31, p-value = 0.007965
## alternative hypothesis: true location shift is less than 0</code></pre>
<p><span class="math inline">\(\Rightarrow\)</span> <em>V</em> = 31, <em>p</em> &lt; .01 <span class="math inline">\(\rightarrow\)</span> H0 wird verworfen.</p>
<p><strong>Formales Berichten des Ergebnisses</strong></p>
<p>Es wurde in einer Wiederholungsmessung untersucht, ob sich Meditation auf Zufriedenheit auswirkt. Zunächst findet sich deskriptiv ein Unterschied: Vor der Meditation liegt der durchschnittliche Zufriedenheitswert bei 5.43 (<em>SD</em> = 1.79), während er nach der Meditation bei 6.53 (<em>SD</em> = 1.44) liegt.</p>
<p>Da die Differenzen nicht normalverteilt waren, wurde ein gerichteter Wilcoxon-Test für abhängige Stichproben durchgeführt. Der Unterschied wurde bei einem Signifikanzniveau von alpha = .05 signifikant (<em>V</em> = 31, <em>p</em> &lt; .01). Somit wird die Nullhypothese verworfen. Die Meditation hat einen positiven Einfluss auf die Zufriedenheit.</p>
</details>
</div>
