---
title: "Tests für unabhängige Stichproben"
date: "2022-12-03"
slug: gruppenvergleiche-unabhaengig
categories: 
  - BSc2
tags:
  - t-Test
  - chi2-Test
  - Wilcoxon-Test
  - unabhängig
subtitle: ''
summary: ''
authors: [koehler, buchholz, irmer, nehler, goldhammer]
lastmod: "2023-02-01T15:39:00+01:00"
featured: no
header:
  image: "/header/BSc2_test_unabh_stpr.jpg"
  caption: '[Courtesy of pxhere](https://pxhere.com/en/photo/662606)'
projects: []
---



{{% detail_disclosure "Kernfragen der Lehreinheiten über Gruppenvergleiche" %}}
<!-- Die divs sind wichtig, damit die Liste funktioniert! Innerhalb dieses Shortcodes ist HTML erlaubt (safeHTML) -->
<div>
<ul>
<li>Wie fertige ich <a href="#Statistiken">Deskriptivstatistiken</a> (Grafiken, Kennwerte) zur Veranschaulichung des Unterschieds zwischen zwei Gruppen an?</li>
<li>Was sind <a href="#Vorraussetzungen">Voraussetzungen</a> des <em>t</em>-Tests und wie prüfe ich sie?</li>
<li>Wie führe ich einen <a href="#t-Test"><em>t</em>-Test</a> in R durch?<br />
</li>
<li>Wie berechne ich die <a href="#Effektstärke">Effektstärke</a> Cohen’s <em>d</em>?<br />
</li>
<li>Wie führe ich den <a href="#Wilcox">Wilcoxon-Test</a> (auch “Mann-Whitney-Test”, “U-Test”, “Mann-Whitney-U-Test”, “Wilcoxon-Rangsummentest”) in R durch?<br />
</li>
<li>Wie führe ich den <a href="#Chi-Sq">Vierfelder-Chi-Quadrat-Test</a> in R durch?</li>
</ul>
</div>
<p>{{% /detail_disclosure %}}</p>
<hr />
<div id="was-erwartet-sie" class="section level2">
<h2>Was erwartet Sie?</h2>
<p>Nachdem wir uns zuletzt mit dem Unterschied zwischen dem Mittelwert einer Stichprobe und dem Mittelwert der dazugehörigen Population, aus der die Stichprobe stammt, auseinandergesetzt haben, fokussieren wir uns nun auf Unterschiede zwischen zwei Gruppen (also zwei Stichproben). Hierbei muss zwischen unabhängigen und abhängigen Stichproben unterschieden werden.</p>
</div>
<div id="aufbau-der-sitzungen-zu-gruppenvergleichen" class="section level2">
<h2>Aufbau der Sitzungen zu Gruppenvergleichen</h2>
<ol style="list-style-type: decimal">
<li>Fragestellung A: Erreichen Studentinnen und Studenten im Nerdiness Personality Attributes-Test im Durchschnitt gleich hohe Testwerte? (<em>t-Test und Cohen’s d für unabhängige Stichproben</em>)</li>
<li>Fragestellung B: Stimmen Studentinnen dem Item “Ich denke immer darüber nach, wie meine Taten sich auf die Umwelt auswirken” stärker zu als Studenten? (<em>Wilcoxon-Test für unabhängige Stichproben</em>)</li>
<li>Fragestellung C: Haben Studierende mit Wohnort in Uninähe (Frankfurt) mit gleicher Wahrscheinlichkeit einen Nebenjob wie Studierende, deren Wohnort außerhalb von Frankfurt liegt? (<em>Vierfelder-</em><span class="math inline">\(\chi^2\)</span>-Test)</li>
</ol>
<hr />
</div>
<div id="prep" class="section level2">
<h2>Vorbereitende Schritte</h2>
<p>Wie man anhand der Fragestellungen bereits gesehen hat, beschäftigen wir uns mit den Werten aus unserem Datensatz. Diesen haben wir bereits unter diesem <a href="/post/fb22.rda">{{% download_image %}} Link heruntergeladen</a> und können ihn über den lokalen Speicherort einladen oder Sie können Ihn direkt mittels des folgenden Befehls aus dem Internet in das Environment bekommen. In den vorherigen Tutorials und den dazugehörigen Aufgaben haben wir bereits Änderungen am Datensatz durchgeführt, die hier nochmal aufgeführt sind, um den Datensatz auf dem aktuellen Stand zu haben:</p>
<pre class="r"><code>#### Was bisher geschah: ----

# Daten laden
load(url(&#39;https://pandar.netlify.app/post/fb22.rda&#39;))  

# Nominalskalierte Variablen in Faktoren verwandeln
fb22$geschl_faktor &lt;- factor(fb22$geschl,
                             levels = 1:3,
                             labels = c(&quot;weiblich&quot;, &quot;männlich&quot;, &quot;anderes&quot;))
fb22$fach &lt;- factor(fb22$fach,
                    levels = 1:5,
                    labels = c(&#39;Allgemeine&#39;, &#39;Biologische&#39;, &#39;Entwicklung&#39;, &#39;Klinische&#39;, &#39;Diag./Meth.&#39;))
fb22$ziel &lt;- factor(fb22$ziel,
                        levels = 1:4,
                        labels = c(&quot;Wirtschaft&quot;, &quot;Therapie&quot;, &quot;Forschung&quot;, &quot;Andere&quot;))
fb22$wohnen &lt;- factor(fb22$wohnen, 
                      levels = 1:4, 
                      labels = c(&quot;WG&quot;, &quot;bei Eltern&quot;, &quot;alleine&quot;, &quot;sonstiges&quot;))

# Skalenbildung

fb22$prok2_r &lt;- -1 * (fb22$prok2 - 5)
fb22$prok3_r &lt;- -1 * (fb22$prok3 - 5)
fb22$prok5_r &lt;- -1 * (fb22$prok5 - 5)
fb22$prok7_r &lt;- -1 * (fb22$prok7 - 5)
fb22$prok8_r &lt;- -1 * (fb22$prok8 - 5)

# Prokrastination
fb22$prok_ges &lt;- fb22[, c(&#39;prok1&#39;, &#39;prok2_r&#39;, &#39;prok3_r&#39;,
                          &#39;prok4&#39;, &#39;prok5_r&#39;, &#39;prok6&#39;,
                          &#39;prok7_r&#39;, &#39;prok8_r&#39;, &#39;prok9&#39;, 
                          &#39;prok10&#39;)] |&gt; rowMeans()
# Naturverbundenheit
fb22$nr_ges &lt;-  fb22[, c(&#39;nr1&#39;, &#39;nr2&#39;, &#39;nr3&#39;, &#39;nr4&#39;, &#39;nr5&#39;,  &#39;nr6&#39;)] |&gt; rowMeans()
fb22$nr_ges_z &lt;- scale(fb22$nr_ges) # Standardisiert

# Weitere Standardisierugen
fb22$nerd_std &lt;- scale(fb22$nerd)
fb22$neuro_std &lt;- scale(fb22$neuro)</code></pre>
<hr />
</div>
<div id="Statistiken" class="section level2 anchorheader">
<h2>1. Fragestellung A: Erreichen Studenten im Nerdiness Personality Attributes-Test im Durchschnitt einen höheren Testwert als Studentinnen?</h2>
<div id="vorbereitung-daten-aufbereiten" class="section level3">
<h3>1.1 Vorbereitung (Daten aufbereiten)</h3>
<p>Die Gruppierungsvariable in unserer Fragestellung muss für die Nutzung der Funktionen in <code>R</code> als Faktor vorliegen. Bei uns soll es um das Geschlecht gehen. Wir können wir mit <code>is.factor()</code> überprüfen, ob die Variable <code>geschl</code> im Datensatz ein Faktor ist.</p>
<pre class="r"><code>is.factor(fb22$geschl)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>Diese Funktion gibt uns einen boolschen Wert (<code>TRUE</code> oder <code>FALSE</code>) wieder und beantwortet damit unsere Frage, ob das Geschlecht ein <code>factor</code> ist oder nicht. Wir sehen aufgrund der Antwort als <code>FALSE</code>, dass die Variable <code>geschl</code> nicht als Faktor vorliegt.</p>
<p>Allerdings haben wir in der Vorbereitung gesehen, dass wir bereits eine Variable erstellt haben, die das Geschlecht als Faktor repräsentiert. Diese hatten wir <code>geschl_faktor</code> genannt. Auch das können wir nochmal überprüfen:</p>
<pre class="r"><code>is.factor(fb22$geschl_faktor)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Hier wird ein <code>TRUE</code> ausgegeben - die Variable ist also ein Faktor. Auch die <code>levels</code> können wir bestimmen</p>
<pre class="r"><code>levels(fb22$geschl_faktor)</code></pre>
<pre><code>## [1] &quot;weiblich&quot; &quot;männlich&quot; &quot;anderes&quot;</code></pre>
<p>Der Faktor hat also 3` Stufen, die bei der Beantwortung möglich gewesen wären.</p>
</div>
<div id="deskriptivstatistik" class="section level3">
<h3>1.2. Deskriptivstatistik</h3>
<p>Im ersten Schritt wollen wir uns die Daten deskriptiv anschauen. Das geht entweder grafisch oder deskriptivstatistisch.</p>
<div id="grafisch" class="section level4">
<h4>1.2.1. grafisch</h4>
<p>Wir werfen zunächst vorbereitend einen tabellarischen Blick auf die Variable Geschlecht.</p>
<pre class="r"><code>table(fb22$geschl_faktor)</code></pre>
<pre><code>## 
## weiblich männlich  anderes 
##      125       23        1</code></pre>
<p>Insgesamt gibt es nur eine Person, welche die Option “anderes” ausgewählt hat. Leider lässt sich über einen Datenpunkt allein keine Varianz bestimmen und auch keine Inferenzstatistik betreiben. Aus diesem Grund müssen wir uns hier auf “männlich” und “weiblich” beschränken und verwenden im Folgenden den gekürzten Datensatz <code>dataB</code>:</p>
<pre class="r"><code># nur Männer und Frauen auswählen:
dataB &lt;- fb22[ (fb22$geschl_faktor==&quot;männlich&quot;|fb22$geschl_faktor==&quot;weiblich&quot;), ]  
dataB$geschl_faktor &lt;- droplevels(dataB$geschl_faktor) # levels aus den Datensatz entfernen, die keine Erhebungen haben</code></pre>
<p>Mithilfe eines Boxplots, bzw. mithilfe von Histogrammen, lassen sich Unterschiede zwischen Gruppen gut untersuchen. Wir verwenden hier einige Zusatzeinstellungen, um die Grafiken übersichtlicher und auch ein wenig ansprechender zu gestalten.</p>
<pre class="r"><code># Gruppierter Boxplot :
boxplot(dataB$nerd ~ dataB$geschl_faktor, 
        xlab=&quot;Geschlecht&quot;, ylab=&quot;Nerdiness&quot;, 
        las=1, cex.lab=1.5, 
        main=&quot;Nerdiness je nach Geschlecht&quot;)</code></pre>
<p><img src="/post/2022-12-05-tests-fuer-unabhaengige-stichproben_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code># Je ein Histogramm pro Gruppe, untereinander dargestellt, vertikale Linie für den jeweiligen Mittelwert
par(mfrow=c(2,1), mar=c(3,2,2,0))
hist(dataB[(dataB$geschl_faktor==&quot;weiblich&quot;), &quot;nerd&quot;], main=&quot;Testwert (weiblich)&quot;, 
     xlim=c(0,6), xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)
abline(v=mean(dataB[(dataB$geschl_faktor==&quot;weiblich&quot;), &quot;nerd&quot;], na.rm=T), col=&quot;aquamarine3&quot;, lwd=3)
hist(dataB[(dataB$geschl_faktor==&quot;männlich&quot;), &quot;nerd&quot;], main=&quot;Testwert (männlich)&quot;, 
     xlim=c(0,6), xlab=&quot;&quot;, ylab=&quot;&quot;, las=1)
abline(v=mean(dataB[(dataB$geschl_faktor==&quot;männlich&quot;), &quot;nerd&quot;], na.rm=T), col=&quot;darksalmon&quot;, lwd=3)</code></pre>
<p><img src="/post/2022-12-05-tests-fuer-unabhaengige-stichproben_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<p><code>dataB$nerd ~ dataB$geschl_faktor</code> ist die Formelnotation in <code>R</code>, welche Sie im Rahmen der Regression noch genauer kennenlernen werden. Links von der <code>~</code> (Tilde) steht die abhängige Variable (hier der Testwert), deren Mittelwertsunterschiede durch die unabhängige Variable (hier Geschlecht) rechts der <code>~</code> erklärt werden soll. Der Befehl <code>par(mfrow=c(2,1), mar=c(3,2,2,0))</code> bewirkt, dass 2 Grafiken untereinander dargestellt werden - und zwar im selben Plot. Das Argument <code>mfrow</code> definiert ein Plot-Array mit der angebenen Anzahl von Zeilen und Spalten (wobei mit <code>mfrow</code> die Plots zeilenweise verteilt werden; alternativ mit <code>mfcol</code>). Mit dem Argument <code>mar</code> werden für unten, links, oben und rechts die Randabstände spezifiziert. Spielen Sie doch einmal selbst an den Einstellungen herum und schauen nach, was die Argumente jeweils bewirken!</p>
<p>Damit von nun an nicht immer zwei Grafiken in einem Plot dargestellt werden, können wir die Einstellungen folgendermaßen zurücksetzen:</p>
<pre class="r"><code>dev.off()</code></pre>
<pre><code>## null device 
##           1</code></pre>
</div>
<div id="deskriptivstatistisch" class="section level4">
<h4>1.2.2. deskriptivstatistisch</h4>
<p>Wir können uns auch Deskriptivstatistiken ansehen. Bspw. könnten wir uns die Mittelwerte oder die SDs etc. ausgeben lassen. Dazu nehmen wir entweder die <code>summary()</code> und wählen die entsprechenden Fälle aus oder wir machen uns das <code>psych</code>-Paket zunutze. Dieses muss zuvor installiert sein (<code>install.packages()</code>). Falls dem so ist, kann das Paket mit <code>library()</code> eingeladen werden. Die Funktion, die uns interessiert, heißt <code>describeBy()</code>, welche die Gruppenaufteilung bereits für uns übernimmt.</p>
<pre class="r"><code># umständlich:
summary(dataB$nerd[(dataB$geschl_faktor==&quot;weiblich&quot;)])  # Gruppe 1: Studentinnen</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   1.500   2.667   3.167   3.104   3.500   4.667      10</code></pre>
<pre class="r"><code>summary(dataB$nerd[(dataB$geschl_faktor==&quot;männlich&quot;)]) # Gruppe 2: Studenten</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   1.833   2.917   3.333   3.370   3.917   4.500      10</code></pre>
<pre class="r"><code># komfortabler:
library(psych)
describeBy(x = dataB$nerd, group = dataB$geschl_faktor)        # beide Gruppen im Vergleich </code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: weiblich
##    vars   n mean   sd median trimmed  mad min  max range  skew kurtosis   se
## X1    1 125  3.1 0.62   3.17     3.1 0.74 1.5 4.67  3.17 -0.05    -0.13 0.06
## ------------------------------------------------------------ 
## group: männlich
##    vars  n mean   sd median trimmed  mad  min max range  skew kurtosis   se
## X1    1 23 3.37 0.69   3.33     3.4 0.74 1.83 4.5  2.67 -0.34    -0.71 0.14</code></pre>
<p>Achtung, bei den hier berichteten <code>sd</code> handelt es sich nicht um die Stichprobenkennwerte, sondern um die Populationsschätzer. Daher berechnen wir die Standardabweichung auch nochmals per Hand:</p>
<pre class="r"><code>nerd_weiblich &lt;- dataB$nerd[(dataB$geschl_faktor==&quot;weiblich&quot;)]
sigma_weiblich &lt;- sd(nerd_weiblich, na.rm = T)
n_weiblich &lt;- length(nerd_weiblich[!is.na(nerd_weiblich)])
sd_weiblich &lt;- sigma_weiblich * sqrt((n_weiblich-1) / n_weiblich)
sd_weiblich</code></pre>
<pre><code>## [1] 0.6206319</code></pre>
<pre class="r"><code>nerd_männlich &lt;- dataB$nerd[(dataB$geschl_faktor==&quot;männlich&quot;)]
sigma_männlich &lt;- sd(nerd_männlich, na.rm = T)
n_männlich &lt;- length(nerd_männlich[!is.na(nerd_männlich)])
sd_männlich &lt;- sigma_männlich * sqrt((n_männlich-1) / n_männlich)
sd_männlich</code></pre>
<pre><code>## [1] 0.6737962</code></pre>
</div>
</div>
<div id="Vorraussetzungen" class="section level3 anchorheader">
<h3>1.3. Voraussetzungsprüfung</h3>
<p>Damit wir den Ergebnissen des <em>t</em>-Tests trauen können, müssen dessen Voraussetzungen erfüllt sein.</p>
<p><strong>Voraussetzungen für die Durchführung des <em>t</em>-Tests</strong></p>
<ol style="list-style-type: decimal">
<li>die abhängige Variable ist intervallskaliert <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>die einzelnen Messwerte sind voneinander unabhängig (Messwert einer Vpn hat keinen Einfluss auf den Messwert einer anderen) <span class="math inline">\(\rightarrow\)</span> ok<br />
</li>
<li>das untersuchte Merkmal ist in den Grundgesamtheiten der beiden Gruppen normalverteilt <span class="math inline">\(\rightarrow\)</span> (ggf.) optische Prüfung<br />
</li>
<li>Homoskedastizität: Varianzen der Variablen innerhalb der Populationen sind gleich <span class="math inline">\(\rightarrow\)</span> Levene-Test</li>
</ol>
<p><strong>zu 3): Optische Prüfung auf Normalverteilung in den beiden Gruppen</strong></p>
<p>Falls das Merkmal in der Population normalverteilt ist und die Stichproben groß genug sind, darf diese Voraussetzung generell als erfüllt betrachtet werden (<span class="math inline">\(\rightarrow\)</span> Zentraler Grenzwertsatz). Für kleinere Stichproben empfiehlt sich eine optische Prüfung auf Normalverteilung. Zur optischen Prüfung auf Normalverteilung gibt es mehrere Möglichkeiten, von denen zwei im Folgenden erläutert und dann jeweils durchgeführt werden.</p>
<ul>
<li>Möglichkeit 1: die bei Normalverteilung erwartete Dichtefunktion über das Histogramm legen und so die Übereinstimmung beurteilen<br />
</li>
<li>Möglichkeit 2: QQ-Plot (quantile-quantile): es wird die beobachtete Position eines Messwerts gegen diejenige Position, die unter Gültigkeit der Normalverteilung zu erwarten wäre, abgetragen. Bei Normalverteilung liegen die Punkte (in etwa) auf einer Geraden.</li>
</ul>
<pre class="r"><code># Gruppe 1 (weiblich) 
par(mfrow=c(1,2))
nerd_weiblich &lt;- dataB[(dataB$geschl_faktor==&quot;weiblich&quot;), &quot;nerd&quot;]
hist(nerd_weiblich, xlim=c(0,6), ylim=c(0,.8), main=&quot;Nerdiness Testwert (weiblich)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, probability=T)
curve(dnorm(x, mean=mean(nerd_weiblich, na.rm=T), sd=sd(nerd_weiblich, na.rm=T)), col=&quot;blue&quot;, lwd=2, add=T)
qqnorm(nerd_weiblich)
qqline(nerd_weiblich, col=&quot;blue&quot;)</code></pre>
<p><img src="/post/2022-12-05-tests-fuer-unabhaengige-stichproben_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Mithilfe von <code>curve()</code> kann eine Linie in eine Grafik eingezeichnet werden. Hierbei bezeichnet <code>x</code> die x-Koordinate. <code>dnorm()</code> hatten wir bereits kennen gelernt. Diese Funktion beschreibt die Dichte der Normalverteilung. Die Normalverteilung ist eindeutig durch ihren Mittelwert und durch ihre Standardabweichung definiert. Wir müssen <code>dnorm()</code> also jeweils den empirischen Mittelwert sowie die empirische Standardabweichung übergeben. Das Argument <code>add = T</code> ist nötig, da sonst ein neuer Plot für die Kurve erstellt wird. Durch <code>add = T</code> wird sie dem Histogramm hinzugefügt. Damit die Dichte sichtbar ist, muss im Histogramm zuvor das Argument <code>probability = T</code> gewählt werden. Ansonsten würden absolute Häufigkeiten anstatt der relativen Häufigkeiten abgetragen werden. Den <code>qqnorm()</code>-Befehl hatten wir auch bereits kennen gelernt. Mit <code>qqline()</code> erhalten wir die nötige Linie, auf welcher die Punkte einigermaßen liegen müssen, damit sie als normalverteilt einzustufen sind.</p>
<p><span class="math inline">\(\rightarrow\)</span> Normalverteilung kann für Gruppe 1 (weiblich) angenommen werden</p>
<p>Wir wiederholen die Befehle von zuvor auch für die zweite Gruppe:</p>
<pre class="r"><code># Gruppe 2 (männlich)
par(mfrow=c(1,2))
nerd_männlich &lt;- dataB[(dataB$geschl_faktor==&quot;männlich&quot;), &quot;nerd&quot;]
hist(nerd_männlich, xlim=c(0,6), ylim=c(0,.8), main=&quot;Nerdiness Testwert (männlich)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, probability=T)
curve(dnorm(x, mean=mean(nerd_männlich, na.rm=T), sd=sd(nerd_männlich, na.rm=T)), col=&quot;blue&quot;, lwd=2, add=T)
qqnorm(nerd_männlich)
qqline(nerd_männlich, col=&quot;blue&quot;)</code></pre>
<p><img src="/post/2022-12-05-tests-fuer-unabhaengige-stichproben_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><span class="math inline">\(\rightarrow\)</span> Normalverteilung kann auch für Gruppe 2 (männlich) einigermaßen angenommen werden (hierbei ist zu beachten, dass die Gruppe der Studenten im Vergleich zur Gruppe der Studentinnen deutlich kleiner ist)</p>
<p>Damit von nun an nicht immer zwei Grafiken in einem Plot dargestellt werden, können wir die Einstellungen folgendermaßen zurücksetzen:</p>
<pre class="r"><code>dev.off()</code></pre>
<pre><code>## null device 
##           1</code></pre>
<p><strong>zu 4) Test auf Homoskedastizität (Levene-Test)</strong></p>
<p>Das Hypothesenpaar im Levene-Test lautet:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Homoskedastizität ist gegeben.<br />
</li>
<li><span class="math inline">\(H_1\)</span>: Homoskedastizität ist nicht gegeben.</li>
</ul>
<p>Ein nicht-signifikantes Ergebnis (<em>p</em> &gt; .05) zeigt also Homoskedastizität an. Den Levene-Test können wir mit Hilfe des <code>car</code>-Pakets durchführen (dieses muss natürlich vorher installiert sein). Die nötige Funktion heißt <code>leveneTest()</code>. Sie nimmt eine Formel entgegen, die die Punktzahl ihrer jeweiligen Gruppe zuweist. Links von der <code>~</code> (Tilde) steht die abhängige Variable (hier der Nerdiness-Testwert), deren Mittelwertsunterschied durch die unabhängige Variable (hier Geschlecht) rechts der <code>~</code> erklärt werden soll. Wir merken uns also, dass die Gruppenzugehörigkeit rechts der <code>~</code> stehen muss.</p>
<pre class="r"><code>library(car)
leveneTest(dataB$nerd ~ dataB$geschl_faktor)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1   0.569 0.4519
##       146</code></pre>
<p><em>F</em>(1,146) = 0.57, <em>p</em> = 0.452 <span class="math inline">\(\rightarrow\)</span> Das Ergebnis ist nicht signifikant, die <span class="math inline">\(H_0\)</span> wird beibehalten. Homoskedastizität wird angenommen.</p>
<p>Für Fragestellung A sind somit alle Voraussetzungen für die Durchführung des <em>t</em>-Test erfüllt. :-) Hätte der Levene-Test keine Homoskedastizität angezeigt (<em>p</em> &lt;. 05), so kann der <em>t</em>-Test trotzdem, nach Korrektur der Freiheitsgrade (“Welch-Korrektur”), durchgeführt werden (s.u.). Die Welch-Korrektur berücksichtigt die Unterschiedlichkeit der Varianzen und wird durch das Argument <code>var.equal = F</code> angefordert (sie ist im Übrigen auch der Default in <code>R</code>!).</p>
</div>
<div id="t-Test" class="section level3 anchorheader">
<h3>1.4. Inferenzstatistik: <em>t</em>-Test</h3>
<p>Zur Erinnerung:</p>
<blockquote>
<p>Fragestellung A: “Erreichen Studentinnen und Studenten im Nerdiness Personality Attributes-Test im Durchschnitt gleich hohe Testwerte?”</p>
</blockquote>
<p><span class="math inline">\(\rightarrow\)</span> Fragestellung ist ungerichtet, erfordert also auch eine ungerichtete Hypothese.</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Unterschiedshypothese</li>
<li>Richtung des Effekts: Ungerichtet</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypothesenpaar (inhaltlich):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Studentinnen und Studenten unterscheiden sich nicht im Nerdiness-Testwert.<br />
</li>
<li><span class="math inline">\(H_1\)</span>: Studentinnen und Studenten unterscheiden sich im Nerdiness-Testwert.</li>
</ul>
<p>Hypothesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_\text{weiblich} = \mu_\text{männlich}\)</span> bzw. <span class="math inline">\(\mu_\text{weiblich} - \mu_\text{männlich} = 0\)</span><br />
</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_\text{weiblich} \ne \mu_\text{männlich}\)</span> bzw. <span class="math inline">\(\mu_\text{weiblich} - \mu_\text{männlich} \ne 0\)</span></li>
</ul>
<p><strong>Signifikanzniveau</strong></p>
<p>Das Signifikanzniveau muss vor der Untersuchung festgelegt werden. Es soll hier 5% betragen. <span class="math inline">\(\rightarrow \alpha=.05\)</span></p>
<p><strong>Durchführung des <em>t</em>-Tests in R: Funktion <code>t.test()</code></strong></p>
<p>Wir hatten im Rahmen des Einstichproben-<em>t</em>-Tests bereits die Funktion <code>t.test()</code> kennengelernt. Diese nutzen wir wieder. Wir übergeben dieser wieder die Formel, die wir bereits im Boxplot und im Levene-Test verwendet haben. Außerdem wählen wir einige Zusatzargumente, die dann zum Zweistichproben-<em>t</em>-Test für unabhängige Stichproben führt:</p>
<pre class="r"><code>t.test(dataB$nerd ~ dataB$geschl_faktor,       # abhängige Variable ~ unabhängige Variable
      paired = FALSE,                   # Stichproben sind unabhängig 
      alternative = &quot;two.sided&quot;,        # zweiseitige Testung (Default)
      var.equal = TRUE,                 # Homoskedastizität liegt vor (-&gt; Levene-Test)
      conf.level = .95)                 # alpha = .05 (Default)</code></pre>
<pre><code>## 
## 	Two Sample t-test
## 
## data:  dataB$nerd by dataB$geschl_faktor
## t = -1.8477, df = 146, p-value = 0.06667
## alternative hypothesis: true difference in means between group weiblich and group männlich is not equal to 0
## 95 percent confidence interval:
##  -0.5496253  0.0184949
## sample estimates:
## mean in group weiblich mean in group männlich 
##               3.104000               3.369565</code></pre>
<p><em>t</em>(<em>df</em> = 146, zweis.) = -1.848, <em>p</em> = 0.067 <span class="math inline">\(\rightarrow\)</span> nicht signifikant, <span class="math inline">\(H_0\)</span> wird beibehalten.</p>
</div>
<div id="Effektstärke" class="section level3 anchorheader">
<h3>1.5. Berechnung der Effektstärke Cohen’s <em>d</em></h3>
<p>Wir wissen nun, dass sich die Mittelwertsdifferenz nicht auf die Population verallgemeinern lässt. Dennoch wollen wir zur Eindordnung des Ergebnisses die Effektstärke ermitteln: Cohen’s <em>d</em> gibt den standardisierten Mittelwertsunterschied zwischen zwei Gruppen an. “Standardisiert” bedeutet, dass wir uns nicht mehr auf der Originalmetrik befinden (hier: Nerdiness-Testwert), sondern mit Standardabweichungen arbeiten. Ein Wert von 1 zeigt also an, dass sich die Gruppenmittelwerte um eine Standardabweichung voneinander unterscheiden. Die Effektstärke berechnet sich wie folgt:</p>
<p><span class="math display">\[ d = \frac{\bar{x}_1-\bar{x}_2} {\hat{\sigma}_{inn}} \]</span> wobei</p>
<p><span class="math display">\[ {\hat{\sigma}_{inn}} = \sqrt{ \frac{{\hat{\sigma}_1^2}*(n_1-1) + {\hat{\sigma}^2_2}*(n_2-1)} {(n_1-1) + (n_2-1)} }\]</span> Cohen (1988) hat folgende Konventionen zur Beurteilung der Effektstärke <em>d</em> vorgeschlagen, die man heranziehen kann, um den Effekt “bei kompletter Ahnungslosigkeit” einschätzen zu können (wissen wir mehr über den Sachverhalt, so sollten Effektstärken lieber im Bezug zu anderen Studienergebnissen interpretiert werden):</p>
<table>
<thead>
<tr class="header">
<th align="center"><em>d</em></th>
<th align="center">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">~ .2</td>
<td align="center">kleiner Effekt</td>
</tr>
<tr class="even">
<td align="center">~ .5</td>
<td align="center">mittlerer Effekt</td>
</tr>
<tr class="odd">
<td align="center">~ .8</td>
<td align="center">großer Effekt</td>
</tr>
</tbody>
</table>
<p><strong>Berechnung von Hand</strong></p>
<p>Wir führen die Berechnung von Cohen’s <em>d</em> zunächst von Hand durch. Dafür speichern wir uns die nötigen Größen ab und wenden dann die präsentierte Formel an:</p>
<pre class="r"><code>nerd_weiblich &lt;- dataB[(dataB$geschl_faktor==&quot;weiblich&quot;), &quot;nerd&quot;]
mw_weiblich &lt;- mean(nerd_weiblich, na.rm=T)
n_weiblich &lt;- length(nerd_weiblich[!is.na(nerd_weiblich)])
sigma_qu_weiblich &lt;- var(nerd_weiblich, na.rm=T) 

nerd_männlich &lt;- dataB[(dataB$geschl_faktor==&quot;männlich&quot;), &quot;nerd&quot;]
mw_männlich &lt;- mean(nerd_männlich, na.rm=T)
n_männlich &lt;- length(nerd_männlich[!is.na(nerd_männlich)])
sigma_qu_männlich &lt;- var(nerd_männlich, na.rm=T) 

sigma_inn &lt;- sqrt((sigma_qu_weiblich* (n_weiblich - 1) + sigma_qu_männlich* (n_männlich - 1)) / (n_weiblich-1 + n_männlich-1))

d1 &lt;- (mw_weiblich - mw_männlich) / sigma_inn
d1</code></pre>
<pre><code>## [1] -0.419214</code></pre>
<p><strong>Berechnung mit Funktion <code>cohen.d()</code></strong></p>
<p>Natürlich gibt es in <code>R</code> auch eine angenehmere Alternative:</p>
<pre class="r"><code>#alternativ:
#install.packages(&quot;effsize&quot;)
library(&quot;effsize&quot;)</code></pre>
<pre class="r"><code>d2 &lt;- cohen.d(dataB$nerd, dataB$geschl_faktor, na.rm=T)
d2</code></pre>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: -0.419214 (small)
## 95 percent confidence interval:
##       lower       upper 
## -0.87020194  0.03177397</code></pre>
<p>Die Effektstärke für diesen Mittelwertsunterschied beträgt <em>d</em> = -0.419.</p>
</div>
<div id="ergebnisinterpretation" class="section level3">
<h3>1.6. Ergebnisinterpretation</h3>
<p>Es wurde untersucht, ob sich Studentinnen und Studenten in dem Nerdiness-Testwert unterscheiden. Tatsächlich findet sich deskriptiv ein Unterschied: Studentinnen weisen einen durchschnittlichen Wert von 3.104 (<em>SD</em> = 0.621) auf, während die Studenten einen Wert von 3.37 (<em>SD</em> = 0.674) aufweisen. Dies entspricht nach Cohens Konvention (1988) einem kleinen bis mittleren Effekt (<em>d</em> = -0.419).</p>
<p>Zur Beantwortung der Fragestellung wurde ein <em>t</em>-Test unter Annahme von Homoskedastizität (<em>F</em>(1,146) = 0.57, <em>p</em> = 0.452) durchgeführt. Der Gruppenunterschied ist nicht signifikant (<em>t</em>(<em>df</em> = 146, zweis.) = -1.848, <em>p</em> = 0.067), somit wird die Nullhypothese beibehalten und die Alternativhypothese nicht angenommen. Studentinnen und Studenten unterscheiden sich im Nerdiness-Testwert nicht bedeutsam.</p>
<hr />
</div>
</div>
<div id="fragestellung-b-stimmen-studentinnen-dem-item-ich-denke-immer-darüber-nach-wie-meine-taten-sich-auf-die-umwelt-auswirken-stärker-zu-als-studenten" class="section level2">
<h2>2. Fragestellung B: Stimmen Studentinnen dem Item “Ich denke immer darüber nach, wie meine Taten sich auf die Umwelt auswirken” stärker zu als Studenten?</h2>
<p>Wir widmen uns nun der 2. Fragestellung. Dazu prüen wir, ob Item nr2 (“Ich denke immer darüber nach, wie meine Taten sich auf die Umwelt auswirken”) zur Messung von Naturverbundenheit von Studentinnen zustimmender beantwortet wird.</p>
<div id="vorbereitung-daten-einlesen-daten-aufbereiten" class="section level3">
<h3>2.1 Vorbereitung (Daten einlesen, Daten aufbereiten)</h3>
<p>Wir benutzen die für Fragestellung A aufbereiteten Daten (<code>dataB</code>) und müssen hier nichts weiter tun.</p>
</div>
<div id="deskriptivstatistik-1" class="section level3">
<h3>2.2. Deskriptivstatistik</h3>
<p>Nun folgt die deskriptive Untersuchung, ob Unterschiede über das Geschlecht vorliegen.</p>
<div id="grafisch-1" class="section level4">
<h4>2.2.1. grafisch</h4>
<p>Wir beginnen mit einer grafischen Auseinandersetzung mit der Fragestellung und erstellen einen Boxplot für die Variable nr2 pro Geschlecht.</p>
<pre class="r"><code># Gruppierter Boxplot:
boxplot(dataB$nr2 ~ dataB$geschl_faktor, 
        xlab=&quot;Geschlecht&quot;, ylab=&quot;nr2&quot;, 
        las=1, cex.lab=1.5, 
        main=&quot;nr2 nach Geschlecht&quot;)</code></pre>
<p><img src="/post/2022-12-05-tests-fuer-unabhaengige-stichproben_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Graphisch ist kein Unterschied zu erkennen.</p>
</div>
<div id="statistisch" class="section level4">
<h4>2.2.2. statistisch</h4>
<p>Nun schauen wir uns das Ganze wieder deskriptivstatistisch an.</p>
<pre class="r"><code>describeBy(dataB$nr2, dataB$geschl_faktor) # beide Gruppen im Vergleich</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: weiblich
##    vars   n mean sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 125 3.78  1      4    3.86 1.48   1   5     4 -0.61    -0.29 0.09
## ------------------------------------------------------------ 
## group: männlich
##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 23 3.39 1.12      4    3.47 1.48   1   5     4 -0.58    -0.37 0.23</code></pre>
<pre class="r"><code># Interquartilsbereich (IBQ) über summary()
summary( dataB[(dataB$geschl_faktor==&quot;weiblich&quot;), &quot;nr2&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   1.000   3.000   4.000   3.776   4.000   5.000      10</code></pre>
<pre class="r"><code>summary( dataB[(dataB$geschl_faktor==&quot;männlich&quot;), &quot;nr2&quot;]) </code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   1.000   3.000   4.000   3.391   4.000   5.000      10</code></pre>
<p>Deskriptiv weist die Gruppe der männlichen Studierenden den gleichen Median auf wie die Gruppe der weiblichen Studierenden. Auch die Interquartilbereiche unterscheiden sich nicht.</p>
</div>
</div>
<div id="voraussetzungsprüfung" class="section level3">
<h3>2.3. Voraussetzungsprüfung</h3>
<p>Um diese Beobachtung inferenzstatistisch zu untermauern, müssen wir den richtigen Test durchführen. Wir beginnen damit, die Voraussetzungen des <em>t</em>-Tests zu untersuchen:</p>
<p><strong>Voraussetzungen für die Durchführung des <em>t</em>-Tests:</strong></p>
<ol style="list-style-type: decimal">
<li>die abhängige Variable ist intervallskaliert <span class="math inline">\(\rightarrow\)</span> nicht ok<br />
</li>
<li>die einzelnen Messwerte sind voneinander unabhängig (Messwert einer Vpn hat keinen Einfluss auf den Messwert einer anderen) <span class="math inline">\(\rightarrow\)</span> ok<br />
</li>
<li>das untersuchte Merkmal ist in den Grundgesamtheiten der beiden Gruppen normalverteilt <span class="math inline">\(\rightarrow\)</span> (ggf.) optische Prüfung<br />
</li>
<li>Homoskedastizität: Varianzen der Variablen innerhalb der Populationen sind gleich <span class="math inline">\(\rightarrow\)</span> Levene-Test</li>
</ol>
<p>Da die erste Voraussetzung nicht erfüllt ist - das Item nr2 ist eine lediglich ordinalskalierte Variable - wollen wir nun einen Wilcoxon-Test (für unabhängige Stichproben) durchführen. Auch für diesen Test gilt es, Voraussetzungen zu untersuchen:</p>
<p><strong>Voraussetzungen für die Durchführung des Wilcoxon-Tests (für unabhängige Stichproben):</strong></p>
<ol style="list-style-type: decimal">
<li>die abhängige Variable ist stetig (zumindest ordinal-skaliert) <span class="math inline">\(\rightarrow\)</span> ok<br />
</li>
<li>die einzelnen Messwerte sind voneinander unabhängig (Messwert einer Vpn hat keinen Einfluss auf den Messwert einer anderen) <span class="math inline">\(\rightarrow\)</span> ok<br />
</li>
<li>das Merkmal folgt in beiden Gruppen der gleichen Verteilung <span class="math inline">\(\rightarrow\)</span> (ggf.) optische Prüfung<br />
</li>
<li>Streuung der Variablen für beide Gruppen ist innerhalb der Populationen gleich <span class="math inline">\(\rightarrow\)</span> Folgt aus der Voraussetzung 3 <span class="math inline">\(\rightarrow\)</span> als Indiz können wir in bestimmten Fällen den Levene-Test nutzen</li>
</ol>
<p><strong>zu 3): Optische Prüfung auf Vergleichbarkeit der Verteilungsform in den beiden Gruppen</strong></p>
<pre class="r"><code>#Gruppe 1 (weiblich) 
par(mfrow=c(1,2))

nr2_w &lt;- dataB[(dataB$geschl_faktor==&quot;weiblich&quot;), &quot;nr2&quot;]
hist(nr2_w, xlim=c(0,6), ylim=c(0,.6), main=&quot;Item nr2 (weiblich)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, probability=T, breaks = c(.5:5.5))

nr2_m &lt;- dataB[(dataB$geschl_faktor==&quot;männlich&quot;), &quot;nr2&quot;]
hist(nr2_m, xlim=c(0,6), ylim=c(0,.6), main=&quot;Item nr2 (männlich)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, probability=T, breaks = c(.5:5.5))</code></pre>
<p><img src="/post/2022-12-05-tests-fuer-unabhaengige-stichproben_files/figure-html/unnamed-chunk-24-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><span class="math inline">\(\rightarrow\)</span> Vergleichbarkeit der Verteilungsform in den beiden Gruppen ist einigermaßen gegeben <span class="math inline">\(\rightarrow\)</span> spricht für Wilcoxon-Test</p>
<p><strong>zu 4) Test auf Gleichheit der Streuungen (Levene-Test)</strong></p>
<p>Das Hypothesenpaar im Levene-Test lautet:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Homoskedastizität ist gegeben.<br />
</li>
<li><span class="math inline">\(H_1\)</span>: Homoskedastizität ist nicht gegeben.</li>
</ul>
<p>Ein nicht-signifikantes Ergebnis (<em>p</em> &gt; .05) zeigt also Homoskedastizität an.</p>
<pre class="r"><code>library(car)
leveneTest(dataB$nr2 ~ dataB$geschl_faktor)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1   0.757 0.3857
##       146</code></pre>
<p><span class="math inline">\(F\)</span>(1, 146) = 0.76, p = 0.386 <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(H_0\)</span> wird beibehalten: Homoskedastizität wird angenommen</p>
</div>
<div id="Wilcox" class="section level3 anchorheader">
<h3>2.4. Inferenzstatistik: Wilcoxon-Test</h3>
<p>Da die abhängige Variable (nr2) nur Ordinalskalenniveau aufweist, führen wir nun den Wilcoxon-Test (für unabhängige Stichproben) durch.</p>
<p>Zur Erinnerung:</p>
<blockquote>
<p>Fragestellung B: “Stimmen Studentinnen dem Item ‘Ich denke immer darüber nach, wie meine Taten sich auf die Umwelt auswirken’ (nr2) <em>stärker</em> zu als Studenten?”</p>
</blockquote>
<p><span class="math inline">\(\rightarrow\)</span> Fragestellung ist gerichtet, erfordert also auch eine gerichtete Hypothese.</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Unterschiedshypothese</li>
<li>Richtung des Effekts: Gerichtet</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypothesenpaar (inhaltlich):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Studentinnen stimmen Item nr2 weniger oder genauso stark zu wie Studenten.<br />
</li>
<li><span class="math inline">\(H_1\)</span>: Studentinnen stimmen Item nr2 stärker zu als Studenten.</li>
</ul>
<p>Hypothesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\eta_\text{weiblich} \leq \eta_\text{männlich}\)</span> bzw. <span class="math inline">\(\eta_\text{weiblich} - \eta_\text{männlich} \leq 0\)</span><br />
</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\eta_\text{weiblich} \gt \eta_\text{männlich}\)</span> bzw. <span class="math inline">\(\eta_\text{weiblich} - \eta_\text{männlich} \gt 0\)</span></li>
</ul>
<p><strong>Signifikanzniveau</strong></p>
<p>Das Signifikanzniveau muss vor der Untersuchung festgelegt werden. Es soll hier 5% betragen. <span class="math inline">\(\rightarrow \alpha = .05\)</span></p>
<p><strong>Durchführung des Wilcoxon-Tests in R: Funktion <code>wilcox.test()</code></strong></p>
<p>Die Funktion <code>wilcox.test()</code> nimmt im Grunde die gleichen Argumente entgegen wie die Funktion <code>t.test()</code>. Damit wir die gerichtete Hypothese in die richtige Richtung aufstellen können, müssen wir wissen, welches das erste Level des Faktors Geschlecht ist:</p>
<pre class="r"><code>levels(dataB$geschl_faktor) # wichtig zu wissen: die erste der beiden Faktorstufen ist &quot;weiblich&quot; </code></pre>
<pre><code>## [1] &quot;weiblich&quot; &quot;männlich&quot;</code></pre>
<p>Da die erste Faktorstufe “weiblich” ist, wissen wir, dass die gerichtete Hypothese “&gt;” lauten muss, also “greater”:</p>
<pre class="r"><code>wilcox.test(dataB$nr2 ~ dataB$geschl_faktor,     # abhängige Variable ~ unabhängige Variable
            paired = FALSE,               # Stichproben sind unabhängig
            alternative = &quot;greater&quot;,      # einseitige Testung, und zwar so, dass Gruppe1(w)-Gruppe2(m) &gt; 0
            conf.level = .95)             # alpha = .05</code></pre>
<pre><code>## 
## 	Wilcoxon rank sum test with continuity correction
## 
## data:  dataB$nr2 by dataB$geschl_faktor
## W = 1719.5, p-value = 0.05846
## alternative hypothesis: true location shift is greater than 0</code></pre>
<p><span class="math inline">\(W\)</span> = 1719.5, p = 0.058 <span class="math inline">\(\rightarrow\)</span> Ergebnis ist nicht signfikant, <span class="math inline">\(H_0\)</span> wird beibehalten.</p>
</div>
<div id="ergebnisinterpretation-1" class="section level3">
<h3>2.5. Ergebnisinterpretation</h3>
<p>Es wurde untersucht, ob Studentinnen dem Item “Ich denke immer darüber nach, wie meine Taten sich auf die Umwelt auswirken” (nr2) stäker zustimmen als Studenten. Deskriptiv besteht kein Unterschied in der Zustimmung: Beide Gruppen weisen einen Median von 4 auf (<span class="math inline">\(IQB_w\)</span> = [3; 4]; <span class="math inline">\(IQB_m\)</span> = [3; 4]). Zur Beantwortung der Fragestellung wurde ein Wilcoxon-Test durchgeführt. Der Gruppenunterschied über das Geschlecht ist nicht statistisch bedeutsam (<em>W</em> = 1719.5, <em>p</em> = 0.058). Somit wird die Nullhypothese beibehalten: Studentinnen stimmen Item nr2 nicht stärker zu als Studenten.</p>
<hr />
</div>
</div>
<div id="fragestellung-c-haben-studierende-mit-wohnort-in-uninähe-frankfurt-mit-gleicher-wahrscheinlichkeit-einen-nebenjob-wie-studierende-deren-wohnort-außerhalb-von-frankfurt-liegt" class="section level2">
<h2>3. Fragestellung C: Haben Studierende mit Wohnort in Uninähe (Frankfurt) mit gleicher Wahrscheinlichkeit einen Nebenjob wie Studierende, deren Wohnort außerhalb von Frankfurt liegt?</h2>
<p>Gehen wir nun zur 3. Fragestellung über. Wir verwenden wieder den vollen Datensatz <code>fb22</code>.</p>
<p>Zusätzlich zur Gruppenvariable ist in diesem Beispiel auch die abhängige Variable nominalskaliert. Um Fragen wie diese zu beantworten, werden daher die Populationswahrscheinlichkeiten (<code>job</code>: ja [<code>ja</code>] vs. nein [<code>nein</code>]) zwischen den beiden Gruppen (<code>ort</code>: Frankfurt [<code>FFM</code>] vs. außerhalb [<code>andere</code>]) miteinander verglichen. Diese Prüfung erfolgt mithilfe der <span class="math inline">\(\chi^2\)</span>-Verteilung <span class="math inline">\(\rightarrow \chi^2\)</span>-Test.</p>
<div id="datenaufbereitung" class="section level3">
<h3>3.1. Datenaufbereitung</h3>
<p>Zunächst müssen wir den <code>ort</code> und den <code>job</code> als Faktor abspeichern und entsprechende Labels vergeben. Damit wir hier keine Probleme bekommen, müssen wir zunächst prüfen, ob die Variablen ein <code>factor</code> sind:</p>
<pre class="r"><code>is.factor(fb22$ort)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>is.factor(fb22$job)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>Dies ist bei beiden nicht der Fall, weswegen wir hier die Variable als Faktor ablegen können. Wir verwenden die Labels, die wir oben bereits in Klammern geschrieben haben.</p>
<pre class="r"><code># Achtung, nur einmal durchführen (ansonsten Datensatz neu einladen und Code erneut durchlaufen lassen!)
fb22$ort &lt;- factor(fb22$ort, levels=c(1,2), labels=c(&quot;FFM&quot;, &quot;anderer&quot;))

fb22$job &lt;- factor(fb22$job, levels=c(1,2), labels=c(&quot;nein&quot;, &quot;ja&quot;))</code></pre>
</div>
<div id="deskriptivstatistikvoraussetzungsprüfung" class="section level3">
<h3>3.2. Deskriptivstatistik/Voraussetzungsprüfung</h3>
<p>Wir wollen wieder Deskriptivstatistiken betrachten und die Voraussetzungen des <span class="math inline">\(\chi^2\)</span>-Tests prüfen.</p>
<p><strong>Voraussetzungen:</strong></p>
<ol style="list-style-type: decimal">
<li>Die einzelnen Beobachtungen sind voneinander unabhängig <span class="math inline">\(\rightarrow\)</span> ok (durch das Studiendesign anzunehmen)</li>
<li>Jede Person lässt sich eindeutig einer Kategorie bzw. Merkmalskombination zuordnen <span class="math inline">\(\rightarrow\)</span> ok (durch das Studiendesign anzunehmen)</li>
<li>Zellbesetzung für alle <span class="math inline">\(n_{ij}\)</span> &gt; 5 <span class="math inline">\(\rightarrow\)</span> Prüfung anhand von Häufigkeitstabelle</li>
</ol>
<p><strong>zu Punkt 3) Zellbesetzung <em>n</em> &gt; 5</strong></p>
<p>Jede Zelle muss mindestens 5 Fälle aufzeigen, da die Ergebnisse sonst verzerrt werden.</p>
<pre class="r"><code>tab &lt;- table(fb22$ort, fb22$job)
tab</code></pre>
<pre><code>##          
##           nein ja
##   FFM       60 35
##   anderer   37 17</code></pre>
<p><span class="math inline">\(\rightarrow n_{ij}\)</span> &gt; 5 in allen Zellen gegeben.</p>
</div>
<div id="inferenzstatistische-beantwortung-der-fragestellung" class="section level3">
<h3>3.3. Inferenzstatistische Beantwortung der Fragestellung</h3>
<p>Kommen wir nun zur inferenzstatistischen Prüfung unserer Hypothese.</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Zusammenhangshypothese<br />
</li>
<li>Richtung des Effekts: Ungerichtet<br />
</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypothesenpaar (inhaltlich):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Studierende mit Wohnort in Uninähe haben mit gleicher Wahrscheinlichkeit einen Nebenjob wie Studierende, deren Wohnort außerhalb von Frankfurt liegt.<br />
</li>
<li><span class="math inline">\(H_1\)</span>: Studierende mit Wohnort in Uninähe haben mit einer höheren oder niedrigeren Wahrscheinlichkeit einen Nebenjob als Studierende, deren Wohnort außerhalb von Frankfurt liegt.</li>
</ul>
<p>Hypothesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\pi_{ij} = \pi_{i\bullet} \cdot \pi_{\bullet j}\)</span><br />
</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\pi_{ij} \neq \pi_{i\bullet} \cdot \pi_{\bullet j}\)</span></li>
</ul>
<p>wobei <span class="math inline">\(\pi_{ij}\)</span> die Wahrscheinlichkeit, in Zelle <span class="math inline">\(ij\)</span> zu landen, ist. Betrachten wir die Häufigkeitstabelle, dann entspricht dies der Wahrscheinlichkeit der Ausprägung der <span class="math inline">\(i\)</span>-ten Zeile (Variable: Wohnortnähe) und der <span class="math inline">\(j\)</span>-ten Spalte (Variable: Nebenjob). <span class="math inline">\(\pi_{i\bullet}\)</span> beschreibt die Wahrscheinlichkeit, die Ausprägung der <span class="math inline">\(i\)</span>-ten Zeile (Variable: Wohnortnähe) zu haben. <span class="math inline">\(\pi_{\bullet j}\)</span> beschreibt die Wahrscheinlichkeit, die Ausprägung der der <span class="math inline">\(j\)</span>-ten Spalte (Variable: Nebenjob) zu haben. Die beiden betrachteten Variablen sind voneinander unabhängig, wenn die Wahrscheinlichkeit für das Auftreten von Y (Nebenjob) nicht davon abhängt, welches X (Wohnort) vorliegt. Ist dies der Fall, lässt sich die Wahrscheinlichkeit für das Auftreten der Kombination der Merkmalsausprägungen in das Produkt der Einzelwahrscheinlichkeiten zerlegen. Bspw. sollte sich die Wahrscheinlichkeit in Frankfurt zu wohnen und keinen Nebenjob zu haben, ausdrücken lassen (gleich sein) mit der Wahrscheinlichkeit in Frankfurt zu wohnen multipliziert mit der Wahrscheinlichkeit keinen Nebenjob zu haben: <span class="math inline">\(\pi_\text{FFM,nein}=\pi_{\text{FFM},\bullet}\cdot\pi_{\bullet,\text{nein}}\)</span> (unter <span class="math inline">\(H_0\)</span>).</p>
<p><strong>Signifikanzniveau</strong> <span class="math inline">\(\alpha\)</span></p>
<p>Die Irrtumswahrscheinlichkeit soll 5% betragen. <span class="math inline">\(\rightarrow \alpha=.05\)</span></p>
<div id="vierfelder-chi2-test-in-r-manuelle-berechnung-über-formel-chi-sq" class="section level4">
<h4>3.3.1. Vierfelder-<span class="math inline">\(\chi^2\)</span>-Test in R: “manuelle” Berechnung über Formel {Chi-Sq}</h4>
<p><strong>erwartete Häufigkeiten berechnen</strong></p>
<p>Für jede Zelle lassen sich die unter Gültigkeit der Nullhypothese erwarteten Häufigkeiten <span class="math inline">\(e_{ij}\)</span> bestimmen (hier sind <span class="math inline">\(n_{i\bullet}\)</span> und <span class="math inline">\(n_{\bullet j}\)</span> die absoluten Häufigkeiten), die zu den Wahrscheinlichkeiten aus dem Hypothesenpaar gehören:</p>
<p><span class="math display">\[e_{ij} = \frac{n_{i\bullet} \cdot n_{\bullet j}}{n}\]</span></p>
<p><span class="math inline">\(n_{i\bullet}\)</span> und <span class="math inline">\(n_{\bullet j}\)</span> lassen sich über die Randsummen bestimmen (sie symbolisieren eigentlich: <span class="math inline">\(n_{i\bullet}=n\hat{\pi}_{i\bullet}\)</span>, mit <span class="math inline">\(n\)</span> als Stichprobengröße). Diese hängen wir unseren Daten an. Anschließend erstellen wir einen neuen Datensatz und fügen alle erwarteten Häufigkeiten dort ein.</p>
<pre class="r"><code>tab_mar &lt;- addmargins(tab) # Randsummen zu Tabelle hinzufügen
tab_mar</code></pre>
<pre><code>##          
##           nein  ja Sum
##   FFM       60  35  95
##   anderer   37  17  54
##   Sum       97  52 149</code></pre>
<pre class="r"><code>expected &lt;- data.frame(nein=c((tab_mar[1,3]*tab_mar[3,1])/tab_mar[3,3],
                              (tab_mar[2,3]*tab_mar[3,1])/tab_mar[3,3]),
                       ja=c((tab_mar[1,3]*tab_mar[3,2])/tab_mar[3,3],
                            (tab_mar[2,3]*tab_mar[3,2])/tab_mar[3,3]))
expected</code></pre>
<pre><code>##       nein       ja
## 1 61.84564 33.15436
## 2 35.15436 18.84564</code></pre>
<p>Bspw. für die Kombination (FFM, nein) ergibt sich eine erwartete Häufigkeit von 61.85, welcher eine beobachtete Häufigkeit von 60 gegenüber steht. Mit dem <span class="math inline">\(\chi^2\)</span>-Test können wir nun bestimmen, ob diese Unterschiede statistisch bedeutsam groß sind.</p>
<p><strong>Prüfgröße</strong> <span class="math inline">\(\chi^2\)</span> berechnen</p>
<p>Formel: <span class="math display">\[\chi^2 = \sum_{i=1}^{2}{ \sum_{j=1}^{2}{ \frac{(n_{ij}-e_{ij})^2} {e_{ij}}}}\]</span></p>
<pre class="r"><code>chi_quadrat_Wert &lt;- (tab[1,1]-expected[1,1])^2/expected[1,1]+
                    (tab[1,2]-expected[1,2])^2/expected[1,2]+
                    (tab[2,1]-expected[2,1])^2/expected[2,1]+
                    (tab[2,2]-expected[2,2])^2/expected[2,2]
chi_quadrat_Wert</code></pre>
<pre><code>## [1] 0.435471</code></pre>
<p><strong>Signfikanztestung: per Vergleich von empirischem und kritischem</strong> <span class="math inline">\(\chi^2\)</span></p>
<p>Die Freiheitsgrade berechnen sich aus der Anzahl der untersuchten Kategorien: <span class="math inline">\(df = (p - 1) \cdot (k - 1)\)</span>. Hier, im Fall des Vierfelder-<span class="math inline">\(\chi^2\)</span>-Tests also mit <span class="math inline">\(df = 1\)</span>, wobei</p>
<ul>
<li><em>p</em>: Anzahl Kategorien Variable “ort” = 2<br />
</li>
<li><em>k</em>: Anzahl Kategorien Variable “job” = 2</li>
</ul>
<p>Zur Bestimmung des kritischen Wertes und des <span class="math inline">\(p\)</span>-Wertes ziehen wir die jeweiligen Funktionen der <span class="math inline">\(\chi^2\)</span> -Verteilung heran:</p>
<pre class="r"><code>qchisq(.95, 1) # kritischer Wert</code></pre>
<pre><code>## [1] 3.841459</code></pre>
<pre class="r"><code>pchisq(chi_quadrat_Wert, 1, lower.tail = FALSE) # p-Wert</code></pre>
<pre><code>## [1] 0.5093166</code></pre>
<p>Insgesamt ergibt sich damit.</p>
<ul>
<li><em>df</em> = 1</li>
<li><span class="math inline">\(\chi^2_{krit}\)</span> = 3.84</li>
<li><span class="math inline">\(\chi^2_{emp}\)</span> = 0.435</li>
<li><span class="math inline">\(\chi^2_{emp} &lt; \chi^2_{krit}\)</span> <span class="math inline">\(\rightarrow H_0\)</span> wird beibehalten</li>
<li><span class="math inline">\(p\)</span> = 0.509</li>
<li><span class="math inline">\(p\)</span>-Wert &gt; <span class="math inline">\(\alpha\)</span>-Fehlerniveau <span class="math inline">\(\rightarrow H_0\)</span> wird beibehalten</li>
</ul>
<p>Daraus lässt sich zusammenfassen: Die Wohnnähe zur Uni hängt nicht damit zusammen, ob ein Nebenjob ausgeübt wird <span class="math inline">\(\chi^2\)</span>(df=1)=0.435, <span class="math inline">\(p\)</span> = 0.509.</p>
</div>
<div id="vierfelder-chi2-test-in-r-funktion-chisq.test" class="section level4">
<h4>3.3.2. Vierfelder-<span class="math inline">\(\chi^2\)</span>-Test in R: Funktion <code>chisq.test()</code></h4>
<p>Die Funktion <code>chisq.test()</code> übernimmt die Arbeit für uns, wenn wir ihr einfach eine 4-Feldertabelle übergeben. Als Argumente brauchen wir hauptsächlich das Objekt mit den Häufigkeiten. Weiterhin müssen wir das Argument <code>correct</code> mit <code>FALSE</code> angeben. Ansonsten würde standardmäßig die Kontinuitätskorrektur nach Yates durchgeführt werden. Diese ist als Alternative gedacht, wenn nicht der <span class="math inline">\(\chi^2\)</span>-Verteilung gefolgt wird. Ein Indiz dafür sind bspw. sehr kleine Zahlen in manchen Kombinationen der Faktoren. Da wir hier in jeder Zelle einen größeren Wert hatten, brauchen wir diese Korrektur nicht.</p>
<pre class="r"><code>chisq.test(tab,        # Kreuztabelle
           correct=F)  # keine Kontinuinitätskorrektur nach Yates</code></pre>
<pre><code>## 
## 	Pearson&#39;s Chi-squared test
## 
## data:  tab
## X-squared = 0.43547, df = 1, p-value = 0.5093</code></pre>
<p>Das Ergebnis unterscheidet sich natürlich nicht zu unserer händischen Berechnung. Die Wohnnähe zur Uni hängt nicht damit zusammen, ob ein Nebenjob ausgeübt wird.</p>
</div>
</div>
<div id="effektstärken" class="section level3">
<h3>3.4. Effektstärken</h3>
<p>Auch für den <span class="math inline">\(\chi^2\)</span>-Test gibt es die Möglichkeit zur Einordnung der Effektstärke. Dabei haben Sie in der Vorlesung zwei Varianten kennengelernt.</p>
<p><strong>Yules Q</strong></p>
<p>Dieses berechnet sich als</p>
<p><span class="math display">\[Q=\frac{n_{11}n_{22}-n_{12}n_{21}}{n_{11}n_{22}+n_{12}n_{21}},\]</span></p>
<p>welches einen Wertebereich von [-1,1] aufweist und analog zur Korrelation interpretiert werden kann. 1 steht in diesem Fall für einen perfekten positiven Zusammenhang (dazu in der entsprechenden Sitzung mehr).</p>
<p>In <code>R</code> sieht das so aus:</p>
<pre class="r"><code>effekt_YulesQ &lt;- (tab[1,1]*tab[2,2]-tab[1,2]*tab[2,1])/
                 (tab[1,1]*tab[2,2]+tab[1,2]*tab[2,1])
effekt_YulesQ</code></pre>
<pre><code>## [1] -0.1187905</code></pre>
<p><strong>Phi</strong> (<span class="math inline">\(\phi\)</span>)</p>
<p>Auch kann man <span class="math inline">\(\phi\)</span> bestimmen:</p>
<p><span class="math display">\[\phi = \frac{n_{11}n_{22}-n_{12}n_{21}}{\sqrt{(n_{11}+n_{12})(n_{11}+n_{21})(n_{12}+n_{22})(n_{21}+n_{22})}}\]</span> welches einen Wertebereich von [-1,1] aufweist und analog zur Korrelation interpretiert werden kann. 1 steht in diesem Fall für einen perfekten positiven Zusammenhang (dazu in der entsprechenden Sitzung mehr).</p>
<p>In <code>R</code> sieht das so aus:</p>
<pre class="r"><code>effekt_phi &lt;- (tab[1,1]*tab[2,2]-tab[1,2]*tab[2,1])/
  sqrt((tab[1,1]+tab[1,2])*(tab[1,1]+tab[2,1])*(tab[1,2]+tab[2,2])*(tab[2,1]+tab[2,2]))
effekt_phi</code></pre>
<pre><code>## [1] -0.0540613</code></pre>
<p><strong>Umsetzung mit <code>R</code></strong></p>
<p>Das Ganze lässt sich auch mit dem <code>psych</code> und der darin enthaltenen Funktion <code>phi()</code> umsetzen:</p>
<pre class="r"><code># alternativ mit psych Paket
library(psych)
phi(tab, digits = 8)</code></pre>
<pre><code>## [1] -0.0540613</code></pre>
<pre class="r"><code>Yule(tab)</code></pre>
<pre><code>## [1] -0.1187905</code></pre>
<pre class="r"><code># Äquivalentes Ergebnis mittels Pearson-Korrelation (kommt in den nächsten Sitzungen)
# (dichotome Variablen)
ort_num &lt;- as.numeric(fb22$ort)
job_num &lt;- as.numeric(fb22$job)
cor(ort_num, job_num, use=&quot;pairwise&quot;)</code></pre>
<pre><code>## [1] -0.0540613</code></pre>
<p>Cohen (1988) hat folgende Konventionen zur Beurteilung der Effektstärke <span class="math inline">\(\phi\)</span> vorgeschlagen, die man heranziehen kann, um den Effekt “bei kompletter Ahnungslosigkeit” einschätzen zu können (wissen wir mehr über den Sachverhalt, so sollten Effektstärken lieber im Bezug zu anderen Studienergebnissen interpretiert werden):</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(|\phi|\)</span></th>
<th align="center">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">~ .1</td>
<td align="center">kleiner Effekt</td>
</tr>
<tr class="even">
<td align="center">~ .3</td>
<td align="center">mittlerer Effekt</td>
</tr>
<tr class="odd">
<td align="center">~ .5</td>
<td align="center">großer Effekt</td>
</tr>
</tbody>
</table>
<p>Der Wert für den Zusammenhang der beiden Variablen ist also bei völliger Ahnungslosigkeit als klein einzuschätzen.</p>
</div>
<div id="ergebnisinterpretation-2" class="section level3">
<h3>3.5. Ergebnisinterpretation</h3>
<p>Es wurde untersucht, ob Studierende mit Wohnort in Uninähe (also in Frankfurt) mit gleicher Wahrscheinlichkeit einen Nebenjob haben wie Studierende, deren Wohnort außerhalb von Frankfurt liegt. Zur Beantwortung der Fragestellung wurde ein Vierfelder-Chi-Quadrat-Test für unabhängige Stichproben berechnet. Der Zusammenhang zwischen Wohnort und Nebenjob ist nicht signifikant (<span class="math inline">\(\chi^2\)</span>(1) = 0.435, <em>p</em> = 0.509), somit wird die Nullhypothese beibehalten. Der Effekt ist von vernachlässigbarer Stärke (<span class="math inline">\(\phi\)</span> = -0.054). Studierende mit Wohnort in Uninähe haben mit gleicher Wahrscheinlichkeit einen Nebenjob wie Studierende, deren Wohnort außerhalb von Frankfurt liegt.</p>
</div>
</div>
