---
title: "Schätzung von Kausaleffekten 1"
output:
  html_document
  
date: '2022-01-31'
slug: kausal
categories:
     - MSc5a
     
tags:
- Kausalität
- ANCOVA

subtitle: ''
summary: ''
authors: [hartig]
lastmod: '2022-01-31 12:51:12 CEST'
featured: no
header:
     image: "/header/KliPsy_Kausal_Head.jpg"
     caption: "[Courtesy of pxhere](https://pxhere.com/de/photo/1109965)"
projects: []
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="pakete-laden" class="section level4">
<h4>Pakete laden</h4>
<pre class="r"><code># Benötigte Pakete --&gt; Installieren, falls nicht schon vorhanden
library(psych)        # Für Deskriptivstatistiken
library(EffectLiteR)  # Für die Schätzung adjustierter Effekte</code></pre>
</div>
<div id="inhalte" class="section level3">
<h3>Inhalte</h3>
<ul>
<li><a href="#Einleitung">Einleitung und Datenbeispiel</a></li>
<li><a href="#PFE">Prima-Facie-Effekt</a></li>
<li><a href="#ANCOVA">Effektschätzung mittels ANCOVA</a></li>
<li><a href="#EffectLite">Effektschätzung mit EffectLiteR</a></li>
</ul>
</div>
<div id="Einleitung" class="section level2">
<h2>Einleitung und Datenbeispiel</h2>
<p>In der psychologischen Forschung ist die Bestimmung kausaler Effekte oft eine Herausforderung, dies gilt auch für die klinisch-psychologischen Forschung. Wenn ein Treatment nicht randomisiert zugeordnet werden kann, besteht die Gefahr, dass andere Einflussgrößen geschätzte Wirkungen des Treatments verzerren.</p>
<p>In unserem fiktiven Datenbeispiel wurden Patient*innen, die an einer Depression oder einer Angststörung leiden, entweder mit einer kognitiven Verhaltenstherapie (CBT) behandelt oder in einer Wartekontrollgruppe belassen. Eine zufällige Zuordnung war nicht vollständig möglich, da die Zuordnung von überweisenden Hausarzt-Praxen der Patient*innen mit beeinflusst werden konnte (z.B. durch Geltendmachung einer besonderen Dringlichkeit der Therapie). Zunächst laden wir diesen Datensatz und verschaffen uns einen Überblick:</p>
<pre class="r"><code>load(url(&quot;https://pandar.netlify.app/post/CBTdata.rda&quot;))
head(CBTdata)</code></pre>
<pre><code>##   Age Gender Treatment Disorder BDI_pre SWL_pre BDI_post SWL_post
## 1  39 female       CBT      ANX      27      10       24       15
## 2  36 female       CBT      ANX      22      13       13       17
## 3  61 female       CBT      ANX      24      11       17       14
## 4  70 female       CBT      ANX      30      15       22       19
## 5  64 female       CBT      DEP      32      12       26       20
## 6  50 female       CBT      ANX      24      15       23       22</code></pre>
<pre class="r"><code>table(CBTdata$Treatment) </code></pre>
<pre><code>## 
##  WL CBT 
## 150 176</code></pre>
<p>Der Datensatz enthält Daten von 326 Patient*innen, davon 176 in der Therapiegruppe (CBT) und 150 in der Wartelisten-Bedingung (WL). Vor und nach dem Treatment wurde die Schwere depressiver Symptomatik mit dem Beck-Depressions-Inventar erfasst (<code>BDI_pre</code> und <code>BDI_post</code>) sowie die Lebenszufriedenheit mit dem Satisfaction With Life Screening (<code>SWL_pre</code> und <code>SWL_post</code>).</p>
<p>Kritisch für die Evaluation von Therapie-Effekten sind insbesondere vorab bestehende Gruppenunterschiede in den AVs und anderen Variablen, diese schauen wir uns mit der Funktion <code>describeBy</code> deskriptiv an.</p>
<pre class="r"><code># Deskriptivstatistiken der Gruppen für Alter und Prätest-Werte (&#39;range=F&#39; macht die Tabelle etwas übersichtlicher)
describeBy(CBTdata[,c(&quot;Age&quot;, &quot;BDI_pre&quot;, &quot;SWL_pre&quot;)], group = CBTdata$Treatment, range=F)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: WL
##         vars   n  mean    sd  skew kurtosis   se
## Age        1 150 48.15 15.41 -0.16    -1.27 1.26
## BDI_pre    2 150 19.95  4.10  0.08     0.04 0.33
## SWL_pre    3 150 18.13  4.04 -0.08     0.31 0.33
## ------------------------------------------------------------ 
## group: CBT
##         vars   n  mean    sd  skew kurtosis   se
## Age        1 176 45.47 15.94  0.02    -1.36 1.20
## BDI_pre    2 176 23.94  3.95 -0.01    -0.25 0.30
## SWL_pre    3 176 14.76  4.06  0.04    -0.28 0.31</code></pre>
<p>Hinsichtlich des Alters sind beide Gruppen sehr ähnlich (<span class="math inline">\(t=1.541\)</span>; <span class="math inline">\(p=0.124\)</span>, <span class="math inline">\(d=0.17\)</span>). Die Patient*innen in der Warteliste-Gruppe haben jedoch deutlich niedrigere BDI-Werte (<span class="math inline">\(t=-8.914\)</span>; <span class="math inline">\(p=0\)</span>, <span class="math inline">\(d=-1\)</span>) und höhere SWL-Werte (<span class="math inline">\(t=7.504\)</span>; <span class="math inline">\(p=0\)</span>, <span class="math inline">\(d=0.84\)</span>), was zeigt, das die Vergleichbarkeit der Gruppen nicht gewährleistet ist.</p>
<p>Zusammenhänge von Alter und Art der Störung mit dem Treatment können wir deskriptiv mit Kreuztabellen darstellen und mit einem <span class="math inline">\(\chi^2\)</span>-Test testen. Wir sehen, dass die Verteilung des Geschlechts auf die Gruppen nicht systematisch ist, dass jedoch dass Patient*innen mit Angsstörung in der Therapiegruppe überrepräsentiert sind:</p>
<pre class="r"><code># Tabelle erzeugen
tab.gender &lt;- table(CBTdata$Treatment, CBTdata$Gender)
# Kreuztabelle mit Anteilen Zeilenweise, durch Multiplikation mit 100 als Zeilenprozent zu lesen
round(prop.table(tab.gender, 2)*100)</code></pre>
<pre><code>##      
##       male female
##   WL    47     45
##   CBT   53     55</code></pre>
<pre class="r"><code># Chi2-Test
chisq.test(tab.gender)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  tab.gender
## X-squared = 0.024746, df = 1, p-value = 0.875</code></pre>
<pre class="r"><code>tab.disorder &lt;- table(CBTdata$Treatment, CBTdata$Disorder)
round(prop.table(tab.disorder, 2)*100)</code></pre>
<pre><code>##      
##       ANX DEP
##   WL   28  64
##   CBT  72  36</code></pre>
<pre class="r"><code>chisq.test(tab.disorder)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  tab.disorder
## X-squared = 40.351, df = 1, p-value = 2.122e-10</code></pre>
</div>
<div id="PFE" class="section level2">
<h2>Prima-Facie-Effekt</h2>
<p>Ungeachtet der fraglichen Vergleichbarkeit schauen wir uns den augenscheinlichen Effekt der Therapie auf depressive Symptome an, grafisch als Boxplot und inferenzstatistisch mittels t-Test.</p>
<pre class="r"><code>boxplot(CBTdata$BDI_post ~ CBTdata$Treatment)</code></pre>
<p><img src="/post/2022-01-31-Kausaleffekte_1_KliPPS_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>BDI.PFE &lt;- lm(BDI_post ~ Treatment, data = CBTdata)
summary(BDI.PFE)</code></pre>
<pre><code>## 
## Call:
## lm(formula = BDI_post ~ Treatment, data = CBTdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -12.4943  -3.4943  -0.1067   3.5057  17.8933 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   18.1067     0.4235  42.750   &lt;2e-16 ***
## TreatmentCBT   0.3877     0.5764   0.672    0.502    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.187 on 324 degrees of freedom
## Multiple R-squared:  0.001394,   Adjusted R-squared:  -0.001688 
## F-statistic: 0.4523 on 1 and 324 DF,  p-value: 0.5017</code></pre>
<p>Wir sehen bereits grafisch, dass sich beide Gruppen kaum unterscheiden. Der Unterschied von 0.39 Punkten ist auch nicht signifikant. Nach diesem Ergebnis hat die Therapie keinen Effekt auf die Schwere der depressiven Symptomatik.</p>
</div>
<div id="ANCOVA" class="section level2">
<h2>Adjustierter Effekt mittels ANCOVA</h2>
<div id="klassische-ancova" class="section level3">
<h3>Klassische ANCOVA</h3>
<p>In der Annahme, dass die Selektion ins Treatment durch die vorab gemessenen Eigenschaften der Patient*innen erklärt werden kann, schätzen wir den Effekt des Treatments zunächst mit einer klassischen ANCOVA, in der die Variablen, hinsichtlich derer sich die Gruppen unterscheiden (Prätest-Werte und Art der Störung), kontrolliert werden:</p>
<pre class="r"><code># ANCOVA mit Treatment und Kovariaten
BDI.adj &lt;- lm(BDI_post ~ Treatment + Disorder + BDI_pre + SWL_pre, data = CBTdata)
summary(BDI.adj)</code></pre>
<pre><code>## 
## Call:
## lm(formula = BDI_post ~ Treatment + Disorder + BDI_pre + SWL_pre, 
##     data = CBTdata)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.6979 -1.8945 -0.0409  2.0341  8.4957 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   5.95691    1.45291   4.100 5.24e-05 ***
## TreatmentCBT -4.05665    0.39788 -10.196  &lt; 2e-16 ***
## DisorderDEP   1.48794    0.38896   3.825 0.000157 ***
## BDI_pre       0.91387    0.04649  19.655  &lt; 2e-16 ***
## SWL_pre      -0.39267    0.04385  -8.955  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.059 on 321 degrees of freedom
## Multiple R-squared:  0.656,  Adjusted R-squared:  0.6517 
## F-statistic:   153 on 4 and 321 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Unter Einbezug der Kovariaten findet sich ein signifikanter Therapieeffekt von -4.06 Punkten. Es wird auch sichtbar, dass alle Kovariaten einen Effekt auf die AV nach dem Treatment haben.</p>
</div>
<div id="generalisierte-ancova" class="section level3">
<h3>Generalisierte ANCOVA</h3>
<p>In einer generalisierten ANCOVA nehmen wir noch die Wechselwirkungen zwischen den Kovariaten und dem Treatment hinzu:</p>
<pre class="r"><code># Zentrierte Kovariaten bilden
CBTdata$BDI_pre_c &lt;- scale(CBTdata$BDI_pre, scale = F)
CBTdata$SWL_pre_c &lt;- scale(CBTdata$SWL_pre, scale = F)
# Generalisierte ANCOVA mit allen Wechselwirkungen zwischen Kovariaten und Treatment
BDI.adj2 &lt;- lm(BDI_post ~ Treatment + Disorder + BDI_pre_c + SWL_pre_c +
                Treatment:Disorder + Treatment:BDI_pre_c + Treatment:SWL_pre_c, data = CBTdata)
summary(BDI.adj2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = BDI_post ~ Treatment + Disorder + BDI_pre_c + SWL_pre_c + 
##     Treatment:Disorder + Treatment:BDI_pre_c + Treatment:SWL_pre_c, 
##     data = CBTdata)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.5620 -1.8491 -0.0809  1.9808  8.0522 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              20.08608    0.45756  43.898  &lt; 2e-16 ***
## TreatmentCBT             -4.38814    0.56952  -7.705 1.68e-13 ***
## DisorderDEP               1.16111    0.59835   1.941   0.0532 .  
## BDI_pre_c                 0.94310    0.06928  13.614  &lt; 2e-16 ***
## SWL_pre_c                -0.41531    0.06672  -6.224 1.52e-09 ***
## TreatmentCBT:DisorderDEP  0.60412    0.78877   0.766   0.4443    
## TreatmentCBT:BDI_pre_c   -0.05988    0.09366  -0.639   0.5231    
## TreatmentCBT:SWL_pre_c    0.04826    0.08878   0.544   0.5871    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.062 on 318 degrees of freedom
## Multiple R-squared:  0.6585, Adjusted R-squared:  0.651 
## F-statistic:  87.6 on 7 and 318 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div id="EffectLite" class="section level2">
<h2>Adjustierter Effekt mittels EffectLiteR</h2>
<p>Den adjustierten Effekt können wir auch mit <code>EffectLiteR</code> schätzen, hierbei wird die Gewichtung nach Kovariaten berücksichtigt. Die Funktion, die wir dazu benutzen heißt <code>effectLite</code>. Das Kriterium (AV) wird dem Argument <code>y</code> übergeben, <code>x</code> die Gruppierungsvariable (UV), <code>z</code> wird als Vektor die Kovariaten übergeben, <code>k</code> werden kategoriale Kovariaten übergeben, <code>data</code> schreiben wir die Daten zu und mit <code>method = "lm"</code> legen wir fest, dass alles auf Basis des linearen Modells geschätzt werden soll.</p>
<pre class="r"><code># Schätzung des Effekts des Treatments auf BDI_post mit effectLite,
# Prätest-Werte als kontinuierliche, Störung als kategoriale Kovariate
# &#39;lm&#39; als Methode für eine Schätzung per ANCOVA
effectLite(y=&quot;BDI_post&quot;, x=&quot;Treatment&quot;, z=c(&quot;BDI_pre&quot;, &quot;SWL_pre&quot;), k=c(&quot;Disorder&quot;), data = CBTdata, method = &quot;lm&quot;)</code></pre>
<pre><code>## 
## 
## --------------------- Variables  --------------------- 
## 
## Outcome variable Y:  BDI_post 
## Treatment variable X:  Treatment   (Reference group:  WL)
## Categorical covariates K:  Disorder 
## Continuous covariates in Z=(Z1,Z2): Z1=BDI_pre Z2=SWL_pre 
## 
## Levels of Treatment Variable X 
##    X   Treatment (original)   Indicator
##    0                     WL       I_X=0
##    1                    CBT       I_X=1
## 
## Levels of Unfolded Categorical Covariate K 
##    K   Disorder   Indicator
##    0        ANX       I_K=0
##    1        DEP       I_K=1
## 
## Cells 
##     Treatment (original)   K   Cell
## 1                     WL   0     00
## 2                     WL   1     01
## 3                    CBT   0     10
## 4                    CBT   1     11
## 
## 
##  --------------------- Regression Model --------------------- 
## 
##  E(Y|X,K,Z) = g0(K,Z) + g1(K,Z)*I_X=1 
##   g0(K,Z) = g000 + g001 * Z1 + g002 * Z2 + g010 * I_K=1 + g011 * I_K=1 * Z1 + 
##             + g012 * I_K=1 * Z2
##   g1(K,Z) = g100 + g101 * Z1 + g102 * Z2 + g110 * I_K=1 + g111 * I_K=1 * Z1 + 
##             + g112 * I_K=1 * Z2
## 
##  Intercept Function g0(K,Z)  [Reference group: WL] 
## 
##    Coefficient   Estimate      SE   Est./SE   p-value
##           g000      2.438   4.470     0.546     0.586
##           g001      1.055   0.127     8.284     0.000
##           g002     -0.351   0.138    -2.541     0.012
##           g010      5.844   5.058     1.155     0.249
##           g011     -0.160   0.153    -1.049     0.295
##           g012     -0.075   0.158    -0.471     0.638
## 
##  Effect Function g1(K,Z)   [Treatment: CBT vs. WL] 
## 
##    Coefficient   Estimate      SE   Est./SE   p-value
##           g100     -0.455   5.059    -0.090     0.928
##           g101     -0.140   0.150    -0.935     0.351
##           g102     -0.059   0.155    -0.378     0.706
##           g110     -4.123   6.443    -0.640     0.523
##           g111      0.081   0.202     0.402     0.688
##           g112      0.200   0.202     0.989     0.324
## 
## 
## --------------------- Cell Counts  --------------------- 
## 
## 
## Cell Counts 
## 
## This table shows cell counts including missings. 
## See also output under lavaan results for number of observations 
## actually used in the analysis. 
## 
##           Disorder   0   1
## Treatment                 
## 0                   45 105
## 1                  116  60
## 
## 
## --------------------- Main Hypotheses --------------------- 
## 
## H0: No average effects: E[g1(K,Z)] = 0
## H0: No covariate effects in control group: g0(K,Z) = constant
## H0: No treatment*covariate interaction: g1(K,Z) = constant
## H0: No treatment effects: g1(K,Z) = 0
## 
##                                         F value   df1   df2   p-value
## No average effects                       93.576     1   314     0.000
## No covariate effects in control group    65.223     5   314     0.000
## No treatment*covariate interaction        0.962     5   314     0.441
## No treatment effects                     17.740     6   314     0.000
## 
## 
##  --------------------- Adjusted Means --------------------- 
## 
##             Estimate      SE   Est./SE
## Adj.Mean0       20.7   0.300      69.0
## Adj.Mean1       16.7   0.283      59.1
## 
## 
##  --------------------- Average Effects --------------------- 
## 
##              Estimate      SE   Est./SE   p-value   Effect Size
## E[g1(K,Z)]      -3.99   0.412     -9.67         0        -0.746
## 
## 
##  --------------------- Effects given a Treatment Condition --------------------- 
## 
##                  Estimate      SE   Est./SE    p-value   Effect Size
## E[g1(K,Z)|X=0]      -3.49   0.491     -7.11   8.03e-12        -0.653
## E[g1(K,Z)|X=1]      -4.41   0.458     -9.63   0.00e+00        -0.825
## 
## 
##  --------------------- Effects given K=k --------------------- 
## 
##                  Estimate      SE   Est./SE    p-value   Effect Size
## E[g1(K,Z)|K=0]      -4.72   0.586     -8.05   1.75e-14        -0.882
## E[g1(K,Z)|K=1]      -3.28   0.580     -5.65   3.58e-08        -0.613
## 
## 
##  --------------------- Effects given X=x, K=k --------------------- 
## 
##                       Estimate      SE   Est./SE    p-value   Effect Size
## E[g1(K,Z)|X=0, K=0]      -4.56   0.584     -7.81   8.53e-14        -0.853
## E[g1(K,Z)|X=1, K=0]      -4.78   0.621     -7.70   1.84e-13        -0.893
## E[g1(K,Z)|X=0, K=1]      -3.03   0.656     -4.63   5.48e-06        -0.567
## E[g1(K,Z)|X=1, K=1]      -3.71   0.606     -6.12   2.78e-09        -0.694
## 
## 
## --------------------- Hypotheses given K=k --------------------- 
## 
## H0: No average effects given K=0: E[g1(K,Z)|K=0] = 0 
## H0: No average effects given K=1: E[g1(K,Z)|K=1] = 0 
## 
##                                F value   df1   df2    p-value
## No average effects given K=0      64.8     1   314   1.75e-14
## No average effects given K=1      31.9     1   314   3.58e-08</code></pre>
<p>Folgendes können wir dem Output entnehmen: Der geschätzet Average Treatment Effect (ATE) fällt mit -3.99 sehr ähnlich aus wie mit der ANCOVA und ist auch hier signifikant.</p>
<p>Zusätzlich erhalten wir noch weitere, differenziertere Schätzer, u.a.:</p>
<ul>
<li>Den Average Effect of the Treatet (ATT) für beide Bedingungen, er beträgt -3.49 für die Kontrollbedingung und -4.41 für die Treatment-Bedingung.</li>
<li>Effekte bedingt auf die kategoriale Kovariate Art der Störung - der bedingte Effekt beträgt -4.72 für Patient*innen mit Angststörung, -3.28 für Patient*innen mit Depression.</li>
<li>Auch für die Kombinationen aus Treatment und Störung werden bedingte Effekte geschätzt (‘Effects given X=x, K=k’).</li>
</ul>
</div>
