---
title: Tests für unabhängige Stichproben - Lösungen
date: '2022-12-09'
slug: gruppenvergleiche-unabhaengig-loesungen
categories:
  - BSc2
tags:
  - t-Test
subtitle: ''
summary: ''
authors: [koehler, buchholz, goldhammer]
lastmod: '2022-12-12T14:00:00+01:00'
featured: no
header:
  image: "/header/BSc2_test_unabh_stpr.jpg"
  caption: "[Courtesy of pxhere](https://pxhere.com/en/photo/662606)"
projects: []
expiryDate: '2023-09-15'
publishDate: '2022-01-16'
_build:
  list: never
---



<p><strong>Daten einlesen</strong></p>
<pre class="r"><code>setwd(&quot;...&quot;)  
load(&quot;fb22.rda&quot;)</code></pre>
<p><strong>Daten aufbereiten</strong></p>
<p>Prüfe zunächst, ob die Variablen Faktoren sind.</p>
<pre class="r"><code>is.factor(fb22$fach)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>is.factor(fb22$ort)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>is.factor(fb22$geschl)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>Falls nicht:</p>
<pre class="r"><code># Lieblingsfach als Faktor - falls es noch keiner war
fb22$fach &lt;- factor(fb22$fach, 
                    levels = 1:5,
                    labels = c(&#39;Allgemeine&#39;, &#39;Biologische&#39;, &#39;Entwicklung&#39;,
                               &#39;Klinische&#39;, &#39;Diag./Meth.&#39;))

# Wohnort als Faktor - falls es noch keiner war
fb22$ort &lt;- factor(fb22$ort, 
                   levels = c(1, 2),
                   labels = c(&#39;Frankfurt&#39;, &#39;anderer&#39;))


# Geschlecht als Faktor - falls es noch keiner war
fb22$geschl &lt;- factor(fb22$geschl, 
                      levels=c(1,2,3), 
                      labels=c(&#39;weiblich&#39;, &#39;maennlich&#39;, &#39;anderes&#39;))</code></pre>
<hr />
<div id="aufgabe-1" class="section level2">
<h2>Aufgabe 1</h2>
<p>Unterscheiden sich Studierende, die sich für Allgemeine Psychologie (Variable “fach”) interessieren, im Persönlichkeitsmerkmal Intellekt (auch: Offenheit für neue Erfahrungen, “intel”) von Studierenden, die sich für Klinische Psychologie interessieren? Normalverteilung des Merkmals in der Population darf angenommen werden.</p>
<details>
<summary>
Lösung
</summary>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: grafisch</strong></p>
<pre class="r"><code>data1 &lt;- fb22[ (which(fb22$fach==&quot;Allgemeine&quot;|fb22$fach==&quot;Klinische&quot;)), ]
data1$fach &lt;- droplevels(data1$fach)
boxplot(data1$intel ~ data1$fach,
        xlab=&quot;Interessenfach&quot;, ylab=&quot;Intellekt&quot;, 
        las=1, cex.lab=1.5, 
        main=&quot;Interessenfach und Intellekt&quot;)</code></pre>
<p><img src="/post/2022-12-09-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: statistisch</strong></p>
<pre class="r"><code># Überblick

library(psych)
describeBy(data1$intel, data1$fach)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: Allgemeine
##    vars  n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 19 3.79 0.48   3.75    3.76 0.37   3   5     2 0.59     0.08 0.11
## ------------------------------------------------------------ 
## group: Klinische
##    vars  n mean   sd median trimmed  mad  min  max range  skew kurtosis   se
## X1    1 57 3.54 0.63   3.75    3.56 0.37 1.75 4.75     3 -0.63     0.34 0.08</code></pre>
<pre class="r"><code># Berechnung der empirischen Standardabweichung

intel.A &lt;- data1$intel[(data1$fach==&quot;Allgemeine&quot;)]
sigma.A &lt;- sd(intel.A)
n.A &lt;- length(intel.A[!is.na(intel.A)])
sd.A &lt;- sigma.A * sqrt((n.A-1) / n.A)
sd.A </code></pre>
<pre><code>## [1] 0.4677997</code></pre>
<pre class="r"><code>intel.B &lt;- data1$intel[(data1$fach==&quot;Klinische&quot;)]
sigma.B &lt;- sd(intel.B)
n.B &lt;- length(intel.B[!is.na(intel.B)])
sd.B &lt;- sigma.B * sqrt((n.B-1) / n.B)
sd.B</code></pre>
<pre><code>## [1] 0.6255499</code></pre>
<p>Mittelwert der Allgemeinen Psychologen (<em>M</em> = 3.79, <em>SD</em> = 0.47) unterscheidet sich deskriptivstatistisch vom Mittelwert der Klinischen (<em>M</em> = 3.54, <em>SD</em> = 0.63).</p>
<p><strong>Voraussetzungsprüfung: Normalverteilung</strong></p>
<p>Nicht nötig, da Normalverteilung in Population angenommen werden darf (s. Aufgabenstellung).</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Unterschiedshypothese<br />
</li>
<li>Richtung des Effekts: Ungerichtet <span class="math inline">\(\rightarrow\)</span> ungerichtete Hypothesen<br />
</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypthesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_\text{Allgemeine} = \mu_\text{Klinische}\)</span></li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu_\text{Allgemeine} \ne \mu_\text{Klinische}\)</span></li>
</ul>
<p><strong>Spezifikation des Signifikanzniveaus</strong></p>
<p><span class="math inline">\(\alpha = .05\)</span></p>
<p><strong>Voraussetzungsprüfung: Varianzhomogenität</strong></p>
<pre class="r"><code>library(car)
leveneTest(data1$intel ~ data1$fach)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  1.3813 0.2437
##       74</code></pre>
<p><em>F</em>(1, 74) = 1.38, <em>p</em> = 0.244 <span class="math inline">\(\rightarrow\)</span> Das Ergebnis ist nicht signifikant, die <span class="math inline">\(H_0\)</span> wird beibehalten und Varianzhomogenität angenommen.</p>
<p><strong>Durchführung des <em>t</em>-Tests</strong></p>
<pre class="r"><code>t.test(data1$intel ~ data1$fach,           # abhängige Variable ~ unabhängige Variable
       paired = F,                   # Stichproben sind unabhängig 
       alternative = &quot;two.sided&quot;,         # zweiseitige Testung
       var.equal = T,                # Varianzhomogenität ist gegeben (-&gt; Levene-Test)
       conf.level = .95)             # alpha = .05 </code></pre>
<pre><code>## 
## 	Two Sample t-test
## 
## data:  data1$intel by data1$fach
## t = 1.6058, df = 74, p-value = 0.1126
## alternative hypothesis: true difference in means between group Allgemeine and group Klinische is not equal to 0
## 95 percent confidence interval:
##  -0.0612611  0.5700330
## sample estimates:
## mean in group Allgemeine  mean in group Klinische 
##                 3.789474                 3.535088</code></pre>
<p><strong>Formales Berichten des Ergebnisses</strong></p>
<p>Es wurde untersucht, ob sich Studierende, die sich für Allgemeine Psychologie interessieren, im Persönlichkeitsmerkmal ‘Intellekt’ (auch: Offenheit für neue Erfahrungen) von Studierenden, die sich für Klinische Psychologie interessieren, unterscheiden. Deskriptiv liegt ein solcher Unterschied vor: Die Mittelwerte betragen 3.79 (Allgemeine, <em>SD</em> = 0.47) und 3.54 (Klinische, <em>SD</em> = 0.63). Der entsprechende <em>t</em>-Test zeigt jedoch ein nicht signifikantes Ergebnis (<em>t</em>(<em>df</em> = 74, zweis.) = 1.61, <em>p</em> = 0.113). Die Nullhypothese konnte nicht verworfen werden und wird beibehalten. Die Studierenden sind im Persönlichkeitsmerkmal ‘Intellekt’ unabhängig davon, ob sie sich für Allgemeine Psychologie oder für Klinische Psychologie interessieren.</p>
</details>
</div>
<div id="aufgabe-2" class="section level2">
<h2>Aufgabe 2</h2>
<p>Sind Studierende, die außerhalb von Frankfurt wohnen (“ort”), unzufriedener im Leben (“lz”) als diejenigen, die innerhalb von Frankfurt wohnen?</p>
<details>
<summary>
Lösung
</summary>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: grafisch</strong></p>
<pre class="r"><code>boxplot(fb22$lz ~ fb22$ort,
        xlab=&quot;Wohnort&quot;, ylab=&quot;Lebenszufriedenheit&quot;, 
        las=1, cex.lab=1.5, 
        main=&quot;Wohnort und Lebenszufriedenheit&quot;)</code></pre>
<p><img src="/post/2022-12-09-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p><strong>Deskriptivstatistische Beantwortung der Fragestellung: statistisch</strong></p>
<pre class="r"><code>library(psych)
describeBy(fb22$lz, fb22$ort)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: Frankfurt
##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 95  4.8 1.15      5     4.9 1.19 1.4 6.6   5.2 -0.77     0.14 0.12
## ------------------------------------------------------------ 
## group: anderer
##    vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 53 4.68 0.91    4.8    4.75 0.89   2 6.2   4.2 -0.73     0.19 0.13</code></pre>
<pre class="r"><code>summary(fb22[which(fb22$ort==&quot;Frankfurt&quot;), &quot;lz&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##     1.4     4.2     5.0     4.8     5.7     6.6       1</code></pre>
<pre class="r"><code>summary(fb22[which(fb22$ort==&quot;anderer&quot;), &quot;lz&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   2.000   4.200   4.800   4.683   5.400   6.200       1</code></pre>
<p>Mittelwert der Nicht-Frankfurter:innen ist deskriptiv niedriger als der der Frankfurter:innen.</p>
<p><strong>Voraussetzungsprüfung: Normalverteilung</strong></p>
<pre class="r"><code>par(mfrow=c(1,2))
lz.F &lt;- fb22[which(fb22$ort==&quot;Frankfurt&quot;), &quot;lz&quot;]
hist(lz.F, xlim=c(1,9), ylim=c(0,.5), main=&quot;Lebenzufriedenheit\n(Frankfurter)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, prob=T)
curve(dnorm(x, mean=mean(lz.F, na.rm=T), sd=sd(lz.F, na.rm=T)), col=&quot;red&quot;, lwd=2, add=T)
qqnorm(lz.F)
qqline(lz.F, col=&quot;red&quot;)</code></pre>
<p><img src="/post/2022-12-09-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><span class="math inline">\(\rightarrow\)</span> Entscheidung: Normalverteilung wird nicht angenommen</p>
<pre class="r"><code>par(mfrow=c(1,2))
lz.a &lt;- fb22[which(fb22$ort==&quot;anderer&quot;), &quot;lz&quot;]
hist(lz.a, xlim=c(1,9), main=&quot;Lebenszufriedenheit\n(Nicht-Frankfurter)&quot;, xlab=&quot;&quot;, ylab=&quot;&quot;, las=1, prob=T)
curve(dnorm(x, mean=mean(lz.a, na.rm=T), sd=sd(lz.a, na.rm=T)), col=&quot;red&quot;, lwd=2, add=T)
qqnorm(lz.a)
qqline(lz.a, col=&quot;red&quot;)</code></pre>
<p><img src="/post/2022-12-09-tests-fuer-unabhaengige-stichproben-loesungen_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><span class="math inline">\(\rightarrow\)</span> Entscheidung: Normalverteilung wird nicht angenommmen</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Unterschiedshypothese<br />
</li>
<li>Richtung des Effekts: Gerichtet <span class="math inline">\(\rightarrow\)</span> gerichtete Hypothesen<br />
</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hypthesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\eta_\text{Frankfurter} \le \eta_\text{nicht-Frankfurter}\)</span><br />
</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\eta_\text{Frankfurter} &gt; \eta_\text{nicht-Frankfurter}\)</span></li>
</ul>
<p><strong>Spezifikation des Signifikanzniveaus</strong></p>
<p><span class="math inline">\(\alpha = .05\)</span></p>
<p><strong>Durchführung des Wilcoxon-Tests</strong></p>
<pre class="r"><code>wilcox.test(fb22$lz ~ fb22$ort,           # abhängige Variable ~ unabhängige Variable
       paired = F,                   # Stichproben sind unabhängig 
       alternative = &quot;greater&quot;,         # einseitige Testung: Gruppe1 (Frankfurter:innen) &gt; Gruppe2 (Nicht-Frankfurter:innen) 
       conf.level = .95)             # alpha = .05 </code></pre>
<pre><code>## 
## 	Wilcoxon rank sum test with continuity correction
## 
## data:  fb22$lz by fb22$ort
## W = 2775, p-value = 0.1515
## alternative hypothesis: true location shift is greater than 0</code></pre>
<p><strong>Formales Berichten des Ergebnisses</strong></p>
<p>Es wurde untersucht, ob außerhalb von Frankfurt wohnende Studierende unzufriedener im Leben sind als die in Frankfurt wohnenden. Deskriptiv zeigt sich das erwartete Muster: die Nicht-Frankfurter:innen sind weniger zufrieden (<em>Mdn</em> = 4.8, <em>IQB</em> = [4.2 ; 5.4]) als die Frankfurter:innen (<em>Mdn</em> = 5, <em>IQB</em> = [4.2 ; 5.7]). Jedoch ist das Ergebnis des einseitigen Wilcoxon-Tests nicht signifikant (<em>W</em> = 2775, <em>p</em> = 0.151). Die Nullhypothese konnte nicht verworfen werden und wird beibehalten.</p>
</details>
</div>
<div id="aufgabe-3" class="section level2">
<h2>Aufgabe 3</h2>
<p>Ist die Wahrscheinlichkeit dafür, innerhalb von Frankfurt zu wohnen, die gleiche für weibliche wie für männliche Erstsemester-Studierende der Psychologie?</p>
<details>
<summary>
Lösung
</summary>
<p>Beide Variablen sind nominalskaliert <span class="math inline">\(\rightarrow \chi^2\)</span>-Test</p>
<p><strong>Voraussetzungen</strong></p>
<ol style="list-style-type: decimal">
<li>Die einzelnen Beobachtungen sind voneinander unabhängig <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Jede Person lässt sich eindeutig einer Kategorie bzw. Merkmalskombination zuordnen <span class="math inline">\(\rightarrow\)</span> ok</li>
<li>Zellbesetzung für alle <span class="math inline">\(n_{ij}\)</span> &gt; 5 <span class="math inline">\(\rightarrow\)</span> Prüfung anhand von Häufigkeitstabelle</li>
</ol>
<pre class="r"><code>fb22$geschlecht &lt;- fb22$geschl
fb22$geschlecht[fb22$geschlecht==&quot;anderes&quot;] &lt;- NA #Umkodieren von &quot;anderes&quot; in fehlenden Wert
fb22$geschlecht &lt;- droplevels(fb22$geschlecht) #Level &quot;anderes&quot; wird eliminiert
tab &lt;- table(fb22$geschlecht, fb22$ort)
tab</code></pre>
<pre><code>##            
##             Frankfurt anderer
##   weiblich         79      46
##   maennlich        15       8</code></pre>
<p><span class="math inline">\(\rightarrow n_{ij}\)</span> &gt; 5 in allen Zellen gegeben</p>
<p><strong>Hypothesen</strong></p>
<ul>
<li>Art des Effekts: Zusammenhangshypothese</li>
<li>Richtung des Effekts: Ungerichtet</li>
<li>Größe des Effekts: Unspezifisch</li>
</ul>
<p>Hyothesenpaar (inhaltlich):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Weibliche und männliche Studierende der Psychologie wohnen mit gleicher Wahrscheinlichkeit innerhalb bzw. außerhalb von Frankfurt.<br />
</li>
<li><span class="math inline">\(H_1\)</span>: Weibliche und männliche Studierende der Psychologie unterscheiden sich in der Wahrscheinlichkeit, innerhalb bzw. außerhalb von Frankfurt zu wohnen.</li>
</ul>
<p>Hypothesenpaar (statistisch):</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\pi_{ij} = \pi_{i\bullet} \cdot \pi_{\bullet j}\)</span><br />
</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\pi_{ij} \neq \pi_{i\bullet} \cdot \pi_{\bullet j}\)</span></li>
</ul>
<p><strong>Durchführung des <span class="math inline">\(\chi^2\)</span>-Test in R</strong></p>
<pre class="r"><code>chisq.test(tab, correct=FALSE)</code></pre>
<pre><code>## 
## 	Pearson&#39;s Chi-squared test
## 
## data:  tab
## X-squared = 0.034116, df = 1, p-value = 0.8535</code></pre>
<p><span class="math inline">\(\chi^2\)</span> = 0.034, df = 1, <em>p</em> = 0.853 <span class="math inline">\(\rightarrow H_0\)</span></p>
<p><strong>Effektstärke Phi (<span class="math inline">\(\phi\)</span>)</strong></p>
<pre class="r"><code>library(psych)
phi(tab)</code></pre>
<pre><code>## [1] -0.02</code></pre>
<p><strong>Ergebnisinterpretation</strong></p>
<p>Es wurde untersucht, ob sich männliche und weibliche Studierende in ihrem Wohnort (Frankfurt vs. außerhalb) unterscheiden. Zur Beantwortung der Fragestellung wurde ein Vierfelder-Chi-Quadrat-Test für unabhängige Stichproben berechnet. Der Zusammenhang zwischen Wohnort und Geschlecht ist nicht signifikant (<span class="math inline">\(\chi^2\)</span>(1) = 0.034, <em>p</em> = 0.853), somit wird die Nullhypothese beibehalten. Der Effekt ist von vernachlässigbarer Stärke (<span class="math inline">\(\phi\)</span> = -0.02). Männliche und weibliche Studierende wohnen also mit gleicher Wahrscheinlichkeit in Frankfurt bzw. außerhalb von Frankfurt.</p>
</details>
</div>
