---
title: "Markdown"
date: '2023-03-24'
slug: Markdown
categories:
  - extras
tags:
subtitle: ''
summary: ''
authors: [pommeranz]
lastmod: '`r Sys.Date()`'
featured: no
header:
  image: "/header/" #https://pxhere.com/de/photo/29 maybe this?
  caption: "[Courtesy of pxhere](https://pxhere.com/de/photo/29)"
projects: []
---

Im Folgenden Tutorial wird euch allgemeines Markdown nähergebracht, mit dem rein textbasierte Arbeiten etwas dynamischer und visuell ansprechender gestaltet werden können.

## Was ist Markdown?

Markdown ist im allgemeineren eine Auszeichnungssprache, die in fast jeder textbasierten Anwendung in relativ ähnlicher Form vorkommt, um spezifische Textdarstellungen und Inhalte in Texten zu ermöglichen. Ein Beispiel dafür ist die *Inline Formatierung*. Mit ihr kann man beispielsweise mit  `**Text**`  **Text fett schreiben** oder auch per  `~~Text~~`  ~~Text durchstreichen~~. Dies kann man meist in vergleichbarer Form auch in einem Messenger der Wahl replizieren. In WhatsApp lässt sich Text zum Beispiel mit `~Text~` durchstreichen. Man kann auch [Links]() einbinden, indem man den gewollten Textteil in `[]` Klammern einschließt und den entsprechenden Link in `()` Klammern setzt.

## Wofür Markdown?

Mit Markdown lassen sich auch mathematische Ausdrücke formulieren und Matrizen darstellen.

Beispielsweise werden 
```
$$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$
```
und
```
$$\begin{array}{ccc}
x_{11} & x_{12} & x_{13}\\
x_{21} & x_{22} & x_{23}
\end{array}$$
```
durch Markdown zu

$$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$

und

$$\begin{array}{ccc}
x_{11} & x_{12} & x_{13}\\
x_{21} & x_{22} & x_{23}
\end{array}$$


## Textbestandteile
Es gibt in Markdown auch typische Bestandteile zur visuellen Trennung des Text, wie man sie aus anderen Dokumentbearbeitungsprogrammen auch gewohnt ist. Darunter fallen Zeilenumbrüche und neue Paragraphen. Diese beiden werden auch, wenn man Markdown nutzt um eine Website zu schreiben, zu den entsprechenden HTML-Gegenstücken kompiliert, `<p></p> für Paragraphen, <br> für Zeilenumbrüche`.

### Paragraph
Ein neuer Paragraph wird erstellt, indem man eine Zeile oberhalb und unterhalb des Text freilässt.


### Neue Zeile
Ein Zeilenumbruch wird in Markdown erstellt, indem man zwei Leerzeichen an das Ende einer Zeile setzt und dann per Enter eine neue Zeile beginnt. In dem Fall von Markdown per RStudio braucht man auch keine Leerstellen, aber diese sind insgesamt typisch für allgemeines Markdown und fallen nicht auf, auch wenn sie überschüssig sind.


## Heading

Ein typischer Bestandteil eines Dokuments sind die Headings, diese werden in Markdown mit Rauten entsprechend des Heading-Level vor dem Wort erstellt.

| Code | Level |
|---|---|
| `# Heading`  | 1 |
| `## Heading`  |  2 |
| `### Heading`  |  3 |
| `#### Heading`  |  4 |
| `##### Heading`  | 5  |
| `###### Heading`  | 6  |

Es ist wichtig, dass die Headings am Anfang der Zeile stehen und das zwischen Rauten und Titel des Headings eine Leerstelle ist, da sie sonst nicht funktionieren. Leerraum zwischen Headings und dem restlichen Text sind auch erwünscht, da sie sonst auch unter Umständen nicht funktionieren.


## Tabellen

Tabellen lassen sich auch per Markdown rein textbasiert erstellen, so wie es auch bei den Headings zuvor gemacht wurde

```
| Spalte 1 | Spalte 2 |
|---|---|
| Spalte 1, Eintrag 1  | Spalte 2, Eintrag 1 |
| Spalte 1, Eintrag 2  | Spalte 2, Eintrag 2 |

```

wird dargestellt als

| Spalte 1 | Spalte 2 |
|---|---|
| Spalte 1, Eintrag 1  | Spalte 2, Eintrag 1 |
| Spalte 1, Eintrag 2  | Spalte 2, Eintrag 2 |

## Blockzitat



## Horizontale Trennstriche
Mit drei Asterisks ***, dashes --- oder underscores ___ kann man eine horizontale Linie als Trenner einbauen. Diese müssen dafür für sich alleine in einer eigenen Zeile stehen und sollten auch eine Zeile Abstand zu restlichem Text haben, da sie sonst zu einem Heading mit den vorherstehenden Inhalten kombiniert werden. Man kann dabei auch beliebig oft die Zeichen wiederholen, statt nur drei mal, sofern man den Code selbst vielleicht auch visuell trennen möchte.


## Markdown in RStudio: Besonderheiten
Markdown in Rstudio, nach welchem sich dieses Tutorial auch richtet, besitzt einige Eigenschaften, die öfters aber nicht zwingend in den meisten Markdown-Anwendungen unterstützt werden. Markdown in RStudio unterstützt beispielsweise HTML-Tags. Dies erlaubt einige weiter Textanpassungen die sonst nicht möglich wären, aber da der Fokus auf Markdown und nicht HTML liegt, gibt es nun nur ein kurzes Beispiel.

### Textfarben per HTML ändern
Per `<p style="color:red">` <p style="color:red">lässt sich der darauffolgende Text rot färben, mit `</p>` </p> wird dies wieder aufgehoben.

Die weiteren Möglichkeiten mit HTML sind auch weitreichender, als nur Textfarbe, man könnte beispielsweise auch Videos einbinden oder weitreichendere Modifikationen an Struktur und Text vornehmen.

***
