---
title: "RMarkdown"
date: '2022-12-06'
slug: RMarkdown
categories:
  #- extras Erstmal auskommentiert :)
tags:
subtitle: ''
summary: ''
authors: [pommeranz]
lastmod: '2022-11-19T10:00:00+01:00'
featured: no
header:
  image: "/header/" #https://pxhere.com/de/photo/29 maybe this?
  caption: "[Courtesy of pxhere](https://pxhere.com/de/photo/29)"
projects: []
---

```{r knitr options, echo=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```


## RMarkdown-Datei erstellen


## Aufbau des Dokuments


## Markdown Syntax
RMarkdown verwendet eine Syntax, die Markdown sehr ähnlich ist. Markdown ist im allgemeineren eine Auszeichnungssprache, die in fast jeder textbasierten Anwendung in normierter Form vorkommt. 

Ein Beispiel dafür ist die *Inline Formatierung*. Mit ihr kann man beispielsweise mit  `**Text**`  **Text fett schreiben** oder auch per  `~~Text~~`  ~~Texte durchstreichen~~. Dies kann man meist in vergleichbarer Form auch in einem Messenger der Wahl replizieren, in WhatsApp etwa lässt sich Text mit `~Text~` streichen!

Auch *Blockelemente* lassen sich in Markdown erstellen, womit man beispielsweise Codeblocks teilen kann, dazu ein Beispiel aus PsyBsc2:

```
#### Was bisher geschah: ----

# Daten laden
load(url('https://pandar.netlify.app/post/fb22.rda'))  

# Nominalskalierte Variablen in Faktoren verwandeln
fb22$geschl_faktor <- factor(fb22$geschl,
                             levels = 1:3,
                             labels = c("weiblich", "männlich", "anderes"))
fb22$fach <- factor(fb22$fach,
                    levels = 1:5,
                    labels = c('Allgemeine', 'Biologische', 'Entwicklung', 'Klinische', 'Diag./Meth.'))
fb22$ziel <- factor(fb22$ziel,
                        levels = 1:4,
                        labels = c("Wirtschaft", "Therapie", "Forschung", "Andere"))

fb22$wohnen <- factor(fb22$wohnen, 
                      levels = 1:4, 
                      labels = c("WG", "bei Eltern", "alleine", "sonstiges"))

fb22$ort <- factor(fb22$ort, levels=c(1,2), labels=c("FFM", "anderer"))

fb22$job <- factor(fb22$job, levels=c(1,2), labels=c("nein", "ja"))
```

Dies geht mit drei Backticks ` ``` ` die jeweils über und unter dem Codeabschnitt stehen

Zuletzt lassen sich mit Base-Markdown auch mathematische Ausdrücke formulieren und Matrizen darstellen.

Beispielsweise  werden 
```
$$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$
```
und
```
$$\begin{array}{ccc}
x_{11} & x_{12} & x_{13}\\
x_{21} & x_{22} & x_{23}
\end{array}$$
```
in RMarkdown zu

$$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$

und

$$\begin{array}{ccc}
x_{11} & x_{12} & x_{13}\\
x_{21} & x_{22} & x_{23}
\end{array}$$

## Code Chunks


## Setup mit knitr


## Inline Code & Parameter


## Zitationen einbauen



***
