---
title: "Pandoc"
date: '2023-03-24'
slug: Pandoc
categories:
  - extras
tags:
subtitle: ''
summary: ''
authors: [pommeranz]
lastmod: '`r Sys.Date()`'
featured: no
header:
  image: "/header/" #https://pxhere.com/de/photo/29 maybe this?
  caption: "[Courtesy of pxhere](https://pxhere.com/de/photo/29)"
projects: []
---

`r blogdown::shortcode_open("detail_disclosure", "Kernfragen dieses Beitrags")`
<!-- Die divs sind wichtig, damit die Liste funktioniert! Innerhalb dieses Shortcodes ist HTML erlaubt (safeHTML) -->
<div>
* Was ist [**Pandoc**](#Pandoc)?
* Welchen [**Nutzen**](#UseCase) bringt mir Pandoc im Vergleich zu Markdown?
* Wie könnte es aussehen, wenn Pandoc [**externe Sprachen**](#HTML) einbindet?
* Was ist die [**Kernaussage**](#Fazit), die ich mir aus dieser Sitzung mitnehmen sollte?
</div>

`r blogdown::shortcode_close("detail_disclosure")`

***

## Was ist Pandoc? {#Pandoc .anchorheader}

Pandoc ist ein Compiler/Converter von und zu Markdown, der in RStudio standardmäßig miteingebunden ist. Pandoc kann zwischen verschiedenen Formaten konvertieren und bietet somit ein erweitertes Funktionsspektrum im Vergleich zu plain Markdown.


## Was kann Pandoc, was Markdown nicht kann? {#UseCase .anchorheader}

Pandoc kann nicht nur reines Markdown, sondern auch HTML, LaTeX und Word-Dokumente kompilieren. Nicht nur kann man damit Pandoc mit den Möglichkeiten von HTML oder LaTeX kombinieren, sondern es bietet noch erweiterte Markdown-Features, mit denen man unter anderem weitere Tabllenformate nutzen kann.

Beispielsweise `simple_tables`, mit denen verschiedene Text-Einrückungen umsetzbar sind.

  Right     Left     Center     Default
-------     ------ ----------   -------
     12     12        12            12
    123     123       123          123
      1     1          1             1

Listen gewinnen auch an Flexibilität und Komplexität.
`fancy_lists` ist ein simples Beispiel dafür, da es schlichtweg nur weitere Nummerierungssymbole wie
römische Zahlen anbietet und eine automatische Nummerierung ermöglicht.

```
#. Eins
#. Zwei
```

wird zu

#. Eins
#. Zwei

Mit Pandoc lassen sich auch mathematische Ausdrücke formulieren und Matrizen darstellen.

Beispielsweise werden 
```
$$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$
```
und
```
$$\begin{array}{ccc}
x_{11} & x_{12} & x_{13}\\
x_{21} & x_{22} & x_{23}
\end{array}$$
```
durch Pandoc zu

$$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$

und

$$\begin{array}{ccc}
x_{11} & x_{12} & x_{13}\\
x_{21} & x_{22} & x_{23}
\end{array}$$

Dies soll jedoch nur einen kleinen Einblick bieten, da Pandoc's Markdown viele Funktionen bietet, die hier den Rahmen sprengen würden. Wichtig ist eher zu verstehen, was Pandoc kann und wie es funktioniert, um den Gesamtprozess zu verstehen. Aber die [Dokumentation von Pandoc](https://pandoc.org/MANUAL.html) empfiehlt sich trotzdem, wenn man mit den erweiterten Features von Pandoc genauer arbeiten will und um sich auch einen Eindruck über alle möglichen Optionen zur Formatierung anzuschauen.

Im Folgenden ersetzen wir die  bereits vorhandenen Tabellen und Listen in unserem Bericht und nutzen die Funktion der mathematischen Formeln um unser Regressionsgewicht in der Hypothese zu benennen.

<!--- Version 1 hier einfügen? -->

[]: # (Bild hier einfügen?)

Erneut steht es im eigenen Ermessen sich jeweils die Lösung selbst zu erschließen oder direkt anzuschauen. Die Basis bildet die finale Version des Markdown des vorherigen Beitrags.

`r blogdown::shortcode_open("detail_disclosure", "Zeig mir die Lösung")`
Folgende Zwei Abschnitte haben sich verändert:
<pre>
#### **Deskriptiv** {#Deskriptivstatistik}

Von der Stichprobe dieses Fragebogen wurde nur die Geschlechterverteilung aufgenommen, welche folgendermaßen aussieht:

 Weiblich   Männlich   Anderes
---------- ---------- ---------
 125        23         1

(. . .)

>
>Hypothesen
>
> #. H1: Das Regressionsgewicht $b_1$ des Prädiktors Nerdigkeit ist signifikant von Null verschieden ($b_1 \neq 0$). Der Zusammenhang von Nerdigkeit und Neurotizität ist statistisch bedeutsam. 
>
> #. H0: Das Regressionsgewicht $b_1$ des Prädiktors Nerdigkeit ist nicht signifikant von Null verschieden ($b_1 = 0$). Der Zusammenhang von Nerdigkeit und Neurotizität ist nicht statistisch bedeutsam. 
>

</pre>
`r blogdown::shortcode_close("detail_disclosure")`

## YAML - Metaheader
In Pandoc lassen sich über den Header weitere Optionen für die Pandoc Template einstellen. Man kann dabei Automatisch Autor, Titel, und ein Abstract einbauen, aber auch einen automatischen Table of Contents, der jeden zuvor definierten Header automatisch in sich eingliedert.

Dies sieht in unserem Beispielbericht wie folgt aus:

<!--- Version 2 hier einfügen? -->

[]: # (Bild hier einfügen?)

Man kann versuchen, sich den Aufbau des Code über Pandocs Guide zu erschließen, oder indem man entsprechende Schlüsselwörter in einer Suchmaschine eingibt.

`r blogdown::shortcode_open("detail_disclosure", "Zeig mir die Lösung")`
Folgender Code steht nun direkt zu Beginn des Dokuments:
<pre>
---
title: Minibericht
author: Kevin Pommeranz
abstract: Im folgenden Bericht werde ich eine lineare Regression und ihre Ergebnisse beispielhaft abbilden, um zu zeigen wie Markdown im wissenschaftlichen Austausch genutzt werden kann. Es ist kein formaler wissenschaftlicher Bericht, sondern nur zur Veranschaulichung!
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3

---
</pre>
`r blogdown::shortcode_close("detail_disclosure")`

## HTML und Pandoc {#HTML .anchorheader}

Pandoc erlaubt die Nutzung von HTML und CSS in Markdown beim Erstellen von Websites. Dies kann nützlich sein, um eine Vielzahl von Funktionen umzusetzen. Mit dem richtigen Rahmen kann man mit HTML viele Seitenelemente automatisieren, wie beispielsweise feste Kopf- und Fußzeilen. Es kann für relativ basale Zwecke verwendet werden, um die Farbe von Schriften anzupassen, aber auch für komplexere Aspekte, wie eine feste Kopfzeile die sich mit dem Scrollen des Textes mitbewegt. Da sich dieses Tutorial aber mit Markdown und weiterführend RMarkdown beschäftigt, wird darauf hier nicht tiefer eingegangen.

Wir können HTML in unserem Bericht nutzen, um Schlüsselwörter beispielsweise in roter Schrift hervorzuheben. Dies ist zwar nicht zwingend gewünscht nach Formaten wie APA, gibt aber ein schönes Anwendungsbeispiel!

<!--- Version 3 hier einfügen? -->

[]: # (Bild hier einfügen?)

Hier wurde nur der Text gefärbt, was mit `<span style='color: FARBE'>Text</span>.` realisiert wird. Farben (`FARBE`) können mit ihrem jeweiligen Namen oder ihrem Hex-Code ausgewählt werden. Wie man sieht ist HTML als Programmiersprache anders aufgebaut als man es vielleicht von R gewöhnt ist.

`r blogdown::shortcode_open("detail_disclosure", "Zeig mir die Lösung")`
<pre>
#### **Was wurde durchgeführt?** {#Durchführung}

Es wurde eine <span style='color: red'>lineare Regression</span> durchgeführt, um zu sehen, ob innerhalb des Datenatz die Nerdigkeit einen linearen Zusammenhang mit der Neurotizität aufzeigt.

</pre>
`r blogdown::shortcode_close("detail_disclosure")`

## Fazit {#Fazit .anchorheader}

Pandoc ist der Interpret von RStudio für Markdown und bietet zusätzliche Funktionen die das Grundrepertoire von plain Markdown erweitern. Eine mögliche Erweiterung ist dabei die Verwendung von HTML, welches nicht selten für Markdown-Sprachen mitverwendet wird, da Markdown zu Beginn überwiegend genutzt wurde, um Internetseiten zu erstellen. Es spielt auch eine essenzielle Rolle in der Konvertierung von RMds zu fertigen Dokumenten, worauf in dem nächsten Skript noch einmal eingegangen wird.

***
